### ISSUE TITLE
No Base Save File

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#1]
Hi, just tried the new release and it is not creating a base save file.

**Comment by goatfungus** [comment]
There are still a few bugs in it unfortunately... but one thing you could check is whether or not the base is version 1 or version 2 in the JSON editor. Go to PlayerStateData->PersistentPlayerBases and check the version number. I've found the structure only supports version 2 at present.

**Comment by goatfungus** [comment]
New release, 1.3.32 should resolve all remaining issues with version 2 bases. Version 1 bases will likely not save at all.

It appears that when NMS was originally released, they had messed up the coordinate system, so they fixed it in a later version. This would explain why people had bases appearing in wrong orientation and floating up in the air after an update was released. Not sure exactly which one it was, but this is the same reason why the editor can't backup the older bases correctly.

I don't think it's worth the trouble of figuring out exactly what they messed up in version 1 to get these bases to backup properly, but if I have time I'll see what I can do.

**Comment by ukmerlin** [comment]
OK seems to be working now many thanks......
