### ISSUE TITLE
[Suggestion] Import and export Discovery and Milestones

### ISSUE THREAD

**Issue by Martan404** [goatfungus/NMSSaveEditor#10]
As the title says, it would be really nice if we could import and export the settings of Discoveries and Milestones

**Comment by Martan404** [comment]
Okey so I just found the JSON editor and it worked great. But a button inside the UI would still be good I think for less advanced users and quicker export/import

**Comment by goatfungus** [comment]
Is this so that you can copy your progress from another save?

If so, the next thing people would ask for is saving mission progress, which is a big job because of a number of dependent factors. I have been holding off even attempting this since Atlas Rises was released.

**Comment by Martan404** [comment]
Yea, I restarted my game when Next came out because my old one was buggy. But I wanted to keep my progress of knows Words and my Milestones because of the huge grind. 

To be honest I don't think Mission progress would be a good idea to import/export. That was my main issue with my old save. Ship, Suit and Multitool was no problems to do but it took me a little while to find how to dp it with the JSON editor. But it works!

**Comment by goatfungus** [comment]
Words should be easy with the JSON editor, milestones are a bit more difficult but there aren't very many of them so you could just run 2 copies of the editor side-by-side and copy the values out.

To be honest, I'm not sure I'll get around to adding a specific export/import process for this as it is not something that would be commonly used and the workaround isn't too bad. So I might just close this one for now.
