### ISSUE TITLE
Always modified externally [BUG]

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#100]
The latest version (19) informs me my save has been modified externally after _every save action_... Nothing else is accessing the save files - the game isn't running in the background or anything similar.

**Comment by tcutchi** [comment]
Same issue here, every save pops up an external modification warning.
Not the worst thing, but pretty annoying lol

**Comment by Rianon** [comment]
I can confirm this too.

**Comment by goatfungus** [comment]
Again? I thought I had fixed this.... sorry.
I'll get onto this shortly.

**Comment by goatfungus** [comment]
Just uploaded a quick patch, version 1.5.19b, which should fix this problem.
I have changed the file watcher service to run only when the editor is deactivated (running in the background). So if you're actively using it, there should be no more modification warnings.

**Comment by Rianon** [comment]
Yep, now all works just as intended. Thanks.
