### ISSUE TITLE
Save Editor not working with current Steam Experimental update

### ISSUE THREAD

**Issue by Devilin-Pixy** [goatfungus/NMSSaveEditor#1009]
# Heads-up

The new Steam Experimental update breaks functionality:

[Experimental Branch 11/06](https://steamcommunity.com/app/275850/discussions/0/4333106094377537940/)
> Refactored the internal save architecture and layout to support future improvements.

In-game build version would be **124106**

SteamDB: https://steamdb.info/app/275850/history/?changeid=23921074

## Log output
[NMSSaveEditor.log](https://github.com/user-attachments/files/15788179/NMSSaveEditor.log)
Shows to have issues with the metadata files.

**Comment by kobs57** [comment]
Yep, same here can't load my save files

**Comment by boldfish** [comment]
I imagine that fixing this would introduce breaking changes for anyone on the public release, so I guess we're waiting until that update.

**Comment by wkitty42** [comment]
> I imagine that fixing this would introduce breaking changes for anyone on the public release, so I guess we're waiting until that update.

i'm thinking the same unless the save file format is versioned...

**Comment by kobs57** [comment]
From the experimental thread

Originally posted by HG Exp notes:
Experimental Branch 11/06

Refactored the internal save architecture and layout to support future improvements.

**Comment by goatfungus** [comment]
I would have got onto this sooner, but had a medical emergency I had to deal with.
See #1019 for more info on the Worlds Part 1 update
