### ISSUE TITLE
Does not work with Worlds Part 1 yet.

### ISSUE THREAD

**Issue by SavieSIlverfall** [goatfungus/NMSSaveEditor#1014]
Hello, 

The save editor is giving errors reading my saves.

https://gyazo.com/b8838ce03d27f1a7f3d6f75756c6f723

**Comment by lightling2020** [comment]
Me too
![20240717-231130](https://github.com/user-attachments/assets/3f9571c9-cb6d-4eec-9ab0-959dadf3866f)

**Comment by perpetualyawn** [comment]
Guys of course it doesn't work with it yet, the update only just dropped less than 2 hours ago. Every major update has done this and GF will get on it when he's able to.

**Comment by wkitty42** [comment]
depends on what you call an "update"... those of us playing on the NMS experimental branch on steam saw the breakage from the announced save file format change a few months ago... that breakage was filed as an issue here at that time... i do not recall seeing any Ack about it, though... only posts from other players confirming they are/were seeing it, too...

**Comment by wyccad** [comment]
as with other major releases there gonna be bugs that'll need to be patched, which will also delay the release of a multitude to mods that no longer work and need to be updated, as well.

**Comment by david-ford** [comment]
> as with other major releases there are gonna be bugs that'll need to be patched, which will also delay the release of a multitude to mods that no longer work and need to be updated, as well.

Generally, yes this is true. However the way GF designed this, it typically will continue to work with new updates as long as the save format remains the same. New items added to the game won't have descriptions, etc, but historically it hasn't completely broken aside from the few times when save files changed significantly. 

This is one of those updates.

**Comment by wkitty42** [comment]
exactly, david-ford... exactly...

FWIW: #1007 and #1009 (both filed on Jun 11) brought the initial issue to light... neither one has had any further comments or updates in the last three weeks... not even an ACK from GF which i find a little unusual...

**Comment by HQuest** [comment]
A quick reminder from @goatfungus himself from past major versions:
From https://github.com/goatfungus/NMSSaveEditor/issues/657#issuecomment-1272008266

> So update has just dropped, and it contains some pretty significant changes to the save format itself. Reverse engineering this will be pretty complicated, so I'm not sure how long it will take to get a working version ready.
> 
> At the moment, only older saves can be viewed/edited, and once you open them in game they get saved in a new format.

Patch 5.0 - Worlds Pt 1 - is likely one of such, albeit perhaps worse as we cannot even open the saves, as the whole metadata changed.

Therefore, just chill out and let the man do his magic. If you are in a hurry, just change the game difficulty and you can play as it pleases you without any major work.

**Comment by optikuzz** [comment]
Likewise, after the update Worlds Part I: Update 5.0 it does not read saves. I'm waiting like everyone else.
![tinki-1](https://github.com/user-attachments/assets/97f50d36-b236-48de-9a6f-681ffa18aff7)

**Comment by SavieSIlverfall** [comment]
> A quick reminder from @goatfungus himself from past major versions: From [#657 (comment)](https://github.com/goatfungus/NMSSaveEditor/issues/657#issuecomment-1272008266)
> 
> > So update has just dropped, and it contains some pretty significant changes to the save format itself. Reverse engineering this will be pretty complicated, so I'm not sure how long it will take to get a working version ready.
> > At the moment, only older saves can be viewed/edited, and once you open them in game they get saved in a new format.
> 
> Patch 5.0 - Worlds Pt 1 - is likely one of such, albeit perhaps worse as we cannot even open the saves, as the whole metadata changed.
> 
> Therefore, just chill out and let the man do his magic. If you are in a hurry, just change the game difficulty and you can play as it pleases you without any major work.

What's it with you people say we need to chill? I dont understand this mentallity. If something does not work, and the developer hasnt bassically responded for over a month to topics and stuff, you shouldnt just say 'let the magic happen'. You should notify him.

**Comment by HQuest** [comment]
Since you cannot chill nor understand why you must exercise patience, feel free to get in touch with him. His Patreon and email addresses are out there. Then, next time the tool breaks, you can do it instead of posting an issue on Github. Saves you the "hassle" of being asked to "chill", and you look less like an entitled 12 year old.

**Comment by SpectralCorbeaux** [comment]
> > A quick reminder from @goatfungus himself from past major versions: From [#657 (comment)](https://github.com/goatfungus/NMSSaveEditor/issues/657#issuecomment-1272008266)
> > > So update has just dropped, and it contains some pretty significant changes to the save format itself. Reverse engineering this will be pretty complicated, so I'm not sure how long it will take to get a working version ready.
> > > At the moment, only older saves can be viewed/edited, and once you open them in game they get saved in a new format.
> > 
> > 
> > Patch 5.0 - Worlds Pt 1 - is likely one of such, albeit perhaps worse as we cannot even open the saves, as the whole metadata changed.
> > Therefore, just chill out and let the man do his magic. If you are in a hurry, just change the game difficulty and you can play as it pleases you without any major work.
> 
> What's it with you people say we need to chill? I dont understand this mentallity. If something does not work, and the developer hasnt bassically responded for over a month to topics and stuff, you shouldnt just say 'let the magic happen'. You should notify him.

The Worlds patch came out yesterday, lil bro. Let the man cook.

**Comment by areithropos** [comment]
I would guess that it was meant as a reference to a new version of the game. Perhaps it sounded to older hands as if something unexpected was to be reported here.
The project here is a hobby and certainly not the focus of life for goatfungus (my assumption, if it is wrong, he may forgive me).
Every so often, we should not assume the worst when reading a text, even if the internet has accustomed us to the worst.

**Comment by SavieSIlverfall** [comment]
> Since you cannot chill nor understand why you must exercise patience, feel free to get in touch with him. His Patreon and email addresses are out there. Then, next time the tool breaks, you can do it instead of posting an issue on Github. Saves you the "hassle" of being asked to "chill", and you look less like an entitled 12 year old.

Since all you want to do is gaslight people and then proceed to insult people, I am just going to block you.

**Comment by jimmgc** [comment]
Here we go again. Entitlement at its best. Can't understand the constant requests to let GF knows about the tool not working on the YESTERDAYs update. I'm sure he knows and WILL get to fix it when HE HAS TIME. This is HIS project the we all decided to use it freely and willling to take the risks of modifying a game saves. Calm down people and let's wait until he get to work like he ALWAYS does. Like another user posted... he has a life and other responsibilities.

This was a BIG update changing a lot of the code and features on the game. So reverse engineering will take time. This is not the first time this happens and again GF always deliver.

This game has a great community and sucks to read posts of users rushing GF to fix the tool by posting the same issue all over again and again... And NO... don't ask him to share his project source code... he has no responsibility to share it. Program your own save editor if you can't wait.

Meanwhile, lets play and enjoy the new update. Sorry guys for the long post. Take care travellers.

**Comment by SavieSIlverfall** [comment]
It's just one single issue thats posted now that the patch has releaseed. Why are you so mad?

**Comment by david-ford** [comment]
Folks, this is not reddit. Please keep on topic and stop fighting about someone reporting an update to the game that breaks the editor. 

Thanks.

**Comment by Duncan-Disorderly** [comment]
> Likewise, after the update Worlds Part I: Update 5.0 it does not read saves. I'm waiting like everyone else. ![tinki-1](https://private-user-images.githubusercontent.com/160212442/350030939-5a0c9c2c-c04b-4613-b1ad-50194d572119.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTI3MzksIm5iZiI6MTcyMTM1MjQzOSwicGF0aCI6Ii8xNjAyMTI0NDIvMzUwMDMwOTM5LTVhMGM5YzJjLWMwNGItNDYxMy1iMWFkLTUwMTk0ZDU3MjExOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMTI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmJhYjg2NzAzZjU3ZmQ4ZjI2MDNlYTU5MzkzOTMyNDA4MTVlNjIwZmM4N2JiN2JhNWYwNWZlYjQ1ZGI2MDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ru7QJZgw1b60P9QZ9JvNGh5XkjTz2T3pyAM2kFXuTW4)

I must say, I adore the pic. It appears to be a very patient looking creature. So much so, it can be described as a living embodiment of patience. We have much to learn from such creatures. For a start, can this creature move? If so, how does a living beanbag chair get out and about? Quite possibly it has legs, but since they're folded underneath the umm... let's call it a blobby. Another possibility could be under the blobby, with a muscular system that ripples and effectively propels it forward. If I can buy one on EBay, my questions will be answered.      

Forgive me for going off topic, but I found the pic fascinating, and felt compelled to comment about it. Whether it was the multiple shots of vodka I had earlier that compelled me is not important. What's important is the lesson it teaches us about patience. So... I suppose it is on topic, as the advice to be patient seems most sound. In the meantime, we can have a giggle.

**Comment by JihuanHu** [comment]
Maybe we all forgot how to play a game without editors and cheaters. Just chill.

**Comment by SingularityAnon** [comment]
> Maybe we all forgot how to play a game without editors and cheaters. Just chill.

It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyways I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!! 

So I am refreshing this constantly so I can enjoy the game again :)

**Comment by areithropos** [comment]
> > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> 
> It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyways I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> 
> So I am refreshing this constantly so I can enjoy the game again :)

Exactly, issues with earlier versions of the game was my incentive to search for a save file editor and goatfungus saved me with his editor back then, and I kept it updated ever since. For me, it was a broken quest line, but I would rather not start over again.
People hopefully enjoy the game and try to relax, and this editor is a good lifesaver, or you can make your game even easier; well, as long as people enjoy it, gaming works as intended.

**Comment by kalkishnu** [comment]
> Maybe we all forgot how to play a game without editors and cheaters. Just chill.

maybe you should save your opinion on how to play games for your social networks and also stap assuming everyone likes to grind pixels.

**Comment by foxpur** [comment]
[NMSSaveEditor.log](https://github.com/user-attachments/files/16316836/NMSSaveEditor.log)

Just in case you still need it...

But, as said, it's new. I understand.

**Comment by JihuanHu** [comment]
> > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> 
> maybe you should save your opinion on how to play games for your social networks and also stap assuming everyone likes to grind pixels.

Maybe you should chill. I just don’t understand how someone can get so offended like you

**Comment by JihuanHu** [comment]
> > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> 
> It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> 
> So I am refreshing this constantly so I can enjoy the game again :)

Dude you don’t need to tell me how important this thing is. All I wanted to say is that wait patiently. If you can’t wait, as previously stated, you are free to make one on your own.

**Comment by SingularityAnon** [comment]
> > > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> > 
> > 
> > It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> > So I am refreshing this constantly so I can enjoy the game again :)
> 
> Dude you don’t need to tell me how important this thing is to you. All I wanted to say is that wait patiently.

No what you said is we forgot how to play without editors or cheaters, and I am being very patient Thanks :)

**Comment by JihuanHu** [comment]
> > > > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> > > 
> > > 
> > > It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> > > So I am refreshing this constantly so I can enjoy the game again :)
> > 
> > 
> > Dude you don’t need to tell me how important this thing is to you. All I wanted to say is that wait patiently.
> 
> No what you said is we forgot how to play without editors or cheaters, and I am being very patient Thanks :)

Yeah I think I am not referring to you. You just admit that by replying to me.

**Comment by JihuanHu** [comment]
By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor is not working, you came to the thread and saw this post, and then you know you should wait for the author to update it?

**Comment by foxpur** [comment]
> By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor was not working, you came to the repo and saw this post, and then you know you should wait for the author to update it? Is the “last commit date” too complicated to understand for some of you?

I could have started a new thread with the same, but seemed a bit repetitive, so I just added my log. I remind that this is exactly what the read.me of the editor says to do, so even thought it just happened the response to make a post of the error is by Dev of the project.

**Comment by cjg67** [comment]
With people using the issues as a forum for ranting that they can not use the save editor when a major update has happened, it makes me long for the days when I was on the internet BEFORE it was ever made public.  Those days we could get emails responded to without spammers or anyone under the age of 18 posting crap everywhere.  It was a tool for the ADULT learning institutions and was great.  Then along came spammers and bloody businesses screwing everything up.
I am an IT professional and all of these moans about things being broken, when the author is FULLY aware just makes me sick.

**Comment by SavieSIlverfall** [comment]
> By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor was not working, you came to the repo and saw this post, and then you know you should wait for the author to update it? Is the “last commit date” too complicated to understand for some of you?

Get out of my topic.

All you're doing is gaslighting. If people wanna bump this topic, they can do it.;

**Comment by JihuanHu** [comment]
> > By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor was not working, you came to the repo and saw this post, and then you know you should wait for the author to update it? Is the “last commit date” too complicated to understand for some of you?
> 
> Get out of my topic.
> 
> All you're doing is gaslighting. If people wanna bump this topic, they can do it.;
> 
> > > > > > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> > > > > 
> > > > > 
> > > > > It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> > > > > So I am refreshing this constantly so I can enjoy the game again :)
> > > > 
> > > > 
> > > > Dude you don’t need to tell me how important this thing is to you. All I wanted to say is that wait patiently.
> > > 
> > > 
> > > No what you said is we forgot how to play without editors or cheaters, and I am being very patient Thanks :)
> > 
> > 
> > Yeah I think I am not referring to you. You just appeared from nowhere and admitted that by replying to me again. You are very patient indeed.
> 
> We dont fucking care about your dumb opinion.

Who's we? I didn't even comment on you. So many crying babies who doesn't even know how GitHub works lol.

**Comment by SingularityAnon** [comment]
> > > By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor was not working, you came to the repo and saw this post, and then you know you should wait for the author to update it? Is the “last commit date” too complicated to understand for some of you?
> 
> > 
> 
> > Get out of my topic.
> 
> > 
> 
> > All you're doing is gaslighting. If people wanna bump this topic, they can do it.;
> 
> > 
> 
> > > > > > > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> 
> > > > > > So I am refreshing this constantly so I can enjoy the game again :)
> 
> > > > > 
> 
> > > > > 
> 
> > > > > Dude you don’t need to tell me how important this thing is to you. All I wanted to say is that wait patiently.
> 
> > > > 
> 
> > > > 
> 
> > > > No what you said is we forgot how to play without editors or cheaters, and I am being very patient Thanks :)
> 
> > > 
> 
> > > 
> 
> > > Yeah I think I am not referring to you. You just appeared from nowhere and admitted that by replying to me again. You are very patient indeed.
> 
> > 
> 
> > We dont fucking care about your dumb opinion.
> 
> 
> 
> Who's we? I didn't even comment on you and you are pretending to care about your post now? I saw how YOU gaslighted others. So many crying babies who don't even know how GitHub works lol.

Bro aren't you the one who said Chill? I'm thinking that's some good advice lol, this turned into a warzone 🤣

**Comment by SavieSIlverfall** [comment]
> > > By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor was not working, you came to the repo and saw this post, and then you know you should wait for the author to update it? Is the “last commit date” too complicated to understand for some of you?
> > 
> > 
> > Get out of my topic.
> > All you're doing is gaslighting. If people wanna bump this topic, they can do it.;
> > > > > > > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> > > > > > 
> > > > > > 
> > > > > > It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> > > > > > So I am refreshing this constantly so I can enjoy the game again :)
> > > > > 
> > > > > 
> > > > > Dude you don’t need to tell me how important this thing is to you. All I wanted to say is that wait patiently.
> > > > 
> > > > 
> > > > No what you said is we forgot how to play without editors or cheaters, and I am being very patient Thanks :)
> > > 
> > > 
> > > Yeah I think I am not referring to you. You just appeared from nowhere and admitted that by replying to me again. You are very patient indeed.
> > 
> > 
> > We dont fucking care about your dumb opinion.
> 
> Who's we? I didn't even comment on you and you are pretending to care about your post now? I saw how YOU gaslighted others. So many crying babies who don't even know how GitHub works lol.

You keep respondign here and you contineud what another user started.

Stop posting here if you're not going to contribute. All you're doing is gaslighting and you defended a person whom started this.

We are using github to report it. Deal with it. We are perfectly fine and capible of doing so.

The only crying baby is you whom cant handle how 1 singular topic was made.
\

**Comment by kalkishnu** [comment]
> > > By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor was not working, you came to the repo and saw this post, and then you know you should wait for the author to update it? Is the “last commit date” too complicated to understand for some of you?
> > 
> > 
> > Get out of my topic.
> > All you're doing is gaslighting. If people wanna bump this topic, they can do it.;
> > > > > > > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> > > > > > 
> > > > > > 
> > > > > > It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> > > > > > So I am refreshing this constantly so I can enjoy the game again :)
> > > > > 
> > > > > 
> > > > > Dude you don’t need to tell me how important this thing is to you. All I wanted to say is that wait patiently.
> > > > 
> > > > 
> > > > No what you said is we forgot how to play without editors or cheaters, and I am being very patient Thanks :)
> > > 
> > > 
> > > Yeah I think I am not referring to you. You just appeared from nowhere and admitted that by replying to me again. You are very patient indeed.
> > 
> > 
> > We dont fucking care about your dumb opinion.
> 
> Who's we? I didn't even comment on you and you are pretending to care about your post now? I saw how YOU gaslighted others. So many crying babies who don't even know how GitHub works lol.

you are the one not understanding this is to report an issue not to post your normie opinion.

**Comment by goatfungus** [comment]
Sorry guys, I didn't have time to read all the arguments above, and by the looks of the last one (above) I probably don't want to ;)

Anyway, I have been out for the last few days due to a medical emergency and have not had a chance to review the update, but I'm in the process of working through it now. I already have a fix for the metadata issue on the Steam version, and should have at least the first fix out later today. Please be patient, and please be kind to eachother.

For for info, see #1019

**Comment by JihuanHu** [comment]
> > > > By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor was not working, you came to the repo and saw this post, and then you know you should wait for the author to update it? Is the “last commit date” too complicated to understand for some of you?
> > > 
> > > 
> > > Get out of my topic.
> > > All you're doing is gaslighting. If people wanna bump this topic, they can do it.;
> > > > > > > > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> > > > > > > 
> > > > > > > 
> > > > > > > It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> > > > > > > So I am refreshing this constantly so I can enjoy the game again :)
> > > > > > 
> > > > > > 
> > > > > > Dude you don’t need to tell me how important this thing is to you. All I wanted to say is that wait patiently.
> > > > > 
> > > > > 
> > > > > No what you said is we forgot how to play without editors or cheaters, and I am being very patient Thanks :)
> > > > 
> > > > 
> > > > Yeah I think I am not referring to you. You just appeared from nowhere and admitted that by replying to me again. You are very patient indeed.
> > > 
> > > 
> > > We dont fucking care about your dumb opinion.
> > 
> > 
> > Who's we? I didn't even comment on you and you are pretending to care about your post now? I saw how YOU gaslighted others. So many crying babies who don't even know how GitHub works lol.
> 
> You keep respondign here and you contineud what another user started.
> 
> Stop posting here if you're not going to contribute. All you're doing is gaslighting and you defended a person whom started this.
> 
> We are using github to report it. Deal with it. We are perfectly fine and capible of doing so.
> 
> The only crying baby is you whom cant handle how 1 singular topic was made.

Since the author has posted a heads up, those who are upset can take a break instead of continuing to demonstrate their lack of education.

**Comment by JihuanHu** [comment]
> Sorry guys, I didn't have time to read all the arguments above, and by the looks of the last one (above) I probably don't want to ;)
> 
> Anyway, I have been out for the last few days due to a medical emergency and have not had a chance to review the update, but I'm in the process of working through it now. I already have a fix for the metadata issue on the Steam version, and should have at least the first fix out later today. Please be patient, and please be kind to eachother.
> 
> For for info, see #1019

Thanks for the heads up and thanks for your continuing support

**Comment by JihuanHu** [comment]
> > > > By the way, I don’t know some of you guys’ problem, but you are definitely not as patient as you claimed to be. Isn’t it pretty obvious that you found out that the editor was not working, you came to the repo and saw this post, and then you know you should wait for the author to update it? Is the “last commit date” too complicated to understand for some of you?
> > > 
> > > 
> > > Get out of my topic.
> > > All you're doing is gaslighting. If people wanna bump this topic, they can do it.;
> > > > > > > > Maybe we all forgot how to play a game without editors and cheaters. Just chill.
> > > > > > > 
> > > > > > > 
> > > > > > > It's not like that. Put yourself in my shoes for a second, I played for Years on Permadeath and fell in LOVE with this game. I did everything in the game I could and was doing Every single expedition as they came out. Well one day a Pirate Player murdered me INSIDE the anomaly, a safe zone. I could've sworn I had no PVP enabled, didn't matter as the game was glitched at the time and i took damage that another player recieved. Anyways I lost it all. In my haste of Dying I shut my system off to try and save myself.. well the whole game glitched as I had never played Normal mode so I lost every single Expedition I had ever done. Anyway years later I choose to get back on and wanna come back with save editor to get my lost progress of hours and hours lost but choose (unknowingly) the day of the update lol!!
> > > > > > > So I am refreshing this constantly so I can enjoy the game again :)
> > > > > > 
> > > > > > 
> > > > > > Dude you don’t need to tell me how important this thing is to you. All I wanted to say is that wait patiently.
> > > > > 
> > > > > 
> > > > > No what you said is we forgot how to play without editors or cheaters, and I am being very patient Thanks :)
> > > > 
> > > > 
> > > > Yeah I think I am not referring to you. You just appeared from nowhere and admitted that by replying to me again. You are very patient indeed.
> > > 
> > > 
> > > We dont fucking care about your dumb opinion.
> > 
> > 
> > Who's we? I didn't even comment on you and you are pretending to care about your post now? I saw how YOU gaslighted others. So many crying babies who don't even know how GitHub works lol.
> 
> You keep respondign here and you contineud what another user started.
> 
> Stop posting here if you're not going to contribute. All you're doing is gaslighting and you defended a person whom started this.
> 
> We are using github to report it. Deal with it. We are perfectly fine and capible of doing so.
> 
> The only crying baby is you whom cant handle how 1 singular topic was made.

Friendly advice, don't try to embarrassing yourself even further. Same to @kalkishnu

**Comment by SavieSIlverfall** [comment]
> Friendly advice, don't try to embarrass yourself even further. Same to @kalkishnu
Friendly advice,  Stop posting like its some kind of general forum.

**Comment by SingularityAnon** [comment]
> Sorry guys, I didn't have time to read all the arguments above, and by the looks of the last one (above) I probably don't want to ;)
> 
> Anyway, I have been out for the last few days due to a medical emergency and have not had a chance to review the update, but I'm in the process of working through it now. I already have a fix for the metadata issue on the Steam version, and should have at least the first fix out later today. Please be patient, and please be kind to eachother.
> 
> For for info, see #1019

Thank you GF for your work, I hope whatever emergency you are going through gets all worked out!! Hope the best for you
