### ISSUE TITLE
Not working with worlds part 1

### ISSUE THREAD

**Issue by Chariot7000** [goatfungus/NMSSaveEditor#1015]
Seems that they changed the save files again

**Comment by cjg67** [comment]
What makes you so special that you have to start a new thread when IT HAS ALREADY BEEN REPORTED AND A NUMBER OF COMMENTS ALREADY POSTED.  YOU ARE NOT SPECIAL, JUST SCUM!!!!!!!

**Comment by Djimple** [comment]
This has already been posted here. Refer to the first post regarding this issue.

Do you actively choose not to use initiative or is it a learning disability?

**Comment by Chariot7000** [comment]
Sorry I didn't saw it, also vai tomar no seu c# don't need to be rude.

**Comment by SingularityAnon** [comment]
> Sorry I didn't saw it, also vai tomar no seu c#, don't need to be rude.

Yeah you poked the wasps nest hahaha GF knows and is working on it

**Comment by MetaIdea** [comment]
You can also use NomNom saveeditor which still works: https://github.com/zencq/NomNom

**Comment by Chariot7000** [comment]
NomNom is full of bugs, unfortunately everytime I use NomNom it causes more problems than benefits :(

**Comment by wkitty42** [comment]
NomNom also is not easily installed on Linux systems for use with NMS in a Proton bottle...

**Comment by Xerkxes** [comment]
> NomNom is full of bugs, unfortunately everytime I use NomNom it causes more problems than benefits :(

i can say this is the only one that works with 5.0 as of the moment. confirming 1:06am PH time SEA like literally yes it will bug out but just by changing the menu will fix most of it and it will apply. im pretty happpy it works the only thing is i dont know which ones are S's and such but by just some tinkering it works fine and perfect hhaha

**Comment by goatfungus** [comment]
Please see #1019
