### ISSUE TITLE
List of all Saveeditors >here<

### ISSUE THREAD

**Issue by MetaIdea** [goatfungus/NMSSaveEditor#1016]
For the time we are waiting for GF to update his great tool, I made a list with all available saveeditors existing:

List of all No Man's Sky Save Editors:
https://www.reddit.com/r/NoMansSkyMods/comments/137je90/list_of_all_no_mans_sky_save_editors/

Discord community specialized in nms saveediting:
[No Man's Sky Creative & Sharing Hub](https://discord.gg/AEXcap6)

**Comment by kalkishnu** [comment]
bro this is not your facebook page.. stap being a dumbass
