### ISSUE TITLE
Change the procgen of specialists to the new post-NEXT format (re-post)

### ISSUE THREAD

**Issue by travisnewman** [goatfungus/NMSSaveEditor#102]
This is in reference to #80 

We got off topic with that and the issue became more about the aside than the main issue, and it was closed when the aside was fixed. I shouldn't have brought up two situations in one issue.

Here's the original problem:

> I have a bug on my pre-NEXT save where all my specialists are in the ground to a certain degree. The korvax scientist is all the way under, the Vy'Keen weapon specialist and exocraft tech are about halfway, and the Gek overseer and farmer are just barely sunken.

> I have a feeling that this is due to the NPC height calculation changing. I've been on a few Korvax freighters, for instance, and they're all normal height but the NPCs on my Korvax freighter are GIANTS.

> There's a way to change the seed for the specialists, but you can't change the race (for kinda obvious reason). BUT they don't just say Korvax, Gek, Vy'Keen, it's Korvax (old), Gek (old), Vy'Keen (old). Is there any way we can switch between old and new models? Am I even understanding how that works properly?

And the original response before we got off-topic:

> I could add the ability to switch old specialists into new ones, but only in that direction (old->new). However, since the model is different they won't look the same as they did before, but by the sound of it you probably won't complain as long as it works.

I responded asking about this but since you closed the issue you may not get notifications for it. Sorry if you'd prefer a different way of re-bringing this up.

**Comment by goatfungus** [comment]
Ah yes... when multiple issues are brought up in one topic, sometimes i miss some when i fix the main one. Apologies.

I am just wondering, since this is really only a once off change, whether we should address it by giving instructions for the JSON editor? That way I won't have to code a new feature that rarely gets used.

**Comment by travisnewman** [comment]
That solution absolutely works for me. If I knew what needed to be changed I would be all over it.

**Comment by goatfungus** [comment]
In the JSON editor, navigate to the following tree entry:
"PlayerStateData"->"NPCWorkers"

You'll notice there are 5 NPC's, numbered 0-4, and each one has a "ResourceElement"->"Filename" value.

**Gek**
Old: "MODELS/PLANETS/NPCS/LOWERORDER/LOWERORDER.SCENE.MBIN"
New: "MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCGEK.SCENE.MBIN"

**Vy'Keen**
Old: "MODELS/PLANETS/NPCS/WARRIOR/WARRIOR.SCENE.MBIN"
New: "MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCVYKEEN.SCENE.MBIN"

**Korvax**
Old: "MODELS/PLANETS/NPCS/EXPLORER/EXPLORERIPAD.SCENE.MBIN"
New: "MODELS/COMMON/PLAYER/PLAYERCHARACTER/NPCKORVAX.SCENE.MBIN"

That should be all you need to change.

NOTE: I wouldn't recommend changing an NPC into a different race, but you probably could if you wanted to. Just note that all the dialogs would be out of whack.

**Comment by travisnewman** [comment]
Those instructions were solid, and as I expected that fixed them clipping into the floor!
