### ISSUE TITLE
Changes don't apply

### ISSUE THREAD

**Issue by Dedsmoll** [goatfungus/NMSSaveEditor#1023]
Hello when i create a new character and do sum changes via nmsse (add a pet, glyphes, etc) the changes doesn't apply to my save. Any solutions ?

**Comment by jdm12983** [comment]
Are you running your save at the same time you are trying to edit it? (Meaning, opened in the game and in the editor) If so, that's the main issue.

Best thing to do is be a the main screen of the game - the one just before you get to see you saves listed. That way the game makes sure to see the changed/updated files.

Also, after you make the changes in the editor; are you going back to the "main" tab and hitting the "Save Changes" button?

Not trying to act like you wouldn't know the simple things; but, sometimes little stuff can slip our minds.

**Comment by BONEGUNN** [comment]
I'm having a similar issue.

I use the editor to make changes, save at the main tab, open the game but none of my Editor saves are available to load. The only options are older saves that have nothing to do with the work I did in the editor.

I have checked the file path a thousand times. Everything is set up as intended.

I wouldn't bother you but I've been using this editor for several years and this is the first problem I've had running it.

I fear there may be an inconsistency with the most recent update.

If you have team viewer, I'd gladly compensate you for your time to troubleshoot the problem whether it is fruitful or not.

The game just isn't worth playing without your editor.

**Comment by Dedsmoll** [comment]
@jdm12983 : ye my game is running during the change and i save ofc x) im gonna try at the title screen as u recommend
@BONEGUNN : same, im using nmsse since almost 1 year and its the 1st time i've this issue, if i understood correctly this update change the metadata of the game so even if the editor has been updated for world he's still a bit broke for now but i guess nmsse's teamwill fix that later :)

**Comment by Dedsmoll** [comment]
@jdm12983 : the title screen technique works ! ty  ;*

**Comment by BONEGUNN** [comment]
The title screen technique did not work to solve my issue.
