### ISSUE TITLE
Unable to claim some expedition or twitch rewards

### ISSUE THREAD

**Issue by cam602** [goatfungus/NMSSaveEditor#1024]
So this is probably user error but I'm unable to claim some expedition or Twitch rewards. 

I have ticked all the boxes in the editor and they show up as available in the game but when I go to claim them them nothing happens. 

This specifically only occurs when trying to claim multi tools ships or eggs.

I have successfully been able to claim freighters and decorations.

Any fixes are much appreciated?

**Comment by Teallie** [comment]
+1

**Comment by 297146007** [comment]
+2

**Comment by Marc-Harony** [comment]
Same problem here since 2023.
The only rewards I can claim are the fireworks :(

**Comment by cam602** [comment]
> Each reward is also added in the Discovery tab as a Known Product under the Curiousity category, just be careful, more than just expedition/twitch rewards are in that category. It was them being present in known products that prevented me from claiming them

Thank you! This was it for me.

**Comment by wkitty42** [comment]
so the trick is to only select them in the Discovery tab and no where else? makes sense...
