### ISSUE TITLE
Account Items Not Owned In Game

### ISSUE THREAD

**Issue by NickThorby** [goatfungus/NMSSaveEditor#1028]
Hi there, 

Thanks for the super quick update!

I'm having one issue where all the account items I've added through the account tab show up as unowned in the quicksilver shop. My previously claimed items show as such, but anything else I cannot claim. 

After loading the save and reopening it in the save editor everything still shows as checked, so I'm not sure where the issue could lie.

**Comment by wkitty42** [comment]
did you see the (now closed) #1024 discussion? there's two places where an item can be enabled... for some, they have to be enabled in both places... for others, they have to be enabled in one of the places and not the other...

**Comment by NickThorby** [comment]
So I did see it, but I think I may be having a slightly different issue. In previous versions I had claimed rewards that I had enabled in the account tab, those still show up as claimed, but for everything else (including things that were previously unlocked for me, I just did not claim them at the time), they now say I must complete the exbidition? 

It's weird because it definitely worked in previous updates, are there maybe some new flags or something my save is missing? I've attached some screenshots so you can see what I mean.

<img width="1728" alt="Screenshot 2024-07-23 at 18 26 51" src="https://github.com/user-attachments/assets/52df8ec2-29fd-46b1-8d20-04d784747b11">

<img width="1728" alt="Screenshot 2024-07-23 at 18 26 29" src="https://github.com/user-attachments/assets/daa0980b-7dae-4a3b-ae52-379d9482e723">

<img width="1728" alt="Screenshot 2024-07-23 at 18 26 15" src="https://github.com/user-attachments/assets/a37a7a0c-d92a-43de-a739-340da43b0c20">

**Comment by NickThorby** [comment]
So after further research it seems this may be a Mac related issue, which makes sense since last time I played on PC.

https://www.reddit.com/r/NoMansSkyTheGame/s/NCDDcTkPuM

Haven't had a chance to test it yet but I will report back
