### ISSUE TITLE
Move Base Not Working

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#103]
gives me an error so it must be testing for something. worth mentioning that when I originally posted I did not realize there was one already on location. But since removed them, rebuilt one and tried again same effect.
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/2304122/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
Looks like the editor either can't find your base computer (^BASE_FLAG) or your signal booster (^BUILDSIGNAL) in your base structure. Both must exist for the swap to happen.

Have a look in your "PersistentPlayerBases" section using the JSON editor and check.

If you build your signal booster outside of the range of the base, or build it beforehand, it is possible that it will be placed in the landscape objects lists instead.

**Comment by ukmerlin** [comment]
What do you call "outside the range of the base"? that concerns me because my actual base is 100u's away from the computer which is why I wanted to move it.

**Comment by goatfungus** [comment]
That should be ok, providing the objects can be found in your base structure and not outside of it. Maybe the game is placing the signal booster as a landscape object because it is so far away?

What you could do is try moving the base computer in stages?

**Comment by ukmerlin** [comment]
Yes thought of that might give it a go. I think the save editor gives a value of complexity and mine is up in the 600 range so I have to believe the game is treating my base as exactly that.

**Comment by ukmerlin** [comment]
OK tried to do it from within 20u and got the same result.

**Comment by goatfungus** [comment]
Did you check the JSON editor?

Should be really easy to do.
- Go to "PersistentPlayerBases"->[the base number]
- Search for "^BUILDSIGNAL"

**Comment by ukmerlin** [comment]
OK so I checked JSON and there was no buildsignal. After some putting down and taking up of the signal I managed to get incremental movements of the base comp to its final resting place. What I noticed is that the NMSE is now taking significantly longer to load and sometimes when there were game changes and sometimes when there are NMSE saves the file is actually not saved. So for example I might move the signal, save, pull into NMSE and load, move the base, save and reload the game point but it would not have moved. Not going to think about it too much any more I am encouraged to see that the base comp is in a more intelligent place and that according to the save file all the stuff I built is considered in that base. THANK YOU.......... :)

**Comment by goatfungus** [comment]
All good!

**Comment by ukmerlin** [comment]
It would be good if you can somehow orient it, problem is the signal booster does not really have a front. What I found is that if you teleport to the base the ship can end up all the way into the buildings. I think I can offset the movement to be outside but then still at the mercy of where the rotation could put it which might be back in the building.
