### ISSUE TITLE
the editor is not working

### ISSUE THREAD

**Issue by KurogaDH** [goatfungus/NMSSaveEditor#1035]
![image](https://github.com/user-attachments/assets/f9aad24a-2c35-40a5-ae08-89c336a6f908)
 the editor is not working, it does not see my saves, I try to select, but nothing happens

**Comment by CatThatPlaysGames** [comment]
I mean you got further than me thats for sure i cant even choose a save path
![image_2024-07-25_170607684](https://github.com/user-attachments/assets/f6d18242-e4ea-43f7-8352-401ca9af378d)

**Comment by BONEGUNN** [comment]
damn

**Comment by BONEGUNN** [comment]
That latest update must have bricked the whole show.

**Comment by BONEGUNN** [comment]
weird... did the file save path change with the new NMS update?

**Comment by KurogaDH** [comment]
> странно... изменился ли путь сохранения файла с новым обновлением NMS?

No

**Comment by Devilin-Pixy** [comment]
@KurogaDH Make sure to select the correct folder where your saves are actually located.
Below is an indication where to look, depending in the platform.
**Steam**
`%appdata%\HelloGames\NMS\st_<Steam64ID>\...`

**Game Pass**
`%LocalAppData%\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\...`

**GoG**
`%appdata%\HelloGames\NMS\DefaultUser\...`

**Linux** & **Steam Deck**
`$HOME/.local/share/Steam/steamapps/compatdata/275850/pfx/drive_c/users/steamuser/Application Data/HelloGames/NMS/st_<Steam64ID>/...`

**Mac**
`/Users/<yourname>/Library/Application Support/HelloGames/NMS/st_<your steam ID>/...`

**Comment by CatThatPlaysGames** [comment]
> @KurogaDH Make sure to select the correct folder (path) where your saves are actually located. Below is an indication where to look, depending on the platform. **Steam** `%appdata%\HelloGames\NMS\st_<Steam64ID>\...`
> 
> **Game Pass** `%LocalAppData%\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\...`
> 
> **GoG** `%appdata%\HelloGames\NMS\DefaultUser\...`
> 
> **Linux** & **Steam Deck** `$HOME/.local/share/Steam/steamapps/compatdata/275850/pfx/drive_c/users/steamuser/Application Data/HelloGames/NMS/st_<Steam64ID>/...`
> 
> **Mac** `/Users/<yourname>/Library/Application Support/HelloGames/NMS/st_<your steam ID>/...`




how do i fix my issue?

**Comment by KurogaDH** [comment]
@CatThatPlaysGames  The file path is specified correctly, but nothing new happens when you try to open the save file.

**Comment by Yiin** [comment]
Save path should look similar to this
![image](https://github.com/user-attachments/assets/83a08d81-b660-408a-aebe-034183e62938)

Not `C:\Users\User\Desktop`

**Comment by jdm12983** [comment]
> ![image](https://private-user-images.githubusercontent.com/173341134/352031622-f9aad24a-2c35-40a5-ae08-89c336a6f908.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTkxNTAsIm5iZiI6MTcyMjAxODg1MCwicGF0aCI6Ii8xNzMzNDExMzQvMzUyMDMxNjIyLWY5YWFkMjRhLTJjMzUtNDBhNS1hZTA4LTg5YzMzNmE2ZjkwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxODM0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjZmMzkxZTBmMjhkOWE4ZWEzZmViNWFjNGIyOGZhMDE5MWJmMjUyZTJiZTNhMGU2NTA2NzgyMjFlOTM1YzQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4eIFN0nYYIXdLLjpOor6oT408Vq0_epmTjKOm-qXYQs) the editor is not working, it does not see my saves, I try to select, but nothing happens

Unless you fixed it after you took the screen shot; your editor is trying to find th4e save files on your "desktop" folder -- and not where they actually are. That's why it's blank.

At the top, choose "File" then "Open File/Path" - choose the correct one from what Devilin-Pixy mentioned earlier. See if that works.,

**Comment by KurogaDH** [comment]
the path worked, it didn't work before and I thought it was because of the game folder and just tried to start saving separately

**Comment by dkeeg18** [comment]
This thread is useless. Saving changes does nothing. Changing your save path does nothing. The app is fucking useless after one use. And there is not one video, not one link, not one thread, nothing that explains how to fix it. I used it once and it worked and after I used it it stopped working. Trouble shooting for hours to no avail. An extremely frustrating waste of my very finite free fucking time. Fuck the creators of this dog shit app.

**Comment by mydevpeeps** [comment]
> This thread is useless. Saving changes does nothing. Changing your save path does nothing. The app is fucking useless after one use. And there is not one video, not one link, not one thread, nothing that explains how to fix it. I used it once and it worked and after I used it it stopped working. Trouble shooting for hours to no avail. An extremely frustrating waste of my very finite free fucking time. Fuck the creators of this dog shit app.

reported for being an asshole.
