### ISSUE TITLE
Edited save file not the same when reloaded in the game NMS Worlds pt1 (Steam)

### ISSUE THREAD

**Issue by DJ-Kav** [goatfungus/NMSSaveEditor#1041]
1. There seems to be a bug with the inventories not getting updated in the game.
- I can make all the changes in the editor and then save the file,
- Go back into the game and I can see the new save file time stamp, so I can see that the editor has saved the file.
- In game, the inventories have not changed to reflect what was in the editor.
- If I delete an item from the 'ship cargo', then it's reflected in the editor when I reload the save.
- It's the same if you refill all items and save in the editor. The change doesn't affect the in game items.
- I've added a screen shot of the ships cargo, so you can see that they're different. This is taken after adding an item to the cargo in the editor, but not there in game. 

2. The save editor doesn't auto detect when the game saves, while the editor is open. 
- It used to in previous versions. If I manually reload the save file in the editor, it updates to the latest save. 

Save editor screen shot of ship cargo
<img width="1163" alt="NMS Save Editor" src="https://github.com/user-attachments/assets/0b873d39-790b-47a7-9a88-9e9f47e57a0c">

In-game screen shot of ship cargo
<img width="1920" alt="NMS Screen-shot" src="https://github.com/user-attachments/assets/4d6a0c9f-2809-4bc5-aaf8-7161b3cde275">

**Comment by TheFlano23** [comment]
How did you fix this issue?
