### ISSUE TITLE
Ininite loading screen after editing older save

### ISSUE THREAD

**Issue by Abysss1356** [goatfungus/NMSSaveEditor#1044]
PC Xbox game pass version. I used the save editor to edit my main save from the update before 'worlds'. The only change i made was learning all of the words in each language. After this, I saved the file, and now every time I try to load the game, it shows the red circle loading icon infinitely. Could this be caused by the game not being able to read the format of this save file after the change to how saves are formatted on the game pass version?
(I dont know for sure if this change was made, I read that the save format changed with the new Worlds update somewhere here.)

**Comment by areithropos** [comment]
The best thing to do is restoring the backup of the save file and load it with the current version of the game. Afterward, you save the game and exit the game and then edit the save file. That is how I did for years, and it worked so far without any trouble. There should be a backup in the backup folder of this editor.

**Comment by Abysss1356** [comment]
> The best thing to do is restoring the backup of the save file and load it with the current version of the game. Afterward, you save the game and exit the game and then edit the save file. That is how I did it for years, and it worked so far without any trouble. There should be a backup in the backup folder of this editor.

I tried restoring a backup (and I think I did it correctly) but even after that I'm unable to load up the game because of the infinite loading screen. I also can't be sure the backup was for the save I'm referring to but it was the only recent backup in the folder. 

Right now I'm hoping that the next save editor update might make some difference, I really don't want to lose my 300h or so that I've put into that save.

**Comment by Devilin-Pixy** [comment]
@Abysss1356 See here: https://hellogames.zendesk.com/hc/en-us/articles/20347739760786-Can-t-load-in-to-game-stuck-on-red-spinning-load-screen-on-Xbox
This should see a fix soon and is not caused by the Save Editor!

**Comment by Abysss1356** [comment]
> @Abysss1356 See here: https://hellogames.zendesk.com/hc/en-us/articles/20347739760786-Can-t-load-in-to-game-stuck-on-red-spinning-load-screen-on-Xbox This should see a fix soon and is not caused by the Save Editor!

@Devilin-Pixy Sadly, this didn't work because, although my issue also causes the infinite loading screen, it has a different cause. This method did bypass the red circle loading screen, but then I became stuck loading forever on the title screen for the same reason as the red circle screen. I definitely caused the problem by editing one of my saves at a bad time in terms of compatability between the save editor and the PC game pass version of NMS.

**Comment by Abysss1356** [comment]
The new patch/update has fixed my issue, i expect it converted the file back to the expected format allowing the game to read it and letting me into the game.
