### ISSUE TITLE
Rechargable upgrades not functioning

### ISSUE THREAD

**Issue by electrodude102** [goatfungus/NMSSaveEditor#105]
I noticed that I have Thermal and Toxic module upgrade technology that don't function. they are fully charged but my default hazard drops to zero as if they weren't installed. 

not sure what the deal is, I noticed when adding through NMSSE they "auto install" to the slot, maybe you could just add the module and have the user install them themselves, idk if that would help?

edit using 1.5.19b

**Comment by goatfungus** [comment]
I had issues with that myself on an unedited save. It was because i had a second Thermal module elsewhere and the game only ever used one of them. I deconstructed the other module and it was working again.

Unfortunately the editor can't really fix bugs that occur in the game itself.

**Comment by electrodude102** [comment]
hmm, Currently, I have one (s)thermal upgrade and one (s)toxic upgrade, neither of which are working.

My original (b)Toxic Upgrade worked fine until I added an S-class (and deleted the b-class) that's why I figured it was an NMSSE issue.
