### ISSUE TITLE
Weird behaviour of all window elements when mouse overing. 

### ISSUE THREAD

**Issue by ulukator** [goatfungus/NMSSaveEditor#106]
Program starts normal and I can work for some time, but if left open for a few hours - something happens with it and program window starts bugging out. Reopening helps. Today I got a new version and this bug happens after 10-15 seconds of tinkering, not hours. It became annoying to a very high level.
Screenshot attached.

![nms save editor bug screen](https://user-images.githubusercontent.com/42574482/44399630-fb7c6380-a550-11e8-8191-c8a28054ff75.JPG)

![nms-bug-2](https://user-images.githubusercontent.com/42574482/44399775-6f1e7080-a551-11e8-8bfb-ce2771e56f8f.JPG)

**Comment by goatfungus** [comment]
People have seen similar issues when using programs that produce overlays in windows. Shutting them down often solves the problem.

**Comment by ulukator** [comment]
If only I knew what is an overlay and what is the program to produce them. I dont use anything special, just a browser and a steam. And nvidia soft + msi afterburner. So.... what could it be? Gimme an example of such software, because I'm an old long retired sysadmin who knows nothing of modern things.
