### ISSUE TITLE
any baning isue?

### ISSUE THREAD

**Issue by RenzelxSpark** [goatfungus/NMSSaveEditor#1060]
im just curious if it can end in any kind of baniment for my game, never used a save editor before

**Comment by RenzelxSpark** [comment]
sorry my bad english, im not american

**Comment by wkitty42** [comment]
no... AFAIK no one has ever been banned from NMS... there's maybe one or two extreme cases but only hearsay...

remember, NMS is a single player with multiplayer sharing... there is no ranking, no scores, and no competition... without those there is no "cheating" or anything to possibly be banned for... your edits in your save affect only your game...
