### ISSUE TITLE
Raw json viewer right panel blank

### ISSUE THREAD

**Issue by viperesque** [goatfungus/NMSSaveEditor#107]
As of version 1.5.19b, I'm having an issue with the raw json viewer where the right panel is permanently blank. Closing and reopening the editor lots of times got it to correctly display on one occasion, and I was able to browse normally. However, the program crashed shortly thereafter and I've been unable to replicate any of the above since.

![image](https://user-images.githubusercontent.com/32559972/44400447-86c81a00-a58e-11e8-9af2-e8176589e08f.png)

**Comment by goatfungus** [comment]
This is the same issue as #98, which I'm trying to solve, so I'll close this one.
