### ISSUE TITLE
Exo-Skiff not in editor

### ISSUE THREAD

**Issue by set-patch** [goatfungus/NMSSaveEditor#1071]
I miss the option to change the inventory of the new Exo-Skiff in the Aquarius Update. Or am I just missing it? In the quick menu, it can be accessed in the "summon vehicles --> summon exo-skiff" section. It would also be nice if you could add the many new fish to the editor.

**Comment by goatfungus** [comment]
It's not in the editor yet, I just need time to get it ready.

**Comment by goatfungus** [comment]
Thanks for your patience, the Skiff - Cold Storage inventory has now been added to the vehicles tab. I've also added all the fish :)

**Comment by set-patch** [comment]
Thank you for quick support.
