### ISSUE TITLE
Name mappings not found

### ISSUE THREAD

**Issue by kostermw** [goatfungus/NMSSaveEditor#1072]
Receiving warnings (since a long time). See screenshot. Don't think it is critical ;-)
![image](https://github.com/user-attachments/assets/a9032df5-37c4-4ea2-9dd2-836b95937ac2)

**Comment by tehface** [comment]
ya he's prolly still working on them, patience :)

**Comment by goatfungus** [comment]
Yup, this should be fixed now.
These warnings are not critical, so you can still use the editor even if you seen these in future.
