### ISSUE TITLE
Exocraft slots unaffected.

### ISSUE THREAD

**Issue by OwlStation** [goatfungus/NMSSaveEditor#1077]
I cannot seem to expand the slot inventory or supercharge the slots. 
Adding inventory to preexisting slots work, and adding technology works 
But the slots themselves are having an issue saving in supercharged mode.

**Comment by goatfungus** [comment]
The game itself doesn't allow you to change the Exocraft inventory slots structure, so I have blocked the changes in the editor too.

**Comment by OwlStation** [comment]
Gotcha, ill just use mods or something.  Thanks again for updating!!
