### ISSUE TITLE
Iron Vulture

### ISSUE THREAD

**Issue by Sweet-heart-bakho** [goatfungus/NMSSaveEditor#1081]
Recently i accidently deleted my ship Iron Vulture (from expidition ADRIFT), i wanted to get it back
![screenshot](https://github.com/user-attachments/assets/39d393ca-8faa-465d-a500-af6f25c8b931)
I clearly remember that he was on this list before, but now he is not, please add him

**Comment by Devilin-Pixy** [comment]
It should indeed be listed there. Hopefully @goatfungus will add it back again with a future update.
Doing it this way on the save itself however, would only change an existing ship model to the model of an Iron Vulture. This would not quite be the same as actually claiming this ship.

Assuming you unlocked the iron Vulture account wide and already having claimed it previously on this save, you'd best undo the claim part, so you can just get it at the QS Shop on the Anomaly again. To do so, you'd have to edit the Raw JSON and remove lines from the save data containing the Iron Vulture ID: `^EXPD_SHIP13`

Click the 'Edit' tab and select 'Edit Raw JSON'. A new window opens up.
On the left side you can navigate to the right section by expanding sections.
You are looking for 'BaseContext > PlayerStateData > KnownSpecials' (reasonably close to the top)
Select that section on the left and on the right side you look for the line containing the ID mentioned above.
If you wish, you can use 'search' by pressing <CTRL> + F
Once found, you have to make sure to completely delete the full line, see Images below.
If it was the very last line in the list, you have to make sure to also remove the comma `,` from the line that is now last listed there.
Once done, click somewhere else on the left side, and it will ask to confirm your changes, making sure you click 'Yes'
![image](https://github.com/user-attachments/assets/15729a1e-1b69-4569-b317-0c26e3d695c5)
![image](https://github.com/user-attachments/assets/af982b03-fdb0-4497-ba81-02067d18a811)

For the next section on the left, you are looking for 'BaseContext > PlayerStateData > RedeemedSeasonRewards' (close to the end)
Here you do the same on the right side, looking for the ID, to completely remove the line containing it.
Make sure you check for the last listed line to not end with a comma. See images below, noting how I did have to remove a comma here for the last listed item.
![image](https://github.com/user-attachments/assets/74c2fd15-990a-45e8-ba03-e5421bbb0146)
![image](https://github.com/user-attachments/assets/8e9d86a7-b957-4276-806b-b8fb714462cb)
Once done, you can close the editor window, making sure to confirm changes.
Then lastly you have to save once more on the actual 'Main' tab.

That should do it, the Iron Vulture should now be available for claiming again at the QS shop on the Anomaly.

**Comment by Sweet-heart-bakho** [comment]
thx that really help me

**Comment by Sweet-heart-bakho** [comment]
close

**Comment by Necirays** [comment]
Can confirm exporting it from another save and importing it back to main save doesn't work, because it's marked as a Hauler and the basic seed just makes a random hauler with all the stats and tech, but not the Iron Vulture.

I can confirm Devilin's solution worked and that's a relief ! TThere is still a bug in the game 1 year after the expedition where if you claim the Iron Vulture when you're ship inventory is full, it just never appears...
I did what you suggested and it finally solved my problem
