### ISSUE TITLE
Where is the last Season Reward and which one is it?

### ISSUE THREAD

**Issue by Kafpai** [goatfungus/NMSSaveEditor#1084]
It's a silly question but my ocd is tripping me up. I counted 175 season rewards in the save editor list. but in game i  can only claim 174 I'd like to know which one I'm missing is there any way to find this out easily? thanks in advance.

**Comment by Devilin-Pixy** [comment]
The list has `EXPD_ODD_EGG` (Void Egg) listed, which is not listed as a season reward in the shop, unless you are on a Nintendo Switch. This was a Switch exclusive reward due to the platform having no multiplayer.
