### ISSUE TITLE
Can I have access to the souce code?

### ISSUE THREAD

**Issue by emilio-simoes** [goatfungus/NMSSaveEditor#1093]
As you describe in your redame:

```
Since No Man's Sky first came out, there have been many notable game-breaking bugs as well as many parts of the game that seemed too grindy and not much fun. Some of the bugs had workarounds or later patches to fix them, but others simply stopped your progress. Either way, I just want to enjoy the game!
```
I feel the same way but the Aquarious update just broke this app. As a developer myself I understand that work comes first but this app happened, the community relies on it and just ignoring the issues will not help anyone.

Open your code to collaborators, I'm sure lot's of us would like to help and add faster fixes to the app. After this many years there's some times i also feel that I need a break from this game, but all the new players do not! And your original feeling still stands.

Is there any one else who would like to contribute to this app? There's a community around NMS, why can't we create a community around this app too?

Raise your hand who would be willing to help and provide fixes and improvements to this app?

**Comment by goatfungus** [comment]
There haven't been many collaborators who have provided solutions even at a conceptual level, ie: figuring out what the structures in the save file actually DO. This is by far the biggest area of need in the editor space. For those who have found solutions at the JSON level, they have been happy providing the details and testing the pre-release versions, for which I have been grateful.

Having said that, the only people I see asking specifically for the source code are people who have had limited to no other interaction with myself or the rest of the users who frequent the chat space. This is your very first opened issue according to GitHub and it's only asking for source code without any example of what you'd actually like to _do_ in the editor itself. This raises the question of whether I should trust you, and my doubts have been confirmed by your recent messaging activity.

You have baselessly accused me of embedding virusses in the software, complained incessantly about not getting the source code on unrelated posts, and I just don't see how it would benefit anyone giving a detractor such as yourself access to do as you please. For all I know, you could _actually_ embed a virus in the code just out of spite, or steal the work for your own project and claim it was all original. I'm sorry, but for you the answer is a **no**.

**Comment by emilio-simoes** [comment]
What I was suggesting is making the code open source and accepting changes to pull requests like all the great open source projects do, changes are visible to every one, issues are easier to find and no one will be able to "steal" your code because it will eventually have a license and it will be public.

This is a model that has been successful for a lot of projects and for a long time. There is nothing wrong with sharing your code, hiding it on the other hand I'm not so sure.

A rest a sure that I particularly don't what to steal your code, but I'm sorry for having tried to help and for offering my help.

Good luck with your project, I'm sure you will make millions with it.
