### ISSUE TITLE
Supercharged All Slots on New Save

### ISSUE THREAD

**Issue by mohif71280** [goatfungus/NMSSaveEditor#1097]
On my main save I have enabled supercharge all slots on Exosuit, Ship and Multitool inventory.
This setting is now copying over when I start a new save.

I know I can go back in and edit the new save but how can I disable this behaviour?

**Comment by BetaTesterMKII** [comment]
It's not the editor it is the way the game handles saves, it keeps that info in cache and when you create a new save it transfers to it.

Just don't load that edited save before creating a new save, if you have quit your game and restart should be fine.

**Comment by mohif71280** [comment]
Thank you, that's really interesting to know!
