### ISSUE TITLE
Cant open up save file

### ISSUE THREAD

**Issue by gahnat** [goatfungus/NMSSaveEditor#1098]
After the new Corrupt Update I am now not able to edit my saves.

Received the following:
![image](https://github.com/user-attachments/assets/5b93764b-fc50-4163-b7b9-d22b5aaadb28)

**Comment by Nyrdin** [comment]
The pre-update savefile will be loaded but not the one created for Expedition 16.

**Comment by gahnat** [comment]
Thanks. Looking forward to the updates
