### ISSUE TITLE
Unable to access the Account tab in NMSSE

### ISSUE THREAD

**Issue by SevenDS** [goatfungus/NMSSaveEditor#1101]
hello dont know if i missed the memo but i van not able to access the account tab to change things i am currently playing normal game in the new  Cursed Expedition

**Comment by RicoAP** [comment]
u must wait for the update

**Comment by mshocklee** [comment]
See #1099 #1087 #1085

**Comment by goatfungus** [comment]
This should be fixed now, see version 1.17.6.
