### ISSUE TITLE
WARNING: cannot read file metadata: mf_save21.hg

### ISSUE THREAD

**Issue by Steveprivate** [goatfungus/NMSSaveEditor#1102]
I have the max number of saves (15). One of those saves (11) save21.hg and Save22.hg will not load into your save editor. The error message is in the title. The save, itself, will load properly into the game and appears to be completely playable. Can you help me solve this problem?

**Comment by mshocklee** [comment]
See #1099 #1087 #1085

**Comment by Steveprivate** [comment]
To [mshocklee](https://github.com/mshocklee), I updated Java 8 yesterday to ensure I was running the latest version. I am not playing on the Experimental branch. However, I do, on occasion, use that branch. With 15 different save files I cannot tell if this particular save was ever used on that branch.

**Comment by mshocklee** [comment]
I mentioned in #1099 that the original issue was from the experimental branch, but it looks like it has now been moved into the live game with the Cursed update.

**Comment by goatfungus** [comment]
This should be fixed now, see version 1.17.6.

**Comment by Steveprivate** [comment]
Same error.

Reading metadata for save21.hg
WARNING: cannot read file metadata: mf_save21.hg
Reading metadata for save22.hg
WARNING: cannot read file metadata: mf_save22.hg

[image: image.png]

**Comment by Steveprivate** [comment]
Wait, I just noticed that the script that you have enabled to check for and
install the latest update only got me to 1.17.5. Is 1.17.6 still being
tested?

**Comment by Steveprivate** [comment]
Okay, success. Had to manually install it  from the repository using the
second link. No errors now on Slot 11.

Sorry for the false alarm.

Thanks!  Regards
