### ISSUE TITLE
Save Editor will not load saves following the recent "The Cursed" update.  

### ISSUE THREAD

**Issue by DonQuixoteIII** [goatfungus/NMSSaveEditor#1103]

**Comment by DonQuixoteIII** [comment]
Log file stated that the editor cannot read the mf_accountdata.hg file
[NMSSaveEditor.log](https://github.com/user-attachments/files/17500991/NMSSaveEditor.log)

**Comment by Webmetalreese** [comment]
Same issue, reinstall/verify does nothing. The program can find the save data, simply does not load when you select. (Steam)

**Comment by nellyfrozen** [comment]
Looks like a good ol' Hello Games thing to do, breaking up any mod/save editor.
Any old save loaded in the editor can be edited ONE TIME, once you start the editor, but after that it won't show up in the select menu.
The errors are:
warning: cannot read file metadata: mf_accountdata.hg
warning: cannot read file metadata: mf_savexx.hg

**Comment by justcallmedots** [comment]
same issue here.

**Comment by mshocklee** [comment]
See #1099 #1087 #1085

**Comment by kobs57** [comment]
whewww! I thought it was me. I  do changes in the editor but nothing register in the game itaself

**Comment by goatfungus** [comment]
This should be fixed now, see version 1.17.6.

**Comment by DonQuixoteIII** [comment]
Thank you so much.  Can't live without your editor....
