### ISSUE TITLE
Old saved games disappear from the load menu, once edited, after latest NMS update "The Cursed".

### ISSUE THREAD

**Issue by nellyfrozen** [goatfungus/NMSSaveEditor#1104]
Any old save loaded in the editor can be edited ONE TIME, once you start the editor, but after that it won't show up anymore and once starting the editor you will get these errors:
warning: cannot read file metadata: mf_accountdata.hg
warning: cannot read file metadata: mf_savexx.hg

Looks like a good ol' Hello Games thing to do, breaking up any mod/save editor.
Playing over STEAM.

**Comment by nellyfrozen** [comment]
Issue is older than last day, waiting for save editor update I guess.

**Comment by mshocklee** [comment]
See #1099 #1087 #1085

**Comment by nellyfrozen** [comment]
> See #1099 #1087 #1085

Saw, yes.

**Comment by brooksie68** [comment]
Just adding a voice to say same issue here.

**Comment by kjboggs** [comment]
Ditto

**Comment by BearyO28** [comment]
Until the save editor is updated u probably won’t be able to use it

**Comment by Findarato** [comment]
Some one needs to clean all these issues up and compress them into one. Every one is having the same problem

**Comment by goatfungus** [comment]
This should be fixed now, see version 1.17.6.

**Comment by nellyfrozen** [comment]
Thnx, bro, works as intended.
Cheers!
