### ISSUE TITLE
Issues with save after game crash

### ISSUE THREAD

**Issue by GhStRdR2k** [goatfungus/NMSSaveEditor#1105]
While loading an autosave my game crashed. Upon restarting the game, my save was no longer visible in game. However it is still accessible with the save editor. I get this warning though when launching the editor.

Slot4Manual
version: 1
totalplaytime: 238:18
Reading account data...
Warning: name mapping not found: kRU
Warning: name mapping not found: v6E
 
Now, I can still edit the save and make changes to it which lists off a lot more of the "name mapping not found" errors. After saving my save with the editor it becomes available in game again, however if I try to reload the save while playing the game it crashes and I have to do this process over again. If I exit the game my save is gone and I have to do this over again.

Is there a way to fix this using the editor? 
Thanks

**Comment by mshocklee** [comment]
This doesn't sound like an issue to report with the editor. I would ask your question on reddit or maybe one of the NMS community discord servers
