### ISSUE TITLE
Cursed

### ISSUE THREAD

**Issue by Wolfhorse60** [goatfungus/NMSSaveEditor#1106]
Not to rush you or ask for anything but do you think NMSSaveeditor before the two weeks of cursed runs out. You think they only gave us twoo weeks to get ahead of you LOL?

**Comment by Findarato** [comment]
People use search. There are a TON of these already

**Comment by goatfungus** [comment]
This should be fixed now, see version 1.17.6.

**Comment by Wolfhorse60** [comment]
Thank you for the update. Sorry I missed this. My email attendance has been poor lately. Two hurricanes in two weeks will do that LOL. I'd like to say thank you so much for making this. It has made the endgame and these frustrating "start over" expeditions a lot more enjoyable.I mean, I love the game after 1600 hours, I don't want to do that beginner stuff anymore. I don't pick lots or get encumbered any more either LOL. How do I tip or send some recompense to you? ThankDwayne
    On Friday, October 25, 2024 at 03:20:47 PM EDT, Brendon Matthews (GoatFungus) ***@***.***> wrote:  
 
 


This should be fixed now, see version 1.17.6.
