### ISSUE TITLE
Thank you Brendon

### ISSUE THREAD

**Issue by the-bloke** [goatfungus/NMSSaveEditor#1107]
Thank you Brendon for the prompt update.
Really appreciate your work and time on.
Cheers and keep safe

**Comment by goatfungus** [comment]
No worries! I appreciate the support :)

**Comment by emilio-simoes** [comment]
Yeah... you would have a lot more support if you let other people help you fix things faster... But what the heck... your a super genius, an we poor mortals can't do anything else but wait for your kindness and giveness... So many stuff that could be fixed faster if you opened the code to others... But hey, you're a god and that's what counts... ;)

**Comment by emilio-simoes** [comment]
Ah! almost forgot! Thanks for doing something that should have been done days ago!
