### ISSUE TITLE
When downloading is blocked as virus?

### ISSUE THREAD

**Issue by Vopenka2** [goatfungus/NMSSaveEditor#1108]
when I attempt to download the latest patch it shows up as "Interrupted virus detected" and then windows defender gives me a notification that is successfully detected and blocked a threat. I just wanted to inquire as to whether this is a fluke or not?
![image_2024-10-26_005644734](https://github.com/user-attachments/assets/eb9aaa35-70c3-49b1-8c73-8006b14adc8e)

**Comment by wkitty42** [comment]
that looks like a false positive from defender...

**Comment by dansan7878** [comment]
i had the same problem

**Comment by byrogerito** [comment]
Também tive o mesmo problema...
Eu tive o mesmo problema

**Comment by byrogerito** [comment]
Credito que ja foi corrigido 
![image](https://github.com/user-attachments/assets/c84389d5-0bfe-476f-b97e-fe10782c1bea)

**Comment by emilio-simoes** [comment]
That´s why he doesn't want other people looking into his code... Hes taking advantage od NMS to make a virus!

**Comment by dansan7878** [comment]
What do you mean?

**Comment by byrogerito** [comment]
> É por isso que ele não quer que outras pessoas vejam seu código... Ele está se aproveitando do NMS para criar um vírus!

ja ta viajando...

**Comment by emilio-simoes** [comment]
Do I have to write this in words? I've offered my help to fix issues in de
code and was ignored! There guys down want anymore else to know what their
code does! Don't you guys think this is strange also? If the No Man's Sky
save code is public for everyone to see what are these guys hiding?

A sábado, 26/10/2024, 18:50, dansan7878 ***@***.***> escreveu:

**Comment by emilio-simoes** [comment]
Até tu estás a viajar mas é no mundo da droga... pensas que só porque falas
(em português simulado) não te vou perceber? Abre os olhos rapaz, porque
falas noutra língua não faz de ti mais esperto

A sábado, 26/10/2024, 18:57, Rogério ***@***.***> escreveu:

**Comment by dansan7878** [comment]
Turn off your Windows antivirus, download and turn it back on. That's what I did and it worked

**Comment by goatfungus** [comment]
The windows defender / antivirus detection issue is due to the zipping program used to package this editor. There are many discussions about it online, which you can search for pretty easily.

For example:
https://superuser.com/questions/1199320/how-to-create-a-self-extracting-archive-without-triggering-false-virus-positives

The reason I haven't solved this is because it requires a digital signature which is not cheap to obtain, and kinda pointless when it's only used for the first extraction. Once the files are extracted you can DELETE the exe file entirely and run the application from one of the batch files, which also takes advantage of the auto-updater.

### Workaround:
Instead of downloading the whole github master branch, just download the package zip file here:
https://github.com/goatfungus/NMSSaveEditor/raw/master/NMSSaveEditor.zip

**Comment by goatfungus** [comment]
I have removed a bunch of unhelpful comments from this thread.

For those of you who have "offered their help" on the application itself thinking that will magically solve the problem with WinZip, you clearly don't know what you're talking about. Please refrain from throwing around wild accusations, like I'm "intentionally implanting a virus on people's machines", and the like. Do some real research. I know you have also asked for the source code recently, but by throwing around these accusations you only show your true character.

As for myself, I will continue to make improvements to this editor as long as there is interest.

**Comment by LockNessMonster1** [comment]
> The windows defender / antivirus detection issue is due to the zipping program used to package this editor. There are many discussions about it online, which you can search for pretty easily.
> 
> For example: https://superuser.com/questions/1199320/how-to-create-a-self-extracting-archive-without-triggering-false-virus-positives
> 
> The reason I haven't solved this is because it requires a digital signature which is not cheap to obtain, and kinda pointless when it's only used for the first extraction. Once the files are extracted you can DELETE the exe file entirely and run the application from one of the batch files, which also takes advantage of the auto-updater.
> ### Workaround:
> 
> Instead of downloading the whole github master branch, just download the package zip file here: https://github.com/goatfungus/NMSSaveEditor/raw/master/NMSSaveEditor.zip



> I have removed a bunch of unhelpful comments from this thread.
> 
> For those of you who have "offered their help" on the application itself thinking that will magically solve the problem with WinZip, you clearly don't know what you're talking about. Please refrain from throwing around wild accusations, like I'm "intentionally implanting a virus on people's machines", and the like. Do some real research. I know you have also asked for the source code recently, but by throwing around these accusations you only show your true character.
> 
> As for myself, I will continue to make improvements to this editor as long as there is interest.

![Screenshot_3](https://github.com/user-attachments/assets/0a9060d8-951d-4aa9-ac27-0bd18b548421)

I was actually planning to keep quiet about these conversations but some guys just don't know how to to loose and think the are the greatest in the word...

So here it is the the No Man's Sky editor source code, a little bit obfuscated but nothing a good programmer can't work arround  ;) 

https://file.io/MgN2921QHhpL

if you delete this I'll just post another link, and another, and another... let's have fun #184 

https://file.io/MgN2921QHhpL
https://file.io/MgN2921QHhpL
https://file.io/MgN2921QHhpL
https://file.io/MgN2921QHhpL
https://file.io/MgN2921QHhpL
