### ISSUE TITLE
Issues in latest experimental patch

### ISSUE THREAD

**Issue by TheBob12** [goatfungus/NMSSaveEditor#111]
After saving ingame in the experimental version of NMS on steam, I can no longer open the save files in the save editor, but works fine to load ingame.

I get this error: https://imgur.com/3x18aMc

The log file:

[INFO] Mem Usage: 129/1891 MB
[INFO] Latest version: "1.5.21"
[INFO] Current version: "1.5.21"
[INFO] Loading slots: C:\Users\Hallu\AppData\Roaming\HelloGames\NMS\st_76561198157096356
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Loading saves for Slot 1...
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] No current save file found for Slot 1 - [EMPTY]
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0
[INFO] Version unknown: 0

**Comment by TheBob12** [comment]
Update:

it appears they have obfuscated the savegame files...
https://i.imgur.com/nBtW2IJ.png

**Comment by gmwjs22** [comment]
saving game the experimental , no longer works.
I have the same problem

**Comment by TheBob12** [comment]
@gmwjs22 Yes that error occurs because the saveeditor is trying to read a specific index from the savegame files that no longer exist, because they have been obfuscated. Which explains why "[INFO] Version unknown: 0" is spammed in the console 

In the new savegame file for me what is supposed to look like:
	"Version": 4626,
	"Platform": "Win|Final",

Now looks like:
	"8>q": "Win|Final",
	"F2P": 4626,

**Comment by pixelbart** [comment]
Yeah they changed all the keys.

**Comment by Alterios** [comment]
I have the same values as @TheBob12. It looks to my untrained eye like all they did was replace the names of the variables. it might be just a matter of replacing the old names with the new ones. and temporarily running a new fork for the experimental branch

**Comment by goatfungus** [comment]
Yeah, all they did was replace all the names in the save file with 3 character replacements.

I think the best step here is to create a dictionary file and use a detection process as part of the version check to determine whether the dictionary should be used or not. This would have the added advantage of not requiring a new fork for experimental.

I have almost finished the dictionary, and I'm just testing it on the save file before I implement it fully in the editor. Should hopefully have a new version in the next few hours.

**Comment by goatfungus** [comment]
I have pushed up an experimental build here: https://github.com/goatfungus/NMSSaveEditor/raw/experimental/NMSSaveEditor.zip

This should correctly map all the changed names in the save file to what they were previously (so the JSON editor is still useful), and reverts it back again once you save.

NOTE: This is an experimental build and should be used with caution. Please backup your NMS save folder before use.

**Comment by meachware** [comment]
First Thank you! I'm on the EXP release and the update was able to read in my save file. I manually edited the RAW JSON (frackin' rebound boltcaster). Opened in NMS fine and all looks ok. I then max filled a couple of items and that worked fine too.

However I am getting maybe 40-ish "name mapping not found: XXX" errors. One is for "RV1". While I can't copy them from the CMD.exe window I can certainly list them here if it helps.

**Comment by goatfungus** [comment]
Those are only warnings really.... the editor should still handle them fine. If you could post your log file that would help.

**Comment by meachware** [comment]
I don't know where/which logs - let me know and I'll post them :)

**Comment by TheBob12** [comment]
@meachware it's called NMSSaveEditor.log and should be located in the same directory as the NMSSaveEditor.jar file... I have mine on my desktop and that's where it saves the log file.

**Comment by meachware** [comment]
@TheBob12 - THANKS! 
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/2320592/NMSSaveEditor.log)

**Comment by Alterios** [comment]
I went through my save files from pre-update and my new one and found the following values for the missing names.
[INFO]   name mapping not found: M2L - Could not find in my save file
[INFO]   name mapping not found: RVl - "Palette"
[INFO]   name mapping not found: Ty= - "ColourAlt"
[INFO]   name mapping not found: xEg - "Colour"
[INFO]   name mapping not found: @6c - "TextureOptionGroupName"
[INFO]   name mapping not found: =Cv - "TextureOptionName"
[INFO]   name mapping not found: tIm - "BoneName"
[INFO]   name mapping not found: kpg -  the value under "RepairTechBuffer", it does not show up in any of the backup saves I have pre-update.

**Comment by Xavanil** [comment]
Here's another log using the Experimental version with the mapping messages - hope it helps.
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/2320778/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
Thanks @Alterios for the mapping info, I'll add it to the dictionary file in the editor.

I am still trying to find the actual mapping algorithm they use internally in NMS. This would be a much better solution than having a hard-coded mapping file, but I still haven't found it yet.

**Comment by Goose7** [comment]
First of all I wanted to say THANK YOU! For this wonderful tool!

So glad you are already on the case with trying to get everthing working again with the EXP!

I was really worried that the future of the trusty NMSSFE was in real danger.

**Comment by Goose7** [comment]
I just got done testing out your recently posted Experimental version of the editor on my 850 Hour Legacy Save file and everything appears to be working fine.

I am getting all those same error messages that other have reported in the console, but the editor still seems to be doing everything it is supposed to be doing, and I just loaded up the save file it edited without any issues that I have seen.

I refilled some of my Frigate Fuel stacks, expanded the slot size of my exosuit cargo section, and finally swapped in a different SEED value for one of my Exotic Ships.

And again... Aside from a whole bunch of various error messages being posted to the console display, everything I changed and saved was present in the game, and there were no issues with using any of them.

Impressive for the first version of this quickly assembled update!  👍

**Comment by goatfungus** [comment]
Normally I wouldn't need to have a separate experimental build for the editor, but because of the total remapping of every key in the file this is a really special case. I generally prefer to keep one editor build compatible with all minor versions of the game, and I plan to go back to that when (or if) these experimental changes actually get pushed onto the public build.

It kinda sucks that once you "upgrade" a save to the experimental build there is no way to play it again if you revert back to the standard public build. I'm working on some tweaks to this experimental build to allow saving back in the older format.

**Comment by goatfungus** [comment]
Ok, since this patched version seems to work fine on both public and experimental releases of NMS, I have merged the changes in the editor into my master branch. If you have downloaded the experimental version it should auto-update to the new version.

I guess we'll see what HG decides to do with this mapping going forward....

**Comment by Goose7** [comment]
Great!  Thanks for the quick work!  I just ran the earlier version of the editor to change one of my Exotic Ship Seeds and the auto-update feature worked like a charm!

I just came up here to confirm that the two versions had indeed been merged since I didn't see "Experimental" listed after the file name like it had with the original version.

Ran some quick tests and everything worked fine, aside from the fact that I am still getting a string of error messages on the console when I first select my save slot of choice.

**Comment by goatfungus** [comment]
Can you share the error messages?
Most of these should have been resolved with the new version.

**Comment by Goose7** [comment]
Sending log next.

Sent from Mail for Windows 10

**Comment by Goose7** [comment]
Sent from Mail for Windows 10

**Comment by goatfungus** [comment]
Sent it where?

**Comment by Goose7** [comment]
I sent the log and a screenshot of the console as a reply to your email.  Did you not get them?  I sent 2.
_____________________
Goldengoose7
goldengoose7@gmail.com

On Aug 25, 2018, at 11:48 PM, Brendon Matthews (GoatFungus) <notifications@github.com> wrote:

Sent it where?

**Comment by goatfungus** [comment]
I think github strips attachments if you send them by mail.... you would need to D&D them into the github message box.... sorry.

**Comment by Goose7** [comment]
Oh!  I see how this is working.  I got your request as an email.  Assumed it was separate from this section here.  Doesn't look like the file attachments were included.

Attempting to include them below using the web page instead:

[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/2321296/NMSSaveEditor.log)

![screenshot_20180825233728](https://user-images.githubusercontent.com/9331773/44625628-c0689000-a8c2-11e8-9b15-884756cbdc8d.png)

**Comment by Goose7** [comment]
Posting these in this thread too just to make sure you see them.  Still getting a feel for how GitHub handles all this stuff.  ;)

[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/2321305/NMSSaveEditor.log)
![screenshot_20180825233728](https://user-images.githubusercontent.com/9331773/44625692-3b7e7600-a8c4-11e8-8327-6abb8d6a920d.png)

**Comment by Goose7** [comment]
Forgot to mention... Those errors above are not the exact same ones I was seeing with the previous EXP version of the Editor.

I believe that q5u mention was included then too, but there were others that are no longer being displayed/reported.  So it looks like some progress was made between versions.  👍

**Comment by goatfungus** [comment]
Cool, thanks for that.
I have found the appropriate mapping for "q5u" in one of my other pre-NEXT saves, but the other 2 I'm not sure of yet.

"kpg" is a key that's been added in experimental, so I don't think we'll find the mapping by comparing saves.

You might be able to find the replacement for "M2L" (I don't have it in any of my saves). Load the JSON editor on your save and do a search for "M2L", and when you find it you should be able to figure out where it is in a backup by looking at the keys near it.

**Comment by goatfungus** [comment]
Added to the editor (not released yet) are the following mappings:
q5u=CN
kpg=MultiplayerPrivileges

If anyone sees any other "mapping not found" messages showing up, please list them here.

**Comment by meachware** [comment]
A few from this am on a fresh character in 1.57 exp
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/2321370/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
@meachware Thanks for that.... how far exactly have you got through the game? I just tried a new character on normal and can't get "M2L", ";YC", or "WX8" to come up.

**Comment by meachware** [comment]
I was 1/2 through repairing my starter ship

**Comment by meachware** [comment]
ah, my starter ship was replaced with the bonus content ship - sorry :(

**Comment by meachware** [comment]
There is something wrong with slots in both the Exosuit; general and cargo and the ship. I expanded my ship to 31 slots (6x6 w/5 missing) but it in game it lists my ship as 31 slots but only shows 29 available. Yesterday my exosuit slots were off by a row (I think 3 slots) until I purchased upgrades to match. However, I could actually use the slots (send to and transfer) just not seeing them in the game UI.
In my new character I added one cargo to my exosuit and it's location is wrong, it's at column 5 row 1 instead of in the 1,1 position.

**Comment by Rianon** [comment]
It's a known bug in exp build right now.

**Comment by meachware** [comment]
@Rianon - thanks :)

**Comment by Goose7** [comment]
@Rianon The slots for my suit's fully upgraded cargo section on my legacy save looked odd too when I first looked at it too.

How many slots is the cargo section supposed to max out at?

@goatfungus  I don't normally do to much in the RAW editor section, but I will search for that "M2L" key shorty and see what I can find.

**Comment by Rianon** [comment]
48 cargo in NEXT.

**Comment by Goose7** [comment]
So it is the same Max as the General Suit Inventory section then?  For some reason I was remembering 42 slots max for cargo.

As you can see from the above image, the Exp reset my Cargo section to 30 slots. Guess I need to go in and some in the missing slots to my Cargo section,

**Comment by Rianon** [comment]
> As you can see from the above image, the Exp reset my Cargo section to 30 slots. Guess I need to go in and in the missing slots to my Cargo section.
I don't think it's a save file bug... if you planning to fix it with editor.

**Comment by Goose7** [comment]
I just fixed it with the editor, so I have my original 48 slots back! -- I am sure the reduction to 30 was the result of those same issues with the original version of this EXP which change the General section to 42, but was then patched by HG with a second Exp release.

**Comment by Rianon** [comment]
>I just fixed it with the editor, so I have my original 48 slots back! -- I am sure the reduction to 30 was the result of those same issues with the original version of this EXP which changed the General section to 42, but was then patched by HG with a second Exp release.

And you can see and use all slots ingame? Interesting.

**Comment by Goose7** [comment]
@goatfungus  -- AH HAH!  I knew I was missing something.

Okay... I will have a look through my save file after lunch and report back.

Thanks for the info.

**Comment by Goose7** [comment]
@goatfungus  -- M2L is found right under something called "UsedEntitlements"

Here is the full string that includes M2L

"M2L":"HORIZOSHIP000000"

That appears to be the only occurrence of those three characters.

Is this what you were looking for?

**Comment by Goose7** [comment]
Also... Is there a keybind for Copy/Paste in the Raw Editor?  I wanted to just grab that whole section and paste it into a message here, but I couldn't figure out how to do it.  So I just transcribed the code above manually.

**Comment by goatfungus** [comment]
@Goose7 The standard copy/paste key bindings, Ctrl-C and Ctrl-V should still work in the JSON editor.

Thanks for the info you posted, I have it now :). The key is not in my saves because I never use the preorder ship even though I can. I'll test it out on my saves and push it into the next version.

**Comment by temp-999** [comment]
@goatfungus  Perhaps this might help. From my current Normal save:

    "UsedEntitlements": [
      {
        "EntitlementId": "HORIZOSHIP000000"
      }
    ],

**Comment by goatfungus** [comment]
@temp-999 yep, that's it.

Just need to find what ";YC" and "WX8" are mapped to.

**Comment by temp-999** [comment]
If @Goose7 could list those lines and the values have some uniqueness, I be happy to search my save file.

**Comment by goatfungus** [comment]
@temp-999 it was @meachware who listed those ones, though he hasn't sent any further info yet. It shouldn't be that hard to find though, just need to compare save files before and after installing experimental.

**Comment by Goose7** [comment]
@goatfungus Cool!  Glad I could help!  I don't use that ship anymore.  I sold it ages ago, but it is obviously still there in my save file years later!  lol!

Would you like me to copy and paste that entire section into a message here?  Though I could have sworn I tried using Ctrl-C and Ctrl-V before, maybe I botched it.  ??

I am not sure how much of that section you actually need, but I will go back in there and see what makes sense from a content perspective.

Stay tuned. :o)

**Comment by Goose7** [comment]
I am sure this is way more of code in that general area than you need, but just in case I missed something, here is a COPY/PASTE of everything above and below the reference to M2L.

`  "RealityIndex":9,
                      "GalacticAddress":{
                           "VoxelX":-946,
                           "VoxelY":-7,
                           "VoxelZ":1513,
                            "SolarSystemIndex":122,
                           "PlanetIndex":0
                      }
                }
           ],
            "FirstAtlasStationDiscovered":true,
            "UsesThirdPersonCharacterCam":false,
           "ProgressionLevel":1,
           "ProcTechIndex":153,
           "IsNew":false,
            "UseSmallerBlackholeJumps":false,
           "UsedEntitlements":[
                {
                      "M2L":"HORIZOSHIP000000"
                }
           ],
           "PlanetPositions":[
                [
                      -166000.0,
                      55000.0,
                      90000.0
                ],`

**Comment by Rianon** [comment]
@goatfungus 
> I am wondering if anyone is keen to help me build a few base parts in multiplayer (on public build) so i can get a save with someone else's structures on it. Then I'll switch over to experimental and see what other mappings are needed. I will need to do this before HG decide to push this experimental branch out to public.

I want to help, but there are two problems:
1) I can't see other players, even their icons, others can see me, but can't interact with me;
2) I have too little speaking practice (English is not my native), so text chat only.
And if second one is not looks like a real problem, but the first one... :(

**Comment by temp-999** [comment]
@goatfungus  Sorry that I couldn't help. But I am more educated now. Loaded the Experimental version and saw what it did to the save file. Reloaded version 1.57.  Thank you for continuing with your product.

**Comment by goatfungus** [comment]
@temp-999 no problems! All input on this is appreciated as it helps me understand the bigger picture.

**Comment by Goose7** [comment]
Just wanted to report that I continue to see the "q5u" error message strings when opening my save in the latest version of the editor.  The one that was pushed last night.

**Comment by goatfungus** [comment]
Nothing was pushed last night..... current version is still the 1.5.22 version which has those keys missing. It won't affect the editor UI though, so you should be ok. I'll push another version later today depending on what happens with the experimental branch (if there are any changes).

**Comment by Goose7** [comment]
That's really odd.  I was prompted to download an update last night when I opened my save with the editor.  It did seem to download and update something.  But the version number is still listed as 1.5.22.

If it happens again, I will take a screenshot of it.  I just assumed you had made some changes and didn't think anything of it at the time.

**Comment by Goose7** [comment]
Excellent! -- I decided to do some more playing with the game tonight, so I will check it out shortly.

Glad you are making such good progress!  I expect we might see another Exp build tomorrow.  They seem to be focusing on Tuesdays as of late for these, but we shall see.

Hopefully the next one doesn't end up breaking all the work you already put into this one!  ;o)

I'll post back if I find anything strange.  Otherwise, I will touch base soon.

**Comment by goatfungus** [comment]
I actually wonder if they will release this experimental build in its current state, as it has broken a lot of stuff. I think they may have bitten off a bit more than they could chew, and some of the changes may be rolled back. We shall see.

**Comment by Goose7** [comment]
The latest update produced a totally clean opening of my save file, but after today's update of the Exp Build I am getting another one of those error message strings for an item I had not seen previously.

Here is the code.  I also tracked it down in the Json.  That is included below the load screen messages.

Reading save file...
  Path: C:\Users\golde\AppData\Roaming\HelloGames\NMS\st_76561198299574875
  Slot: Slot 1 - NORMAL
  Filename: save.hg
Parsing JSON...
  using name mappings: 24/08 experimental
  name mapping not found: D6b
  name mapping not found: D6b
  name mapping not found: D6b
  name mapping not found: D6b
  name mapping not found: D6b
  name mapping not found: D6b
  name mapping not found: D6b
  name mapping not found: D6b
Finished.

`},
                                 "FL":{
                                      "C":1
                                 },
                                 "RID":"0eLFhukT6QcX9MgMO6+BKNcaCVAvR5cSCLjTn904jbE=",
                                 "D6b":"ST"
                           },
                           {
                                 "DD":{
                                       "UA":"0x207A00F832E9FD",
                                       "DT":"Interactable",
                                      "VP":[
                                            "0x157882B7335961EA",`

**Comment by goatfungus** [comment]
Yeah, i get "D6b" showing up on mine as well. I suspect its an entirely new key though.

**Comment by Goose7** [comment]
I figured that it had to be new since none of us had that key before.

Also... Rolling back to the previous Nvidia driver from August 1 resolved the hitching problems for me.  Still getting some FPS drops when entering planets though

**Comment by Goose7** [comment]
I just got word that they added a Quick Silver Merchant inside the Anomaly station where Nada and Polo hang out.

I wonder if this is the source of that new key?

**Comment by goatfungus** [comment]
Ok, looks like most of this is resolved now, so I'm going to close this issue.
If you have any problems with key mappings in the latest release (1.5.24) please post them as separate issues.
