### ISSUE TITLE
Graphics and Text Formatting / Scaling for Large/High Resolution Monitors?

### ISSUE THREAD

**Issue by Goose7** [goatfungus/NMSSaveEditor#115]
I know you have a lot on your plate right now, so no huge rush on this.   I have been dealing with this for nearly 2 years, but since I can now communicate with you directly on here, I figured I would raise the issue and see what perhaps can be done.

I am running my PC on a SONY XBR 65" 4k Panel running at its native resolution of 3840x2160 in Windows 10.  

When I use the NMS Editor, I have a hell of a time seeing and reading anything being displayed because none of the text or graphics scales for my display resolution.  I generally have to pull up a chair and sit a foot away from the screen to be able to use the program.

I also have some formatting issues with the Discovery Menu items being very close to each other and partially overlapping.  This has proven to make reading the items off the list somewhat difficult, even when I am right up at the screen.

I took some screenshots just now to better demonstrate what I am talking about.  These windows take up less than ¼ of my screen area, but increasing the window size does nothing to make the text or graphics content any larger and more readable.  I don't have this issue with any of my other applications.  They all seem to scale fine.

I can't read any of these sections from where I normally sit when gaming.  The text is just too tiny to make out.

Thanks in advance!  👍 

![screenshot_20180826191227](https://user-images.githubusercontent.com/9331773/44637314-581eba80-a965-11e8-8957-297fdd38d931.png)
![screenshot_20180826191319](https://user-images.githubusercontent.com/9331773/44637325-61a82280-a965-11e8-947b-528ec5a98063.png)
![screenshot_20180825172606](https://user-images.githubusercontent.com/9331773/44637332-68cf3080-a965-11e8-8a47-ce0366a7ae1b.png)

**Comment by Ottiz** [comment]
Hmmm, I'm thinking this may have something to do with the windows registry keys

**Comment by Goose7** [comment]
@Ottiz  -- Good question.

@goatfungus  I should reiterate that I have had this issue with everything being tiny for the entire length of the project.  The icons, text and overall formatting of lists were always small and squished together even when I was running my previous 1080p resolution large panel.

It only got worse when I upgraded to my 4k display running at Native 4k resolution of 3840x2160.  

Is there any hope for us?  Or is this resolution/scaling issue related to your use of Java?  Does it have hooks in there for creating a truly Native 4k version?  I would settle for a 1440p or higher at this point.

I don't know what resolution the current editor is using, but it even seemed to low for a 1080p display.

????

If the size of everything increased as you increased the size of the windows, that would be ideal!  Then I could make it full screen and be able to read everything from my gaming chair!  👍

**Comment by Goose7** [comment]
This is what the current editor looks like on my display in Full Screen.  (3840x2160)

![nms editor fullscreen 4k](https://user-images.githubusercontent.com/9331773/44810895-043feb80-ab88-11e8-8c86-6325b7634278.png)

**Comment by Goose7** [comment]
@Ottiz It would be nice to see some kind of provision for our type of display.  They are only going to become more and more popular as people upgrade their stuff.

I hate having to sit with my nose up to the screen any time I want to do anything with this Editor.

**Comment by goatfungus** [comment]
I agree with @Ottiz on this one.... might be a configuration problem with Java itself. It has a built in theme for Windows which in your case is messing up the font sizes.

There are was i can tweak the font sizes in the app, but this would mean that if I get it to work perfectly for you it will look horrible for others. Stupid Java! I am actively looking for a better solution.

**Comment by Goose7** [comment]
I did try those font size change options when you offered them, but they didn't really work that well.  They mainly wrapped all the text down to two or three lines making it even harder to read, so I ditched that stuff.

The primary problem is the overall size of everything.  The text alone can't be increased unless the icon sizes and those fixed width windows increase along with it.  Otherwise is all just wraps into a mess.

**Comment by Ottiz** [comment]
I'm looking at a Java message board with other posts regarding small application size and DPI ratio based issues, and some mentioned trying a higher Java version 9. I'll be trying this later today. I'll let you know how this goes.

**Comment by Goose7** [comment]
@Ottiz Sounds good!  I'm not sure what version of Java I have here.  I assume it is the latest version available, but I will check that later too.

**Comment by goatfungus** [comment]
Cool, so it's a start at least.

I mostly focused on the inventory slots with this build, basing the grid width and image size off the default font metrics used by the UI. I also changed the row height of all the tables as well. Basically, if your system uses a larger font, these elements will now scale to match.

I wanted to see if this actually worked properly before making any further changes, but now that I know it does I can work on the rest.

**Comment by Goose7** [comment]
@goatfungus -- Excellent!  It definitely is a great start!

I would be happy to do some Beta testing of newer versions if it would help?  If it makes it easier for you to check on changes to the font sizes of the UI. 

Maybe park them somewhere, or just attach them to an email?

Just let me know.  Otherwise, I will look forward to see what the next round of changes in these areas look like.  👍 

Thanks again for taking this on.  :o)

**Comment by goatfungus** [comment]
@Goose7 Just wondering if you could test this one out for me. Font sizes should still be the same, but the editor should make more room for the text labels on the left hand side.
[NMSSaveEditor.zip](https://github.com/goatfungus/NMSSaveEditor/files/2346721/NMSSaveEditor.zip)

**Comment by Goose7** [comment]
Sure!

I will give it a spin tonight and report back.  I have found a few oddities with the original version I was waiting to get into if they were still there in  the next update.

I’ll let you know about that as well.  Stay tuned!  :o)
_____________________
Goldengoose7
goldengoose7@gmail.com

On Sep 3, 2018, at 4:59 PM, Brendon Matthews (GoatFungus) <notifications@github.com> wrote:

@Goose7 <https://github.com/Goose7> Just wondering if you could test this one out for me. Font sizes should still be the same, but the editor should make more room for the text labels on the left hand side.
NMSSaveEditor.zip <https://github.com/goatfungus/NMSSaveEditor/files/2346721/NMSSaveEditor.zip>

**Comment by goatfungus** [comment]
Drop the .jar file in where you installed the editor before (overwrite the old one), it's the only file that has changed. Should say version 1.5.26 when you open it normally.

**Comment by Goose7** [comment]
I tried doing that after it wouldn’t open on its own and I got this:

Initializing environment...
Error: working directory error: S:\NMS%20MODs%20Archive\NMS%20SaveEditor%20Backup\Latest
Press any key to continue . . .
_____________________
Goldengoose7
goldengoose7@gmail.com

On Sep 3, 2018, at 10:57 PM, Brendon Matthews (GoatFungus) <notifications@github.com> wrote:

Drop the .jar file in where you installed the editor before (overwrite the old one), it's the only file that has changed. Should say version 1.5.26 when you open it normally.

**Comment by goatfungus** [comment]
Hmmmm.... that's a really odd one. Ok, back to drawing board :)

**Comment by goatfungus** [comment]
Ok, try this one if you could:
[NMSSaveEditor.zip](https://github.com/goatfungus/NMSSaveEditor/files/2350023/NMSSaveEditor.zip)

I didn't account for spaces in the path.

**Comment by Goose7** [comment]
Ah!  That makes sense backed on the error I was getting before.

Okay!  This one worked.  Although I was prompted to update the Editor?  But ignored it.

I see that the fields appear to be longer on the left side, but without any change to the actual font for that section, I am not sure how those fields will behave when they have larger text?

Still getting that odd blank area on my Exosuit Inventory Menu unless I go full screen and then back to a smaller window size.

![screenshot_20180904150949](https://user-images.githubusercontent.com/9331773/45060595-6a7bb100-b055-11e8-978b-da2d6b272d98.png)

**Some other areas of the save file:**

![screenshot_20180904150920](https://user-images.githubusercontent.com/9331773/45060615-841cf880-b055-11e8-8351-002b0276224a.png)

![screenshot_20180904151029](https://user-images.githubusercontent.com/9331773/45060638-a151c700-b055-11e8-905a-8acf0800ba6b.png)

**Comment by Goose7** [comment]
Hey Brendon!

As of this latest TEST version it is every time I open the editor.  All the other sections of the save such as Ship, Freighter etc. always seems to scale fine, with any tiles to the right of the window size just sit off screen.

But the Exosuit section has always behaved this way.  If I make the window full screen, then all the icons draw in with the proper order, and then if I reduce the window size back to where it was the formatting is basically like all the other sections.

Not sure what is special about the Exosuit section that makes it behave so differently.  ???

**Comment by goatfungus** [comment]
That is really odd.
Can you try this one:
[NMSSaveEditor.zip](https://github.com/goatfungus/NMSSaveEditor/files/2351001/NMSSaveEditor.zip)

**Comment by Goose7** [comment]
BINGO!  Whatever you changed did the trick!  The Exosuit window looked like this when I first opened the Editor without having to change the default window size.  👍 

_Ignore the partially viewable blue window in the lower right corner.  That is my monitoring software window I use for selective screenshots.  It is supposed to move out of the way, but it often doesn't._

![screenshot_20180905084756](https://user-images.githubusercontent.com/9331773/45105350-e410af00-b0e8-11e8-8ad1-b659a637f8c9.png)

**Comment by goatfungus** [comment]
Ok, that's great..... next version will be 1.5.26, but might be slightly different from the last one I sent you. So keep an eye out for it. I should have labelled the version differently.

**Comment by Goose7** [comment]
Sounds good!

Are you going to increase the default font size for the actual UI?  

And can this be specifically done to only certain areas/fields?

Specifically useful to me would be a much larger ship SEED number field.  That is about the only UI element I interface with on a regular basis, since I tend to swap out my various Exotic ship skins every few days to keep things interesting.

Thanks again!

I am always promoted to update the Beta version you sent me when I launch it. -- I will just check with the download section here and wait until I see the latest version.
