### ISSUE TITLE
Ship Seed

### ISSUE THREAD

**Issue by Xav120** [goatfungus/NMSSaveEditor#117]
I've been messing around with Ship seeds and I found one online I'd like to use but I've found that whenever I try to edit the seed of my ship the editor automatically changes it back to what it was before.

I'm trying to change it to 0x3ff352f1e3000715g but no matter what I do it instantly switches to 0x7FAE5EFB5D6A1B2B before I have a chance to save

**Comment by goatfungus** [comment]
Take the "g" off the end and it should work.

**Comment by Xav120** [comment]
Yeah I also commented on the site that generated the seed and according to them I do have to remove the g so it was a problem with their script

Thanks for responding so soon however and sorry if I have wasted your time in any way
