### ISSUE TITLE
error message in console: 'reverse mapping not found: V?r'

### ISSUE THREAD

**Issue by lofblad** [goatfungus/NMSSaveEditor#118]
I'm not sure if it means anything really, but I get this error message repeatedly in the command console, when starting the app with the bat file.

reverse mapping not found: V?r

This is the complete content of the console output:

Mem Usage: 255/3779 MB
Latest version: "1.5.23"
Current version: "1.5.23"
Loading saves for Slot 1...
Reading save file...
  Path: C:\Users\lofblad\AppData\Roaming\HelloGames\NMS\st_76561197971588066
  Slot: Slot 1 - NORMAL
  Filename: save2.hg
Parsing JSON...
  using name mappings: 24/08 experimental
  name mapping not found: V?r
  name mapping not found: V?r
  name mapping not found: V?r
  name mapping not found: V?r
  name mapping not found: V?r
  name mapping not found: V?r
Finished.
Setting health: 200
Formatting JSON...
  using name mappings: 24/08 experimental
  reverse mapping not found: V?r
  reverse mapping not found: V?r
  reverse mapping not found: V?r
  reverse mapping not found: V?r
  reverse mapping not found: V?r
  reverse mapping not found: V?r
Creating backup...
Writing new save file...
Finished.
Loading saves for Slot 1...
Finished.

**Comment by lofblad** [comment]
Edit: Oh, and I haven't had a public build for a while, I've been playing on experimental for a good while.

**Comment by lofblad** [comment]
Alright, I've compared my latest save to a previous one, and this is what I've found:

The very end of the long list of discoveries differs, and that's where my line appeared. After I submitted my issue, the missing name was "V?r". After playing, and making new discoveries, the missing name was "D6b". Weird. 

So it seems the new save format adds a couple of lines after the discoveries list. In my save file, it looks like this:

,
						"FL":{
							"C":1
						},
						"RID":"Pnm9spHT/N+M20FWgBIYUGohMz3Po2BxeTTT9PUtQOw=",
						"D6b":"ST"

So I'm guessing that my previous save had the "V?r" where there is now "D6b". In my previous save, these lines are missing, and the list of discoveries just ends.

Hope that helps.

**Comment by goatfungus** [comment]
I actually think these 2 are unrelated keys. I know that "D6b" is a new key they added to the discovery manager system (it's in one of my saves), I'm still not sure where "V?r" is located though.

**Comment by lofblad** [comment]
Yeah, that's what it seems like. V?r was probably there in the same place as D6b, as it's not present in the save file anymore. 

I found it in a save file that was made after the 24/8 update. It's not their before, so it's likely added.


						"FL":{
							"V?r":1
						},
						"RID":"VKiiyw6TAl/QE3+GXHTbkjzsnX0VI1CWKjUhSszHo5Y="

And as I said, it's not there anymore, and the D6b line is not present in that same post-24/8 file.

**Comment by jaszhix** [comment]
`V?r` is "H" I think. The way I got these figured out was by backing up a pre-experimental save, then letting the game migrate it. If you open both save files and format them (without sorting), their original order is the same. So with two mostly identical save files with 99% of the same values, you can identify the obfuscated keys, and they'll be on the same line numbers for the majority of the file.

My only concern at this point is whether or not HG is going to regenerate these from a checksum - that would make things more complicated. It also seems silly they're doing this on the keys instead of a compression solution. This problem has been solved already, with solutions like [lz-data](http://pieroxy.net/blog/pages/lz-string/index.html).

**Comment by goatfungus** [comment]
@jaszhix Exactly. I think its all been a proverbial reinvention of the wheel.

Thanks for the info on the "V?r" key, I'll add that to the next build.

**Comment by goatfungus** [comment]
I have updated the mappings table in the latest build, so should be all good now.
