### ISSUE TITLE
Very tiny icons in Update 1.5.23

### ISSUE THREAD

**Issue by Ottiz** [goatfungus/NMSSaveEditor#119]
Since the latest editor update my icons have shrunk to tiny tiny little ones, I have tried adjusting my video card resolution and scaling but nothing changes. 

(new to this forum thing so my posting skills are inept)

https://ibb.co/d1YAYU

[<a href="https://ibb.co/d1YAYU"><img src="https://thumb.ibb.co/d1YAYU/Tiny_Icons_since_latest_update.jpg" alt="Tiny_Icons_since_latest_update" border="0"></a>](url)

**Comment by goatfungus** [comment]
Looks like you have the same problems as mentioned in #115, so I'll close this one as a duplicate.
