### ISSUE TITLE
JSON minified key mappings

### ISSUE THREAD

**Issue by nerdshark** [goatfungus/NMSSaveEditor#120]
Thanks to an image in [this reddit thread](https://www.reddit.com/r/NoMansSkyTheGame/comments/91voi6/fix_for_the_lost_progress_corrupt_save_bug_if_you/) (image [here](
https://imgur.com/lsxHJd0)), we now have two more deobfuscated keys:

- `;YC` maps to `MaintenanceContainer` (`PlayerStateData.RepairTechBuffer[][';YC']`)
- `WX8` maps to `InventoryIndex`(`PlayerStateData.RepairTechBuffer[]['WX8']`)

**Comment by goatfungus** [comment]
Thanks for that, I'll add them in next update.
