### ISSUE TITLE
Game unplayable after 1.58 - Inventory bug

### ISSUE THREAD

**Issue by johnnystuff** [goatfungus/NMSSaveEditor#121]
Hi, I'm asking here because I'm pretty sure it's related to the horrible things I did with this little tool here, but the fact is pretty nasty: as soon as I hit the inventory button the game crashes. It just switches off, totally and always. Tried loading up an old save file, creating a new save point in game, doing "stuff" like flying around, talking to people, scanning... everything works just fine but then I hit the inventory and game over.

I haven't done many "brutal" things with this tool. Maybe the worst was changing the number of slots of my multitool, the number of slots of the base/freighter containers from 5 (iirc) to full 9, gifting me with a bunch of nanites and regenerating the key of the multitool itself just to change its appearance, and swifting things around in order for the bonuses of the upgrades to apply better.

As far as the logs, the only bad thing it tells me is that V?r and D6b thing, but I'm not sure that's the issue. Anyway, here's a screenshot of my logs: https://imgur.com/Eutfb2l.jpg

Can't actually play now, hoping there's a fix. Lemme know how I can provide any further information if needed.

**Comment by johnnystuff** [comment]
Ok after some more testing it occurred to me that I have a bunch of mods installed and... long story short, it was one of them. In particular it was just a graphical glitch of some sort due to the resizing of the hud by one of those "21:9 hud fix" mods for those who have a 21:9 monitor like me.

Sorry for the wrong claims, my bad :)

**Comment by Goose7** [comment]
Glad you figured it out.  Rule of thumb with NMS anytime you run into something weird is to remove all your Mods and try the game in vanilla.

This is the first thing HG support will tell you as well.
