### ISSUE TITLE
Suggestion: Add "Uncheck all words" option.

### ISSUE THREAD

**Issue by LordBlade** [goatfungus/NMSSaveEditor#13]
So, because your word list cheat doesn't actually work to add the words (they don't get displayed in speech), unfortunately a side effect of us having tried using the words cheat means that now everything is marked as known.

It seems that the game registers the fact that the words are known (so we can't learn new ones), but we're stuck with the words not showing during text.

So can we get an option to "uncheck" all words? So that way we can get back to learning them properly?
Better yet (if possible) a way to check what words are ACTUALLY known, so that we can have the editor sync up our list properly (so it only has checks on the words we currently know).

Thank you very much.
I greatly appreciate the editor, it's just a shame the word stuff causes so much hassle.

**Comment by MikeGamerGuy** [comment]
I just tested this on an old save with the Atlas Rises version of the editor.  I edited the save to know all the words, then loaded it in the current version of NMS.  It worked, so this might be a bug in the current editor.  Haven't tested it on a current save yet.

**Comment by goatfungus** [comment]
The words list function in the editor hasn't changed since October 2017, not even for NEXT.

What I think is happening is that part of the file conversion process in the game is updating the structure of the known words in the save file, but only doing it if the file hasn't already been upgraded. This means that the editor may be writing older (and incompatible) data which is only partially working. I still need to confirm this.

**Comment by LordBlade** [comment]
Interesting. Well, hopefully there's a fix in time. Would be nice to be able to just get the complete language thing done. Or at least fix it so that I can properly learn things again.

For now I've been unchecking words one by one, but of course that's taking forever. lol

**Comment by goatfungus** [comment]
I have made a slight change to the editor, so now if you click the Learn All button it will only tick the words that the game actually uses for each race. So for example "give" is used by all 3 races so will have 3 ticks, but "war" is only used by Gek and Vy'keen so will not put a tick in the Korvax column.

This doesn't really help you much, but should hopefully fix future issues.

**Comment by LordBlade** [comment]
So is there any way to fix my situation? Where I have all the words checked in the editor, but I don't actually know the words in game? Because hopefully there's some way of resetting what's checked in the editor without having to go through each word one by one.

**Comment by goatfungus** [comment]
You could try using the JSON editor and setting the KnownWords section to [].
That should clear all known words, then try the Learn All button again afterwards.

**Comment by goatfungus** [comment]
I have added an "Unlearn All" button in version 1.5.9 (now available).
