### ISSUE TITLE
Ship seed with trailing space is ignored

### ISSUE THREAD

**Issue by soupwizard** [goatfungus/NMSSaveEditor#130]
I was changing the look of one of my ships and noticed that if I cut & paste a seed from a website and paste it with a trailing space, that seed is ignored. Removing the trailing space causes the new seed to be accepted.

**Comment by goatfungus** [comment]
Same thing happens when you enter any other invalid character, but that is normal. It would be a bit of a painful process to try to account for extra spaces here and there on every field in the editor, so it relies on the user to correct it themselves instead.

**Comment by soupwizard** [comment]
String.trim() will do it easily.

**Comment by goatfungus** [comment]
Of course you are right. The point is if I do it for one field I'd be expected to do them all. At the moment all the editor checks for is validity, it doesn't reformat values or strip whitespace. It doesn't have to be perfect, it just has to work.

Anyway, I won't rule it out as a potential future change, but it's not going to be a high priority.

**Comment by goatfungus** [comment]
While I was messing around with some decompiling, I decided to tweak some of the input fields slightly. I don't think I got all of them, but the seed fields at least will now trim whitespace.
