### ISSUE TITLE
Corrupt Waypoint Thumbnails (discoveries)

### ISSUE THREAD

**Issue by s-p-a-r-k-y** [goatfungus/NMSSaveEditor#131]
**Corrupt Waypoint Thumbnails (discoveries) since yesterday**. Happens on all systems.
·   Dont know the cause
·   Running 1.58 and have only used Final releases prior (no experimental branches). Log:
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/2347219/NMSSaveEditor.log)
·  You state the error in D6b is a red-herring (#126)
·  Savefile attached:-
[mf_save3.zip](https://github.com/goatfungus/NMSSaveEditor/files/2347225/mf_save3.zip)

Any pointers forthcoming appreciated.
Sparky

**Comment by goatfungus** [comment]
After looking at your log, it looks like the editor is doing what it is supposed to. The editor currently doesn't touch the waypoints structure in the save file, so I suspect this might be a bug in the latest release of NMS.

This doesn't surprise me, as there were a number of new bugs introduced in that branch and reported when it was still in experimental. HG didn't do anything about them and just pushed it to public. Was not a good move.

**Comment by goatfungus** [comment]
I think most of these issues have been fixed in the game itself. Please feel free to reopen this issue if you're still experiencing problems.
