### ISSUE TITLE
Suggested batch file upgrade.

### ISSUE THREAD

**Issue by XanTheDragon** [goatfungus/NMSSaveEditor#133]
(I don't know if I'm supposed to be able to label this or not, I'd have added enhancement myself if I could.)

I did an alteration to the batch file used for launch to make use of the autoupdate flag I located whist sniffing around to see what launch flags there were.

This suggested enhancement will make the batch file automatically upgrade the jar file based on the downloaded file. Of course, this isn't the best solution since the better one would be to update the jar, but for now here's the batch file I use personally.
[NMSSaveEditor.bat.zip](https://github.com/goatfungus/NMSSaveEditor/files/2355499/NMSSaveEditor.bat.zip)

**Comment by goatfungus** [comment]
Not sure which batch files you have, but the ones that come with the editor already use error level 2 to detect whether the user is choosing to update (as opposed to error level 1 which is an app error), and it is working.... not sure we need the additional console pauses and status messages when the editor has dialog boxes for it already.

What it usually does is show a confirm dialog window in the editor asking if you want to upgrade.... if yes, it downloads the jar file using a different filename.... then it exits with errorlevel 2.
The batch file then detects the errorlevel as an upgrade request, replaces the old file with the new, and then starts it back up again.

**Comment by goatfungus** [comment]
The batch file should already contain the following:

```
@echo off
:start
java -jar NMSSaveEditor.jar -autoupdate
if errorLevel 2 (
	move /Y ~NMSSaveEditor.dl NMSSaveEditor.jar
	goto start
)
if errorlevel 1 (
	pause
)
```

**Comment by XanTheDragon** [comment]
Oh! I see. Every time I've updated, I've only grabbed the jar file, not the whole zip. I forgot to check your update stamp on the batch file so I never saw that you did such a change. My bad.

**Comment by goatfungus** [comment]
Thanks for the help though, I do appreciate it.

Make sure you delete the old -debug batch files, as that flag no longer exists.
