### ISSUE TITLE
Error since 9-6 update

### ISSUE THREAD

**Issue by Grabby-LaToosh** [goatfungus/NMSSaveEditor#134]
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_181
[DEBUG] Working Dir: D:\games\nms\SaveEdit
[INFO] Starting Editor...
[DEBUG] Save Path: C:\Users\XXXXX\AppData\Roaming\HelloGames\NMS\st_76561198009421194
[DEBUG] Mem Usage: 257/3801 MB
[DEBUG] Latest version: "1.5.26"
[DEBUG] Current version: "1.5.26"
[INFO] Loading saves for Slot 4...
[INFO] Reading save file...
[INFO] Slot: Slot 4 - SURVIVAL
[INFO] Filename: save7.hg
[INFO] Parsing JSON...
[INFO] using name mappings: NMS 1.58
**[WARNING] name mapping not found: sHl
[WARNING] name mapping not found: 8GF
[WARNING] name mapping not found: D6b**
[INFO] Finished.

**Comment by goatfungus** [comment]
Warnings should not impact save editor function. They just mean that HG have added some extra keys to the save file that aren't mapped yet.

I'm wondering if you could do me a favour and find these keys in the JSON editor, and copy the lines around it into another reply so I can figure out where they come from.

**Comment by Grabby-LaToosh** [comment]
sHl = 2 instances, part of section for
 
					{
						"Timestamp":1534638672,
						"ObjectID":"^MESSAGEMODULE",
						"UserData":16777224,
						"Position":[
							-0.78204345703125,
							-0.003143310546875,
							29.280059814453126
						],
						"Up":[
							-0.000012159347534179688,
							0.9999998807907105,
							0.00045236945152282715
						],
						"At":[
							-0.0061775147914886478,
							0.00045230984687805176,
							-0.999980628490448
						],
						"sHl":"Welcome Travelers to Grabby's World!"
					},

					{
						"Timestamp":1535870637,
						"ObjectID":"^MESSAGEMODULE",
						"UserData":0,
						"Position":[
							-33.85430908203125,
							3.455108642578125,
							28.95849609375
						],
						"Up":[
							-0.0003439486026763916,
							1.0,
							0.00029414892196655273
						],
						"At":[
							0.7443775534629822,
							0.0004524439573287964,
							-0.6677590012550354
						],
						"sHl":"Welcome To Grabby's World!"
					},
					
8GF = End of Freighter section

		},
		"RepairTechBuffer":[],
		"MultiplayerPrivileges":1282,
		"8GF":"0x220309FDD1FBC3"
	},

D6b = This one has MANY instances, all are either Flora or Fauna

					{
						"DD":{
							"UA":4718008141456327,
							"DT":"Animal",
							"VP":[
								"0x4D3F4D7E92DBA122",
								"0xA4B28F806C8A8507",
								"0xBFED73A0577804BC",
								"0x982A45FE83A52290"
							]
						},
						"DM":{},
						"OWS":{
							"LID":"",
							"UID":"76561198122291990",
							"USN":"vRDXv",
							"TS":1536251114
						},
						"FL":{
							"C":1
						},
						"RID":"sIAUslccrnZiE+Jr9qS5EATSLMT+RziSCfImpKv9eSs=",
						"D6b":"ST"
					},

**Comment by goatfungus** [comment]
That is good info, thanks for this!

You wouldn't happen to have an older save (pre 1.56) with message modules in it would you? It would really help to map them across to what they used to be.

**Comment by goatfungus** [comment]
Awesome, so that confirms "sHl" = "Message". I will add this to the mapping table.

The other 2 are new keys introduced after they started mapping the file, so it might be a little difficult to figure them out.

**Comment by goatfungus** [comment]
Ok, I think I have found all 3 mappings now, and have released a new version. Should be all good now :)
