### ISSUE TITLE
Couple of Sub-Windows/Menus Escaped the Text Reformat

### ISSUE THREAD

**Issue by Goose7** [goatfungus/NMSSaveEditor#135]
Just noticed these in the latest update.

![screenshot_20180906222739](https://user-images.githubusercontent.com/9331773/45256566-fd199a00-b34c-11e8-9df7-305b2f553dc9.png)

![screenshot_20180906222806](https://user-images.githubusercontent.com/9331773/45256567-03a81180-b34d-11e8-98c7-68876516928e.png)

@goatfungus -- Are you still working on the larger UI text version?   All the text fields have been widened, but the actual text is still the original size.

**Comment by Goose7** [comment]
I am unable to increase the length or width of these windows, which might help with this if it was possible.  ??

**Comment by goatfungus** [comment]
Ah, yes. I knew i would forget something.
I'll look at fixing in the next update, thanks.

**Comment by Goose7** [comment]
@goatfungus 

Cool!  I will look forward to checking out the next update.  Can I assume that the larger font size for the entire UI is still coming at some point?  It this can't be scaled, a Native 4k version of the Editor would be most welcome!

Cheers and thanks in advance!  👍

**Comment by goatfungus** [comment]
This should all be fixed now, as of 1.5.28 release.
