### ISSUE TITLE
Feature Request: Enter Key Function

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#137]
Hi, I am observing that when you save in the application the main window does not update the save date time.

It would be cool in the current search scheme if when hitting enter when there is a valid object in the search bar that it operated that function first. And then, if the search and create items matched hitting enter would add the item.

**Comment by goatfungus** [comment]
I have fixed the modified date issue in the latest release, 1.5.28. I am not sure what you mean by search scheme for the rest of it. Can you please clarify?

**Comment by ukmerlin** [comment]
Thank you...
I usually just type and then hit enter. If I have already been adding items hitting enter will add the previous item. If there is no previous item it will add nothing. Would be good if the "enter" key focus tracked the active field in some way. I had suggested either with field compares or null compare but that is without knowing how the panel works in the first place :)

**Comment by ukmerlin** [comment]
I think todays update has nerfed the app. At least in base moving as for some reason it has stopped. While on the topic I was finding the last week that sometimes in a base move half the base would be gone, the half around the radius of the base computer. I intended to check the JSON but this update came along before I had a chance.
And; any feel for what parameters are the height of the base computer? what would I tweak to lift all components straight up? Ta! :)
