### ISSUE TITLE
Savegameproblem after Gameupdate 1.60

### ISSUE THREAD

**Issue by MurphySlaw666** [goatfungus/NMSSaveEditor#139]
When i try to use the " Save as " Button to Save my Changes on an other Slot i can't open the Savegame in No Man's Sky because it doesn't shows up there.
After i had made my Changes and opend the Game the new Savegame is gone.

**Comment by goatfungus** [comment]
I don't have any problem with the Save As button.

If you've used Alt-Tab in the game menu, used "Save As" and then return to the game menu it won't show up if you're already on the selection menu. Just right-click to go back to the first menu, and choose the Play Game option again to make the list reload.

**Comment by MurphySlaw666** [comment]
I don't use Json during playing the Game. I will try.

**Comment by MurphySlaw666** [comment]
Using " Save as " during the Game workes!. Thank you for help.
