### ISSUE TITLE
Is it possible to delete ship via the save editor?

### ISSUE THREAD

**Issue by Jayshua83** [goatfungus/NMSSaveEditor#14]
Would like to be able to delete ships from my save via the editor since you can't sell them in-game!

**Comment by LordBlade** [comment]
I would love this option myself. For some insane reason, the game itself doesn't allow you to delete/abandon/sell ships that you don't want. If you hit your max ships, you basically have to keep flying about in ones you want to replace hoping to find new ones. Which is incredibly stupid.

**Comment by goatfungus** [comment]
You should be able to do this now (Version 1.5.4)
