### ISSUE TITLE
CHANGELOG.md doesn't update automatically

### ISSUE THREAD

**Issue by lofblad** [goatfungus/NMSSaveEditor#142]
Just a minor enhancement I guess, but it would be nice if the CHANGELOG.md file would update with the auto update function.

**Comment by goatfungus** [comment]
CHANGELOG.md isn't supposed to be downloaded at all, and isn't in the self-extracting archive. Did you download this manually?

**Comment by lofblad** [comment]
It isn't in the archive? I was pretty sure I used to get an updated file every time I updated before?

**Comment by goatfungus** [comment]
Was never in the archive, only on the github site.
