### ISSUE TITLE
Freighter Base Save Location

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#143]
Seems like this should also use the base backup folder

**Comment by goatfungus** [comment]
Does it not? I have double checked and it already uses the same folder as planetary base backups.

**Comment by ukmerlin** [comment]
I just checked with the latest release and it is still saving to the NMSE root directory but bases go to the bases folder.

**Comment by Rianon** [comment]
I confirm this.

**Comment by goatfungus** [comment]
Turns out if you don't have a freighter name the editor navigates back to parent directory.
I have fixed this in latest release, 1.5.30.
