### ISSUE TITLE
Technology Modules should not stack when moved

### ISSUE THREAD

**Issue by Xavanil** [goatfungus/NMSSaveEditor#144]
Tech modules purchased from vendors do not stack in game prior to installation.  Moving them to another inventory in the save editor stacks them, leaving only one in game.

**Comment by goatfungus** [comment]
Looks like a problem with the game data files. The game data says that tech modules stack like normal items, so HG must be doing something weird like hard-coding the size limits in the game itself when they already have a structure that defines the limits. Nice quality code right there.

I don't usually like to introduce hard-coded rules in the editor to overcome game issues like this, as they are usually fixed fairly quickly, but I'll see if I have time.

**Comment by goatfungus** [comment]
This should be fixed in version 1.5.32 (just released)
