### ISSUE TITLE
Suit Technology Slots not expanding/enabling

### ISSUE THREAD

**Issue by Nimarus84** [goatfungus/NMSSaveEditor#145]
I have a feeling this is a known issue. I noticed this has been fixed for ship tech slots at least. Expanding and Enabling tech slots in suit show okay on the editor. However, the game still shows only 14 slots available (7x2).

Running latest Save Editor 1.5.29 and latest Experimental Build.

**Comment by roie-r** [comment]
That was changed in NMS patch 1.60 (or was is 1.59?)... Suit tech slots are now limited to 7X2 - whatever you'll input in the editor the game will crop it down to size.

**Comment by ymgenesis** [comment]
I noticed this issue a while ago. Was this a new(ish) feature of NMS? Restricting the exosuit tech slots? Or was it a bug? Bug would suggest that there's hope of it being resolved, is all I mean.

**Comment by roie-r** [comment]
According to the Wiki 14 is the intended number of tech slots. The game, now, just enforces it and overwrites external edits... Feature or bug - with NMS it's sometimes hard to tell.

**Comment by goatfungus** [comment]
I have introduced a hard-coded 7x2 max size rule in version 1.5.30, so it should now match the in-game rule.
