### ISSUE TITLE
There's no Patreon link in the README.md.

### ISSUE THREAD

**Issue by dtupper** [goatfungus/NMSSaveEditor#15]
You should fix that!

**Comment by lofblad** [comment]
Yeah how do we support your work? I can't find a paypal or anything like that.

**Comment by goatfungus** [comment]
Ok, I have set up a Patreon account now (got to be a first time for everything).

https://www.patreon.com/goatfungus

**Comment by dtupper** [comment]
Subbed. Thanks for putting this up, and thanks for all your hard work.
