### ISSUE TITLE
moving enabled/disabled slots around for exocraft

### ISSUE THREAD

**Issue by nexusmods-snarkhunter** [goatfungus/NMSSaveEditor#150]
Before the latest Exocraft update, each vehicle's inventory slots could be individually enabled/disabled, so we could rearrange inventory to get rid of gaps, etc. Now, the save editor still allows those changes, but they seem to be completely ignored in game. Suggestion: if there is no workaround, then maybe grey out the Enable Slot option on right context menu in save editor so players know that isn't possible.

**Comment by goatfungus** [comment]
This is good to know.... I suspect HG may have restricted the inventory for vehicles in game, but didn't have time to test this myself. Hopefully they aren't planning to do this for ships/freighters too.... it could get messy. I'll keep this one open while we do more investigation.

**Comment by goatfungus** [comment]
I have disabled the enable/disable slot function for Exocrafts in version 1.5.32 (just released).
