### ISSUE TITLE
Exocraft inventories not increased after patch 1.63

### ISSUE THREAD

**Issue by HansWestra** [goatfungus/NMSSaveEditor#152]
Seems that previous edits/saves using this editor borked the exocraft inventories after patch 1.63
Any chance that it could be fixed?

**Comment by goatfungus** [comment]
Please provide screenshots.

If you mean the game doesn't recognize 6x8 resized inventory on exocraft anymore, that is a new restriction in the game which the editor has no control over. I haven't yet put in a size restriction in the editor.

**Comment by Jontom18** [comment]
E.g. On Roamer there are 28 slots. If you use the Save Editor to enable all 35 slots and save when you go back into the game the default 28 are only available.

**Comment by HansWestra** [comment]
I used save editor and used enable all slots on the exocrafts.
I did not resize exocraft inventories, i just moved components around to the top rows.
Somehow after patch 1.63 i now still have to original exocraft inventory sizes.
It would appear that changes made with editor somehow 'locked' this in place and prevented the new resized inventory's from becoming actual.

Cant tell for sure though :/
If its not editor related i'll just have to wait until HG patches the game further.
Would hate to loose the save though and restart.
Got a lot of stuff at the galactic hub atm 😊

Anyhow it's not a top priority thing game is playable just fine asides from this weird exocraft inventory thing.
Anything that can be done though would be appreciated.
________________________________

**Comment by goatfungus** [comment]
Ok, so it appears the game now ignores the slots structure in the save file entirely. I have no idea why they would do this, and yet leave the structure in the file. HG what are you doing!?!

From what i could gather, if you have resized the inventory or unlocked slots with the editor, the game will do its best to move any items into the new structure, and if you have any overflow, those items are gone. I would like to check if those items aren't "gone" but merely hidden, but the existing inventory move bug in the game makes it difficult to test this.

Probably the best solution here is to remove the ability to enable slots for exocraft, so I'll look at doing that in the next update.

**Comment by goatfungus** [comment]
I have disabled the enable slot function in version 1.5.32 (just released)

**Comment by HansWestra** [comment]
aight little update, trashed my save, restored only dat files from backup and issue was resolved.
Apparently after logging 1700+ hrs on this save, there were remnant files from older versions in the save directory overriding  exoocraft inventories and as an added bonus my terrain edits were reset as well so  i can actualy buid crap again. ::)
