### ISSUE TITLE
Filter out already owned products / blueprints

### ISSUE THREAD

**Issue by emodric** [goatfungus/NMSSaveEditor#153]
I like to use the save editor as a helper app that gives me a nice overview of my save game, without wasting time in game in the menus.

Currently, it's very hard to see what blueprints you're missing in the list of available items. It would be super helpful if dialogs to add new products or blueprints would filter out already known items and just hide them.

**Comment by goatfungus** [comment]
See #53... I'm not sure I'll get a chance to do this, but it is on the list already.
