### ISSUE TITLE
Exosuit technology slots resize

### ISSUE THREAD

**Issue by Jontom18** [goatfungus/NMSSaveEditor#155]
You changed it so we could not change it from the default 7x2 but now I have technologies that were in the extra slots that aren't accessible. I have moved out a number of slots into the main inventory hoping they would pop into the free slots on reload but to no avail. Anyway to move the tech in the hidden extra slots ?

**Comment by goatfungus** [comment]
Sounds like the game has screwed up your slots if some of the stuff is hidden. Might pay to use JSON editor and delete the items out manually.
