### ISSUE TITLE
Discovered systems and planets

### ISSUE THREAD

**Issue by emodric** [goatfungus/NMSSaveEditor#156]
Hi,

Would it be possible to show discovered systems and planets together with their coordinates/economy types/conflict levels/biomes in the editor, in read only mode ofcourse? Is that info stored in the save game at all?

Thanks!

**Comment by goatfungus** [comment]
No. The save file only stores the seed for the system itself, none of those things are stored with it. The game uses this seed in it's procedural algorithm to show what you see on screen.

**Comment by emodric** [comment]
Alright, thanks!
