### ISSUE TITLE
Broken Frigates

### ISSUE THREAD

**Issue by MuteButtonHero** [goatfungus/NMSSaveEditor#159]
Its a known issue in NMS that science frigates are broken and you can't repair them. Attempting to leaves you falling into space.

So I thought perhaps I could fix it using the SE but there's not a place for that in the UI and poking through the JSON I could not identify it. I assume it has to be somewhere in the save but I can't identify it.

If you could add a function in the UI or just identify that item in the JSON it would help us get around a nasty HG bug.

Thanks!

**Comment by MuteButtonHero** [comment]
Oh, I should add that there did seem to be a place for that in the JSON but it showed 0 damage on ships I know were damaged. Maybe pointing at the wrong thing? HG could have changed it because they do that a lot.

**Comment by Anticept** [comment]
It's not just damage that you have to set, there's also a damage module code that codifies which modules are actually broken. You have to completely remove that line if I recall (experience based on pre-next).
