### ISSUE TITLE
[BUG] non-alphabet characters in player's base name cause an error when using the base backup function

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#162]
What the title says:
Having [^] in a base name just pops a 'error occurred in the backup' message.
Having [:] in a base name crops the suggested file's name at the [:] and saves an empty file.
Having [::] in a base name gives the a 'error occurred in the backup' message.

I didn't check other characters, so there maybe be more of the same. Needless to say, the ones mentioned above work in-game or I wouldn't have found this bug.

Perhaps just cleaning non-legal characters from the file name would be enough? Cheers :)

**Comment by goatfungus** [comment]
I have completed a solution for this (cleaning out invalid characters as suggested), but I was wondering how urgent it is? I have been waiting for more significant changes to be made to the game before I send out another release....

**Comment by roie-r** [comment]
Since no one complained about it so far - I'd say 'not urgent at all' (apparently, I'm the only one who adds odd characters to base names - and uses your tool to back them up) :)

**Comment by goatfungus** [comment]
This should be fixed now in the latest version, 1.5.33.
