### ISSUE TITLE
name mappings: NMS 1.61

### ISSUE THREAD

**Issue by Rrys00** [goatfungus/NMSSaveEditor#166]
I'm running version 1.5.34 of NMSSE.  When I start it and load my latest save (I'm on version 1.71 of NMS) NMSSE shows that version 1.61 of name mappings is in use.  Is this generated by NMSSE, or is it reading this from the game save?

Thanks

**Comment by roie-r** [comment]
Name mapping was added to NMSSaveEditor to handle the shortened/obfuscated object names introduced in patch 1.58; Since patch 1.61 it doesn't need updating (so far) so the function's comment stayed the same.

**Comment by goatfungus** [comment]
What @roie-r said above..... I generally only update version numbers on things that have changed, and since 1.61 there have been no additional mappings needed. Hope that solves the confusion.
