### ISSUE TITLE
Missing new procedual product - Ancient Bones

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#168]
What the title says, 'Add Item' function doesn't have the new 'Ancient Bones' (PROC_BONE) in the their icon is missing too.

**Comment by gorlaxx** [comment]
The save editor updates automatically, but these kind of changes require manual update.
The procedural products from Abyss, Aquatic Treasure (PROC_SEA) and Terrifying Sample (PROC_FEAR) not yet added either, so Excavated Bones (PROC_BONE) and Salvaged Scrap (PROC_SALV) from Visions will have to wait, but I hope that we will get it soon.

See my other comment regarding this here:
https://github.com/goatfungus/NMSSaveEditor/issues/163
