### ISSUE TITLE
Missing name mappings in 1.76

### ISSUE THREAD

**Issue by Rianon** [goatfungus/NMSSaveEditor#169]
![3](https://user-images.githubusercontent.com/1091383/49258008-f9297f80-f444-11e8-9bee-59f643a96177.png)
When I tried to edit my save today I saw 3 new item names not detected by editor. All new items I have in inventory (in comparison with previous save) is just 3 fireworks I bought from quicksilver bot. So it is very possible that fireworks are exactly that missing items.

**Comment by goatfungus** [comment]
Name mappings are nothing to do with Items, so this is just a coincidence.... as you'll notice with the latest changelog, I updated the items list and icons but not the name mappings for new structures in the save file. Name mappings are still in progress.

**Comment by Rianon** [comment]
Sure. This is the context for "rk3":
`
"LastUABeforePortalWarp":"0x206A0003CACAFB",
"StoryPortalSeed":0,
"ShopNumber":8,
"rk3":1
`
and this is for "tiH" (there're many pieces of it, but always in a such context):
`
"FL":{
	"C":1,
	"tiH":1
},
"RID":"d4ldleueFbwSdWI/Hw1Kmyo0h3bY7ElPYosr6ajzVIU=",
"PTK":"ST"
`

**Comment by goatfungus** [comment]
This issue will be ongoing as new data structures are added. I'll open a new issue once the next version of NMS is released.
