### ISSUE TITLE
Cant edit Freighters - Most stuff greyed out

### ISSUE THREAD

**Issue by snckrz** [goatfungus/NMSSaveEditor#17]
For some reason many of the tabs are greyed out. E.G The Freighter Tab, vehicles, discoverys... Interestingly even Save functions are greyed out.

**Comment by goatfungus** [comment]
This seems to be caused when the game sets your primary ship index higher than the number of ships you have. The editor wasn't checking for this, and just assumed it would be correct.

I have added a sanity check in Version 1.5.5 which should fix this.
