### ISSUE TITLE
Feature Request: Freighter NPC Editor

### ISSUE THREAD

**Issue by Furiant** [goatfungus/NMSSaveEditor#175]
Not sure if this topic is covered in the "Change Freighter NPC Spawn" request (#80), but I'd really like to be able to input a code for my freighter captain and navigator. I want them to be in uniform!

**Comment by goatfungus** [comment]
Unfortunately, there is only one value to control your freighter. A single seed value gets expanded out to determine a whole range of things, including the models for each NPC. You could say it's a limitation of the procedural generation algorithm in the game itself.

It would be nice if the game used procedural generation to initialize the freighter only, and once you have it loaded you could then customize, but currently any customization is limited to the room layout only.
