### ISSUE TITLE
Error on line #34962: invalid exponent!

### ISSUE THREAD

**Issue by Nutcil** [goatfungus/NMSSaveEditor#177]
When I try to load up my save file for my game it pulls up, Save File Recovery (advanced users only).
It says the problem is on line 34962 but then brings me to line 45604. This is what it says.
{
	"b2n":"^DIST_WALKED",
	">MX":{
		"eoL":4.1007998384263e23
	}
},
the problem number is "eoL":4.1007998384263e23
I have tried to change it and save but when I do all my tabs in the hack is empty.
if there is any help it would be greatly appreciated

**Comment by goatfungus** [comment]
I'd like to know how exactly you walked 400000000000000000000000 miles on one planet in the game? That is really impressive! ;)

You could try changing it to 100000.0 and that should be more than enough for the milestone.

I think the problem may be dependent on the operating system, as a positive exponent value is typically written as 4.1007998384263e+23 on my save files, but that is different to yours. I'll put in a check in the next update to catch this problem in future.

**Comment by Nutcil** [comment]
Dude I am dying lol sorry it like just came threw but I got it thank you but I completely forgot about doing this man. I just put everything up to get all the achievements lol. But I guess if you work for NMS then I mean a little determination can get you anywhere lol
