### ISSUE TITLE
[Suggestion] Freighter colour palette seed

### ISSUE THREAD

**Issue by UbiquitousMoose** [goatfungus/NMSSaveEditor#18]
Hey,

Awesome utility,

I've noticed that in NEXT, PlayerStateData->CurrentFrieghterHomeSystemSeed sets the colour palette for your freighter, it doesn't appear to affect anything else from what I can tell from the dozen or so values I've tried. In my testing it didn't seem to change the palette for the docking module though, just the main body - I may have missed something there.

Anyhow, a possible line of investigation for another value for the freighter tab.

Moose.

**Comment by goatfungus** [comment]
The next release will have this, as well as ability to modify frigates.

**Comment by goatfungus** [comment]
The new seed value field has been added in 1.5.6.
