### ISSUE TITLE
Update for Beyond?

### ISSUE THREAD

**Issue by lucifer6642** [goatfungus/NMSSaveEditor#182]
Not an issue as such, more just hoping.

NMS Beyond came out today, with a whole bunch of new stuff. I hope you'll be updating the editor to support it.

Thank you for the fun had so far with the editor on previous versions.

**Comment by AnotherFoxGuy** [comment]
The editor still works, I just used it to fix up my freighter 
But it would be nice if it supported the new features

**Comment by dtupper** [comment]
No rush, but greatly looking forward to this! I have a few saves I need to fix up and I'm worried about messing with them in pure JSON.

**Comment by richarddoge8079** [comment]
Found his latest update on https://nomansskymods.com/mods/no-mans-sky-save-editor/
![image](https://user-images.githubusercontent.com/19426598/63111166-b4884900-bfbf-11e9-8340-2181218b5d07.png)
Safe to say it will take a while, but at least the current version will have to do for now till BEYOND ver of the editor comes out

**Comment by goatfungus** [comment]
Hi all. Yes, I am currently working on an editor update for beyond, but considering the amount of changes they have made it may take a bit of time. :)

**Comment by bradzoob** [comment]
you're a legend :)

**Comment by goatfungus** [comment]
Ok, first release for Beyond is ready. Please note that there is a good chance that not everything will be working in-game yet, but its a start.
- Items lists & icons have been updated
- Added substance limit of 9999 on creative/normal saves.

**Comment by gorlaxx** [comment]
Thank you for your awesome work!

I know adding procedurally generated items takes time, so I tried to add the Abyss and Visions related procedural products in December (using GitHub and Atom) and seemingly they were in the code, but there was no option for them in the menu to be chosen.

If you have some time, could you look at it? The information can be found in the PROCEDURALPRODUCTTABLE.MBIN file and the main property names are: SeaLoot, SeaHorror, Salvage and Bones.

**Comment by goatfungus** [comment]
Procedural products have been updated now (as of version 1.6.1).
