### ISSUE TITLE
Known Words not loading

### ISSUE THREAD

**Issue by AzzaNancazza** [goatfungus/NMSSaveEditor#185]
The Known Words list on the Discovery tab does not populate, as if you had not learnt any words. 

There are some JSON warnings are shown in the console:

![Capture](https://user-images.githubusercontent.com/49847508/63206587-8748b180-c10b-11e9-8606-cba6e1d0ae26.PNG)

**Comment by goatfungus** [comment]
The way words are stored in the save file has been changed in BEYOND. I have a fix for this ready for the next editor update.

**Comment by goatfungus** [comment]
This is now fixed (as of version 1.6.1)
