### ISSUE TITLE
Game crashing after update

### ISSUE THREAD

**Issue by WKrooshof** [goatfungus/NMSSaveEditor#186]
I'm not sure if it's related to the latest update, but since the I've only edited some inventory stock, my game keeps crashing on random points, talking to NPC; walls disappearing etc.

**Comment by Alterios** [comment]
A lot of those are reported bugs from the update itself. The save editor creates backups of the unedited files. Try restoring that and see if the bugs go away.

**Comment by WKrooshof** [comment]
Yes I think that's the issue, will close this :)
