### ISSUE TITLE
Building Crash to Desktop

### ISSUE THREAD

**Issue by sonicviz** [goatfungus/NMSSaveEditor#189]
This was working fine in Beyond until the save editor was updated for Beyond. 

Now, every time I try and connect any objects with wiring it crashes to desktop, 

I don't see this as a widely reported bug so my gut feel is telling me this is possibly something introduced by the recent save editor changes. As mentioned, I was using the pre-beyond save editor with beyond and old save files just fine, but after you updated it I can longer use electrical wiring - which is a bit of a game breaker!

**Comment by ensemblebd** [comment]
weird, i tested it on mine out of curiosity and didn't experience the issue. 
Am thinking it's a specific glitch with a specific reason

**Comment by sonicviz** [comment]
hmmm..thanks for checking. If other people can't replicate it then I guess my Beyond dream run is over. I haven't really had any problems with it so far, but now weird glitches are happening maybe I should just uninstall it and check back in 6 months.

**Comment by sonicviz** [comment]
I give up

**Comment by ensemblebd** [comment]
Sorry wish I could help. I can confirm for me that traveling to new system after save op, works normally with building operations. My first guess is Mods are causing it, but you'd have to reset everything to verify. Wish you the best, and hopefully the repo owner will come in and give his 10 cents

**Comment by sonicviz** [comment]
It's ok, I closed it because on further testing I don't think it's SE related. 
I have old save files that work, then suddenly stop with crash to desktop.
I deleted all saves, removed all mods, verified files, and started a new creative mode game and it crashes to desktop just trying to build a module when you add something to it, like a door.

So basically my NMS which was working fine is now unplayable if you want to build anything. 
Something is seriously wrong with software that is so twitchy, 

It seems closest to this issue reported here: https://steamcommunity.com/app/275850/discussions/1/1762481957309393715/

I have it on an 1gb SSD so going to move it back to C drive to see if that clears it.

**Comment by sonicviz** [comment]
Nope, that didn't work. It's not permissions. 
/Uninstall

I've got better things to do with my time than play crash test dummy for twitchy games.

**Comment by sonicviz** [comment]
I think I figured it out. After doing a full uninstall/reinstall it seems you can't get access to the full build menu until you set up a base. 

However, in the cases where I was crashing to desktop I had the full build menu available from the start and could rez objects without having a base computer. So what I think was happening is that when I tried to attach two objects together it crashed as it tried to attach them to a base, but as no base existed it crashed. 

The weird thing is in creative mode build menu before you build a base it shows one Aquatic module, the marine shelter. I guess that's a safety feature as you don't technically need a base in order to rez it.
