### ISSUE TITLE
█ SUGGESTION █ Frigate Editor

### ISSUE THREAD

**Issue by Unforgivinq** [goatfungus/NMSSaveEditor#19]
Add an editor inside Freighters to edit Frigates or make it separately with its own class and ranking including seeds and stats.

**Comment by Unforgivinq** [comment]
@goatfungus is this do-able or being worked on?

**Comment by goatfungus** [comment]
Its currently being worked on. Most of it is done, i just have a few more
tweaks to do.

**Comment by Unforgivinq** [comment]
Also might you know when this might be released? Also is there a possibility to add frigates using this instead of having to find and buy each one?

**Comment by goatfungus** [comment]
This has been added to 1.5.6 release. It also includes the ability to make copies of existing frigates or remove them if needed.

**Comment by Unforgivinq** [comment]
I LOVE YOU <3
