### ISSUE TITLE
new (?) name mappings

### ISSUE THREAD

**Issue by tamlin-mike** [goatfungus/NMSSaveEditor#190]
Editor 1.6.1.
On loading a save I get:
```
using name mappings: NMS 2.0
  WARNING: name mapping not found: BpT
  WARNING: name mapping not found: J=S
  WARNING: name mapping not found: vyN
  WARNING: name mapping not found: Bur
```
Identified from savefile:

BpT - integer (very small). Seen in conjunction with (and with same value as) h4X, so possibly the height of the grid.

J=S - string rep. of 64-bit integer. Seen same ID as from the K7E setting. (SteamID?)

vyN - string. User name. Possibly (most likely?) the "Last edited by" string, as seen hovering over a base computer.

Bur - bool. Only ever seen one instance of this in a savefile so far, and it was `false`. In the same section as `@Vn`.

**Comment by goatfungus** [comment]
Thanks. I have found the proper names for 3/4 of those, and will add to next update.

**Comment by goatfungus** [comment]
Ok, version 1.6.2 should fix 3 of those warnings, but you will still get the following:
WARNING: name mapping not found: Bur

Just ignore this for now.

**Comment by tamlin-mike** [comment]
Thanks for the expedient fix.

To keep the github issue count down; new missing mapping found, this time the othe way around:

`WARNING: reverse mapping not found: GrenadeAmmo`.

**Comment by uecasm** [comment]
FYI, `U2F` is another name not found in 1.6.2.

**Comment by tamlin-mike** [comment]
@uecasm Yup, I found that too now. Seems to be for frigate mission/expedition:
```
"NumberOfSuccessfulEventsThisExpedition":10,
"NumberOfFailedEventsThisExpedition":0,
"Events":[
	{
		"Seed":[
			true,
			"0xB2610351A3F4C248"
		],
		"UA":118747258656379,
		"AffectedFrigateIndices":[],
		"RepairingFrigateIndices":[],
		"AffectedFrigateResponses":[],
		"EventID":"^COMBAT_0",
		"InterventionEventID":"^",
		"U2F":"^",                    // <- Here
		"Success":true,
		"IsInterventionEvent":false,
		"AvoidedIntervention":false
	},
```

So it can safely be ignored, but for completeness should probably get a name eventually.

**Comment by goatfungus** [comment]
Regarding the following:
`WARNING: reverse mapping not found: GrenadeAmmo`
This particular value was removed from the save file way back before NEXT, and isn't used by the game anymore. I am wondering if this is from a really old save?

I will add the U2F mapping in the next version.

**Comment by tamlin-mike** [comment]
@goatfungus 
> `GrenadeAmmo`
>  I am wondering if this is from a really old save?

It was a Beyond-only savefile. If I were to guess it came from the plasma grenade multitool weapon I unfortunately (*) picked up from buying a multitool at a vendor where it was preinstalled.

(*) Fun sidenote; That plasma grenade was a very unfortunate find, since every f'ing time I tried to back out of the the too deep "menu"'s there was one extra RMB-click. Result? Plasma grenade launched into wall or machine and splattered my guts all over the place. _Ressurect_! :-)

**Comment by uecasm** [comment]
Now showing `wb:` as well.

**Comment by M-o-o** [comment]
Bur = ShipNeedsTerrainPositioning
U2F = OverriddenDescription
wb: = UsesThirdPersonVehicleCam  (possibly VR-only, doesn't appear to work for me in non-VR)

**Comment by goatfungus** [comment]
These mappings should be all resolved now (as of version 1.6.5)...
Thanks @M-o-o for your help :)

**Comment by cengelha** [comment]
No really contributing help for now (as all is resolved already anyway) but may I ask where/how do you find these mappings?

**Comment by M-o-o** [comment]
New for 2.2 Synthesis
`CA4        Layout
OGV        IsLarge
cf5        Outfits
SuJ        Multitools
j3E        ActiveMultioolIndex
qVG        PrimaryMode
jl;        SecondaryMode
deQ        BufferProtected`

**Comment by goatfungus** [comment]
Done, thanks for the info @M-o-o.
