### ISSUE TITLE
UI freaks out on right click

### ISSUE THREAD

**Issue by uecasm** [goatfungus/NMSSaveEditor#191]
Sometimes, when I right-click on an inventory slot in the grid to use the context menu, the UI completely freaks out.  Doesn't happen every time, but enough to be annoying.

Not sure of a better description for it -- it starts drawing everything multiple times and off to the side and the whole UI moves around with the mouse and just generally doesn't draw correctly.

This is using a fresh install of Java x64 1.8.0.221-b11.

![image](https://user-images.githubusercontent.com/539951/63336410-39de7580-c393-11e9-9d82-24dfcfdf7f67.png)

**Comment by uecasm** [comment]
FYI, it reliably happens whenever I right-click on one of the bottom (6th) row cells in the Exosuit inventory, or the bottom (5th) row in the Ship or Vehicles inventories.  The others seem to be immune, perhaps because they're smaller anyway.

**Comment by uecasm** [comment]
It also happens in the right-most cells, though I didn't notice that at first because they're still locked in my game.

Perhaps an off-by-one error somewhere?

**Comment by goatfungus** [comment]
If it were an indexing issue then everyone would experience the same thing.

My thoughts: Right click should be bringing up a context menu, and on the bottom / right most columns this could cause it to display outside of the main window frame. This would normally not be a problem as it is controlled by the version of java you are using in combination with your operating system. Problems similar to this have been solved by the user reinstalling Java or installing a different version.

**Comment by uecasm** [comment]
The context menu does appear, and it always appears correctly drawn.  The drawing issue usually happens when it closes, although it can also affect other windows (eg. clicking Add Item shows corrupted visuals in that dialog).

Also, it does sometimes occur in other cells as well, including those in the centre.  It's just a lot more likely to happen on the bottom row for some reason.

As I said, this was a fresh install of the latest Java.

**Comment by uecasm** [comment]
Just tried installing the 32-bit version of Java as well and explicitly running it under that:

    "C:\Program Files (x86)\Java\jre1.8.0_221\bin\java.exe" -jar NMSSaveEditor.jar -autoupdate

Exact same behaviour.

**Comment by uecasm** [comment]
Here's what it does in action, in case that helps...
[capture.zip](https://github.com/goatfungus/NMSSaveEditor/files/3545665/capture.zip)

**Comment by goatfungus** [comment]
The logs don't show anything strange?

**Comment by uecasm** [comment]
Nope:
```
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_221
[DEBUG] Working Dir: D:\Games\Tools\No Man's Sky
[INFO] Starting Editor...
[DEBUG] Save Path: <deleted for privacy>
[DEBUG] Mapping not available: tiH
[DEBUG] Mem Usage: 41/260 MB
[DEBUG] Latest version: "1.6.4"
[DEBUG] Current version: "1.6.4"
[INFO] Loading saves for Slot 3...
[INFO] Reading save file...
[INFO] Slot: Slot 3 - NORMAL
[INFO] Filename: save5.hg
[INFO] Parsing JSON...
[INFO] using name mappings: NMS 2.0
[WARNING] name mapping not found: Bur
[INFO] Finished.
```

**Comment by goatfungus** [comment]
This should be fixed now. There were a few indexing issues.
