### ISSUE TITLE
How to move your base computer?!

### ISSUE THREAD

**Issue by Yolo56** [goatfungus/NMSSaveEditor#192]
Hello everyone !

I repost my comment for everyone, who dont saw it. Maybe i will find someone who can know how to change the computer base properly without move everything arround. I do a looooot of test, and i still do not know how the game proceed his locations values. I take like 4h to change some locations, but my base have like 230 objects, and i only do 50.

I begin to hear voices during my sleep and want to blow my door with an axe...
Please can you give me a hand to solve this problem?

**Watch bellow for known, how to access the values.**

First you need to go in the Advanced Edit Save.
![image](https://user-images.githubusercontent.com/54182465/63306939-e44f8d80-c2ec-11e9-9a0c-9e672d5227b2.png)
You click here
![image](https://user-images.githubusercontent.com/54182465/63306975-ffba9880-c2ec-11e9-8f5c-50d8f11aa46e.png)
And the location of your base are here.
![image](https://user-images.githubusercontent.com/54182465/63307064-46a88e00-c2ed-11e9-8a1f-a57afa7275fb.png)
After that, you search the name your base with CTRL + F
And you just above that, you will see 
![image](https://user-images.githubusercontent.com/54182465/63310692-f4bb3480-c2fb-11e9-869d-08dad2b78d1c.png)

**Comment by temp-999** [comment]
Maybe this help?

https://github.com/jaszhix/NoMansConnect

**Backup and restore your base and move it to new locations**

**Comment by Yolo56** [comment]
Ty, i will watch that.
But i'm feeling it's for transfert a base to another. 
Not for "move" or replace the actual position of your computer without touching anything.

**Comment by goatfungus** [comment]
There is an easier way:
Place down a blueprint analyser or save point, and use the editors built-in move function.

NOTE: This was broken in early releases for BEYOND due to a versioning issue. Should be fixed now (as of 1.6.2).
