### ISSUE TITLE
Item stack limit

### ISSUE THREAD

**Issue by BobMaster1982** [goatfungus/NMSSaveEditor#193]
I started a game in Survival mode and I did not realise that the stack limits of mine-able resources is significantly lower.

So I tried to use the Save Editor to change SubstanceMaxStorageMultiplier, set them all to 40, but my stack limits are still the same.

Is there anything special I need to do to force this ?

Greetings,
BobMaster

**Comment by goatfungus** [comment]
The SubstanceMaxStorageMultiplier no longer works in game (it's ignored). What you can do is move your stack to another inventory and back again, and it should pick up the new maximum.

**Comment by BobMaster1982** [comment]
Ok thanks, too bad.
