### ISSUE TITLE
feature request (re: updates)

### ISSUE THREAD

**Issue by Toccatta** [goatfungus/NMSSaveEditor#194]
The editor could use a feature to disable auto-update for those users of No Man's Sky that don't intend to upgrade to the newest version immediately, and don't want the editor they use to have features removed due to incompatibility with a version that they're not actually playing yet.

Not everyone is playing the most up-to-date version of NMS, and I would hate to lose the ability to use your incredibly useful editor because you've eliminated features that are useful in the version I'm playing, as they're no longer possible in the current release (and I'm absolutely NOT suggesting the features shouldn't be disabled... just that I should be able to set an option on my editor to stop nagging me to update to the newest EDITOR version until I'm ready to update NMS.exe to the newest GAME version.)

I'd also like to request information on how to get the previous version (1.5.37) to stop demanding that I update to 1.6.1 each time I start it up, since that version doesn't have any disable auto-update feature, and even if you added one to the newest version, it wouldn't really help my situation right now.

**Comment by goatfungus** [comment]
If you are still playing NEXT / VISIONS and haven't upgraded to BEYOND, there is an archived version (see the changelog file)... as for BEYOND, you still have to click the confirmation if you want it to download the new version, so if you simply click cancel it won't upgrade.

You might consider that a nag screen, but I did find that when the editor previously had no version check people were reporting bugs that were already fixed.

**Comment by Toccatta** [comment]
I completely understand why you would prefer to have the program auto-update rather than having to field questions about problems that you've already fixed... but if you added an option to turn off the auto-update and had it turned ON by default, only the people like myself that have a valid reason to want to continue using an older version would ever turn it off.

Even if that option is out of the question, perhaps you can give me an idea on how to prevent the program from detecting a newer version. I tried firewalling both inbound and outbound connections to java.exe, javaw.exe, and javaws.exe, but it kept demanding I update. I also removed the -autoupdate switch from the batch file, but that didn't help either. Does it check each time you start the program, or does it flag somewhere locally when it detects an available update so that it doesn't even need internet access any more? I checked the registry, but didn't find any information that looked like it would apply to NMSSaveEditor.

**Comment by Toccatta** [comment]
My "valid" reason is that new versions sometimes disable features that are no longer supported by the game executable. However, if a person isn't playing the most recent version of NMS.exe, that might remove features that ARE supported in the game they're playing. This has already happened to me once before. I don't remember the exact version, but I think it was when I was playing 1.33 and the current version was 1.37 and the ability to change available slots on exovehicles was removed from the editor. I had to manually edit the json files to do what had always been a simple task before, because the slot locations as well as the height and width had been hard-coded by HelloGames, but on a version I wasn't playing.

**Comment by goatfungus** [comment]
The details: It checks each time you start the program by comparing the version number to the VERSION.txt file here on GitHub. If they are different, it displays the message. If you run the app without the -autoupdate flag, it will still warn you that the versions are different but won't update. You can see the version number difference in the log file.

In most cases, if I remove a feature like the one you described, it will still be available using "Test Mode" (in the Edit menu). The only real exception to this would be if the change was part of a major game update (ie: 1.77 -> 2.0) and in that case I will keep a forked version of the editor here on GitHub for users who don't upgrade.

**Comment by Darlken** [comment]
This is along the same topic, yet a little different.  Not everyone wants the original stack sizes changed. Can you please add a button to change the stack size in the game, and to change the original stack size back to normal. Their are a lot of people that use your editor to fix issues with the game. Not everyone wants to change things. Thank you for your editor and your time.
