### ISSUE TITLE
Feature Issue

### ISSUE THREAD

**Issue by Darlken** [goatfungus/NMSSaveEditor#197]
The changing of stack sizes in creative and normal.
I, for one, use your save game editor to fix bugs and issues with NMS. I feel this a amazing tool, Thank you for your hard work and time put into this editor.

I was unhappy to see that you automatically changed the stack sizes in the game without a way to change them back. I maybe missing something in the editor. It has effected all saves and new  games as well. I have tested it by making multiple new games and the stack sizes have all been changed. This change is not just effecting the saved game but Moding the game as a whole.

So my question is this, Is their a way to change the stack sizes back to the original size in the game editor? If not or if you have to do it manually, could you please make a button that would allow these changes to be made and set the default to OFF. This way people can still use this amazing tool and not be forced to have their game Modded automatically?
 
Thank you again for this awesome tool. I hope to be able to use it again in the future.

**Comment by uecasm** [comment]
It sounds like you missed the fact that NMS Beyond itself increased the stack size for Normal games.  No save editor required.  If you prefer the smaller sizes, you have to play on Survival instead.

**Comment by Darlken** [comment]
OMG I totally did miss that fact and I am extremely sorry for accusing your editor for the change in stack size. I started a Survival game when Beyond came out and just started a normal game.
Thank you very much for taking the time to let me know. 
Once again thank you for all your hard work with the editor and I hope all goes well for you.
