### ISSUE TITLE
System file error when I run the .bat file of this save editor

### ISSUE THREAD

**Issue by Versora** [goatfungus/NMSSaveEditor#198]
The answer is probably staring me in the face, but since the game updated to Beyond I get the system file error cannot find file, and yes I got the latest version from here. So I'm probably thinking this in the works for an update. Yes, I also have the latest Java, unless I specifically need Java 8.
![error](https://user-images.githubusercontent.com/54393521/63497629-c5d2c900-c489-11e9-928c-5189d69532f5.png)

**Comment by uecasm** [comment]
Java is either not installed, or not in your PATH.  You would get the same thing if you open a command prompt and just type "java".

**Comment by Versora** [comment]
the weird part is: Java is indeed installed. I can try reinstalling Java to see if that helps though
