### ISSUE TITLE
Steam Cloud Sync Issue

### ISSUE THREAD

**Issue by MikeGamerGuy** [goatfungus/NMSSaveEditor#20]
When copying a save to an empty "slot" and loading the game, the game or steam deletes the newly saved slots when it syncs with the cloud.  To reproduce, have an empty slot and load another save in the editor.  "Save as" and copy the game to an the empty slot.  Load the game normally and you will notice that the slot doesn't exist.  If you disable cloud saving in the game properties, things work as intended.  Not sure if this is your problem or a HG problem.

**Comment by goatfungus** [comment]
Steam Cloud Sync has always had an issue with No Man's Sky, especially when using the editor as well. I usually turn it off and rely on backups instead.

If you really need to use it, try keeping the game open on the menu when you do any editing. I suspect the sync replaces your local files on game startup (from cloud), and pushes them back to the cloud on game shutdown, which means any changes made while the game isn't running may get overwritten.

**Comment by MikeGamerGuy** [comment]
Yes, that's what I started doing.
