### ISSUE TITLE
Resize Inventory

### ISSUE THREAD

**Issue by leseh11** [goatfungus/NMSSaveEditor#202]
If i click resize inventory on exosuit nothing change

**Comment by goatfungus** [comment]
Do you not see this dialog?
<img width="187" alt="resize" src="https://user-images.githubusercontent.com/41274031/63744003-174bdf80-c8f2-11e9-9807-8863874e5588.png">

Please note: The max you can resize to is 8x6

**Comment by goatfungus** [comment]
It sounds like you either aren't saving the file in the editor, or not exiting to the main menu in the game before using the editor. The editor does not edit your game file while you are playing.

**Comment by jimh54** [comment]
none of the ship technology slots can be expand greater than 7x3 in new game saves. i have a previous save from before the update and it remained 8x6. perhaps this is something to do with the beyond update.
