### ISSUE TITLE
cannot edit file

### ISSUE THREAD

**Issue by SJamison76** [goatfungus/NMSSaveEditor#206]
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/3561821/NMSSaveEditor.log)
Lots of java errors, cannot edit anything or open the file. Java Version 8 Build 221

[java-error.txt](https://github.com/goatfungus/NMSSaveEditor/files/3561812/java-error.txt)

[NMSSaveEditor.txt](https://github.com/goatfungus/NMSSaveEditor/files/3561813/NMSSaveEditor.txt)

**Comment by goatfungus** [comment]
Save file must be corrupted.
Since this was reported so long ago, please feel free to open another issue if you're still having problems.
