### ISSUE TITLE
Text scaling issue

### ISSUE THREAD

**Issue by TheBob12** [goatfungus/NMSSaveEditor#21]
When using a higher text scaling in windows, (when using 4k, I believe) the treeview in the JSON editor becomes weird. I think it's because the text size changes in windows, but java doesn't scale the height of the font or something like that. 
![image](https://user-images.githubusercontent.com/41843643/43361659-1bc70a16-92d5-11e8-86a5-c914cb00aa49.png)

**Comment by goatfungus** [comment]
Is this the JSON editor only, or are other windows/tabs in the editor messed up too?

**Comment by TheBob12** [comment]
Only the json editor

**Comment by goatfungus** [comment]
I see what you mean. Looks like the windows theme/scaling is not sizing everything correctly.
I'll look at adding some customization options to the config file so if anyone experiences this issue it can be solved.

**Comment by goatfungus** [comment]
This should be fixed now, version 1.5.11
