### ISSUE TITLE
[BUG] Freighter base backup/restore is disabled

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#212]
The freighter base backup restore buttons are disabled. Is this intentional?

**Comment by kotyra-74** [comment]
Indeed, why can’t you save and restore the freighter’s base?

**Comment by Gilgamaesch** [comment]
Will you renew this feature in later versions? I think, it will be helpfull.

**Comment by goatfungus** [comment]
This was fixed in a recent version.
