### ISSUE TITLE
Base storage issue

### ISSUE THREAD

**Issue by DarkAvengerT** [goatfungus/NMSSaveEditor#214]
I changed the storage by unlocking grayed out cells, and now when I try to click on items in game in the storage they are freaking out, shaking and unmovable. I can try to reload and check again, maybe change some storage back to default and see if it makes a different, but this is annoying.

**Comment by Rudolpher** [comment]
Either reloading or going to the opposite storage type has so far fixed that issue and once fixed it hasn't returned without further altering inventory layout or adding more boxes to the 'network'.
