### ISSUE TITLE
Stacking limits of many items have changed

### ISSUE THREAD

**Issue by VulcanTourist** [goatfungus/NMSSaveEditor#215]
The presumed stacking limits of many non-substance items need to be adjusted to reflect recent updates to the game.  Some portable devices, if added to a slot, are shown with a stack size of 5, but the game only allows a single device to stack in a slot.  Other items, such as Starship Launch Fuel, Warp Cells, and Navigation Data, have had their stack sizes increased, and so now stack more compactly than the Editor will allow.

**Comment by goatfungus** [comment]
Apologies for the extremely long delay, I have been bogged down in work related stuff. I have updated the stack sizes in the latest build (1.6.6), so it should be all good to go now.

**Comment by VulcanTourist** [comment]
Thank you for the continued devotion and maintenance!  In spite of slight room for UI improvement, this remains the most accessible modding related tool available to players.
