### ISSUE TITLE
Error after load save file

### ISSUE THREAD

**Issue by Rambo99** [goatfungus/NMSSaveEditor#216]
After start editor and load save file system send error :
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/3640001/NMSSaveEditor.log)

[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.aB.a(Unknown Source)
[STDERR] 	at nomanssave.Application.k(Unknown Source)
[STDERR] 	at nomanssave.Application.i(Unknown Source)
[STDERR] 	at nomanssave.Application.r(Unknown Source)
[STDERR] 	at nomanssave.T.run(Unknown Source)
[STDERR] 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)
[DEBUG] Mapping not available: tiH

**Comment by goatfungus** [comment]
Probably a corrupted save file.
Since this is an older issue, I'm going to close it. Feel free to reopen if you're still having problems.
