### ISSUE TITLE
Little flaw. Missing stats. 

### ISSUE THREAD

**Issue by Prolbo** [goatfungus/NMSSaveEditor#219]
Ship mobility, tool damage and tool scan range are not presented in editor. It would be nice if they would be. 

If this tied hardly to ship/tool seed/form-factor or just impossible throught save edit, I'm sorry for bothering. (Also I'm sorry if tool dmd & scan is just 100%++ stats - it not obvious)

**Comment by m0lz** [comment]
Thats an issue with the game itself, stats have been missing for upgrades since 2.12 and 2.13 Experimental. Its still a problem in the public release of NMS 2.14 too.

**Comment by Prolbo** [comment]
Yeah. Checked it. Seems like ship mobility hardly binded to ship seed. Also, somehow it different for NPC and Player.
