### ISSUE TITLE
Feature request: Unlimited Base Building

### ISSUE THREAD

**Issue by STOKE-STER** [goatfungus/NMSSaveEditor#22]
Hey Goat Fungus,

Found this easy guide to disable base building limits: https://imgur.com/a/8Hn4B#Gh582Al
Thought it could be something you may want to add to your program. I know it's not a change to the save data but rather actual game settings, it'd still be pretty cool to use in unison with your base backup stuff tho :)

Thanks for making an awesome editor

**Comment by Unforgivinq** [comment]
This would be a game editor orientated feature less than a save but who's to say this program cant be both? ;)

**Comment by GKboki** [comment]
@STOKE-STER @Unforgivinq 
Go to [your Steam] library and find [No Man’s Sky]
[Right click on the game’s title and ]Hit properties down the bottom
Go to local files tab at top
Click browse local files
Double click on Binaries
and again on settings
open TKGRAPHICSSETTINGS.MXML
Go to the last two properties in the file RemoveBaseBuildingRestrictions and set it to “true” and/or set BaseBuildingLimit to an arbitrarily high number.

**Comment by STOKE-STER** [comment]
@GKboki Hey man, I already knew how to do this, I just thought it might be cool to have in the program as toggle option in the bases tab :)

**Comment by goatfungus** [comment]
I have tried to keep this project strictly as a save editor, not interfering with the game itself or configs in any way. There are other mods and solutions out there, so I'd prefer not to start down that road or it could open up a whole raft of other similar ideas and suggestions.

I might add these details you've posted to an upcoming FAQ I'm building, if that's ok with you?
