### ISSUE TITLE
Feature request: PS4 save files

### ISSUE THREAD

**Issue by killmanor** [goatfungus/NMSSaveEditor#221]
I can decrypt and re-encrypt and am more than happy to provide my game save to do this if necessary. 

The code is in a readable format I just don’t know what values to change myself in order to edit the items etc in game

**Comment by cengelha** [comment]
Hi,
I'm working on my own save editor (see profile).

I wrote something in the newer issue #258. Maybe you can provide some additional information there.

**Comment by goatfungus** [comment]
Already done, just cleaning up.
