### ISSUE TITLE
Feature Request: Drop Down File List

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#223]
Would be useful if this was wide enough to show the date of the file too.

**Comment by DNJI** [comment]
Hello, is this open source? Can I get a source code? If you can, this is my email: 2634963005@qq.com thank you

**Comment by DNJI** [comment]
I'm very interested in this. I want to try it on my own.

**Comment by goatfungus** [comment]
I have added the last save date and increased the width of these in version 1.6.7.

**Comment by ukmerlin** [comment]
Please reopen:
1. If I pick a game slot and scroll down to back up files I still do not know what date the backups are that I am looking at.
2. Trying to open backup files the game slot still shows the original game slot and date.
3. After trying to open four back up slots I get a scrolling of the error "Warning: Could not build word groups: null" I am guessing this is due to reaching a backup that predates the current version states of game vs tool.
