### ISSUE TITLE
[BUG] Frigate traits strength actual values don't match description in the list

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#224]
The strength values listed in the frigate traits dropdown menu (+2 combat, -1 speed) do not match the trait's ID (COMBAT_TER_2, SPEED_BAD_1) in the console window - which are the real values being assigned.

**Comment by temp-999** [comment]
Don't know - maybe this will help. I compiled this from my 30 frigates and don't have all the possibilities. I also couldn't figure out how to pick the appropriate TraitIDs for the corresponding description. File is comma delimited.

NMS: how the game displays the frigate trait
NMSSE: how the save editor displays the frigate trait
Save File: TraitIDs

NMS,NMSSE,Save File
Ablative Armour +4 Combat,"Ablative Armour (Combat,5)",
Advanced Maintenance Drones Damage Reduction,"Advanced Maintenance Drones (Durability,2)",
Advanced Power Distributor -6 Expedition Fuel Cost,"Advanced Power Distributor (Fuel Capacity,5)",
Ammo Fabrications +2 Combat,"Harvester Drones (Combat,1)",
Anomaly Scanner +2 Exploration,"Anomaly Scanner (Exploration,4)",
Asteroid Vaporizer +6 Industry,"Asteroid Vaporizer (Mining,6)",MINING_SEC_6
Auto Translator +1 Trading,"Auto Translator (Diplomatic,1)",
Automatic Investment Engine +4 Combat,"Automatic Investment Engine (Combat,5)",
Cartography Drones +6 Exploration,"Cartography Drones (Exploration,6)",
Cloaking Device +6 Combat,"Cloaking Device (Combat,6)",
Combat Specialist +15 Combat,"Combat Specialist (Combat,7)",COMBAT_PRI
Dynamic Ballast -2% Expedition Duration,"Dynamic Ballast (Speed,2)",SPEED_TER_8
Efficient Warp Drive -4 Expedition Fuel Cost,"Efficient Warp Drive (Fuel Capacity,2)",
Experimental Impulse Drive -3% Expedition Duration,"Experimental Impulse Drive (Speed,3)",
Experimental Weaponry +4 Combat,"Experimental Weaponry (Combat,5)",
Expert Navigator -2% Expedition Duration,"Expert Navigator (Speed,2)",
Exploration Specialist +15 Exploration,"Exploration Specialist (Exploration,7)",EXPLORE_PRI
Extendable Drills +2 Industry,"Extendable Drills (Mining,2)",
Faulty Torpedoes -6 Combat,"Faulty Torpedoes (Combat,-3)",COMBAT_BAD_3
Harvester Drones +1 Combat,"Harvester Drones (Combat,1)",
Harvesting Drones +1 Combat,"Harvester Drones (Combat,1)",MINING_TER_4
Haunted Radar -2 Exploration,"Haunted Radar (Exploration,-1)",EXPLORE_BAD_5
Hidden Weaponry +1 Combat,"Hidden Weaponry (Combat,1)",
Holographic Components Damage Reduction,"Holographic Components (Durability,2)",
Holographic Displays +2 Exploration,"Holographic Displays (Exploration,2)",
HypnoDrones +2 Trading,"HypnoDrones (Diplomatic,4)",
Industrial Specialist +15 Industry,"Industrial Specialist (Mining,7))",MINING_PRI
Leaky Fuel Tubes +4 Cost Per Warp,"Leaky Fuel Tubes (Fuel Rate,-3)",FUEL_BAD_3
Local Time Dilator -1% Expedition Duration,"Local Time Dilator (Speed,1)",
Long-Distance Sensors +3 Exploration,"Long-Distance Sensors (Exploration,3)",EXPLORE_TER_6
Mass Driver -1% Expedition Duration,"Mass Driver (Speed,1)",
Massive Guns +2 Combat,"Massive Guns (Combat,4)",
Mind Control Device +6 Trading,"Mind Control Device (Diplomatic,6)",
Mineral Extractors,"Mineral Extractors (Mining,1)",
Misaligned Sensors -4 Exploration,"Misaligned Sensors (Exploration,-2)",EXPLORE_BAD_4
Negotiation Module +2 Trading,"Negotiation Module (Diplomatic,2)",
Oil Burner +1 Cost Per Warp,"Oil Burner (Fuel Rate,-1)",
Outdated Maps -4 Exploration,"Outdated Maps (Exploration,-2)",
Overclocked Power Distributor -4 Expedition Fuel Cost,"Overclocked Power Distributor (Fuel Capacity,2)",
Oxygen Recycler -2 Expedition Fuel Cost,"Oxygen Recycler (Fuel Capacity,1)",
Planetary Data Scoop +1 Exploration,"Planetary Data Scoop (Exploration,1)",EXPLORE_TER_1
Poorly-Aligned Ballast +2 Cost Per Warp,"Poorly-Aligned Ballast (Fuel Rate,-2)",
Realtime Archival Device +2 Exploration,"Realtime Archival Device (Exploration,4))",
Reinforced Hull +3 Combat,"Reinforced Hull (Combat,3)",COMBAT_TER_3
Remote Market Analyser +2 Trading,"Remote Market Analyser (Diplomatic,2)",
Remote Mining Unit,"Remote Mining Unit (Mining,3)",
Robot Crew -6 Expedition Fuel Cost,"Robot Crew (Fuel Capacity,3)",
Self-Repairing Hull Damage Reduction,"Self-Repairing Hull (Durability,2)",
Small Hoppers -4 Industry,"Small Hoppers (Mining,-2)",
Spacetime Anomaly Shielding +6 Exploration,"Spacetime Anomaly Shielding (Exploration,6)",
Support Specialist -15 Expedition Fuel Cost,"Support Specialist (Fuel Capacity,7)",FUEL_PRI
Terraforming Beams +4 Industry,"Terraforming Beams (Mining,5)",FUEL_TER_7
Thief on Board -4 Trading,"Thief on Board (Diplomatic,-2)",TRADING_BAD_4
Thirsty Crew +1 Cost Per Warp,"Thirsty Crew (Fuel Rate,-1)",FUEL_BAD_1
Tractor Beam +4 Combat,"Tractor Beam (Combat,5)",
Trade Specialist +15 Trading,"Trace Specialist (Diplomatic,7)",TRADING_PRI
Tremendous Cannons +6 Combat,"Tremendous Cannons (Combat,6)",
Tuned Engines -4 Expedition Fuel Cost,"Tuned Engines (Fuel Capacity,2)",
Ultrasonic Weapons +2 Combat,"Ultrasonic Weapons (Combat,4)",
Uncalibrated Warp Drive -6 Exploration,"Uncalibrated Warp Drive (Exploration,-3)",EXPLORE_BAD_3
Underpowered Lasers -4 Industry,"Underpowered Lasers (Mining,-2)",
Wormhole Generator -3% Expedition Duration,"Wormhole Generator (Speed,3)",

**Comment by temp-999** [comment]
Don't know - maybe this will help. Compiled from my thirty frigates and will not be complete. Could not determine which TraitIDs went with which trait description. Records are comma delimited.

NMS: game trait description
NMSSE: save editor trait description
Save File: TraitIDs

NMS,NMSSE,Save File
Ablative Armour +4 Combat,"Ablative Armour (Combat,5)",
Advanced Maintenance Drones Damage Reduction,"Advanced Maintenance Drones (Durability,2)",
Advanced Power Distributor -6 Expedition Fuel Cost,"Advanced Power Distributor (Fuel Capacity,5)",
Ammo Fabrications +2 Combat,"Harvester Drones (Combat,1)",
Anomaly Scanner +2 Exploration,"Anomaly Scanner (Exploration,4)",
Asteroid Vaporizer +6 Industry,"Asteroid Vaporizer (Mining,6)",MINING_SEC_6
Auto Translator +1 Trading,"Auto Translator (Diplomatic,1)",
Automatic Investment Engine +4 Combat,"Automatic Investment Engine (Combat,5)",
Cartography Drones +6 Exploration,"Cartography Drones (Exploration,6)",
Cloaking Device +6 Combat,"Cloaking Device (Combat,6)",
Combat Specialist +15 Combat,"Combat Specialist (Combat,7)",COMBAT_PRI
Dynamic Ballast -2% Expedition Duration,"Dynamic Ballast (Speed,2)",SPEED_TER_8
Efficient Warp Drive -4 Expedition Fuel Cost,"Efficient Warp Drive (Fuel Capacity,2)",
Experimental Impulse Drive -3% Expedition Duration,"Experimental Impulse Drive (Speed,3)",
Experimental Weaponry +4 Combat,"Experimental Weaponry (Combat,5)",
Expert Navigator -2% Expedition Duration,"Expert Navigator (Speed,2)",
Exploration Specialist +15 Exploration,"Exploration Specialist (Exploration,7)",EXPLORE_PRI
Extendable Drills +2 Industry,"Extendable Drills (Mining,2)",
Faulty Torpedoes -6 Combat,"Faulty Torpedoes (Combat,-3)",COMBAT_BAD_3
Harvester Drones +1 Combat,"Harvester Drones (Combat,1)",
Harvesting Drones +1 Combat,"Harvester Drones (Combat,1)",MINING_TER_4
Haunted Radar -2 Exploration,"Haunted Radar (Exploration,-1)",EXPLORE_BAD_5
Hidden Weaponry +1 Combat,"Hidden Weaponry (Combat,1)",
Holographic Components Damage Reduction,"Holographic Components (Durability,2)",
Holographic Displays +2 Exploration,"Holographic Displays (Exploration,2)",
HypnoDrones +2 Trading,"HypnoDrones (Diplomatic,4)",
Industrial Specialist +15 Industry,"Industrial Specialist (Mining,7))",MINING_PRI
Leaky Fuel Tubes +4 Cost Per Warp,"Leaky Fuel Tubes (Fuel Rate,-3)",FUEL_BAD_3
Local Time Dilator -1% Expedition Duration,"Local Time Dilator (Speed,1)",
Long-Distance Sensors +3 Exploration,"Long-Distance Sensors (Exploration,3)",EXPLORE_TER_6
Mass Driver -1% Expedition Duration,"Mass Driver (Speed,1)",
Massive Guns +2 Combat,"Massive Guns (Combat,4)",
Mind Control Device +6 Trading,"Mind Control Device (Diplomatic,6)",
Mineral Extractors,"Mineral Extractors (Mining,1)",
Misaligned Sensors -4 Exploration,"Misaligned Sensors (Exploration,-2)",EXPLORE_BAD_4
Negotiation Module +2 Trading,"Negotiation Module (Diplomatic,2)",
Oil Burner +1 Cost Per Warp,"Oil Burner (Fuel Rate,-1)",
Outdated Maps -4 Exploration,"Outdated Maps (Exploration,-2)",
Overclocked Power Distributor -4 Expedition Fuel Cost,"Overclocked Power Distributor (Fuel Capacity,2)",
Oxygen Recycler -2 Expedition Fuel Cost,"Oxygen Recycler (Fuel Capacity,1)",
Planetary Data Scoop +1 Exploration,"Planetary Data Scoop (Exploration,1)",EXPLORE_TER_1
Poorly-Aligned Ballast +2 Cost Per Warp,"Poorly-Aligned Ballast (Fuel Rate,-2)",
Realtime Archival Device +2 Exploration,"Realtime Archival Device (Exploration,4))",
Reinforced Hull +3 Combat,"Reinforced Hull (Combat,3)",COMBAT_TER_3
Remote Market Analyser +2 Trading,"Remote Market Analyser (Diplomatic,2)",
Remote Mining Unit,"Remote Mining Unit (Mining,3)",
Robot Crew -6 Expedition Fuel Cost,"Robot Crew (Fuel Capacity,3)",
Self-Repairing Hull Damage Reduction,"Self-Repairing Hull (Durability,2)",
Small Hoppers -4 Industry,"Small Hoppers (Mining,-2)",
Spacetime Anomaly Shielding +6 Exploration,"Spacetime Anomaly Shielding (Exploration,6)",
Support Specialist -15 Expedition Fuel Cost,"Support Specialist (Fuel Capacity,7)",FUEL_PRI
Terraforming Beams +4 Industry,"Terraforming Beams (Mining,5)",FUEL_TER_7
Thief on Board -4 Trading,"Thief on Board (Diplomatic,-2)",TRADING_BAD_4
Thirsty Crew +1 Cost Per Warp,"Thirsty Crew (Fuel Rate,-1)",FUEL_BAD_1
Tractor Beam +4 Combat,"Tractor Beam (Combat,5)",
Trade Specialist +15 Trading,"Trace Specialist (Diplomatic,7)",TRADING_PRI
Tremendous Cannons +6 Combat,"Tremendous Cannons (Combat,6)",
Tuned Engines -4 Expedition Fuel Cost,"Tuned Engines (Fuel Capacity,2)",
Ultrasonic Weapons +2 Combat,"Ultrasonic Weapons (Combat,4)",
Uncalibrated Warp Drive -6 Exploration,"Uncalibrated Warp Drive (Exploration,-3)",EXPLORE_BAD_3
Underpowered Lasers -4 Industry,"Underpowered Lasers (Mining,-2)",
Wormhole Generator -3% Expedition Duration,"Wormhole Generator (Speed,3)",

**Comment by goatfungus** [comment]
The original change I made previously was only an indicator... It wasn't able to show current in-game values. However, I have included the real in-game values in the latest version, 1.6.7. Enjoy.
