### ISSUE TITLE
Standard heap size too small - and 4G heap size seems to be too much -solved- FYI

### ISSUE THREAD

**Issue by Graslama** [goatfungus/NMSSaveEditor#225]
fixed it with this batch file:
`
@echo off
:start
java -Xmx512M -Xms64M -jar NMSSaveEditor.jar -autoupdate
if errorLevel 2 (
	move /Y ~NMSSaveEditor.dl NMSSaveEditor.jar
	goto start
)
if errorlevel 1 (
   pause
)
`
solved the
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space - msg and
Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by Devilin-Pixy** [comment]
Are you using 32-bit Java, because then the max is 2G?

**Comment by Graslama** [comment]
Ya right, it is the 32bit java version. but allocating 512Mbyte was the trick to load the bigger save files.
