### ISSUE TITLE
New Patch 2.15 Update - New Name Mappings Not Found

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#226]
Not sure if related but when trying to paste from clipboard it said clipboard empty which it should not have been.

Parsing JSON...
  using name mappings: NMS 2.0
  WARNING: name mapping not found: idA
  WARNING: name mapping not found: pwt
  WARNING: name mapping not found: C0j
  WARNING: name mapping not found: i4g
  WARNING: name mapping not found: tww
Finished.

**Comment by austerud** [comment]
I'm getting the same thing when I open a save to edit. What does it mean?

**Comment by roie-r** [comment]
> 
> 
> I'm getting the same thing when I open a save to edit. What does it mean?

Means HG added new objects to the save file's structure and the editor needs updating.

**Comment by austerud** [comment]
Thanks

**Comment by goatfungus** [comment]
I have added these new mappings to the latest version, 1.6.7. Enjoy.
