### ISSUE TITLE
Multi Tool Editing is broken in Synthesis

### ISSUE THREAD

**Issue by micmou** [goatfungus/NMSSaveEditor#228]
Changes made to the multi tool with the editor are reverted by the game upon load.

**Comment by micmou** [comment]
Probably something to do with the fact we can now hole multiple Multi Tools

**Comment by ElectroOne** [comment]
I agree.. Broken Multi-tool in Synthesis. (reverts back in game)

**Comment by micmou** [comment]
He will get to it eventually for now I will deal with the UGLY alien one I have found.

**Comment by goatfungus** [comment]
Multiple tools? Oooh.... will have a look when I can, watch this space.

**Comment by micmou** [comment]
Yay also wanted to say Thanks for all the work you put into the tool.

**Comment by goatfungus** [comment]
Ok, looks like I've worked it out. New version of the editor (1.6.8) is available with support for multiple tools. Enjoy!

**Comment by ElectroOne** [comment]
Yeah man, you Rock.. Your Update works like a Charm!
