### ISSUE TITLE
Multple broken strings warning's in Synthesis save...

### ISSUE THREAD

**Issue by Keybordkiller** [goatfungus/NMSSaveEditor#229]
![2019-12-01 (2)](https://user-images.githubusercontent.com/58393559/69915408-80c11a00-141c-11ea-9a13-66e0009f3407.png)

Every time I use the editor, I get this. I'm guessing because there isn't an update to the editor out yet, since Synthesis dropped?

Afraid to use editor, other than to look at things without saving.

**Comment by goatfungus** [comment]
If you see this kind of warning it's not usually an issue. It just means HG have added some new values to the save file which I haven't analysed yet, so you can just carry on editing normally and the editor will just leave these values in place.

That said, I have just dropped a new update for the editor (1.6.8) which includes all of those missing mappings. Enjoy!
