### ISSUE TITLE
Delete vehicles

### ISSUE THREAD

**Issue by Shadowrunner340** [goatfungus/NMSSaveEditor#233]
Is it possible to delete vehicles?

**Comment by ukmerlin** [comment]
Why would you delete vehicles? They only ever appear on a planet if you build/call one otherwise they are just abandoned at the last position you used it.

**Comment by Shadowrunner340** [comment]
Because I dont like them, and I want the one I built gone.

**Comment by roie-r** [comment]
Just summon the vehicle to a random planet and leave it there. It wont pop up again by itself.
The vehicles aren't like ships, they're permanent.
