### ISSUE TITLE
Deleting a multi-tool situationally messes up the game

### ISSUE THREAD

**Issue by woomiez** [goatfungus/NMSSaveEditor#235]
Deleting a multi-tool apparently requires the others to be re-numbered or moved to a lower slot in the save file, or the game will lose access to it.
e.g. If you have 3 MTs and delete MT #0, you will no longer be able to switch MTs ingame, getting a blank icon and the message "only 1 multi-tool available". The MT shown in the inventory page is a random one that may or may not correlate with your actual other MTs, but it will always be completely blank (= broken).
Deleting a higher-numbered slot MT seems to work fine, as long as they are consecutively numbered from 0 on.

**Comment by Graslama** [comment]
Hi, I found when I wanted to get rid of my relatively useless multitool that a simple delete in SE is not advisable.
The following error can be reconstructed (previously create current saves - automatic and manual):
- 2 multitools are in the inventory
- delete multitool [0] via SE
- In the game you now only have Multitool [0], which is absolutely empty.
- after reload in SE the Multitool tab seems to be empty
- The file can no longer be saved via SE
+ not even if you have saved it in NMS in the meantime
+ you can see that the time display at "Modified" does not change when saving the file
- JSON editor can no longer be called

(If you delete Multitool [1], no error seems to occur...)

**Comment by goatfungus** [comment]
This should be fixed now. There was an issue with the indexing.
