### ISSUE TITLE
Living Ship Update - Two Items Not Found

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#240]
WARNING: name mapping not found: Xf4
  WARNING: name mapping not found: 5LX

**Comment by micmou** [comment]
I mean it is fairly obvious why is it not... As I am sure Fungus is aware the update is out and they are fairly quick on the draw doing updates.

**Comment by ukmerlin** [comment]
Of course peasant! 
But it's good to get it in the que

On February 19, 2020 4:21:17 PM EST, micmou <notifications@github.com> wrote:
>I mean it is fairly obvious why is it not... As I am sure Fungus is
>aware the update is out and they are fairly quick on the draw doing
>updates.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/goatfungus/NMSSaveEditor/issues/240#issuecomment-588476739

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by micmou** [comment]
Oi boi dont call me a peasant but yes you could have just said that there was a new update.

**Comment by Purg25** [comment]
so the question then is. how long does it take for them to do updates?

**Comment by k5jat** [comment]
Also, to add to this, the new alien ships come up unknown as do all of their modules.

**Comment by goatfungus** [comment]
New version of the editor, 1.6.9, adds support for the Living Ships update. Enjoy.
