### ISSUE TITLE
A way to save an entire ship on a database or external file!

### ISSUE THREAD

**Issue by Cerberuschan** [goatfungus/NMSSaveEditor#241]
is there any way to save an entire ship with the items, upgrades and everything else on a database or external file? 
it's a pain to edit the ship you're using every time you want to change it's appearance or hunt for new ones without losing the one your using.

i think this would make a great addition to the editor, a great quality of life feature!

**Comment by meachware** [comment]
THIS! Would be HUGE! The Willowtree editor for Borderlands (1) has a “locker” feature that is accessible within the editor so after you place or create an item in there you just copy it to current save and obvs available to all save files

**Comment by Cerberuschan** [comment]
i know, i use borderlands editor too and that feature is really awesome! this could be the thing we need in nms, since the game don't let you collect all the ships you want, the editor could help us out by letting us store the ships we want to keep!

**Comment by meachware** [comment]
I was able to locate and copy the entire ship info in the rawJSON but man I hate messin' with that

**Comment by goatfungus** [comment]
I like this idea too :)
It would be nice if the saved copy preserves the slots and installed technology, but no other items. The only problem is that I will not be able to generate a nice thumbnail for each nor read their auto-generated name, so you would need to specify a custom name for them.

**Comment by Cerberuschan** [comment]
The name comes with the seed, so saving the seed the original name should stay, the most important thing is to store the seed, the class, the slots and upgrades. That would be perfect.

**Comment by goatfungus** [comment]
I was meaning more along the lines of knowing what to name the exported file as... it would be ok if the ship has a custom name, if not I'll have to get the user to type one in.

**Comment by Cerberuschan** [comment]
@goatfungus the user typing the name would be great, we can describe the ship right there and know what that ship is for future reference. Man, it's great that you embraced the ideia that fast. Thank you.

**Comment by goatfungus** [comment]
Ok, your wish has been granted (I think).... I've added Import/Export buttons for ships and multitools to the latest version, 1.6.10. Let me know how it goes.
