### ISSUE TITLE
Issue with adding Living Ship base technologies 

### ISSUE THREAD

**Issue by Chrystal007** [goatfungus/NMSSaveEditor#242]
Hi GoatFungus,

First of all, thank you so much for this tool, I really appreciate the effort you put into it and how quickly you pushed out a new update! I would just like to point out that I've been seeing an issue with it which has maybe gone unnoticed, that is; trying to change the living ship slots doesn't work, in fact, all ship slots now behave inconsistently when trying to expand and reduce the dimensions of their inventories (they never snap to the correct value), and trying to add living ship technologies and upgrades does not actually add them. 

Thanks for reading. Please keep me updated, I would appreciate a reply if you can.

**Comment by Chrystal007** [comment]
EDIT: It appears that the game needs to be exited and then reopened for certain changes to take effect. I have experimented and found that the living ship upgrades and inventory dimension changes work with this change. So that's good, those two things were just my bad. However, sadly it seems the issue with not being able to change the fighter inventory dimensions (specifically, shrinking them) still doesn't seem to work, as in the dimensions simply snap back to the original when I try to reduce them. Could this be due to a changed in-game mechanic?

**Comment by meachware** [comment]
Similar issues:
Manually changed my starter ship to living (using valid seed). I’ve tried adding the necessary “organs” in either the storage sacs or organ chamber. I can add them and they look fine in the editor, even switching saves & reloading looks correct. However when I load my save in game I get the living ship but none of the organs are showing. When I exit & reopen the save file in the editor, they are indeed missing.

As stated above, thank you for your hard work on this project, make NMS even more fun.

**Comment by Chrystal007** [comment]
@meachware thanks for the reply. I was wanting to reduce inventories because this was actually possible before the latest update but using disable slots works fine too anyway. What's a bit more worrying, as you mentioned, is the editor deleting the technologies. I checked back this morning and the technologies I added to the living ship last night all have vanished, and this time when I try to add them back they are gone :( not sure what to do ... Hope goat fungus notices this quickly

**Comment by goatfungus** [comment]
A few answers:

- After making a change to a save file, you must reload the save file in game. I find the best thing to do is exit to Mode Select and alt-tab to do the editor changes.

- If you expand the inventory on ANY container and enable all the new slots, you cannot reduce the inventory unless you disable the slots again (make them grey). I did this on purpose so that nobody complains that their items are deleted when they reduce their inventory to something silly.

- The living ship organs might be tied to the missions you do to get the ship, but I am not sure as I have not tested it. If that's the case, you may need to add the completed missions into your save.

- As for technologies deleting, I haven't noticed this on my save. However, I did get my living ship through the conventional means... some of the "Upgrade Modules" for living ship don't appear to do anything but they can be added and removed without issues.

**Comment by goatfungus** [comment]
@Chrystal007 are you sure you aren't trying to add "Grafted Eyes" to one of your other ships, maybe an Exotic? The Add Item dialog in the editor displays only the tech that can be placed in the current container... so for example: living ships can have grafted eyes but no standard hyperdrive, and ordinary/exotic ships are the opposite.

**Comment by Chrystal007** [comment]
Hey goat fungus thanks for the useful replies. I was trying to add grafted eyes to a ship which was already set to organic. Still not sure why the technologies are deleting though. Am I supposed to add them to the "known technologies" list as I noticed that photon Cannon is there, but the living ship base modules are not

**Comment by tehface** [comment]
If that's the case, you may need to add the completed missions into your save

^^ how do i do that?

**Comment by meachware** [comment]
Thanks for your feedback & support.
Re: “The living ship organs might be tied to the missions you do to get the ship, but I am not sure as I have not tested it. If that's the case, you may need to add the completed missions into your save.”

I was able to resolve the issue by copying a good ship (entire json data) into my just started save file without issues. I even (later) moved the “organs” around (in game) & did not lose anything. So there may still be an issue with data structure for living ships.

Thanks again for your continued support!

**Comment by Chrystal007** [comment]
Ok, so I've experimented a bit more with the editor and here are my findings:

- The reproduction steps are: buy a new ship, then change its type to living. 

- It appears that there IS indeed some way (like the flag I mentioned) the game uses for telling whether a ship is supposed to be living or not. Since we already know living ships can only have all alien tech, I found that the alien ship which I converted from a normal bought ship can still have the normal ship technology which must mean that somewhere that flag is still set to it being a normal ship. This makes sense, since the game still thinks the ship is a normal ship, and thus deletes any living tech it finds added by the editor, which is indeed adding the technology properly, but somewhere in the code that flag or indicator to set the ship to a living ship is not being set. 

- I did not notice any differences between the JSON of the working living ship and the converted living ship. This means that flag or indicator is located somewhere else. This means the solution to this would be to find where it is and find a way to set it to living ship.

**Comment by goatfungus** [comment]
Ah, that's a good find!

I'll look at changing the stats automatically if the ship type is changed, but it might have to wait for a future update.... i will keep this open in the meantime.

**Comment by Chrystal007** [comment]
Ok cool, is there going to be a pinned workaround in the Git or something for players who also find this problem and come here to comment on it?

**Comment by goatfungus** [comment]
Ok, I'm nearing a solution for this, just thought I would run it by you:

When a ship is changed from non-living to living:
- Show confirm dialog
- Set the "^ALIEN_SHIP" base stat to 1.0
- Delete ALL technologies from the ship inventory

When a ship is changed from living to non-living:
- Show confirm dialog
- Delete the "^ALIEN_SHIP" base stat
- Delete ALL technologies from the ship inventory

When a ship is changed from non-living to any other non-living:
- No other changes made.

**Comment by Chrystal007** [comment]
Hi, thanks for the reply. Yes, that sounds about right, though to avoid potential trouble I would probably delete the inventory stuff first before setting or removing the ^ALIEN_SHIP base stat, since setting say, a non-alien ship to an alien ship (and still having its technologies there) could confuse the game or cause more problems.

**Comment by meachware** [comment]
The order is irrelevant unless people are still in game while they are edit the save file. If that’s happening then I guess but wouldn’t the game have to reload the file anyway?

PS did you guys see on Exp that organ upgrade modules can be upgraded from “C” to “S”. Sweet, just did it on the few modules I have installed

**Comment by Chrystal007** [comment]
I assumed they'll be in-game since most folks just use reload

**Comment by goatfungus** [comment]
Ok, I have implemented a solution to this in version 1.6.11.... it mostly works, but you will need to add in the required technologies by hand since the editor will have to delete all the non-living ones. It should work in both directions too.
