### ISSUE TITLE
Base stats' last digits in GUI differ from JSON view

### ISSUE THREAD

**Issue by NAVras-Z** [goatfungus/NMSSaveEditor#243]
Noticed this minor thing while viewing my save. For example: 
Multitool, Damage - 34.878929138183594
In JSON      - "Value":34.878929138183597

Ship, Hyperdrive - 44.846832275390625
In JSON - "Value": 44.846832275390628

**Comment by goatfungus** [comment]
That's all to do with how computer systems deal with floating point numbers.... they are not exact, but for this purpose I would doubt a difference of 0.00000000000001% will affect your gameplay in the slightest!

**Comment by NAVras-Z** [comment]
xD yea I see, thx.
