### ISSUE TITLE
Issue with editor itself

### ISSUE THREAD

**Issue by devcai** [goatfungus/NMSSaveEditor#244]
My save editor is showing old saves that I messed with a while ago and wont show my actual saves in my save folder so I can edit them. It's even showing saves I've deleted. Any way to fix this?

**Comment by meachware** [comment]
File menu -> Open File/Path and select the correct folder

**Comment by devcai** [comment]
I've obviously done that already. Still shows saves that are deleted already and a cant edit my actual saves.

**Comment by devcai** [comment]
It's super frustrating. Maybe I should back up my save and reinstall nms all together??? Idk

**Comment by meachware** [comment]
> 
> 
> I've obviously done that already. Still shows saves that are deleted and I cant edit my actual saves.

Um, nothing there was obvious at all, sorry. Deleting NMS will pretty much do nothing unless you are still running on Win7 or it's installed on some cock-a-mamey drive structure (e.g drive D:, E:, F:, etc)..

Perhaps try deleting the NMS editor and try installing that again. 

Regardless good luck

**Comment by goatfungus** [comment]
Backups are stored in a different folder from your save files....

Your gave saves should be in a folder something like this:
C:\Users\[USER]\AppData\Roaming\HelloGames\NMS\st_12345678901234567

**Comment by goatfungus** [comment]
Also, a long time ago HG were experimenting with using steams cloud storage for backing up your save files... it has been a recommendation for a long time to switch this setting off:

<img width="419" alt="Capture" src="https://user-images.githubusercontent.com/41274031/75098127-58118080-5617-11ea-89fd-eea8a8685c45.PNG">

**Comment by devcai** [comment]
Solved

**Comment by devcai** [comment]
Ahh okay thnx for quick responses btw! I finally fixed it reinstalled the software n I think I was probably using it wrong. lol.. I'll let you know if anything else comes up.

**Comment by devcai** [comment]
Okay... it actually went back to broken again idk what to do or how to use github that well so I guess Ill keep trying stuff. I had redownloaded/installed and it worked for the first run. Did I install it wrong or something???

**Comment by devcai** [comment]
> Backups are stored in a different folder from your save files....
> 
> Your gave saves should be in a folder something like this:
> C:\Users\[USER]\AppData\Roaming\HelloGames\NMS\st_12345678901234567

Yep that's what my file location is set to in the program and everything and no I dont have the cloud save thing on.

**Comment by devcai** [comment]
Update: I reinstall the software and restart pc and it works for a second but only like directly after restart then goes back to the wrong saves. Maybe it's my comp or something. Any ideas would be helpful/PLS HALP.. I'll keep trying stuff in the mean time.

**Comment by goatfungus** [comment]
That is really weird... sounds like something is syncing wrong in your user folder. I'm not sure how to help you resolve this, as it's unlikely to be the editor.
Is the game itself running? Just make sure you exit the game before using the editor, and mayme that will work?

**Comment by devcai** [comment]
Solved the issue today... I dont really know what was going on but it's been working today. Also have another question so I might start a different thread. Thanks all!
