### ISSUE TITLE
Ship technology issue

### ISSUE THREAD

**Issue by Meloun55** [goatfungus/NMSSaveEditor#245]
Hi guys, I have an issue with add technology to my ship and it doesn't matter what type of ship it is. In "Type" column I have nothing to choose, its just empty.
![proof](https://user-images.githubusercontent.com/61363504/75099372-3ab1c780-55c1-11ea-9f31-c53baf4e006e.jpg)

**Comment by goatfungus** [comment]
Apologies for that, I introduced a bug with the Living Ships addition. Should be fixed in new version 1.6.10.
