### ISSUE TITLE
New Procedurally Generated Artifacts (Living Ships update)

### ISSUE THREAD

**Issue by GoldenAppleNB** [goatfungus/NMSSaveEditor#246]
Space encounters introduced more procedurally generated artifacts, which are not shown properly in current editor

**Comment by goatfungus** [comment]
Can you please give me an example, or a screenshot?

**Comment by GoldenAppleNB** [comment]
these; I'm not sure if there's more
![image](https://user-images.githubusercontent.com/12419400/75103166-0bdd2680-55ac-11ea-9d66-2ced9259b1ee.png)
![No Man's Sky 2020-02-22 19_45_29](https://user-images.githubusercontent.com/12419400/75103175-1f888d00-55ac-11ea-842c-6299a01eb876.png)

**Comment by goatfungus** [comment]
Ok, must be a new file somewhere.... I'll see if i can find it.
