### ISSUE TITLE
Bug: Save Editor Hangs (Windows 7)

### ISSUE THREAD

**Issue by Sonador** [goatfungus/NMSSaveEditor#25]
Save Editor Hangs at various points after playing the game, closing it, and opening the save editor. Most readily reproducible when selecting the "Category" portion of the Add Item menu. Issue remedied only by full system reboot.

Video: https://streamable.com/ols4n

Debug log:
[INFO] Latest version: "1.5.7"
[INFO] Current version: "1.5.7"
[INFO] Loading saves for save 1...
[INFO] Reading save file...
[INFO]   Path: C:\Users\Sonador\AppData\Roaming\HelloGames\NMS\st_76561198004662708
[INFO]   Slot: Slot 1 - NORMAL
[INFO]   Filename: save2.hg
[INFO] Parsing JSON...
[INFO] Finished.

**Comment by Sonador** [comment]
Issue also remedied by saving the save file immediately upon opening it, before proceeding to edit the inventory.

**Comment by STOKE-STER** [comment]
I'm gonna go out on a limb and say that's more of an xp issue.. But I have no clue

**Comment by goatfungus** [comment]
Yeah, it does look like a windows theme problem unfortunately. I have no way to test this since I upgraded all my Windows 7 machines to Windows 10.

**Comment by goatfungus** [comment]
Odd that you got NMS running on Windows 7.... I can't even get it to install as it says it's unsupported. I might just have to close this issue.
