### ISSUE TITLE
Question about maximum values for Shields and Hyperdrive

### ISSUE THREAD

**Issue by temp-999** [goatfungus/NMSSaveEditor#250]
On the Ships tab, was there a reason to **cap** the Base Stats values for Shields, Hyperdrive and probably Damage at 1000.0? It doesn't seem to be a NMS restriction since they can be changed in the JSON and remain unchanged after a restart.

**Comment by Chrystal007** [comment]
I'm not sure about that as well, tested and confirmed working.

**Comment by goatfungus** [comment]
For those stats, I put in an arbitrary limit to stop people from puting in values that may break their game. I am not sure exactly what the game can handle, so I picked 1000 thinking it would be high enough that most people wouldn't even notice that there even was a limit!

I'm sure you could go above that, but why? NPC ships are still ridiculously easy to destroy even with shields and damage values under 10. If these cap values are really something people want increased in the editor then it's easy enough to change, but they have been in place for years now and you're the first to ask!

**Comment by Chrystal007** [comment]
I see, that makes sense. I prefer to fight using inferior stats simply because its a far better challenge

**Comment by temp-999** [comment]
OK.
