### ISSUE TITLE
[Feature Request] Vehicles Tab no "Enable All Slots" on right click menu

### ISSUE THREAD

**Issue by max3228** [goatfungus/NMSSaveEditor#252]
Hi Brendon,
You have really done an excellent job on the NMS Save Editor and continue to provide free updates (v1.6.11 (BEYOND).
Could I request that you enable "Enable All Slots" [no pun intended] on the Vehicles Tab as it currently remains greyed out, if at all possible please.
I have played NMS since April 2017 [PC] but since the BEYOND Update it has changed the game beyond [npi] all recognition with over 1000+hrs.

**Comment by roie-r** [comment]
Vehicles inventory was changed in a previous update and is now static. If go into the json code and change it manually then start the game, you'll see NMS crops it down to the previous size - nothing the editor can do about that.

**Comment by max3228** [comment]
Thank you Sir for your reply to my request.

 

Your NMS Save Editor is still a wonderful resource and I mainly use it for editing the Jason code once I go through a portal “OnOtherSideOfPortal”.

 

Regards,

Mike Senior
