### ISSUE TITLE
UI completely glitches out, mostly after various interactions with the exosuit inventory.

### ISSUE THREAD

**Issue by NCC-Therenall** [goatfungus/NMSSaveEditor#253]
**Version**: 1.6.11, though it's been going on.

The issue seems to be centered around the exosuit inventory, at least in my attempts to reproduce it, I get it to happen there all the time. I've tried with several save files, seems to do it on all of them.

Example:
 - Just right-clicking twice in the inventory will trigger it
 - Enabling all slots has triggered it
 - Clicking add item has triggered it

If it makes any difference, I'm not using the java.com release of the JRM 8, I'm using the one from Adopt OpenJDK from: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9 (specific installer/version is `OpenJDK8U-jdk_x64_windows_openj9_8u242b08_openj9-0.18.1`.) Happens using the regular, or 4G versions. 

![image](https://user-images.githubusercontent.com/32750893/75397358-9e3f3c00-58c4-11ea-8d42-6ada9e909774.png)

![image](https://user-images.githubusercontent.com/32750893/75397371-a26b5980-58c4-11ea-8916-d2f017cd74ea.png)

*Edit*: Here's a copy of one of my saves I can reproduce it on: [NMS Save.zip](https://github.com/goatfungus/NMSSaveEditor/files/4258734/NMS.Save.zip)

**Comment by ancienthydrolysis** [comment]
I'm having the same issue, but I'm using the official release of Java. I hope this gets fixed soon.

**Comment by W1ndst0rm** [comment]
I'm having the same problem. It happens whenever the right click context menu extends outside the bounds of the main window, so when right clicking on the bottom row or rightmost column generally. Resizing the main window so that the context menu will fit seems to workaround the issue at least for me.

**Comment by Kherae** [comment]
I have input! maybe helpful?
changed inventory scaling to 0.5, problem mostly gone. problem mostly occurs for me when clicking the edge tiles of inventory when they are too close to the lower/right bounds. I'm on a widescreen monitor. 1920 by 1080. keep window small, problem occurs more that way. why? found out program is going super-dumb when it tries to render the context menu outside the window's bounds, in a particular way. there's more to it than that, of course. it is primarily happening in the last slot, when it is close to the bottom right section. i've gotten it to where I can reproduce it almost perfectly every time
I've got an image that highlights it a bit.
https://cdn.discordapp.com/attachments/215940434516639745/854676425742745600/unknown.png

I hope this helps!
