### ISSUE TITLE
Some ship values are being applied to the incorrect ship.

### ISSUE THREAD

**Issue by ArghRad** [goatfungus/NMSSaveEditor#254]
I recently scrapped my slot-1 ship in-game.  Now NMSSaveEditor displays the wrong ship as my current one, and Use Old Colours is improperly selected for a newer ship instead of my legacy one.
Looks like these particular bits of ship data (loaded from different sections) are just out of sync - not accounting for any empty scrapped ship slots.

**Comment by goatfungus** [comment]
I noticed an issue with the ship indexing in the editor recently and fixed it. So hopefully this won't happen anymore.
