### ISSUE TITLE
Continuous Screenshots and locations

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#256]
Whilst on the other side of a portal NMSE will continuously take screenshots and save. Not sure how / why but it would also do it if I scanned something.
![NMSE saves](https://user-images.githubusercontent.com/27774213/75805211-66fede00-5d4f-11ea-9853-60e019e2c005.jpg)

**Comment by goatfungus** [comment]
Is this an issue with NMSSaveEditor or No Man's Connect?
