### ISSUE TITLE
Editor for PS4

### ISSUE THREAD

**Issue by Storm21CH** [goatfungus/NMSSaveEditor#258]
Hi there
No error but an idea ...
I have an unencrypted savegame of my PS4 savegame from Altlas Rises. It is possible to change the money etc. Do you want to have a look at it? And maybe porting the editor to PS4? Think the offsets are the same ... Thanks for your answer! regards

**Comment by Pd69bq** [comment]
I'm on PS4 too, as long as you can decrypt the save file (with save wizard), all the data are in plain text, editing is the easiest part. thing is, it's really hard to read but doable. 

with the help of HxD, I've changed my multi tool seed and base stats, my starship and capital freighter seed and base stats, I've even added the homeword seed to my capital freighter make sure that it won't change its color randomly

**Comment by Storm21CH** [comment]
Save Wizard not needed! I do it with the PS4 Savemounter and HxD. But I didn't have plaintext for everything, but I was able to edit money and atlas seeds. But I have e.g. the Nanits entry not found...
All plaintext?

**Comment by Pd69bq** [comment]
yes, all in plaintext, irrc, first is unites then nanites then quicksilver. since you have already found the correct address of nanites, other two are actually really easy to spot. or, you can just simply search the actual number of your unites

**Comment by Storm21CH** [comment]
Thank you! Ok then... I don't have everything in plain text... Think Savemounter only decodes the account binding and not the savegame itself. I searched for the Nanits in plain text and hex, but did not find them. Hmmm... I have to look again... You did that with Game Wizard? Do you also have this memory.dat? regards

**Comment by Pd69bq** [comment]
I updated my previous post

yes, I use save wizard to decrypt/encrypt PS4 save files, HxD for editing. and yes, I think memory.dat is the actual decrypted NMS save file name.

**Comment by Storm21CH** [comment]
Here is a part from memory.dat, the money is plain text, but not everything. I find neither the text nor the value for the nanites, nor in hex value. Thanks a lot!

�0�ñHoloExplorerInteraction":{"GalacticAddress_�±Value":7813¹�i-�T[0.0,�b-1.0]}[�ScepticZ�O1797Z�_NooneX�?743X�RealthŠ‡4hip�á8,"Shield":100
�p�÷4200,"Energy":91,"Units":1410065461,"TimeAlive":458214,"TotalPlayTim�þ"MarkerStack":[{"Table":1,"Event":"^RADIOTOWER_R",¥Éº81566366l�êñ8F

**Comment by Pd69bq** [comment]
it's the correct address. if you can decrypt the whole file tho, you should be able to see the Nanites and Quicksilver (Specials)

> "HoloNooneInteraction":{"GalacticAd:dress":0,"Value":5901,"Position":[0.0,0.0,0.0,-1.0]},"Health":144,"ShipHealth":500,"Shield":100,"ShipShield":200,"Energy":99,"Units":100,"Nanites":100,"Specials":99895939,"ThirdPersonShip":false,"TimeAlive":596240,"TotalPlayTime":1364408,"MarkerStack":[{"Table":1,"Event":"^OUTPOST","GalacticAddress":4912617997558906,"BuildingSeed":

**Comment by cengelha** [comment]
Hi,
I'm working on my own save editor (see profile).

Can you provide me the following things?

1. a decrypted crossplay save/output of the tools
1. some intructions for the tools you use (preferably as link) as reference/for my own understanding
1. are the tools you mentioned producing the same (decrypted) output?

I will see what I can do with it.

**Comment by Storm21CH** [comment]
Use NomNom

**Comment by goatfungus** [comment]
I've been working on PS4 save files for this editor... I was wondering if anyone has a recent memory.dat from after the Frontiers update?

If so, please post it here: #463
