### ISSUE TITLE
Editor for Frigate Stats not Working / purely Comsetic

### ISSUE THREAD

**Issue by Caipa85** [goatfungus/NMSSaveEditor#264]
If you add/change Traits of Frigates it is purely cosmetic.

The game does not register your changes to the traits. And a cosmetic change is worthless.

Method of proof: Add Traits "Expert Navigator" and "Experimental Impulse Drive" then in-game select a mission, add the frigate and you will see no change to the mission timer. You will see a change with a non save game editor frigate.

You might also consider tying the traits to stats, I.e. if the trait +3 Trade gets changed to +6 Industry it would Subtract 3 from Trade and Add 6 to Industry.

**Comment by goatfungus** [comment]
The stats don't map directly to the traits as far as I'm aware, but I'll look into it.

**Comment by goatfungus** [comment]
This should be all working properly now.
