### ISSUE TITLE
Slot 1 - [EMPTY] not running experimental 

### ISSUE THREAD

**Issue by thenommer15** [goatfungus/NMSSaveEditor#266]
Hello there,

I installed your editor so I could alter the color of my favorite ship. However when I attempt to use it, the game slot field shows Slot 1 - [EMPTY] and I get the 'Save file not found for Slot 1 - [EMPTY].

I made sure to disable steam cloud save but I still having this issue.

Any help is appreciated,
Phil

**Comment by dragons666espana** [comment]
Above the game slot field should be your save game path. 
Mine is like this (user name edited).
C:\Users\xxxxxx\AppData\Roaming\HelloGames\NMS\st_76561198272527033

**Comment by thenommer15** [comment]
Right, I am able to navigate to the save file location. It just can't be loaded into the editor.

**Comment by dragons666espana** [comment]
Main menu. File. Open path.
Find your saved file & open. This should then show up in the Save Path section of File Details.
