### ISSUE TITLE
Exomechs

### ISSUE THREAD

**Issue by devcai** [goatfungus/NMSSaveEditor#267]
Update to editor for use with the new exomech patch soon?

**Comment by areithropos** [comment]
Yes, please! It would be awesome! Thank you for all your efforts, @goatfungus .

**Comment by 740297616** [comment]
+1

**Comment by sollevix67** [comment]
+1

**Comment by Devilin-Pixy** [comment]
Has been updated a couple of hours ago:
https://github.com/goatfungus/NMSSaveEditor/blob/master/CHANGELOG.md
