### ISSUE TITLE
Feature Request: Delete Leftover TeleportEndpoints.

### ISSUE THREAD

**Issue by Seranthor** [goatfungus/NMSSaveEditor#27]
Is it possible to remove the leftover(deleted) TeleportEndpoints? It seems that when you delete a base the Teleport endpoint remains in the dataset.

**Comment by goatfungus** [comment]
Good idea. This will be done soon.

**Comment by crypt1cx** [comment]
Oh yeah, i would absolutely love this too. I had so many issues with the teleportendpoints.

**Comment by KindarConrath** [comment]
Something like this, the ability to manage Teleport locations in some way is quite desirable as currently the game saves all your bases, even ones you have since removed.

**Comment by Seranthor** [comment]
Actually tried that GKboki, either I did something wrong or it didn't work.

**Comment by VividClarity** [comment]
**For Example, would I delete this?** 


],
		"TeleporterType":"Base",
		"Name":"My Base Name"
	},
	{
		"UniverseAddress":{
			"RealityIndex":0,
			"GalacticAddress":{
				"VoxelX":-1648,
				"VoxelY":8,
				"VoxelZ":-564,
				"SolarSystemIndex":5,
				"PlanetIndex":0
			}
		},
		"Position":[
			-403.65704345703127,
			-7053.67431640625,
			73.52896118164063
		],
		"Facing":[
			-0.769915759563446,
			0.5919315814971924,
			0.23842556774616242

**Comment by Goose7** [comment]
You can remove these using the Raw Json Editor.  It works fine and I managed to remove a half dozen previously deleted bases from my Terminus list.

It is a somewhat tedious process, so an actual feature in the regular editor would be awesome and save a lot of time!  And as far as I know, the bug that leaves deleted bases in the endPoints section is still there in the latest EXP build, so this is going to be an ongoing issue for the foreseeable future I'm afraid!

**Comment by goatfungus** [comment]
I think this has been resolved in the latest experimental branch of the game, so I'll close this one for now.
