### ISSUE TITLE
Frigate changes

### ISSUE THREAD

**Issue by jct3531** [goatfungus/NMSSaveEditor#273]
My frigate fleet was good to begin with but I wanted to boost a couple stats because I'm tired of having to fix a couple of them all the time....if I could attack and destroy a damage one I would probably do it and recruit a replacement.  Someone else mentioned that the changes made on the editor are only cosmetic but half of the ones I edited accepted the boosted stats after saving the slot file.  I can't get the edits to take hold on the other half.  Is this part of the mod or did I do something on my own that I'll never be able to do again?  Thanks for all your work, it's made a great game even better.

**Comment by goatfungus** [comment]
The traits used to be cosmetic, but I have now tied them to the stat they modify.... enjoy.
