### ISSUE TITLE
Is there no way to manipulate the MANEUVERABILITY of a Starship's Base Stats?

### ISSUE THREAD

**Issue by Theleb-Kaarna** [goatfungus/NMSSaveEditor#274]
First off, Thank You GoatFungus for this most essential NMS tool/resource. It's usefulness could never be overstated. Might be the closest we'll ever get to the equivalent of the Console/Console Commands like in a Bethesda Game for example.

So, per topic (apologies if already covered), in the "Ships" tab, under "Base Stats", I see where you can manipulate "Health", Shield", "Damage", "Shields" and "Hyperdrive". However, the "Maneuverability" field (as seen in game) is absent. So, am I missing where the "Maneuverability" stat can be manipulated? Or, if really absent, could this functionality be added to the Save Editor? Again, apologies if already covered and thanks in advance=)

**Comment by roie-r** [comment]
The ship's base maneuverability value is derived from the its type, class bonus, and the ship's seed - there's no saved value to change in the save file.

**Comment by Theleb-Kaarna** [comment]
Thanks for the response! That made sense, but I wanted to test anyways so I (eventually) bought 3 identical Exotics from the same system. While their inventory slots and other specs (Shield, hyperdrive, damage, etc) varied, the maneuverability stat was the same for all 3 (value of 423.2). What's screwy and was initially throwing me off is that sometimes this value randomly changes: Sometimes when I enter (or scan) one of the three Exotics, it's 437.6 (instead of 423.2). After playing for a while it seems to stay at 423.2 for the duration of the play session. Weird. I've not tested with other starship types yet... I'm guessing it's a glitch. Anyways, thanks again for your response.
