### ISSUE TITLE
Does not work with the windows store version or i have no clue where the saves are located

### ISSUE THREAD

**Issue by doomtrigger** [goatfungus/NMSSaveEditor#276]
Saves are not showing up in the editor

**Comment by Akasasmotive** [comment]
They appeared to be stored at \AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs

They won't open with the editor though. Is it looking for a specific file extension?

**Comment by doomtrigger** [comment]
Thats where i found then as well but the editor does not detect them even
after changing bto hg files

**Comment by cengelha** [comment]
Hi, I currently working on my own save editor and was looking for such information.

The "HelloGames.NoMansSky_bs190hzg1sesy" part is the same for both of you?

Can any of you upload the zipped "SystemAppData" directory?

**Comment by jefuslives** [comment]
Windows Store Apps have their own DRM requirements for save data files, so the files will not be compatible without a converter tool.  As they are likely encrypted with a private key, this may be impossible.

**Comment by JustCallMeUni** [comment]
> 
> 
> Windows Store Apps have their own DRM requirements for save data files, so the files will not be compatible without a converter tool. As they are likely encrypted with a private key, this may be impossible.

I have it on MS Store and the saves appear to be made up of plain text mixed with data.

**Comment by tylerszabo** [comment]
@jefuslives I'm confident it'll be possible; the files are readable and writable as the current user so key material should be available to that user - it's just a matter of finding out where it's coming from.

Since the game is playable offline the key material is likely stored locally.

**Comment by cengelha** [comment]
It is possible and it is done. Check out my editor ;)

**Comment by tylerszabo** [comment]
@cengelha glad you got it working but I don't see the code. Did you publish the source elsewhere?

**Comment by cengelha** [comment]
It's not yet published but I will do it in that repo when it's out of pre-release as stated in the readme

**Comment by goatfungus** [comment]
This is working now for MS Game Pass.
