### ISSUE TITLE
WARNING: name mapping not found

### ISSUE THREAD

**Issue by NameInProgress** [goatfungus/NMSSaveEditor#278]
After changing the item amount values and moving them around I get this thing during the next trying to edit inventory.

**Comment by ced3new** [comment]
same issue here. i get this upon opening the savefile. https://i.imgur.com/8GqxbE0.png

**Comment by GnaspGames** [comment]
It's something to do with the new crossplay update - They've added some new data to the save file that the SaveEditor doesn't recognise. 

You'll probably have to wait and see if @goatfungus updates the editor for the new data.

**Comment by qWOMBATp** [comment]
Please update - thank you!

**Comment by melhiore** [comment]
Same issue here. There is also problem with manipulating storage slots in the Exocrafts. Raised in another ticket. I would aslo appreciate an update.

**Comment by goatfungus** [comment]
This should be mostly fixed now, sorry for the delay. Closing issue due to duplication.

**Comment by digimancer** [comment]
Fyi, I still always get these and just ignore them:

Reading account data...
  WARNING: name mapping not found: Jxp
  WARNING: name mapping not found: >W7
  WARNING: name mapping not found: ilV
  WARNING: name mapping not found: MyN
  WARNING: name mapping not found: jSo

**Comment by qeveren** [comment]
Yeah just trying this for the first time and I get a heap of these.

**Comment by wkitty42** [comment]
they're only warnings and do not really affect the operation of the editor... at worst, you won't see the actual name of an item in your possession... aside from that, it is cosmetic until someone figures out the actual name... not to mention this issue was closed 5 years ago...

**Comment by digimancer** [comment]
Yep, the app mostly works fine regardless. 
Those 5 items I mentioned also may coincide with some of the new unreleased Corvette parts 
(some reactors, a rocket, bathrooms, and a few other cosmetics).
