### ISSUE TITLE
Save Editor Breaks on Linux With OpenJDK 8

### ISSUE THREAD

**Issue by HenrickTheBull** [goatfungus/NMSSaveEditor#279]
Disclaimer: I know the game isn't Linux Native but it runs awesome under Steam's Proton on Fedora 32, sometimes even better than on Windows.

Using Fedora 32, with OpenJDK 1.8 (Java 8). It fails a "Headless" check when starting the editor.
![image](https://user-images.githubusercontent.com/3945192/84835826-122f5c80-affa-11ea-92fe-336cffe09377.png)

This is solved by simply upgrading to OpenJDK 11 and using `sudo alternatives --config java` and swapping to OpenJDK 11. This should work on any modern distro.

Hope this can make it into the Readme so it'll help some other Linux user, if not at least it will be here in issues for Google to index!

**Comment by goatfungus** [comment]
This should be solved with new version.
