### ISSUE TITLE
No new saves found

### ISSUE THREAD

**Issue by ther-richardson** [goatfungus/NMSSaveEditor#280]
When I open the editor I can only see saves from months ago, nothing recent. It shows something that I think are my original saves and nothing from my recent sessions. 
For instance I logged out of NMS just now and when I open the editor is shows me saves from May.  I have tried uninstalling and reinstalling the editor. I have tried deleting the old saves. I have tried updating the path to the files. I even uninstalled it and scrubbed the registry and reinstalled it and I still see saves that do not match my latest sessions. If I open all of those sessions I cannot find one that lists the current ships I am using in game.

Cheers and thanks for the great editor.

**Comment by ther-richardson** [comment]
Can anyone give any enlightenment on this issue?

**Comment by UltraCyberGod** [comment]
Post the path to your save files... Please.

**Comment by ther-richardson** [comment]
They are right where the game put them by default  C:\Users\MyUserName\AppData\Roaming\HelloGames\NMS\st_76561198268435550

**Comment by ther-richardson** [comment]
After reading a comment on the Steam community forum I even tried moving the editor to the same dir as the files but it made no difference.

**Comment by ther-richardson** [comment]
Any ideas?

**Comment by ther-richardson** [comment]
Still no thoughts

**Comment by UltraCyberGod** [comment]
If it was me I'd look at NMS Save Editor so uninstall it removing any backups that is has done. Double check I got everything. I'd be aiming to kill what ever it finding. NMSSE should find it by default so I'm guessing it looking at it's backups for some reason. Hope this helps I'll look again at mine an see if I can come up with more...

**Comment by ther-richardson** [comment]
I can try that again, but I deleted the files at one point, scrubbed the registry and then re-downloaded and installed with no success.

**Comment by devcai** [comment]
Are you clicking on the correct icon to launch it? It's the one with the java logo. Other than that idk.

**Comment by ther-richardson** [comment]
It is hard not to, there are only two files in the folder. the .exe and the .jar and the .exe is the installer and does not do anything.

________________________________

**Comment by UltraCyberGod** [comment]
I suppose I'm going with the idea that my brain tells me that if the save editor seems to be loading old games then the old games must by logical thought, be somewhere?

On 21 Jul 2020 12:58, ther-richardson <notifications@github.com> wrote:

It is hard not to, there are only two files in the folder. the .exe and the .jar and the .exe is the installer and does not do anything.

________________________________

**Comment by ther-richardson** [comment]
So, I went into appdata and looked for anything else related to the editor and found nothing. Deleted all my backups got rid of any files other than the jar that we dated before July and opened it and this is what I get.
[cid:8d70b176-1452-4c8f-8045-89ae896fc103]
Is it safe t get rid of the following two files?
[cid:61f44361-25dc-4bb2-ab62-a041d5683259]

________________________________

**Comment by ther-richardson** [comment]
Found it, COMODO Security by default will do a sandbox on files programs  it is unsure of and It builds and stores the sessions in a folder on the HD (typically c:\VTRoot) so if you disable the process per this article it should function https://steamcommunity.com/discussions/forum/1/617328967248066054/

**Comment by ther-richardson** [comment]
That did it and now it works fine other than it keeps telling me there is a new version that does not seem to exist.

**Comment by UltraCyberGod** [comment]
That's Great News!!! There is a new version of the NMSSaveEditor only released 2 days ago might need a manual download mine updated automatically.
