### ISSUE TITLE
Can't resize Cargo

### ISSUE THREAD

**Issue by Cyravehl** [goatfungus/NMSSaveEditor#281]
I just loaded my game after a short time away.

I had set my Cargo boxes to 8x6,  but they now seem to be locked at 5x5.

I tried several times to resize back to 8x6, but it doesn't work.
I thought maybe it was now hard coded, but the Editor says it can resize still.

Is there anyway to fix this,  or have I lost all the items in the Slots above the 5x5 limit?

**Comment by UltraCyberGod** [comment]
I have tried this too and confirm the same. No changes after saving both in Normal and Survival.

**Comment by Cyravehl** [comment]
@UltraCyberGod DO NOT SPEAK FOR ME!!!

I DID enable slots, both 1 x 1 and Enable All, but doesn't work - I'm still stuck on 5x5 limit.

**Comment by melhiore** [comment]
My containers are 48 slots, I could do that last week. Procedure is the same as extending any other storage space...

**Comment by Cyravehl** [comment]
Don't know then, tried several times.  Been using the editor for 2 years (or thereabouts), so I'm not new to using it.
It simply no longer works, I can got get anything over 5x4 (20 Slot) no matter what I do.  Even tried using a different PC.

So I simply don't know, it did work, perfectly, now it doesn't work (for slots).

**Comment by flatline4400** [comment]
Not working for me either.

**Comment by goatfungus** [comment]
Only vehicles are hard-coded... but I have recently expanded a few of the inventories as they were expanded in game.
