### ISSUE TITLE
Editor does not recognize Game Pass Game Saves

### ISSUE THREAD

**Issue by XDaast** [goatfungus/NMSSaveEditor#282]
Hi, 
Is there any way you can make this compatible with the Game Pass version? Thank you. The editor will not read them.

I've attached my game save.
[3A51643576D441A1B6ABE60BF69BED86.zip](https://github.com/goatfungus/NMSSaveEditor/files/4845754/3A51643576D441A1B6ABE60BF69BED86.zip)

**Comment by lightblueandy** [comment]
Also seeing this issue. Following.

**Comment by kikiwako** [comment]
Unfortunately I don't think it will possible because game pass encrypts the savefiles. I tried the game on game pass but now I'm ditching it for steam since you can't mod the game pass version either.

**Comment by goatfungus** [comment]
Game pass support has been added to NMSSaveEditor now.
