### ISSUE TITLE
Unable to run editor

### ISSUE THREAD

**Issue by Midknyghte** [goatfungus/NMSSaveEditor#283]
I had the editor installed a few months back and it ran fine. I went to run it today and this is the message I am getting...

![Desktop Screenshot 2020 07 16 - 22 15 13 43](https://user-images.githubusercontent.com/68384259/87675702-ad128680-c7b2-11ea-9f9d-71855f74560a.png)

**Comment by DartPower** [comment]
If you have a troubles with java, use this
https://www.java.com/en/download/uninstalltool.jsp
And/or install Java (again)
https://www.java.com/en/download/win10.jsp

Or you may try another JRE (Java)
https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot
![image](https://user-images.githubusercontent.com/2005369/87680817-8f2f2c80-c786-11ea-9a0f-dadbb96d1b58.png)

**Comment by Midknyghte** [comment]
Much appreciated!
