### ISSUE TITLE
Vehicles storage/slots - broken after last update to 2.6

### ISSUE THREAD

**Issue by melhiore** [goatfungus/NMSSaveEditor#284]
I could manipulate the storage space of the vehicles (Colossus etc.) before 2.6 update. Last update reverted my slots to the basic that vehicle come with and I no longer see the button above the storage space to change it... Looks like 2.6 update have broken few things...

**Comment by micmou** [comment]
@goatfungus  There are also new things like titles and new items. Most everything in the editor works but a update dropped 2 days ago called Desolation. Also sorry for the hijack @melhiore but its better than creating a new issue.

**Comment by goatfungus** [comment]
New version is ready now, version 1.6.13 includes the new items from Desolation plus new Procedural Tech for freighters. Hopefully I haven't missed anything. Enjoy!

**Comment by melhiore** [comment]
Hello, hello, just downloaded new version and the issue with slots for vehicles is still present. Also noticed the WARNING message described here: https://github.com/goatfungus/NMSSaveEditor/issues/278 is also there. Not sure if this is intended but does not really solve the problem, sorry... Can you also consider publishing your SaveEditor on Nexus mods?? Much better tracking system, comment section and donation option...

**Comment by obogorr** [comment]
I am having the same issue
