### ISSUE TITLE
EXO_RECHARGE aren't in item list

### ISSUE THREAD

**Issue by Christianwidjaya** [goatfungus/NMSSaveEditor#286]
While these is not crucial, but nice to have

EXO_RECHARGE : exocraft recharger unit
The in game name changes with their corresponding engine type

RAW json data:
				"Type":{
					"InventoryType":"Technology"
				},
				"Id":"^EXO_RECHARGE",
				"Amount":-1,
				"MaxAmount":100,
				"DamageFactor":0.0,
				"FullyInstalled":true,
				"Index":{
					"X":1,
					"Y":1
				}

I hope this helps!

**Comment by goatfungus** [comment]
This should be fixed now.
A new category was added that I didn't account for.
