### ISSUE TITLE
Warning error

### ISSUE THREAD

**Issue by PappyVanWink** [goatfungus/NMSSaveEditor#288]
This is what I get after desolation patch and I choose the current save game. Is this normal?

![nms-editor-error](https://user-images.githubusercontent.com/68614531/88099551-510c8100-cb69-11ea-937d-52949bb5ff5d.jpg)

**Comment by leeveblank** [comment]
I am getting the same errors, and it doesn't let me save files now.

**Comment by leeveblank** [comment]
Are you able to save?

**Comment by PappyVanWink** [comment]
Yes, but not in the newest save I have to replay a bunch.

**Comment by goatfungus** [comment]
Those warnings happen when HG adds things to the game, but it's nothing to worry about.
