### ISSUE TITLE
Name mappings still 2.31

### ISSUE THREAD

**Issue by r8dxxx** [goatfungus/NMSSaveEditor#289]
1.6.13 still shows it's using NMS 2.31 name mapping

https://imgur.com/a/yyfoQCf

**Comment by leeveblank** [comment]
I am having the same issue. Was able to use save editor once just fine, and then suddenly its only using 2.31 name mapping now. Cannot save game

**Comment by hlemcke** [comment]
JSON Parsing shows name mappings "NMS 2.31". In my current save game, the following names could not be mapped. I still saved the game and it seems stable, although I don't see ship names.

Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - NORMAL - Juli 23, 08:33
  Filename: save.hg
Parsing JSON...
  using name mappings: NMS 2.31
  WARNING: name mapping not found: Ovv
  WARNING: name mapping not found: EkX
  WARNING: name mapping not found: Bg3
  WARNING: name mapping not found: aNF
  WARNING: name mapping not found: T>Z
  WARNING: name mapping not found: TFZ
  WARNING: name mapping not found: hyA
  WARNING: name mapping not found: jqx
  WARNING: name mapping not found: 8wT
  WARNING: name mapping not found: GLf
  WARNING: name mapping not found: myI
  WARNING: name mapping not found: 8sY
  WARNING: name mapping not found: GPe
  WARNING: name mapping not found: @lX
  WARNING: name mapping not found: 3R<
  WARNING: name mapping not found: bLP
  WARNING: name mapping not found: eEU
  WARNING: name mapping not found: bnC
  WARNING: name mapping not found: jA9
  WARNING: name mapping not found: 5XZ
  WARNING: name mapping not found: kr6
  WARNING: name mapping not found: :Je
Finished.

**Comment by leeveblank** [comment]
Has anyone figured out how to work around this? Can’t save any changes

**Comment by qWOMBATp** [comment]
Also experiencing this with Steam version of NMS.

**Comment by Cylaar818** [comment]
also getting this. tried clearing java cache in the off chance it was caching something there from an old version, but no dice. i assume the xmls need to be updated in the jar, but i dont know much about java, and i'm not about to try and snoop on the process further, or unpack the pck files to confirm at this point. :)

Parsing JSON...
  using name mappings: NMS 2.31
  WARNING: name mapping not found: Ovv
  WARNING: name mapping not found: EkX
  WARNING: name mapping not found: Bg3
  WARNING: name mapping not found: aNF
  WARNING: name mapping not found: T>Z
  WARNING: name mapping not found: TFZ
  WARNING: name mapping not found: hyA
  WARNING: name mapping not found: jqx
  WARNING: name mapping not found: 8wT
  WARNING: name mapping not found: GLf
  WARNING: name mapping not found: myI
  WARNING: name mapping not found: 8sY
  WARNING: name mapping not found: GPe
  WARNING: name mapping not found: @lX
  WARNING: name mapping not found: 3R<
  WARNING: name mapping not found: bLP
  WARNING: name mapping not found: eEU
  WARNING: name mapping not found: bnC
  WARNING: name mapping not found: jA9
  WARNING: name mapping not found: 5XZ
  WARNING: name mapping not found: kr6
  WARNING: name mapping not found: :Je
Finished.

**Comment by goatfungus** [comment]
This should be mostly fixed now, sorry for the delay.

**Comment by Cylaar818** [comment]
> This should be mostly fixed now, sorry for the delay.

No worries thanks for your efforts!
