### ISSUE TITLE
Feature Request: Change number of items in a stack

### ISSUE THREAD

**Issue by KindarConrath** [goatfungus/NMSSaveEditor#29]
It would be nice, when trying to fix my inventory, if I could change the number of items IN a stack, instead of always getting the max, for example 93/250 Oxygen instead of 250/250.

Side note: this editor is great! Thanks for your hard work.

**Comment by goatfungus** [comment]
I have added the ability to change the exact quantity of item stacks in version 1.5.9, though this is still limited to the stack max.
