### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

### ISSUE THREAD

**Issue by alexzms** [goatfungus/NMSSaveEditor#290]
![image](https://user-images.githubusercontent.com/26690162/88397611-c80a7980-cdf6-11ea-8ebc-64e703a170ce.png)
i got the game from xbox game pass for pc and download the game from that, is that the cause?

**Comment by qWOMBATp** [comment]
> i got the game from xbox game pass for pc and download the game from that, is that the cause?

No, I have the Steam version and also receive this error.

**Comment by goatfungus** [comment]
This should be fixed now.
