### ISSUE TITLE
New Salvaged Freighter Tech

### ISSUE THREAD

**Issue by ardyalligan** [goatfungus/NMSSaveEditor#291]
Hello. I noticed that the new salvaged freighter modules are buildable, but only in the freighter's tech slots. In-game, those items are actually meant to be installed in the main freighter inventory as well as in the tech slots, but procedural items are not available in the save editor's Add Item menus (only substance and product). 

Would you please update Save Editor to allow placement of procedural tech in the Freighter's main inventory slots?

Thanks very much!

![Example of how to use salvaged freighter modules](https://user-images.githubusercontent.com/48868318/88434786-924d9c80-cdc6-11ea-86c5-f92373f44ada.PNG)
![Save Editor Freighter Main Slots Menu](https://user-images.githubusercontent.com/48868318/88434924-d476de00-cdc6-11ea-8104-d07e4eca4c77.PNG)

**Comment by Sezyrrith** [comment]
To add, as it's closely related: when adding the Product/Consumable Salvaged Fleet items to the regular inventory (the ones you 'use' to add the module to your freighter), the ID gives a non-usable item in game. For example, ^U_FR_SPE4 is the ID given when adding a class S Salvaged Fleet Beacon, and while this produces an item in game, it's unusable and has no seed (ergo, it says it's from %NAME% in the description). Some JSON editing and item farming ingame led me to the following IDs:
^UP_FRSPE#<seed>: Fleet Speed
^UP_FRFUE#<seed>: Fleet Fuel 
^UP_FRTRA#<seed>: Fleet Trading
^UP_FRMIN#<seed>: Fleet Mining
^UP_FRCOM#<seed>: Fleet Combat
^UP_FRHYP#<seed>: Freighter Hyperdrive
So, for example, ^UP_FRHYP#99045 gives an S-class freighter hyperdrive upgrade from the reddit favorite SV Ayoro XIX (I've always gotten +100% efficiency and 246 ly on it).
Note: before, the ^U_FR_SPE4 was the S class, SPE3 was the A class and so on - this set doesn't seem to follow that convention. I didn't mess with it much, but my limited testing used the seed 99045 and the one time I made a typo it while testing IDs (I think as 99405) it came up C class.

**Comment by goatfungus** [comment]
This should be fixed now, sorry for the delay.

**Comment by ardyalligan** [comment]
Hi.

Thank you for this update!

I've been trying to replicate my friend's freighter layout
<https://cdn.discordapp.com/attachments/681970618123681851/739276912039428203/sketch-1596327695899.jpg>
(he's on PS4), but it doesn't seem possible to install these tech upgrades
into the General slots using Save Editor. I think that's what you're
saying, right? Installing them seems essentially like an RNG activity in
the game.

Thanks again,
ardyalligan

**Comment by TheSmilez** [comment]
> This should be fixed now, sorry for the delay.

Sadly it is not - There is no seed # for any of the B, A, or S classes - Only C.
