### ISSUE TITLE
Unable to backup/restore freighter base

### ISSUE THREAD

**Issue by celestialcanoe** [goatfungus/NMSSaveEditor#294]
The options for backing up or restoring the freighter base are greyed out, with no "items" listed. 
![image](https://user-images.githubusercontent.com/68818102/88483011-98f52480-cf2a-11ea-8f1a-5254a87f858c.png)
Is there are an in-game requirement for something that has to be built in the base for it to be recognized?

**Comment by Graslama** [comment]
but you can still do it within the RAW JSON Editor
but yeah
this button would make it easy again

**Comment by celestialcanoe** [comment]
Yeah, not sure how to do that without breaking anything. I figured out how to open the raw JSON, I'm guessing it's under...FreighterLayout? PersistentPlayerBases?
But I'm not sure what I'd have to copy/paste and where.

(Main goal is to be able to load my old layout on a new Freighter; though that might have been obvious).

**Comment by goatfungus** [comment]
This has been fixed in later version, just cleaning up.
