### ISSUE TITLE
Starship Trails

### ISSUE THREAD

**Issue by cinnamonRoll17** [goatfungus/NMSSaveEditor#297]
I was editing a savefile a little bit, and decided to add a starship trail, but I dont find the item, I only see it in the "Known Technologies" editor but no way to add it

**Comment by Infinality** [comment]
I've had this exact same issue.  The way to fix it is to remove it from the learned technologies in NMSSaveEditor.  Then add a few thousand to your nanites and save.  Launch NMS, and go to the Anomaly and just purchase them there.

**Comment by goatfungus** [comment]
This has been fixed in later version, just cleaning up.
