### ISSUE TITLE
Webroot / Malware

### ISSUE THREAD

**Issue by Infinality** [goatfungus/NMSSaveEditor#299]
Webroot flags NMSSaveEditor.exe as malware.  Are you aware of this, and do you know why?

**Comment by goatfungus** [comment]
Not sure why, it uses the standard 7-zip executable builder so shouldn't be a problem.

**Comment by Infinality** [comment]
`Tue 2020-07-28 07:25:17.0841	Infection detected: C:\Users\REDACTED\Downloads\NMSSaveEditor.exe [SHA256: E2B31DDA309F08C611E2FF3C87540C44938BED5702787C09B0984CC4EDCF4F85] [MD5: 8DF95D0EBC1D1FA72C4FF4C9DCFFE9C6] [3/00080800] [W32.Adware.Gen]`

Maybe it just thinks anything created with that is W32.Adware.Gen?

**Comment by goatfungus** [comment]
There is no adware in the exe or jar version. False positive
