### ISSUE TITLE
graphical glitches inside the program

### ISSUE THREAD

**Issue by koekblik2** [goatfungus/NMSSaveEditor#3]
whenever i right click somewhere in the inventory this happens: https://gyazo.com/57b40b91b86511b0f08af15f06a3953a

any idea how to fix this?
thanks in advance!

**Comment by goatfungus** [comment]
Someone else had a similar issue when using MSI Afterburner + RivaTuner for overlays, and when they turned those off it worked fine.

**Comment by koekblik2** [comment]
@goatfungus Nice! even though it wasn't rivatuner or MSI afterburner it was my Strix sound card program that was causing the trouble thanks for helping me man!

**Comment by goatfungus** [comment]
Wierd, but glad it works for you now :)
