### ISSUE TITLE
[Unknown] Shell folder bind error: Java

### ISSUE THREAD

**Issue by Acidhub** [goatfungus/NMSSaveEditor#30]
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.InternalError: Could not bind shell folder to interface
[INFO] 	at sun.awt.shell.Win32ShellFolder2.initSpecial(Native Method)
[INFO] 	at sun.awt.shell.Win32ShellFolder2.access$300(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2$1.call(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2$1.call(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker.invoke(Unknown Source)
[INFO] 	at sun.awt.shell.ShellFolder.invoke(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2.<init>(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolderManager2.getNetwork(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2.access$400(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2$2.call(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2$2.call(Unknown Source)
[INFO] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Unknown Source)
[INFO] 	at java.lang.Thread.run(Unknown Source)
[INFO] Latest version: "1.5.7"
[INFO] Current version: "1.5.7"
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.InternalError: Could not bind shell folder to interface
[INFO] 	at sun.awt.shell.Win32ShellFolder2.initSpecial(Native Method)
[INFO] 	at sun.awt.shell.Win32ShellFolder2.access$300(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2$1.call(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2$1.call(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker.invoke(Unknown Source)
[INFO] 	at sun.awt.shell.ShellFolder.invoke(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2.<init>(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolderManager2.getNetwork(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2.access$400(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2$2.call(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolder2$2.call(Unknown Source)
[INFO] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[INFO] 	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Unknown Source)
[INFO] 	at java.lang.Thread.run(Unknown Source)

**Comment by goatfungus** [comment]
This looks like a Windows or Java permission problem. Try reinstalling Java and see if that helps.
