### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by Bonetwizt** [goatfungus/NMSSaveEditor#304]
Im on windows 10 with the steam version of the game. Wiith the latest release (1.6.14) I cannot save changes made to the savefile.

 the log reads 
`[INFO] using name mappings: NMS 2.61
[INFO] Finished.
[INFO] Preparing game slot...
[INFO] Formatting JSON...
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
[STDERR] 	at java.util.ArrayList.elementData(Unknown Source)
[STDERR] 	at java.util.ArrayList.get(Unknown Source)
[STDERR] 	at nomanssave.util.h.getValue(Unknown Source)
[STDERR] 	at nomanssave.util.h.al(Unknown Source)
[STDERR] 	at nomanssave.Application.p(Unknown Source)
[STDERR] 	at nomanssave.Application.r(Unknown Source)
[STDERR] 	at nomanssave.Application.o(Unknown Source)
[STDERR] 	at nomanssave.J.actionPerformed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.doClick(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)`

and also
`[INFO] Formatting JSON...
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException`

**Comment by Infinality** [comment]
Were you manually editing the JSON?  If so, you might want to check for syntax errors like missing or extra brackets, commas, etc.  Just a thought.

**Comment by Bonetwizt** [comment]
No, I was only using the save game editor features, no direct editing.

**Comment by Jossem** [comment]
laatste update van editor veroorzaakt problemen, saving changes not possible (error) Windows 10

**Comment by karimatrix** [comment]
i had similar issue, deleted save editor and reinstalled it fresh in other directory on disk. Somehow it helps.

**Comment by Bonetwizt** [comment]
I fixed my issue, somehow, some value in my multi tool was out of range. Bought a new one at a base, fixed it.

**Comment by goatfungus** [comment]
This issue should now be fixed.
