### ISSUE TITLE
save game files appear to have changed in the last 24hrs

### ISSUE THREAD

**Issue by Novoca1n3** [goatfungus/NMSSaveEditor#311]
When I open a save game file and view the json, a number of errors appear in the command window (java heap space errors). When I view PersistentPlayerBases the number of bases I have has gone from 15 to 29 although none of the bases after 15 are visible in the GUI or from within the game. Once the PersistentPlayerBases node is expanded the json viewer freezes and the only way to close down save game editor is to kill the command window. I wonder if HG have made some changes to the save file ready for this weeks release.

BTW, if I open save game backups made yesterday all is good and the additional 14 bases are not present. I haven;t added any additional bases today

**Comment by ukmerlin** [comment]
I do not see where HG has pushed anything out anywhere. You can end up with additional bases in your save file if you stop in a system with other people, most of which will have bases with no real content except a base computer.

**Comment by Novoca1n3** [comment]
Hmm, ok. That could be it. I did visit the UAS EIS today and there were quite a lot of bases. Either way it seems to have corrupted by save game file as I can no longer open and view my base data in json. Not a big issue as I'll just copy across a backup from last night. Didn't really do much today except browse

**Comment by ukmerlin** [comment]
You might not need to, if you visit another system the other bases will all drop off.

**Comment by Novoca1n3** [comment]
Ok. I did that and they dropped off. Thanks. Returning to the UAS EIS put them back which is a pain as I was looking at creating a base there.
