### ISSUE TITLE
Yet another large update

### ISSUE THREAD

**Issue by micmou** [goatfungus/NMSSaveEditor#312]
Another massive update dropped today being called Origins it has a version number that bumped the game from 2.something to 3.something and there are a load of new features as well as the reorganizing of the crafting trees and the removal of some rarely used items. Figured I would drop this here for ya like I always do.

**Comment by Bounty780** [comment]
Agreed

**Comment by SubsterNL** [comment]
I haven't seen a post by the author in months.. Just hope he didn't abandon the project.. That would be so sad... :(

**Comment by Infinality** [comment]
If he has abandoned it, the least he could do is open the source code!  Let other people help!

**Comment by batspaceman** [comment]
Yeah I'm having issues because of the new update - specifically with scrap dealer banned upgrade modules and the new ship trails and figurines - only nulls is available for whatever reason, as all the others already displayed as owned in the quicksilver shop, and they dont show in my known technology when I check via either the tab OR the json editor. I don't know if or how I could manually add them, since I don't know how I could find the code-name for them. I _might_ be able to guess for the figurines, but the starship trails I have no idea about since I don't have a reference point. If anyone else has any experience finding the names for such things, any help is appreciated.

**Comment by bjorno43** [comment]
Give the author some time guys. If you've ever taken a look at the raw savegame data, you'd know that it's a minified JSON string. It takes time to figure out how all the data is actually saved inside this string. Especially with large updates where lots of things have been added / removed / changed.

If you really can't wait, here's a small guide to at least be able to edit your credits / nanites / quicksilver:

1. Browse to %appdata%\Roaming\HelloGames\NMS\"some_identier"
2. Open up your savegame with some text editor. This should one of the save.hg / save2.hg / save3.hg etc files. Easiest way to figure out which savegame you need is to check which one of those has been modified last. That should be the one you've saved last.
3. Search for: "wGS": ### - Where ### is the number of credits you have. Change it to your liking
4. Search for: "7QL": ### - Where ### is the number of nanites you have. Change it to your liking
5. Search for: "kN;": ### - Where ### is the number of quicksilver you have. Change it to your liking

Those 3 values should be right next to eachother. Makes it a bit easier. Save the file, reload the save.

PS: Always make a backup of your savegame before editing! Don't say I didn't warn you if you mess up and lose your savegame!

**Comment by batspaceman** [comment]
The save editor still works absolutely fine for anything it used to work for. The only missing functionality is NEW content that has been added in origins. -  specifically the things I mentioned, but I'm sure there's more.

**Comment by Novoca1n3** [comment]
> The save editor still works absolutely fine for anything it used to work for. The only missing functionality is NEW content that has been added in origins. - specifically the things I mentioned, but I'm sure there's more.

That's not true. If you try to view raw json it will crash/freeze 90% of the time. If yoh make changes and save all the new item blueprints get deleted from your save game

**Comment by goatfungus** [comment]
Don't worry, the project is not abandoned. It just took a while to get the editor working properly for the new version (Origins).
Should be all up and running again now. Enjoy :)

**Comment by batspaceman** [comment]
chad

**Comment by Novoca1n3** [comment]
Legend. Thank you. Back to base building 😁

**Comment by Cheater42** [comment]
Thanks, goatfungus - very much appreciated!

**Comment by micmou** [comment]
> I haven't seen a post by the author in months.. Just hope he didn't abandon the project.. That would be so sad... :(

Generally speaking goatfungus doesnt say much in here from what I have noticed but generally speaking once someone pings him with a new update notification he apirates a few days later and says good to go lads... Hes a magician like that xD I doubt he needs to be pinged but I know with how life is that sometimes a nice reminder is good.

Also thanks for the update goatfungus a lot of people including myself very much appreciate it.
