### ISSUE TITLE
Several Issues Noted.

### ISSUE THREAD

**Issue by Darena-Bryant** [goatfungus/NMSSaveEditor#313]
This is my first post here so forgive me if these have been reported before.

I noticed that when moving certain items from General to Cargo in the Exosuit (in this case Glass), the max quantity seems to change. An example is I had 25 glass in my General Storage, and when I tried to move it to Cargo, it split into two stacks of 10 without moving the stack out of General. Also of note, at the time of the move, I already had two stacks of Glass that were at 50 each, yet the stacks that appeared were both at 10 max each.

This leads into the next issue, which is that after editing inventory and logging into the game and back out again, certain items seem to gain larger stack values. This includes the Glass, which I can only edit in a single stack of 10 in the cargo of my Exosuit, but was able to increase to stacks of 50 after logging in and out again. Other items that seemed affected were the Ion Battery, Advanced Ion Battery and Oxygen Capsule, all of which doubled their max value from 100 to 200 after logging in, then out again while they were in cargo slots.

Lastly, and something of a small one, the Boltcaster Ricochet Module reads in the description that it's for the Pulse Spitter, and vice versa. I haven't tested if they work as intended just yet; it might be just an error in the descriptions.

**Comment by goatfungus** [comment]
In the latest update of the game (Origins), Hello Games changed the stack sizes on a number of items. This was not reflected in the editor as I hadn't updated it yet. It should be all good now though.

**Comment by Novoca1n3** [comment]
What about the new craftable items and tge items that have been removed? Was that updated in the new version?
