### ISSUE TITLE
JSON editor not working

### ISSUE THREAD

**Issue by billlcarr** [goatfungus/NMSSaveEditor#315]
Since the origins update, even in the new save editor version, I'm getting an error when I try to edit the raw JSON. This is the message I get-

Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

This never happened before the origins update. And it doesn't seem to happen with every save. Occasionally I'll try with a new save and it'll work like normal. But then the next time I try it, on a different, newer save, it'll start doing that again. Really weird. Any ideas what could be happening?

**Comment by Novoca1n3** [comment]
I used to get this before Origin's update. Turned out to be caused by visiting a system with a lot of player bases. Their bases actually get saved in your PersistedPlayerBases collection until you leave the system

**Comment by billlcarr** [comment]
I'm in Calypso, so there aren't really any systems with a lot of player bases lol

**Comment by Novoca1n3** [comment]
Strange indeed. I've been able to use the new version to view and update my 17 bases (using json viewer) across 6 different galaxies without any issues. Would be good to know what's causing your issue

**Comment by billlcarr** [comment]
Yeah, would love to know. The only thing I really use it for is restoring my freighter base if it disappears (which has happened to me twice over the past few years).

I just now warped to a brand new undiscovered system, and saved the game, and it's still doing it.

What's really strange is I noticed it happen right after the update. Then the next day I tried on a newer save and it worked like normal. Now it's doing it again. Bizarre

**Comment by Novoca1n3** [comment]
Same. I only use it for Bases. Not interested in using it to cheat my way through the game lol

**Comment by billlcarr** [comment]
Yeah man, it's a godsend for bases. Being able to back up and restore them on a new planet saves a lot of tedious work when one gets buried, or ends up in a different biome after an update. Building bases is really fun. Rebuilding a base you already spent days perfecting, not so much.

**Comment by billlcarr** [comment]
I just compared my new save (that's getting this error) with one of the backups the editor makes from about 3 days ago (that's not getting this error), and the new save is about 9mb, the backup is about 6mb. No clue what would cause it to increase so much in size.

**Comment by Novoca1n3** [comment]
That's a pretty big difference. Mine have only jumped around 1-200k since the update due to creating another base. If you use Notepad++ you can compare the two files and it will show you the differences. My bet it will be something to do with items in PersistentPlayerBases as you're getting the same message I was.

**Comment by billlcarr** [comment]
Cool thanks, I'll try that!

**Comment by billlcarr** [comment]
Well, tried, but notepad++ goes unresponsive forever. How long should comparing a 6mb file to a 9mb file take?

**Comment by Novoca1n3** [comment]
Can take quite a long time as there's a lot of text in the save file. Also depends on your CPU and RAM configuration. took one of my compares around 13 minutes

**Comment by billlcarr** [comment]
OK, thanks! I didn't give it that long. I'll try again. Thanks a lot :)

**Comment by nms2020org** [comment]
I got the same error message as OP, I tried both versions 1.7.0 and 1.6.14, they can json edit my older save files before Origins update, but not the save files after the update.

**Comment by billlcarr** [comment]
Have your save files grown in size? I'm thinking maybe there's something in the update that's making save files get bigger after a while, which I suppose could be causing the out of memory error. The first time this happened with the editor was shortly after the update. I thought maybe there was something wrong with my save, so I went back to a previous save. All was well for a while, but eventually I started getting that error again. Unfortunately I didn't check the file size the first time it happened, so I don't know for sure if there's a connection.

**Comment by Novoca1n3** [comment]
Mine haven't changed that much. Maybe 1-200k

**Comment by nms2020org** [comment]
Yes, my save file indeed gets significantly large, from 5M to 7M, approximately.
I updated my Java environment (adding path to a recent Java installation), now I can json edit again.

**Comment by billlcarr** [comment]
Damn, I was hoping that would  do the trick. I just updated Java, but it's still doing the same thing.

**Comment by billlcarr** [comment]
Well I got it working now. I was apparently running 32bit java. I uninstalled it and installed the 64bit version and it's working like normal. Whew.

Thanks for all the help guys!

**Comment by nms2020org** [comment]
I am glad you worked it out. Thanks to you, fellow travelers, and happy blendering.

**Comment by billlcarr** [comment]
It looks like the problem was the 32 bit version of java couldn't handle the larger file size, and the larger file size was caused by a bug that was patched today. Switching to 64 bit java solved it initially, and after today's update, my save file went from 9.6mb to 6.5mb. So I'm closing this because it appears to have nothing to do with the save editor.
