### ISSUE TITLE
[BUG] Unrecognized tech items

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#317]
There are a few tech items, added in previous updates, which are missing from the lists:
**Exocraft tech:**
EXO_RECHARGE

**ship tech:**
T_BOBBLE_APOLLO
T_BOBBLE_ART
T_BOBBLE_ATLAS
T_BOBBLE_NADA
T_BOBBLE_NULL
T_BOBBLE_POLO
T_SHIP_DARK
T_SHIP_GOLD
T_SHIP_GREEN
T_SHIP_RED

**Comment by goatfungus** [comment]
Thanks for the info.
I have added these in now, so they should be available in version 1.7.1.

**Comment by roie-r** [comment]
More unrecognized products (not tech), missed those first time around; the new freighter customization paint:
FREIGHT_PAINT
FREIGHT_RED
FREIGHT_PURPLE
FREIGHT_BLUE
FREIGHT_CYAN
FREIGHT_GREEN
FREIGHT_YELLOW
FREIGHT_ORANGE
FREIGHT_WHITE
FREIGHT_PINK
FREIGHT_BLACK
