### ISSUE TITLE
Technology/Product ID Request

### ISSUE THREAD

**Issue by Aeramis** [goatfungus/NMSSaveEditor#318]
Hello, I was wondering if you could make a document that has all the known Technology/Product ID names and what they are for each? I know it is in your save editor, but I don't have a PC save file to pull them from there.

It would be nice that have that.

**Comment by Aeramis** [comment]
I'm also looking for the other Item ID's too.

**Comment by cengelha** [comment]
Hi,
I have something like that in my editor. The catalogue section is currently a bit broken but will be fixed in the release after the next. The table works but you cannot view the details (at least not for all).

**Comment by Aeramis** [comment]
> 
> 
> Hi,
> I have something like that in my editor. The catalogue section is currently a bit broken but will be fixed in the release after the next. The table works but you cannot view the details (at least not for all).

Do you by any chance know what the ID is for the Extreme Weather Sols?

**Comment by cengelha** [comment]
You mean the Milestone? That one doesn't have an ID. The value for that is in _PlayerStateData.HazardTimeAlive_. It's stored in seconds and to get the value displayed in-game you have to divide it by 900.

**Comment by Aeramis** [comment]
> 
> 
> You mean the Milestone? That one doesn't have an ID. The value for that is in _PlayerStateData.HazardTimeAlive_. It's stored in seconds and to get the value displayed in-game you have to divide it by 900.

Thanks for that, bare in mind I am doing this on a PS4 save file. I have found two locations for HazardTimeAlive. My in-game shows the SOLS as 2.4 / 3.0 as the current Milestone. 

But on the Hex Edit for the save show the value as 454. I'm not sure how it is getting that number. Dividing by 900 = 0.5044444
So that isn't the case here. I am not sure how 454 equates to 2.4.

**Comment by cengelha** [comment]
If you hex edit the file there will be one for each save you have (e.g. 1 auto and 1 manual save in a slot or 2 auto saves in 2 slots). Maybe you changed the wrong one.
It follows the pattern slot 1 auto, slot 1 manual, slot 2 auto, etc. But as slots in the in-game selection screen aren't ordered by slot number but last save date you may have to try which is the one you want to edit.

Instead of doing it manually, you can use my editor for this. It supports PS4 (SaveWizard and Save Mounter) as well.

**Comment by Aeramis** [comment]
how do I load the ps4 save in it?

**Comment by cengelha** [comment]
Just select the directory with your memory.dat in it (file must have this name)

**Comment by Aeramis** [comment]
> 
> 
> Just select the directory with your memory.dat in it (file must have this name)

It keeps crashing. I get an exception error. 
I go to Open > Selected Folder and then it crashes.

**Comment by Aeramis** [comment]
![NomNom Error](https://user-images.githubusercontent.com/72037691/95024526-5d688c00-0638-11eb-80f9-8045c2369216.jpg)

**Comment by cengelha** [comment]
Please create a new issue in my repo with the report file attached or pasted. This is not the right place for it ;)

**Comment by Aeramis** [comment]
> Please create a new issue in my repo with the report file attached or pasted. This is not the right place for it ;)

I will have to do it later.  At work now.

**Comment by cengelha** [comment]
Just released an update that may resolve your problem.

**Comment by Aeramis** [comment]
> Just released an update that may resolve your problem.

Is that the one that added the Origins loading screen?

**Comment by cengelha** [comment]
3.0.0.9. But maybe you better wait for the 3.0.0.10 hot fix 😅

**Comment by Aeramis** [comment]
@cengelha Is there another way to contact you, I just have some questions on non issues.

**Comment by cengelha** [comment]
@Aeramis Here you go https://github.com/cengelha/NomNom#authors
