### ISSUE TITLE
Salvaged Freighter Upgrades Only Has "C" Class

### ISSUE THREAD

**Issue by TheSmilez** [goatfungus/NMSSaveEditor#321]
When picking from: **Product > Procedural > Salvaged**
Only "C" class mods are generated. I've tried editing the seed numbers but no luck.

ALSO...

When picking from: **Product > Consumable > Salvaged**
They seem to be using the old format... eg. _^U_FR_COM4_ instead of _^UP_FRCOM_
This makes the item unusable.

**Comment by TheSmilez** [comment]
**_EDIT:_**
It does not reflect on the save editor itself, but it will reflect in game if you change seed number to "99045".

**Comment by cengelha** [comment]
That one is a bit tricky. 
UP_FRCOM (Product) deploys into UP_FRCOM1-4 (Product) and that deploys into U_FR_COM1-4 (Tech). Not sure about if I got the IDs right from memory, but you get the idea.

But UP_FRCOM is a procedural item (has a seed) and based on the seed you get the different classes.
Directly adding UP_FRCOM1-4 to your inventory doesn't work ultimately as you cannot install them.
The transition from the first product to the second is done on the fly by the game. No chance for the editor to tell what you actually have.

So, you have to try your luck with the seeds of UP_FRCOM or you just install the tech directly

**Comment by TheSmilez** [comment]
> That one is a bit tricky.
> UP_FRCOM (Product) deploys into UP_FRCOM1-4 (Product) and that deploys into U_FR_COM1-4 (Tech). Not sure about if I got the IDs right from memory, but you get the idea.
> 
> But UP_FRCOM is a procedural item (has a seed) and based on the seed you get the different classes.
> Directly adding UP_FRCOM1-4 to your inventory doesn't work ultimately as you cannot install them.
> The transition from the first product to the second is done on the fly by the game. No chance for the editor to tell what you actually have.
> 
> So, you have to try your luck with the seeds of UP_FRCOM or you just install the tech directly

Thanks for the info.

I managed to get it working by applying the same seed number to the "C" working module and it translates automatically to an "S" type when loading up the game.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
