### ISSUE TITLE
[Feature Request] Edit Freighter's Fleet Coordination

### ISSUE THREAD

**Issue by Astronox** [goatfungus/NMSSaveEditor#322]
If it's possible, I think a good enhancement would be to add a field in the Freighter editing tab to change the Fleet Coordination stat.

Thank you for all the hard work you put into this tool.

**Comment by roie-r** [comment]
Fleet coordination is derived from installed freighter upgrades in-game. It's not a saved property - the editor can do nothing about it.

**Comment by cengelha** [comment]
It actually is. It has a base stat just like the Hyperdrive

**Comment by goatfungus** [comment]
I have added this now, will go in next update. Sorry it has taken so long.
