### ISSUE TITLE
[feature request] ability to edit in quicksilver

### ISSUE THREAD

**Issue by PItlosTails** [goatfungus/NMSSaveEditor#323]
pretty much title, would love to be able to purchase something

**Comment by ukmerlin** [comment]
What do you mean? You can edit QS content under exosuit..

**Comment by PItlosTails** [comment]
oh i couldnt find it and there was no picture of it... by the way do you know why the program wont run it says "C:\ProgramData\Oracle\Java\javapath\java.exe" despite me having it
