### ISSUE TITLE
Save Issue 

### ISSUE THREAD

**Issue by Louis2257** [goatfungus/NMSSaveEditor#325]
I have an issue where i load the save into the editor, make changes etc. Then when loading back into the game no changes have been made and its taken me back to a previous save. Have tried multiple times with multiple saves and nothing works. Thankfully I made backups. 

I am pretty sure 1.7.0 didn't have this issue.

**Comment by Infinality** [comment]
Are you sure you are saving to the same file and slot that your game is saved in?  Did you try playing NMS, saving, then opening it in the editor again?  Just brainstorming.

**Comment by Louis2257** [comment]
Yeah tried that. I even reinstalled the program to clear any saves it might’ve got confused with to not avail.

I will try again tomorrow by using a different game save and see if that works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ukmerlin** [comment]
I am now having the same issue. It appears to not be saving.

**Comment by Chaaozz** [comment]
Did anyone manage to fix this or work out why it may be happening? I'm stuck in the same boat

**Comment by Louis2257** [comment]
I think for me it was cause I changed my time from set automatically to a manual time. This basically forced it back to an older save... I think.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
