### ISSUE TITLE
Does this work when playing from the windows store?

### ISSUE THREAD

**Issue by Deathwatchbeto** [goatfungus/NMSSaveEditor#326]
Tried finding my save it would not appear on the editor at all. Was wondering if I'm doing something wrong or if it just doesn't work from the windows store.

**Comment by Infinality** [comment]
You probably need to locate the save file on your C drive somewhere.  For Steam, it stores it in a path that looks like this:

c:\Users\YOURUSER\AppData\Roaming\HelloGames\NMS

You might try searching for folders on your C drive named "HelloGames" and work from there.  Once you have identified the path, use that when opening the NMS editor.

**Comment by freythman** [comment]
Try this instead:
https://github.com/cengelha/NomNom

They tout limited Windows Store version support, with caveats.

**Comment by goatfungus** [comment]
This editor works for MS Game Pass saves now.
