### ISSUE TITLE
Feature Request: Display Procdural Tech Stats

### ISSUE THREAD

**Issue by dracahn** [goatfungus/NMSSaveEditor#327]
Hello,
I am requesting the ability to see procedural tech stats.  So here's the idea:
When a user pulls up the procedural tech item, there is a new button on the page.
When a user clicks that button a new window pops up.
That new window is a table with a list of this procedural tech's IDs along with what stat values it will provide.
I can sort that list by the various values and select one.
That ID is used as the new ID for the tech slot.

Primarily this will be useful for X-teir tech so I can select an upgrade that gets what I actually want instead of rolling over and over again and hoping I get a good one.

**Comment by ukmerlin** [comment]
The editor only looks at the save file. The items you are talking about are procedural which are buried in the game code. Until you go to install even the game will not know what it is supposed to be. It is entirely dependent on what you already have and other procedural rules at the time.
