### ISSUE TITLE
Modifier exception

### ISSUE THREAD

**Issue by KLLTY** [goatfungus/NMSSaveEditor#328]
When the editor is opened, the tabs cannot be used, stuck, cannot be used normally, and the archive cannot be read normally.

**Comment by KLLTY** [comment]
![Screenshot](https://user-images.githubusercontent.com/57021305/95309501-cd3b7880-08bd-11eb-9220-7f4101b68c89.png)

**Comment by KLLTY** [comment]
The modifier cannot be read to the archive and cannot be used as shown
![Uploading Screenshot.png…]()

**Comment by goatfungus** [comment]
This should be fixed in latest version.
