### ISSUE TITLE
Is this updated for Origins?

### ISSUE THREAD

**Issue by raymonders** [goatfungus/NMSSaveEditor#329]

**Comment by marknl** [comment]
I just installed No Mans Sky on PC, started a new game until i reached my ship. Then got in and out to save, opened it up in the editor and started to add in what I have on PS4. Seems to work fine so far.

**Comment by mediajolt001** [comment]
How did you get the data from your PS4?

**Comment by marknl** [comment]
> How did you get the data from your PS4?

I just made pictures of the stuff I have on PS4 and duplicated that in the editor, like exosuit, starship and multi tool slots, and modules i had. You DO need to start over with quests though.

**Comment by mediajolt001** [comment]
Makes sense. Thanks!

--
Joseph J Jolton
j@jolton.com
On 10/14/2020 12:10:35 PM, Marknl <notifications@github.com> wrote:
How did you get the data from your PS4?
I just made pictures of the stuff I have on PS4 and duplicated that in the editor, like exosuit, starship and multi tool slots, and modules i had. You DO need to start over with quests though.

**Comment by m0lz** [comment]
"Is this updated for Origins?"

I think there was an update around the time the first origins release, but not since all the following patches to the game.

NMSSaveEditor does not recognise the new currency in the game, and there are probably more items

**Comment by goatfungus** [comment]
Yes. It's up to date with Frontiers now.
