### ISSUE TITLE
Not really an Issue, more a question for those in the know.

### ISSUE THREAD

**Issue by Seranthor** [goatfungus/NMSSaveEditor#33]
Which variable in the below controls the horizontal facing (like if you want the door to face NSEW?)
and is it dependent on the alignment of the base computer (Base Flag)?

			"Timestamp":1532835073,
			"ObjectID":"^MAINROOMCUBE",
			"UserData":0,
			"Position":[
				-6.148223876953125,
				5.864166259765625,
				12.18304443359375
			],
			"Up":[
				-0.0000623166561126709,
				1.0,
				0.0001238211989402771
			],
			"At":[
				0.4592229723930359,
				0.0001385807991027832,
				-0.8883209228515625
			]
		},

**Comment by Seranthor** [comment]
would also be helpful if I knew which variable controlled the vertical placement of the object. Thanks.

**Comment by goatfungus** [comment]
"Position" controls the actual placement relative to the base flag (which should always be at [0,0,0]).
"Up" controls the vertical rotation (for most core buildings this would be set to [0,1,0]).
"At" controls the rotation around the y-axis.

It is a LOT easier to see what they do now compared to Atlas Rises, as all vectors used to be rotated around a unique world point for each base.

**Comment by Seranthor** [comment]
reason I'm asking is I've stripped one base down to just computer and one block and I'm trying to align everything so its not sitting there with a carpet of water.
