### ISSUE TITLE
Visiting a system with multiple player bases crashes save editor when using JSON viewer

### ISSUE THREAD

**Issue by Novoca1n3** [goatfungus/NMSSaveEditor#330]
If you visit a system that has multiple player bases those bases get stored in PersistentPlayerBases until you leave that system and do a save. If you try to view save game data using the JSON viewer before leaving the system and saving the app crashed and requires a kill to close it down. Many people use Blender and the NMS add-in for Blender to create/modify bases. These tools work with JSON via the JSON viewer
![Capture](https://user-images.githubusercontent.com/24946111/95927695-36197800-0e0b-11eb-840a-8660b8d2de02.JPG)

**Comment by Devilin-Pixy** [comment]
Looks like Java is running out of memory. Make sure to use 64-bit java and if the issue persists, increase the 'max heap' size using command line parameters. See: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html

You can check current defaults used through the following command:
`java -XX:+PrintFlagsFinal -version | findstr HeapSize`
It will show the amount of bytes used for 'InitialHeapSize' and 'MaxHeapSize' amongst a few other things.

**Comment by Novoca1n3** [comment]
> Looks like Java is running out of memory. Make sure to use 64-bit java and if the issue persists, increase the 'max heap' size using command line parameters. See: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html
> 
> You can check current defaults used through the following command:
> `java -XX:+PrintFlagsFinal -version | findstr HeapSize`
> It will show the amount of bytes used for 'InitialHeapSize' and 'MaxHeapSize' amongst a few other things.

Sorry for not getting back to you earlier. Thanks for the info. Turns out I had the x86 version installed. When I put the x64 version on the error went away. Thanks for your help
