### ISSUE TITLE
[Request] PS4 Save Support? - Save format is very similar 

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [goatfungus/NMSSaveEditor#331]
@goatfungus 
Hi, I tried getting ur save editor to open the PS4 ver of NMS save, but to no avail, it just sees it as an empty save.

however, the save structure at 1st glace is same I believe.
from offset 1048, the save follows the same structure from the PC ver, although with the ps4 version everything is in one file settings etc... 
I tried tinkering with the save cutting bits out to match the PC ver but it still wouldn't read it properly...

[memory.dat.zip](https://github.com/goatfungus/NMSSaveEditor/files/5398154/memory.dat.zip) <-- Save Slot 1, Autosave
I've attached my decrypted save
if you have some time maybe you could add support for PS4 saves?
I used savewizard to dump my save data...

**Comment by Pd69bq** [comment]
+1
decrypted ps4 save is basically the PC save minus the json format and with some extra PS4 header. 

even tho we don't require save editor to handle the decryption/encryption I dunno y most of the dev don't support PS4 format willingly just bc the save needs pre-processing by the save wizard? same things happened in CP 2077 save editor, one of the save editor dev thought that save wizard is not a proper tool

**Comment by goatfungus** [comment]
Do you happen to have a save file from after the Frontiers update?
I've been working on PS4 Support, and just need a recent save to test out.
