### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Crinkletoes** [goatfungus/NMSSaveEditor#332]
I have Save Editor 1.7.1.  I deleted my base computer using the Editor and now when I start my game it starts from scratch.  All of my progress is lost but the Save Editor shows that I have all of my progress and items.  Every save in normal mode that I select has me starting from the beginning.  How do I start a save ( I have about 40 of them) from the Save Editor? Or did my deleting a file inside of the teleportEndpoints folder delete my progress along with my base?

**Comment by ukmerlin** [comment]
There is an issue with the current editor version on the new release. But apart from that it is not a good idea to simply delete a base in the editor. The game has a number of other components that link to its existence such as teleporting.

**Comment by Crinkletoes** [comment]
Okay, Thank you.
