### ISSUE TITLE
Base Stats

### ISSUE THREAD

**Issue by Emmennater** [goatfungus/NMSSaveEditor#339]
I see that Damage Potential, Shield Strength, and Hyperdrive Range are all base stats you can change in the editor except one.
Maneuverability is another base stat a ship comes with but when I go the the editor it isn't a variable you can change.
Is it possible to change this base stat because I went into the JSON editor and I couldn't find any variable relating the the maneuverability, even trying to see if I could change the strength of the pulse engine upgrades (which I couldn't because the strength of them are dependent on the seed of the module).

**Comment by Horonelius** [comment]
As far as I know, even though it gives you a numerical value for maneuverability, the base value is tied to ship class.
