### ISSUE TITLE
Not detecting my save file.

### ISSUE THREAD

**Issue by jblade209** [goatfungus/NMSSaveEditor#340]
I use xbox game pass version of the game, I think ive found my save file but when i go to the path using the file editor the files dont show. 
my location is as follows: 
C:\Users\[User]\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\000901FE1C1929BF_29070100B936489ABCE8B9AF3980429C

**Comment by Novoca1n3** [comment]
You can't use save editor with Xbox Game Saves as they're in a different format and encrypted

**Comment by goatfungus** [comment]
You can now :)
