### ISSUE TITLE
Inventory Slots Missing

### ISSUE THREAD

**Issue by 1darklyte** [goatfungus/NMSSaveEditor#344]
Hello, 

I used NMSSaveEditor to modify how many inventory slots I had in my storage containers in my base. After a few months of not playing I came back to find the inventory slots back to the normal size/quantity and all the items missing.

Any idea how I can fix this?

**Comment by Miangoco** [comment]
I'm getting this problem too it happened after origins update, not sure if is problem of the update or the save editor, to "fix" just add an extra slots to your containers at least to see the missing items

**Comment by 1darklyte** [comment]
ya I think the items are there but they are "blocked" out because the slots are missing. Trying to reapply the size increase doesn't make them appear either. :(

**Comment by Miangoco** [comment]
Ooh if you already has all slots unlocked yeah they won't appear, I guess is time to rearrange everything

**Comment by 1darklyte** [comment]
I saw this got closed without comment. Did it end up getting fixed/resolved?
