### ISSUE TITLE
mf_save*.hg checksum

### ISSUE THREAD

**Issue by Kashouryo** [goatfungus/NMSSaveEditor#345]
Hello!
Thank you for creating this powerful tool for us to experiment in NMS!
Since this editor is not open source, the only option for me is to ask here...
There's a checksum file that the game checks when loading a save(for some reason it loads fine even I delete the checksum? weird).
I'd like to know how does mf_save*.hg calculated? An explanation or formula would be largely appreciated
Thank you

**Comment by JiFish** [comment]
@Kashouryo Did you ever figure this out?

It's pretty frustrating that every save editor I can find is closed-source and that the checksum doesn't seem to match any hash I'm familiar with.

**Comment by Kashouryo** [comment]
Not yet. And for some reason the game doesn't even care for the checksum.

**Comment by MetaIdea** [comment]
I covered everything here:
https://github.com/MetaIdea/nms-savetool/blob/b83bb4aa8621ce663c432b604307beaeacef0985/src/nomanssave/Storage.cs#L361
