### ISSUE TITLE
Can you make this work with....

### ISSUE THREAD

**Issue by TheWhiskeypedia** [goatfungus/NMSSaveEditor#349]
Decrypted PS4 saves?  NomNom's works with them, but this looks so much more robust, with features I'd really like to explore and try.  I could upload my memory.dat if needed so you could see the differences?  One of my friends that I cross play with has been raving about how good this editor is lol.

**Comment by Haffoc** [comment]
I'd like to see the editor support the PS4 too.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
