### ISSUE TITLE
was tainted metal forgotten?

### ISSUE THREAD

**Issue by RevoNation** [goatfungus/NMSSaveEditor#350]
i looked in the list of products (all in all) tainted metal. but i can't find it I can't put it in a slot. is that wanted, or will it (hopefully) come in an update? I haven't noticed other things yet, but I'll do the freighter again and see if more things disappear or aren't shown in the inventory. tainted metal also belongs to origins.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
