### ISSUE TITLE
update won't run

### ISSUE THREAD

**Issue by Elmarts** [goatfungus/NMSSaveEditor#351]
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/5937398/NMSSaveEditor.log)

Running under linux Mint 19.3.  the JAR file used to run fine, but this last update somehow has broken it so it no longer opens, even though the jar file is marked as executable and is associated with OpenJDK JAVA 8 runtime.  I have Steam NMS running under Mint normally as well

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
