### ISSUE TITLE
Companion update

### ISSUE THREAD

**Issue by Reavenstriek** [goatfungus/NMSSaveEditor#353]
Is there a way that you can add the ability to customize the egg timer in the save editor? Waiting a day is never fun. or the ability to add the creature eggs to inventory as well

**Comment by ORLOFT** [comment]
Does that mean this mod will currently works after the companion update?  Obviously it wouldn't be able to give you companion items or what have you, but aside from that, does it function post Companion update?

**Comment by MyersP** [comment]
Overall it sees to still work. I am getting multiple "WARNING: name mapping not found: XID" errors in the cmd window for the save I have played in the new version. 
My other old saves do not have the issue loading. It could just be an issue with that particular save, but I had not seen it before.

**Comment by MickCasanova** [comment]
Am also getting the same map naming errors since the update.

**Comment by Pd69bq** [comment]
I did a before and after save compression and found some interesting things

`"Scale":0.7620813846588135,"XID":"^ROBOTANTELOPE","osl":["^_HEAD_CURVEB","^_CURVEBACC_2","^_ACC_BACKDISC","^_RIBCAGE_1","^_LEGSBACK_1","^_PLATING_1","^_CORDSLEGBACK_","^_BODY_1","^_LEGSFRONT_1","^_CORDSLEGFRONT_","^_SHOULDERACC_CANISTERS","^3223551756"]` 

I believe these r the size and species and parts of ur companions

**Comment by KBurd67** [comment]
Is there a way to enable Base deletion using this mod?  There's a glitch in the game that doesn't allow base deletion.

**Comment by ukmerlin** [comment]
This works fine after the companion update, in fact some other functionality returned. 
Specific for KBurd67 you can edit the raw JSON and simply delete the offending bases.
You will find it helpful to be in a system with few to no other players bases.

**Comment by goatfungus** [comment]
I have added the name mappings for the Companions update a few hours ago, so it should be all working now.
