### ISSUE TITLE
No saves show up?

### ISSUE THREAD

**Issue by jcjakec** [goatfungus/NMSSaveEditor#354]
I  go to the save folder but none are in there.

**Comment by ukmerlin** [comment]
Guessing you are on PC.
What is your file path? It should look like this on Steam; (cannot say for GoG anymore)
C:\Users\username\AppData\Roaming\HelloGames\NMS

**Comment by jcjakec** [comment]
> Guessing you are on PC.
> What is your file path? It should look like this on Steam; (cannot say for GoG anymore)
> C:\Users\username\AppData\Roaming\HelloGames\NMS

Had it on ms store, thatl be the problem. I have it on steam now though, so will try again.
