### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by DartPower** [goatfungus/NMSSaveEditor#355]
Why this project hostings here... (on Github, yes.) and hosting only obfuscated binaries? 
This is not a binary hosting, just a open source project hosting.
One question: Why?

**Comment by Azure-Fang** [comment]
> 
> 
> Why this project hostings here... (on Github, yes.) and hosting only obfuscated binaries?
> This is not a binary hosting, just a open source project hosting.
> One question: Why?

Not all projects on GitHub are open-source. The most important terms in context are:
> D.3. Ownership of Content, Right to Post, and License Grants
>
> You retain ownership of and responsibility for Your Content. If you're posting anything you did not create yourself or do not own the rights to, you agree that you are responsible for any Content you post; that you will only submit Content that you have the right to post; and that you will fully comply with any third party licenses relating to Content you post.
>
> Because you retain ownership of and responsibility for Your Content, we need you to grant us — and other GitHub Users — certain legal permissions, listed in Sections D.4 — D.7. These license grants apply to Your Content. If you upload Content that already comes with a license granting GitHub the permissions we need to run our Service, no additional license is required. You understand that you will not receive any payment for any of the rights granted in Sections D.4 — D.7. The licenses you grant to us will end when you remove Your Content from our servers, unless other Users have forked it.
>
> D.5. License Grant to Other Users
>
> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).
>
> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you adopt a license. If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.

Nowhere in the terms is it stated that projects on GitHub must be open source, though public projects grant users the ability to copy and use the project as it is. It may have been in the past, but as GitHub has become a more wide-reaching (and for-profit) service, it's come to conform to more project and license types.

Also, an issue isn't really the place to discuss this. If you have an issue with a project, you can always report it.

**Comment by Kashouryo** [comment]
Find a better reason for him to open source the prpject. You can host closed source content on github.

**Comment by DartPower** [comment]
This is so bad. Proprietary software is not good at my experience.  I often see amateurs developers. Lately they have only hurt.

I'm not saying this project is bad. But I am very disappointed in people who make their projects proprietary.
Disappointed. Strong. All over humanity.
