### ISSUE TITLE
Changes to nmanssave/db/jsonmap.txt

### ISSUE THREAD

**Issue by WardoPo** [goatfungus/NMSSaveEditor#358]
Hi, I'm trying to help with adding the companions update functionality.
I know a pull request would be more appropriate but, as stated in  #355 this isn't an open source project, so I wont mess with the code.

I've done my best to identify the new sections of the save file, I've added the names to my jsonmap.txt

#Here my discoveries

**At the top-level**

`Mcl` - Is the Companion Registry
`uKZ` - Appears to be the default value for the Companion Registry (What you'd have If you haven't adopted a companion or deleted all of them)
`j30` - Appear to be  some modifiers for the animation skeleton rigging, (All default values in my save)
9Lg - Are the companion spaces that the player has unlocked so far

**At each of the previous entries level**

#### Companion Registry

`osl` - BodyPart Model Array
`WTp` - appears to be the seed, but it's only affecting the animal's colour, not its model nor texture. When corresponded with the discoveries it appears as the first entry in the VP array
`1p=` - Does not appear in discoveries, doesn't seem to alter anything about the creature's appearance or data.
`m9o` - this changes the name of the species but does not appear to affect the animal's appearance. When corresponded with the discoveries it appears as the third entry in the VP array
`JrL` - Doesn't seem to alter anything about the creature's appearance or data. When corresponded with the discoveries it appears as the fourth entry in the VP array
`6fx` - Corresponds with `Wtp` by default. If altered while true it changes the model's head size.
`Q6I` -  When set to `true` it resets the creature spawn to an egg once (but does not reverse to false)

`8jm` - Creature's Native Climate `PetBiomeClimates` in `GCCREATUREGLOBALS`
`HbY `- Seems to correspond to the Temperment  `Temperments` in `GCCREATUREGLOBALS`

The following values seem to be multipliers, resulting in variations on the creature's info and appearance
"XwC" - It Appears to be changing and compressing it, and the creature's gender and age
"tDR"
"KY5"
"@Hb"
**More Investigation in needed**

`xDJ` - Corresponds with the companions Trust
`JAy ` - Represents its personality (Fisrt value for Playfulness, Second for Gentleness  ,and third for Independence) From -1 to 1
`IEo` - Represents the creature status (First value for affection and second for hunger) Closer to 0 for full and closer to 1 for empty.

**Comment by Pd69bq** [comment]
I forgot which one is but there's a key similar to Q6I corresponds to the recoloring

**Comment by WardoPo** [comment]
> irrc, uAX corresponds to the egg sequencer recoloring, similar to WTp and Q6I, default is [false,"0x0"].
> 
> when dye injector was used, uAX become true and the seed will overweight the value of WTp

Thank you, I had no idea, not plan any tests to check for it~
