### ISSUE TITLE
Missing Discoveries

### ISSUE THREAD

**Issue by FirecrackerTag** [goatfungus/NMSSaveEditor#361]
Under the "Discovery" tab there are over 300 items with missing name and missing category (no image/icon is there either). While this is only a minor inconvenience the quicksilver items seems to be effected by this as well. Purchased Quick Silver items are not showing up either. 
![SE Discoveries](https://user-images.githubusercontent.com/81199845/112076058-aad5a880-8b47-11eb-9905-ccb2010a7c5c.JPG)

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
