### ISSUE TITLE
No Man's Sky EXPEDITIONS?

### ISSUE THREAD

**Issue by louanbastos** [goatfungus/NMSSaveEditor#363]
Will be an update to EXPEDITIONS Update?

**Comment by Bean1415** [comment]
I hope there is an EXPEDITIONS Update plz

**Comment by nightfall73** [comment]
+1 for expeditions, please

**Comment by phendrena** [comment]
I'd suggest an update to bring things in-line with the current release BUT disallow editing of the specific Expeditions save file.

**Comment by thorgorn** [comment]
Would love an update for this patch

**Comment by goatfungus** [comment]
Version 1.7.4 (just released) should support the Expeditions update. Enjoy
