### ISSUE TITLE
[BUG] json editor 'unexpected end of file' when editing a single-value object

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#365]
When selecting any item from the objects tree, that's a type of single-value, such as **Units** or **Nanites**,  and trying the edit the value, the editor throws 'unexpected end of file'.

**Comment by goatfungus** [comment]
Ah yes, that must have been broken in the companions update, as I was trying to improve the JSON Editor.... I'll look at fixing this soon.
