### ISSUE TITLE
Expedition save file

### ISSUE THREAD

**Issue by FurudeRika** [goatfungus/NMSSaveEditor#368]
The editor seems to have some problem reading expedition save files, it would show like "slot 1 - [EMPTY]"

**Comment by FurudeRika** [comment]
https://gyazo.com/b71fdf8fd6cdadf373ffbf6d4d6ffafb

**Comment by goatfungus** [comment]
Can you please send me a copy of your log file... I'm not getting the same issue.

**Comment by FurudeRika** [comment]
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 12.0.2
[DEBUG] Working Dir: D:\Download
[INFO] Starting Editor...
[DEBUG] Save Path: C:\Users\User\AppData\Roaming\HelloGames\NMS\st_76561198201634439
[DEBUG] Mapping not available: tiH
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[DEBUG] Mem Usage: 537/8569 MB
[DEBUG] Latest version: "1.7.4"
[DEBUG] Current version: "1.7.4"
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Loading saves for Slot 1...
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] No current save file found for Slot 1 - [EMPTY]
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.ao.a(Unknown Source)
[STDERR] 	at nomanssave.Application.p(Unknown Source)
[STDERR] 	at nomanssave.Application.o(Unknown Source)
[STDERR] 	at nomanssave.Application.n(Unknown Source)
[STDERR] 	at nomanssave.C.setSelectedItem(Unknown Source)
[STDERR] 	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:579)
[STDERR] 	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:907)
[STDERR] 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
[STDERR] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
[STDERR] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:551)
[STDERR] 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
[STDERR] 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
[STDERR] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201
[INFO] Version unknown: 7201

**Comment by Bean1415** [comment]
> https://gyazo.com/b71fdf8fd6cdadf373ffbf6d4d6ffafb

I have the same issue

**Comment by liviniumnetwork** [comment]
I also have the exact same problem. The save file for the expeditions game mode doesn't show a save to modify, saying empty, although not, & fails to load.
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/6262563/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
Ok.... I have figured it out and added the new type of save to the editor. Should be ok now (version 1.7.5)

**Comment by Encarnado** [comment]
Don't know if you need this. I have completed the expedition.
Reading save file...
  Slot: Slot 2 - EXPEDITION - Apr 6, 01:16
  Filename: save3.hg
Parsing JSON...
  using name mappings: NMS 3.3
  WARNING: name mapping not found: J<o
  WARNING: name mapping not found: D=h
  WARNING: name mapping not found: CT3
  WARNING: name mapping not found: Vc6
  WARNING: name mapping not found: 8eX
  WARNING: name mapping not found: VOG
  WARNING: name mapping not found: q:;
  WARNING: name mapping not found: x3h
  WARNING: name mapping not found: x5Z
  WARNING: name mapping not found: GcZ
  WARNING: name mapping not found: tV6
  WARNING: name mapping not found: TG<
  WARNING: name mapping not found: ObG
  WARNING: name mapping not found: 7tH
  WARNING: name mapping not found: mTG
  WARNING: name mapping not found: aZF
  WARNING: name mapping not found: 6<9
  WARNING: name mapping not found: a4X
  WARNING: name mapping not found: C6D
  WARNING: name mapping not found: wmu
  WARNING: name mapping not found: Hr:
  WARNING: name mapping not found: Q6s
Finished.

**Comment by JB2021-81** [comment]
Thank you so much GoatFungus, can't wait to play expeditions with some much better weapons/ships. You're the best!

**Comment by Encarnado** [comment]
> Thank you so much GoatFungus, can't wait to play expeditions with some much better weapons/ships. You're the best!

I don't see the need to use the save editor for that, but that's my point of view.
Through the expedition you will earn a class S Explorer ship, a class S alien weapon and a void egg.
Main boring things in this expedition is the grind of units/nanites/di-hydrogen (for frigate fuel/life support gel)/"everybody starting in the same position and most systems surrounding the rendezvous points all discovered"/the annoyance of the excess of bases/save beacons on rendezvous points. The 5th rendezvous point is just terrible.
Hello Games should had disabled building on the rendezvous planets.

**Comment by Rich-1d12** [comment]
Thanks for the update GoatFungus, much appreciated.

**Comment by liviniumnetwork** [comment]
Something that I did to make the expedition a lot easier, when the tool wasn’t working, was first I backed up my save files. Just in case my idea severely messed up & crippled my game. Then using Visual Studio Code I opened up both save files, my first normal mode one that I had completed & had everything I could need, & the second expedition one that I had played legitimately for several hours. I was then able to simply copy everything from in my main file & paste it into my new file. Then simply save & reload quick save. I had everything including my base. However please keep in mind if you do this, for whatever reason though the tool now works again, you will also spawn wherever you left your main character. I had to travel 675thousand light years in game to get back to where you first start the expedition, then another 100 thousand to get to the end of phase one.
