### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by Bean1415** [goatfungus/NMSSaveEditor#369]
![image](https://user-images.githubusercontent.com/81740372/113678731-f7af9800-968c-11eb-9801-9e8ba7dd6454.png)

Can't save changes on Patch 1.7.5 (EXPEDITIONS), I can save as, to another empty save file and it keeps the changes

**Comment by goatfungus** [comment]
That would usually happen if the file is open and locked in another program. If that's the case, shutting down the offending program will do the trick.

**Comment by Bean1415** [comment]
For some reason I still have the issue after restarting my pc

**Comment by goatfungus** [comment]
You might need to run the editor as Administrator, as there might be a permission issue on the file itself.

**Comment by Bean1415** [comment]
it doesnt give me the option to run as administrator 
ive trade every way to run it as so
I can run any other program as administrator

**Comment by Bean1415** [comment]
> You might need to run the editor as Administrator, as there might be a permission issue on the file itself.

Hey issue is fixed, restarted my pc and tried again and it turns out AVG was blocking it the whole time...
