### ISSUE TITLE
Twitch Drops

### ISSUE THREAD

**Issue by Sikksens** [goatfungus/NMSSaveEditor#370]
Hey there,

I missed 2 days of the twitch drops and wanted to know if this tool can be used to obtain the drops that were missed, notably the 2 A-Class fighters?

**Comment by liviniumnetwork** [comment]
Hello,
You can try looking for the ships seed using this website, then replacing your ships seed & saving. It will change your ship to whatever ship you are after.
https://www.nmseeds.club/Seeds/Search

**Comment by liviniumnetwork** [comment]
Or this website too: https://nomansseeds.com/
Hopefully one of these help you.

**Comment by Sikksens** [comment]
Thanks, ya I found the seeds for the ships from day 2-5, just couldn't find the day 1 explorer "Eokai's Prime Inquirer"

Here they are if anyone else is looking for them.
Hoshis HP7 (Fighter) - _0x6FF7793FBC58837_
Nemesis of the Kudama (Fighter) - _0xBCEF59E1A64E28DC_
Ultimate Pride JB2 (Hauler) - _0x9557186C7D37C2EC_
Prime Song JZ4 (Shuttle) - _0x9E58062EEDC436B_
