### ISSUE TITLE
exocraft - unable to extend slot count

### ISSUE THREAD

**Issue by melhiore** [goatfungus/NMSSaveEditor#371]
In any of my exocrafts I am unable to activate additional slots. There is no option in the settings to do so... Can this be looked at please...

**Comment by goatfungus** [comment]
This was locked in the game itself, so allowing you to activate extra slots would cause you to lose items when it reverts back to the default shape. However, you can switch the editor to "Test Mode" in the Edit menu to remove these restrictions if you really want, but I would advise against it.

**Comment by melhiore** [comment]
Nice, wasn't aware of that. Thank you!! I am not going to break things then...
