### ISSUE TITLE
Editor does not populate

### ISSUE THREAD

**Issue by Tarnakk4** [goatfungus/NMSSaveEditor#372]
So, ran into a really odd one I can't find an answer to in the FAQ. When I launch either by the .bat or .jar files, it creates the window and does not fill it. Completely blank. On rare occasion, if I let it sit for 6-8 minutes, it will launch, but generally it creates a blank white screen. When it does come up, it again takes multiple minutes to allow things like selecting the file to use, etc.

I can't find anything on my end causing this, but no one else is reporting it. Java is fully updated. I can't even get the software to run enough to generate a log file.

Does anyone have any idea what might be causing this?

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
