### ISSUE TITLE
It seems the class bonus multiplier did not change after I changed freighter class

### ISSUE THREAD

**Issue by ShanyaoJiang** [goatfungus/NMSSaveEditor#374]
Thank you very much for your work! It is great.

I found the stat did not change when I set my freighter to an upper class. I think the bonus multiplier are the same even I change it to Class S. Please have a check. 

Thank you

**Comment by goatfungus** [comment]
Stats are generated by a procedural function in the game itself, so the editor can't do this. You can change the Hyperdrive stat manually though.
