### ISSUE TITLE
A couple of missing features with the editor.

### ISSUE THREAD

**Issue by X66Herobrine66X** [goatfungus/NMSSaveEditor#375]
Found a couple of bugs and missing features with the editor.

- The editor won't let me change the maneuverability of my ships.
- The editor won't let me install living ship tech and modules on normal ships and vice versa.
- Can't find companion eggs when I search for them in the item adder.

**Comment by devcai** [comment]
1 You can't change maneuverability. It was never a feature. You will need to install a different mod or some tech that actually changes maneuverability in game.

2 I Don't think that was ever a feature either. It was a patched out bug.

3 Pretty sure you can add eggs but you'll probably have to edit them in the json editor.

**Comment by X66Herobrine66X** [comment]
About the living ships, I saw a video where they used a bug to transfer the living ship upgrades to the normal ship. Even if they patched the bug, surely they wouldn't have gone out of their way to make it physically impossible for a living ship upgrade to reside in a normal ship? Couldn't I just copy the json data for my living ships upgrades over to the normal ships data? Like this data:
`			{
				"Type":{
					"InventoryType":"Technology"
				},
				"Id":"^UA_SGUN3#81485",
				"Amount":-1,
				"MaxAmount":100,
				"DamageFactor":0.0,
				"FullyInstalled":true,
				"Index":{
					"X":2,
					"Y":0
				}
			},`

**Comment by JB2021-81** [comment]
One other issue I've had is the Golden Vector Ship will NOT allow me to move 2 items from the general tab to Tech tab, even if I do it in this editor. Also, Whenever I maxed out other ships it shows nearly 10k on every stat, not so with the Vector Ship, Not sure if Hello Games Nerfed that ship on purpose??

**Comment by Fanoo** [comment]
Under function page Discovery,please add the function which can add all tech and all products.
