### ISSUE TITLE
Bug deleting multitools plus newbies ideas

### ISSUE THREAD

**Issue by TychaiosIlithios** [goatfungus/NMSSaveEditor#377]
Hello, great program, very useful. The only real issue I ever once had with it was during total replacement of default multitool with two imported. It showed picture of one of the imported ones but failed to load them and behaved like there was no multitool available. Did not test it fully but do believe this has something to do with deleting multitool that is currently active.

As for ideas to read and ignore
1) Separate tab with checkbox table for rerolling stuff and one reroll button.
Explanation - when I got the taste of scamming for the looks of items, very soon got into the act of standing in freighter hangar, rolling freighter seed, six ship seeds and 3 tool seeds. It would be very convenient if all of that could be done with one button via the mentioned rerolling tab.
2) Starship maneuverability parameter
3) Along with rerolling thing, there could be also clone command for ship and multitool template. I.e. I've been rolling scouts then suddenly want to roll living ships. Currently have to create export file for living ship template then manually import 5-6 times then rename them 1-2-3-4-5-6 for convenience. That could also be automated. Yesss, that's a very lazy feature - cuz many users love and want very lazy features.
Thanks for reading and may timely vaccination be with you.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
