### ISSUE TITLE
This doesn't work for No Man's Sky on the Xbox Gamepass

### ISSUE THREAD

**Issue by zakaturtle** [goatfungus/NMSSaveEditor#378]
I would like for it to work for nms on the gamepass so I don't have to spend weeks gathering quicksilver, so if someone knows how or if there is another one that works for the gamepass please let me know.

**Comment by Daisame** [comment]
My understanding is that the Microsoft Store version of games get protected folders on your game, so it is very hard, if nearly impossible to mod games from the Microsoft store. If you want to mod, you may have to buy and use the Steam version.

**Comment by Novoca1n3** [comment]
NomNom has the ability to edit Xbox Game Pass. Also allows you to Export as JSON and onto Steam. Next version will enable exporting between all platforms.

**Comment by adbowers** [comment]
> I would like for it to work for nms on the gamepass so I don't have to spend weeks gathering quicksilver, so if someone knows how or if there is another one that works for the gamepass please let me know.

You might want to try [ReshadeForUWP](https://github.com/MilkyDeveloper/ReshadeForUWP). I was able to get that to work for a couple of Windows Store games.

**Comment by goatfungus** [comment]
MS Game Pass support has recently been added.
