### ISSUE TITLE
 Error moving items?

### ISSUE THREAD

**Issue by RevoNation** [goatfungus/NMSSaveEditor#379]
I use the 1.7.5 of the save editor. Now I noticed when I want to move something to another place in the expedition score. For all things the 9999 items limit only have to be moved 250 items at a time and the directory with stacks of 250 is thrown away until it is full. is this fault only with me? I use mods, but none that go to the size of the inventory.

I'll try to reinstall the se, but I don't understand why it does that.

It is subsequently possible to set the stack size back to 9999, but it can't be.

**Comment by RevoNation** [comment]
after new istall of the se, he makes the same problem.

**Comment by shaheenfazim** [comment]
I don't know much about this, but I have heard that some particular saves like permadeath stack limit are 250 compared to normal which is 9999, maybe expedition to is like this. If u want 9999 every time u could use trainers like https://flingtrainer.com/trainer/no-mans-sky-trainer/

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
