### ISSUE TITLE
Expeditions 3.40 

### ISSUE THREAD

**Issue by JB2021-81** [goatfungus/NMSSaveEditor#381]
A brand new expedition just launched this morning & a host of bug fixes! 

[https://www.nomanssky.com/2021/05/no-mans-sky-expedition-2/](url)

**Comment by gggg336** [comment]
The expedition just wrapped up with the end of the community mission as well as a new update that came with a new, hand crafted frigate and the frigate tab of the save editor is now broken if you have the new frigate.

**Comment by MrDevlin** [comment]
seconding above:
the new unique frigate breaks the frigate tab (fails to update window correctly) but if you can select another one you can edit it normally in spite of the bugged window

**Comment by Mike-Blackwell** [comment]
There seems to be a new attribute associated with the new "Mass Effect" Frigate that breaks the Frigate table (format) as @MrDevlin suggested one can kind of select other Frigates if you can select them by moving ones cursor around to re paint the table..

**Comment by goatfungus** [comment]
This should be fixed now. :)

**Comment by Mike-Blackwell** [comment]
Brendon, many thanxs for the fix, it now works as before along with that I now also see my two Normandy ships... 

Out of curiosity did you do anything in regards to the Companions or is there a work around? I know their never satisfied!!
