### ISSUE TITLE
Stack size wrong for Living Slime in Cargo inventory

### ISSUE THREAD

**Issue by tanareed** [goatfungus/NMSSaveEditor#383]
The item Living Slime has a 9999 stack size when in the Cargo section of your inventory in a Normal or Expedition save, much the same as its counterparts Residual Goop, Viscous Fluids, Runaway Mould, etc. In an Expedition save, this is set to 250 in the editor, unlike in a Normal save (which has the correct 9999 value).

**Comment by goatfungus** [comment]
This was a problem with Expedition saves, but is now fixed.
