### ISSUE TITLE
Normandy SR1

### ISSUE THREAD

**Issue by Ehren1337** [goatfungus/NMSSaveEditor#384]
Can you add Normandy SR1 to list before it ends on May 31?

**Comment by Lynderyn** [comment]
Normandy JSON pull
{
	"ResourceSeed":[
		true,
		"0xE876443F6A0A28A6"
	],
	"HomeSystemSeed":[
		true,
		"0x0"
	],
	"TimeOfLastIncomeCollection":1621829607,
	"CustomName":"",
	"FrigateClass":{
		"FrigateClass":"Normandy"
	},
	"Race":{
		"AlienRace":"Explorers"
	},
	"TotalNumberOfExpeditions":32,
	"TotalNumberOfSuccessfulEvents":540,
	"TotalNumberOfFailedEvents":1,
	"NumberOfTimesDamaged":1,
	"TraitIDs":[
		"^NORMANDY_1",
		"^NORMANDY_2",
		"^NORMANDY_3",
		"^NORMANDY_4",
		"^NORMANDY_5"
	],
	"Stats":[
		30,
		22,
		7,
		7,
		8,
		0,
		3,
		0,
		0,
		0,
		3
	],
	"RepairsMade":0,
	"DamageTaken":0
}

**Comment by goatfungus** [comment]
Normandy frigate should be available now in version 1.7.6, but it took a bit of work. Enjoy.

**Comment by Ehren1337** [comment]
Thank you so much! 😃😎
