### ISSUE TITLE
SSV Normandy SR1 frigate not defined

### ISSUE THREAD

**Issue by temp-999** [goatfungus/NMSSaveEditor#385]
The new frigate from Expedition 2 is available in my Normal (non-expedition) game. I got it as an expedition award in the Anomaly. I also got the Myth Beacon and the Historiographical Dosimeter. When I use NMSSE and select the Frigate tab it errors out. 

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_271
[DEBUG] Working Dir: C:\Users\<removed>\Desktop\Gaming\No Man's Sky Folder\NMSSaveEditor
[INFO] Starting Editor...
[DEBUG] Save Path: C:\Users\<removed>\AppData\Roaming\HelloGames\NMS\st_<removed>
[DEBUG] Mapping not available: tiH
[DEBUG] Mem Usage: 129/1896 MB
[DEBUG] Latest version: "1.7.5"
[DEBUG] Current version: "1.7.5"
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - NORMAL - May 22, 13:22
[INFO] Filename: save2.hg
[INFO] Parsing JSON...
[INFO] using name mappings: NMS 3.3
[WARNING] name mapping not found: J<o
[WARNING] name mapping not found: Whh
[WARNING] name mapping not found: i1<
[WARNING] name mapping not found: dn2
[WARNING] name mapping not found: RqY
[WARNING] name mapping not found: U6K
[WARNING] name mapping not found: oQl
[INFO] Finished.
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.bA.getValueAt(Unknown Source)
[STDERR] 	at javax.swing.JTable.getValueAt(Unknown Source)
[STDERR] 	at javax.swing.JTable.prepareRenderer(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
[STDERR] 	at javax.swing.plaf.ComponentUI.update(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintComponent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paint(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintChildren(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paint(Unknown Source)
[STDERR] 	at javax.swing.JViewport.paint(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintChildren(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paint(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintChildren(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paint(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintChildren(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paint(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintChildren(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paint(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintChildren(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paint(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager.paint(Unknown Source)
[STDERR] 	at javax.swing.JComponent._paintImmediately(Unknown Source)
[STDERR] 	at javax.swing.JComponent.paintImmediately(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager$4.run(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager.access$1200(Unknown Source)
[STDERR] 	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
[STDERR] 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by goatfungus** [comment]
Can you please post a copy of the frigate JSON from the JSON Editor?

**Comment by goatfungus** [comment]
Normandy frigate should be available now in version 1.7.6, though I am still working on some of the name mappings.

**Comment by temp-999** [comment]
Thank you! 

I'll close out my request as Devilin-Pixy's list is much more encompassing.
