### ISSUE TITLE
3.42 Content Missing

### ISSUE THREAD

**Issue by Lynderyn** [goatfungus/NMSSaveEditor#388]
Multiple items added between the 1.75 and 3.42 update appear to be missing.  This includes the Normandy and some of the items received while hunting for the normandy.

**Comment by Fevix** [comment]
Of note, it seems the Frigates menu fails to load entirely (tab will light up, but previous tab remains visible and interactable) when loading a save that has the Normandy.

**Comment by goatfungus** [comment]
Can you please post a copy of the FleetFrigates section of your save file from the JSON Editor?

**Comment by goatfungus** [comment]
Normandy frigate should be available now in version 1.7.6, though I am still working on some of the name mappings.
