### ISSUE TITLE
Can't find the option to install some of the recipes I can learn

### ISSUE THREAD

**Issue by lofblad** [goatfungus/NMSSaveEditor#39]
I added the recipes for upgrades I found in the technologies list under milestones, but I can't seem to be able to build them in game. They don't appear under either product or technology when I try to build them.

**Comment by goatfungus** [comment]
Procedural technology can't be built, they can only be purchased from vendors. The editor is a bit misleading here as it shows all possible technology in the list, including ones that cannot be learned.
