### ISSUE TITLE
Can't open jar file and .bat files do nothing

### ISSUE THREAD

**Issue by ratjohnson** [goatfungus/NMSSaveEditor#391]
Running the .jar with java.exe opens a black window quickly and closes it. I've tried this with the latest java build and java build 8 update 251. The .bat file also does the same thing where it opens a small black window and then closes it. I've reinstalled java three times and nothing seems to be working. I've looked over the readme several time and have followed the instructions, but the gui never opens.

**Comment by goatfungus** [comment]
If this still persists, open another ticket with a copy of your log file.
