### ISSUE TITLE
In 1.7.6, saving a JSON edit of an Expedition two save file doesn't complete

### ISSUE THREAD

**Issue by tdacon** [goatfungus/NMSSaveEditor#393]
I opened in NMSSE an expedition two (Beachhead) save file after it had been converted from expedition mode to normal mode. For any edit of the raw JSON, no matter how insignificant, the save did not complete: I clicked the X to close the editor dialog, got the confirmation dialog and replied Yes. Ordinarily the editor dialog closes but it stayed up after replying Yes, and I could not continue until I'd tried it again and replied No. And of course the edits were not saved.

The save worked correctly on any other file I tried to edit, including an expedition one save file that had been converted much earlier.

**Comment by goatfungus** [comment]
Strange.... can you take a look at the log file and see if it mentions an error?
It may be a problem with the format in the new NMS version.

**Comment by tdacon** [comment]
Oops, forgot the mf file (attached)

Tom

________________________________

**Comment by goatfungus** [comment]
This should be fixed in all Expedition saves from version 1.9+.
