### ISSUE TITLE
Companions UI

### ISSUE THREAD

**Issue by Paddymancer** [goatfungus/NMSSaveEditor#397]
Great work. Just curious will we be seeing a UI for companions in the future? I've poked around the JSON and saw some segments pertaining to what I think may be the pets. Is it actually possible?

**Comment by DaVyper** [comment]
Under PlayerStateData there is Pets and Eggs sections, pretty easy to edit and even do custom pets once you know what parts/sub-parts/accessories are available for them.

**Comment by theunsfvo** [comment]
I was just about to ask if there will be a UI section for companions, I think it will be used even more than the ship import/export feature ;)

**Comment by DaVyper** [comment]
if you want to backup and restore pets and a lot of other things:   [NMS Collections Backup Restore and Sharing Tool](https://www.nexusmods.com/nomanssky/mods/1879)

**Comment by theunsfvo** [comment]
> if you want to backup and restore pets and a lot of other things: [NMS Collections Backup Restore and Sharing Tool](https://www.nexusmods.com/nomanssky/mods/1879)

Thanks, I'll try it, but prefer the Save Editor you guys did... are there plans to add companions?

**Comment by DaVyper** [comment]
Don't know - I'm not the Developer, just a User like you.

**Comment by goatfungus** [comment]
This feature has been added to version 1.8.7.
