### ISSUE TITLE
"There was an error saving the file"

### ISSUE THREAD

**Issue by OGTrumpetDaddy** [goatfungus/NMSSaveEditor#398]
Hello,
I recently changed from an HDD to an SSD and had my game saved in the steam cloud during the switch. Upon loading it up on the new drive after reinstalling it. Every time I try to edit that save and click save changes it spits out, "There was an error saving the file"

**Comment by dalehere** [comment]
I've been getting the "There was an error saving the file" message for many months and versions now.  The editor worked for me a long time ago though.  Updating Java and trying 64-bit (versus 32-bit) didn't help.

**Comment by kristisbeach** [comment]
I'm having the same issue.

**Comment by Aznafing** [comment]
Hello i have the same issue with the new version of the save editor how to fix it ?
Thanks :)

**Comment by LadyAthena1** [comment]
I had this issue as well, couldn't figure it out. THen I turned off my anti virus.. Have you tried that?

**Comment by Za-Warudo** [comment]
Same issue. Newest version, Defender Real-Time protection is off, save folder is NOT set to read-only.

Relevant portion of the log:

> Formatting JSON...
> Creating game slot...
>   using name mappings: NMS 4.0 (savegame)
> Loading saves for Slot 1...
> WARNING: Cannot load backup.1671448852032.zip
> WARNING: Cannot load backup.1671448862110.zip
> WARNING: Cannot load backup.1671448881780.zip
> Finished.
> Save file deleted from storage: save.hg
> Formatting JSON...
> ERROR: Could not write save file: save.hg

**Comment by goatfungus** [comment]
Cleaning up.
