### ISSUE TITLE
[Feature request] Analysis visor upgrades

### ISSUE THREAD

**Issue by DarkPoke** [goatfungus/NMSSaveEditor#40]
So, I have been wanting to add the analysis visor upgrades to my character, but the drop down on the editor only has the single analysis visor which is the module, not the upgrade for said module. They do share the same name, and I am wondering if you could add it? 
![f6f1dc198af36f5d041c47934ac3b243](https://user-images.githubusercontent.com/39809832/43485447-1ffcf68e-94c6-11e8-8a37-e85d00e1e1ec.png)
As you see here, they share the same name, and the ones currently what I have are the ones I bought in game.

**Comment by goatfungus** [comment]
See #7 

Procedural technology such as this has it's name automatically generated by a special name generator function in-game. I have not yet found this function, so can't replicate it in the editor yet. For now it just uses the default names.
