### ISSUE TITLE
Feature Request: Expandable Exocraft Slots

### ISSUE THREAD

**Issue by XargonX19** [goatfungus/NMSSaveEditor#403]
Right now we can't increase the size of our exocraft slots, but there are mods out there that allow this and it would be a cool feature to add to the save editor.  

See https://www.nexusmods.com/nomanssky/mods/1691?tab=posts&BH=0 for an example

**Comment by atlantisking1985** [comment]
You can; just turn safe mode off; or edit it into the raw json.
That said, you'll need a mod anyway to keep the slots there once the save is loaded in game; as the game resets it unless a mod is on that prevents that.

**Comment by XargonX19** [comment]
That makes sense!  Thank you!
