### ISSUE TITLE
Editor not working with Frontiers

### ISSUE THREAD

**Issue by SparkFoxx** [goatfungus/NMSSaveEditor#404]
Since frontiers came out, the editor won't even load the save file anymore, please fix.

**Comment by justnice980** [comment]
Can confirm. Save can be found, but all tabs are greyed out and not clickable.

**Comment by HansWestra** [comment]
Can confirm, most like has to do with the fact that update increased number of save slots to 15,
So editor probably has an issue finding the saves properly in the proper slots.

**Comment by baldrs** [comment]
Confirmed. Wanted to unlock all "legacy structures" that I didn't unlock before Frontiers came out(who would have thought they would deprecate them), but it does not open the save file.

**Comment by jrcastine** [comment]
Be patient everyone, the update just dropped for PC today.  It's going to take some time for this application to be updated.

**Comment by Mike-Blackwell** [comment]
Agree with jrcastine, it just dropped (change is hard) for those of us who use the app daily (for base builds) I for one can/will wait. 

Brendon, is there anything the user committee can help in your endeavors?

**Comment by alzorglub** [comment]
The save files now seem to be zipped in some way, and there is a lot of work to do as Frontier is a big update that brings a lot of new content, so it may take some time.
Let's encourage the author for the hard work ahead.

**Comment by areithropos** [comment]
they made changes to the save file as mentioned in the patch notes.

**Comment by Studiedfiber** [comment]
> Can confirm. Save can be found, but all tabs are greyed out and not clickable.

Same here.

**Comment by Elmarts** [comment]
Just ran into this issue also.  Thankful for all the work done to date, and am willing to happily await an update.

**Comment by Mike-Blackwell** [comment]
@Studiedfiber pray tell where did you found the save files? and what format is it .zip or something else?

**Comment by Fletcherea** [comment]
The only reason I still play nms is this editor, hope it gets up and running again!

**Comment by Elmarts** [comment]
/mnt/b25ddf96-5606-44a0-8a01-9fdcc846a5cf/steam 
games/steamapps/compatdata/275850/pfx/drive_c/users/steamuser/Application 
Data/HelloGames/NMS/st_76561198019089164

**Comment by Elmarts** [comment]
I have started to play the entire game (story lines) in Creative for the 
same implied reason - avoiding grinding and unnecessary stress :)

**Comment by DesertEagleF** [comment]
The official update notes (https://www.nomanssky.com/frontiers-update/) has said "new save system changes the format of save data", so the Editor won't work until it updates, or you can use old save files automatically backed, they're under the "strbackup" folder as the notes said.

**Comment by grahamhague** [comment]
Since the Frontiers update, I have encountered a couple of major bugs with the game. HG will need to sort them out, which may impact any changes to the Editor, so getting it working again may take a while. Nevertheless, hopefully the HG bugs, and any fixes for them, will not cause the editor any future problems.

**Comment by KayPT** [comment]
> 
> 
> The official update notes (https://www.nomanssky.com/frontiers-update/) has said "new save system changes the format of save data", so the Editor won't work until it updates, or you can use old save files automatically backed, they're under the "strbackup" folder as the notes said.

This is correct, the save files changed from being "plain text" to a different format that seems difficult to read, the editor might take a long time to update unless @goatfungus is already trying.

We'll just have to wait.

**Comment by Mike-Blackwell** [comment]
Slow question based on @DesertEagleF comment, I would argue that we can still use the editor on the strbackup files could we then place the updated file back into the normal savefile folder to let the game convert the file to the new format... the one drawback is that the new building parts would not be available, I know it sounds convoluted but it might be a workaround until a better solution is available.

@grahamhague you make mention of encountering a couple of major bugs with the game, such as?
1) lights that previously were lite in prior releases now do not shine with power applied, also unable to attach power wire(s) to newly placed lights, 
2) Stacked Glass Cube rooms use to expand into larger open area, now the upper glass cube and curved Roof modules has its flooring showing to the lower glass cube room, 
3) Mechanical Garage Door are no longer work.
any more?

**Comment by baldrs** [comment]
I've edited backed up file and then saved it into a new slot and moved it
to normal save directory. It worked perfectly.

**Comment by Break-Winder** [comment]
So looking for a temporary solution until someone figures out the new file format which seems to be some kind of binary stream file I have had some success with manual editing.

Historically I mostly use the editor to occasionally bump up values for Units, and Nanites and more frequently use it when ship hunting to grab and swap the starship seeds to change my ship model without having to rebuild the thing in game.

Obviously back up your save files before you mess with this. I made 1 small editing error the first time I did this and the game just freezes, so you've been warned.

Some of the save file is in regular ASCII including credits, nanites, ship names, and ship seeds (mostly).  This works much easier if you know the current value you're trying to replace and can search for it.  I was able to modify credits and nanites with no issue and switch my ship seed.  The latter is a little trickier as you're looking for the seed without the "0x". For example, if my current fighter seed is "0x5624A889C3795ED1" and i want to replace it with "0x6B48A3DDD75D11EE" first search for your ship name and you'll see the seed number without the "0x" a little below it (or just search). Replace "5624A889C3795ED1" with "6B48A3DDD75D11EE", save and reload and you should be good to go.  

I haven't tried this with freighters yet but may later.

This should get me by for the time being. The only other thing I occasionally do is fill my stack of Emergency Broadcast Beacons but I can live without that for now.

**Comment by grahamhague** [comment]
Issues with NMS after Frontiers that I have encountered (not really a subject for here, but I am answering Mike Blackwell question):

1) Fleet missions when complete, I debrief the commander and get the rewards, but the fleet is still flagged as active, so I cannot send it on any new missions.
2) Walking around the settlement, I occasionally get bumped into the Overseer Office in a position I cannot move from, and have to reload the last save game. Well, twice!
3) I completed a Nexus mission and on entering the Anomaly to get the reward, the ship suddenly bounced up in the air and got stuck in the roof, from where I could do nothing! Again, I had to abandon the Nexus mission and reload a previous save file. This may not be a Frontiers issue, of course, but I have never had it before.

I had a couple of minor things, such as renaming the settlement didn't appear in the space station transporter list at first.

As I say, these are not relevant to the NMS editor unless HG fixing them changes the save game construction, but I shouldn't think it would.

**Comment by Mike-Blackwell** [comment]
@grahamhague thanxs for the comeback, I trust you've sent HG an issue report with your observations?

Just to level set with the new file structure...

a) The normal Frontiers Game fileSave Directory is C:\Users\USERNAME\AppData\Roaming\HelloGames\NMS\st_123456789 that contain the **New** file format (gets created once you've first play that particular gamesave in Frontiers)
b) The pre- Frontiers Game filesave is C:\Users\USERNAME\AppData\Roaming\HelloGames\NMS\st_123456789\strbackup that contain JSON file format

Did I miss anything are there other files elsewhere?

@Break-Winder thank-you for sharing, I'm trying to understand "Some of the save file is in regular ASCII including credits, nanites, ship names, and ship seeds (mostly)" which file are you implying and what editor are you using to manipulate and save the updates with?

**Comment by Mike-Blackwell** [comment]
Well, I just proved (to myself) I had originally played my PERMADEATH gamesave yesterday which got converted to the new gamesave format, I took my strback-up Save 7 & 8 (my PERMADEATH pre-Frontier) gamesave) and started my Frontier NMS again which came up with my Pre-Frontier gamesave so it does work. As previously stated it doesn't allow for any Frontier unique progress but if your doing builds it is a workaround until a better solution has been implemented.

**Comment by DarkOakMetarex** [comment]
Yep we just need to wait patiently.

**Comment by goatfungus** [comment]
Working on it.... looks like the save structure changed, so I need time to figure it out.

**Comment by tuvitor** [comment]
@goatfungus thanks for staying on top of it. This tool has been an essential help in my No Man's Sky adventures.

**Comment by Yufukuai** [comment]
> So looking for a temporary solution until someone figures out the new file format which seems to be some kind of binary stream file I have had some success with manual editing.
> 
> Historically I mostly use the editor to occasionally bump up values for Units, and Nanites and more frequently use it when ship hunting to grab and swap the starship seeds to change my ship model without having to rebuild the thing in game.
> 
> Obviously back up your save files before you mess with this. I made 1 small editing error the first time I did this and the game just freezes, so you've been warned.
> 
> Some of the save file is in regular ASCII including credits, nanites, ship names, and ship seeds (mostly). This works much easier if you know the current value you're trying to replace and can search for it. I was able to modify credits and nanites with no issue and switch my ship seed. The latter is a little trickier as you're looking for the seed without the "0x". For example, if my current fighter seed is "0x5624A889C3795ED1" and i want to replace it with "0x6B48A3DDD75D11EE" first search for your ship name and you'll see the seed number without the "0x" a little below it (or just search). Replace "5624A889C3795ED1" with "6B48A3DDD75D11EE", save and reload and you should be good to go.
> 
> I haven't tried this with freighters yet but may later.
> 
> This should get me by for the time being. The only other thing I occasionally do is fill my stack of Emergency Broadcast Beacons but I can live without that for now.

I have discovered that editing units and nanites values causes the game to load an older save on my end, I am relating it to something to do with higher values that the game can't handle or it's not expecting. Or probably I am replacing or moving a value that I shouldn't and it messes up with the save. Could you help me with this? I can't figure out why this happens

**Comment by Break-Winder** [comment]
> @Mike-Blackwell thank-you for sharing, I'm trying to understand "Some of the save file is in regular ASCII including credits, nanites, ship names, and ship seeds (mostly)" which file are you implying and what editor are you using to manipulate and save the updates with?

I was working with the quicksave file for save slot 1 so save.hg. I used Notepad ++

> @Yufukuai I have discovered that editing units and nanites values causes the game to load an older save on my end, I am relating it to something to do with higher values that the game can't handle or it's not expecting. Or probably I am replacing or moving a value that I shouldn't and it messes up with the save. Could you help me with this? I can't figure out why this happens

What were you trying to edit the savegame with? the NMSSaveEditor? That won't work it'll revert back to an older backup zip and nothing you change will be loaded in the game.  I modified my quick save file for slot 1 (save.hg) using Notepad++.  

A little more detail:

First i went in-game and looked at my current value, for example nanites, which was say 101301. I then opened the save file in NP++ and searched for that value, which only appeared once, and modified it to 102301, just as a test, saved the file and reloaded my save in-game and I did indeed have 102,301 nanites.

A couple things to note, I have not tested replacing values that are different in length so say if i had 1000 nanites and I edited it to be 100000 nanites. I'm not sure if that would mess up the file structure or not but I will test it and report back.  

Be aware the game has upper limits on on these values
Units and Nanites can only go as high as 4,294,967,295 so i would avoid trying to set it higher than that as I'm not sure what will happen.

I mentioned i ran into trouble once and that was just my poor old eyes not paying attention to the length of the seed I was editing.  Starship seeds are for the most part 16 characters in length (excluding the 0x) and I accidentally deleted the character after the seed in the file when replacing it.  When i tried to load the save game the game just hard froze, luckily i realized my error and corrected it.  I know there are some older starship seeds that are shorter than 16 characters, I would imagine replacing the 16 digit one in the file for your ship with one that's shorter and vice-versa would be ok but I have not tested this.

Hope that clarifies things a bit. I know this is janky but like i said it allows me to continue to do my business as usual activates in game, for the most part anyway while we wait for someone much smarter than I to unravel this mess and update the editor :)

I'm going to look at trying to figure out how to modify or "refill" item stacks in my inventory as that's the only other thing I occasionally do, it looks harder though because while I can find the item tag in plain text in the file I cannot yet determine where the quantity information is stored, if it's in binary it'll be hard to impossible to do.

**Comment by Yufukuai** [comment]
> > @Mike-Blackwell thank-you for sharing, I'm trying to understand "Some of the save file is in regular ASCII including credits, nanites, ship names, and ship seeds (mostly)" which file are you implying and what editor are you using to manipulate and save the updates with?
> 
> 
> 
> I was working with the quicksave file for save slot 1 so save.hg. I used Notepad ++
> 
> 
> 
> > @Yufukuai I have discovered that editing units and nanites values causes the game to load an older save on my end, I am relating it to something to do with higher values that the game can't handle or it's not expecting. Or probably I am replacing or moving a value that I shouldn't and it messes up with the save. Could you help me with this? I can't figure out why this happens
> 
> 
> 
> What were you trying to edit the savegame with? the NMSSaveEditor? That won't work it'll revert back to an older backup zip and nothing you change will be loaded in the game.  I modified my quick save file for slot 1 (save.hg) using Notepad++.  
> 
> 
> 
> A little more detail:
> 
> 
> 
> First i went in-game and looked at my current value, for example nanites, which was say 101301. I then opened the save file in NP++ and searched for that value, which only appeared once, and modified it to 102301, just as a test, saved the file and reloaded my save in-game and I did indeed have 102,301 nanites.
> 
> 
> 
> A couple things to note, I have not tested replacing values that are different in length so say if i had 1000 nanites and I edited it to be 100000 nanites. I'm not sure if that would mess up the file structure or not but I will test it and report back.  
> 
> 
> 
> Be aware the game has upper limits on on these values
> 
> Units and Nanites can only go as high as 4,294,967,295 so i would avoid trying to set it higher than that as I'm not sure what will happen.
> 
> 
> 
> I mentioned i ran into trouble once and that was just my poor old eyes not paying attention to the length of the seed I was editing.  Starship seeds are for the most part 16 characters in length (excluding the 0x) and I accidentally deleted the character after the seed in the file when replacing it.  When i tried to load the save game the game just hard froze, luckily i realized my error and corrected it.  I know there are some older starship seeds that are shorter than 16 characters, I would imagine replacing the 16 digit one in the file for your ship with one that's shorter and vice-versa would be ok but I have not tested this.
> 
> 
> 
> Hope that clarifies things a bit. I know this is janky but like i said it allows me to continue to do my business as usual activates in game, for the most part anyway while we wait for someone much smarter than I to unravel this mess and update the editor :)
> 
> 
> 
> I'm going to look at trying to figure out how to modify or "refill" item stacks in my inventory as that's the only other thing I occasionally do, it looks harder though because while I can find the item tag in plain text in the file I cannot yet determine where the quantity information is stored, if it's in binary it'll be hard to impossible to do.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Yeah I did it with NP++ and changing its length messes up the save game enough to make the game not even load it.

**Comment by Break-Winder** [comment]
> Yeah I did it with NP++ and changing its length messes up the save game enough to make the game not even load it.

I guess you could just sub out all 9's and then increment up to the next decimal in the game, save, rinse and repeat.

**Comment by goatfungus** [comment]
Update: looks like HG have opted to work with a proprietary compression algorithm, as I can't seem to find anything that matches the new file format. I have a basic understanding of how it works now but there are still parts missing, so I doubt I'll find a solution tonight. Might try again tomorrow.

**Comment by amik71** [comment]
There are references to lz4 in the executable file, maybe it is it or something based on it?

**Comment by alphawolf918** [comment]
@goatfungus Thank you for all of your hard work.

**Comment by goatfungus** [comment]
> There are references to lz4 in the executable file, maybe it is it or something based on it?

Yeah, I thought that too. Was the first place I looked, but it doesn't appear to comply with the standard. Will keep trying.

**Comment by iBlinde** [comment]
Managed to get my Game Pass save to update through NMS game... Nothing lost, all ships and inventories/bases/etc. edited previous to NMS game update still there.
Might be a way to compare and identify game save parts too? 

Might workaround for others maybe?? 

Get into the WGS folder, you might want to backup the contents before messing about, 

Remove the folders by date to before the frontiers update, 

Load up your favourite NMS save editor and let it find the latest save (the date you stopped deleting upto,) and do whatever you need for now. 

Save, 

Run NMS game. 

Hope someone finds this helpful.?

**Comment by goatfungus** [comment]
Well, after messing around with this all day without any tangible results, I've decided to take a break for now.

I have sent an email to HG to see if they will disclose any information on the compression used, but not too hopeful as this likely comes under their own intellectual property. No harm in trying though :)

**Comment by goatfungus** [comment]
Well, I've made a breakthrough, and it looks like a solution for the compression will be fairly simple to implement. The only thing left to work out is the checksum/manifest file which also had a format change. I'm hoping I'll have something ready in the next few days. :)

**Comment by vvvv21** [comment]
> 嗯，我已经取得了突破，看起来压缩的解决方案实施起来相当简单。唯一需要解决的是校验和/清单文件，它也有格式更改。我希望我能在接下来的几天里准备好东西。:)

i love u ,baby

**Comment by SparkFoxx** [comment]
> Well, I've made a breakthrough, and it looks like a solution for the compression will be fairly simple to implement. The only thing left to work out is the checksum/manifest file which also had a format change. I'm hoping I'll have something ready in the next few days. :)

Thanks man, you're the best!

**Comment by Belui123** [comment]
> Что ж, я совершил прорыв, и похоже, что решение для сжатия будет довольно просто реализовать. Единственное, что осталось доработать, - это файл контрольной суммы / манифеста, в котором также был изменен формат. Я надеюсь, что в ближайшие несколько дней у меня что-нибудь будет готово. :)

Will wait. The faster, the better

**Comment by philou-felin** [comment]
> Will wait. The faster, the better

I think you meant "take your time". ;) ;)

**Comment by Studiedfiber** [comment]
Thank you so much for your great work, i really can't play NMS without this program it is essential to my adventures :)

**Comment by Mike-Blackwell** [comment]
Brendon, side question once you've made your first working Frontiers SaveEditor app will we still have edit JSON capability?

**Comment by YegFoxx** [comment]
https://www.nexusmods.com/nomanssky/mods/1566
maybe it will somehow help.

**Comment by iBlinde** [comment]
> https://www.nexusmods.com/nomanssky/mods/1566
> maybe it will somehow help.

This is what I used to get my XB Game Pass save working again, after deleting Frontiers saves and resaving a pre-frontiers save to update the timestamp.   Then NMS just did its thing.

**Comment by Mike-Blackwell** [comment]
So if one understands @YegFoxx and @iBlinde, the  NOMNOM app (for Xbox PC files) hasn't solved the new Frontiers format as of yet and currently only working on pre-frontiers files only?

**Comment by Devilin-Pixy** [comment]
@goatfungus You may want to check some discussion in the NMS - Creative & Sharing Hub (Discord)
https://discord.gg/sDtV6DQV
Check the #savegame-edit channel where user Ice#1024 shared some Python code to get things to work
Message link: <https://discord.com/channels/627059745160953866/720411261019619399/883074047540359278>

Code:

```
import sys
import struct
import lz4.block as lb

savefile = sys.argv[1]

with open(savefile, 'rb') as save:
    with open(savefile[:-3]+'_1.hg', 'wb') as opt:
        while save.read(4) == b'\xE5\xA1\xED\xFE':
            block_size = struct.unpack('i',save.read(4))[0]
            dest_size = struct.unpack('i',save.read(4))[0]
            save.read(4)
            decom = lb.decompress(save.read(block_size), uncompressed_size=dest_size)
            print('block_size:', block_size, 'dest_size:', dest_size, 'actual_size:', len(decom))
            opt.write(decom)
        if save.read(1):
            save.seek(0)
            while (block:=save.read(524288)):
                opt.write(b'\xE5\xA1\xED\xFE')
                com = lb.compress(block, store_size=False)
                opt.write(struct.pack('i', len(com)))
                opt.write(struct.pack('i', len(block)))
                opt.write(b'\x00'*4)
                opt.write(com)
```

Doesn't quite deal with the Steam Metadata File though.

Good luck!

**Comment by iBlinde** [comment]
I jumped onto different save editors to try backup of my saves, then fell upon the only solution I could get to work..I don't think it matters which editor is used.
But, no to your question.. Nomnom could open my Frontiers save, it's just thatfor me Frontiers wouldn't accept the save from NMS XBox Frontiers, but NMS PC Frontiers happily took my pre-update save (even though it's been edited and buggered with).  I had to delete the Frontiers saves to get it to work though.
Hope this answers your question.

**Comment by Mike-Blackwell** [comment]
I too have used NOMNOM for my Xbox PC saves, I just installed the latest and it focused on my Steam (PC) Files and was able to open my PERMADEATH SaveFile (it was the only Frontiers converted file) with no issues so it seems that @zencq (Christian Englehardt) was able to solve the new format...

**Comment by Raylativ** [comment]
3.6.0.18-alpha.18 -- 3 hours ago
This one is only for compatibility with the new save streaming system!
No new features or a database update yet. This will be added in the next planned release
https://github.com/cengelha/NomNom/releases

Migration from xBox gamepass to Steam 15 minutes ago worked perfect. :)

maybe it will somehow help

**Comment by Bujiko** [comment]
Been trying for days. Just joined the discussions. This worked

**Comment by Bujiko** [comment]
> 
> 
> 3.6.0.18-alpha.18 -- 3 hours ago
> This one is only for compatibility with the new save streaming system!
> No new features or a database update yet. This will be added in the next planned release
> https://github.com/cengelha/NomNom/releases
> 
> Migration from xbox gamepass to steam 15 minutes ago worked perfect. :)
> 
> maybe it will somehow help

Been trying for days. Just joined the discussions. This worked

**Comment by Shyressa** [comment]
NomNom seemed to work fine.. but not as easy to use as Goat's .. so I am happy to wait for him to get his fixed if i wanna do any editing!

**Comment by Mike-Blackwell** [comment]
I'll second that one and his JSON editor works....

**Comment by Alidar78** [comment]
> 
> 
> Well, I've made a breakthrough, and it looks like a solution for the compression will be fairly simple to implement. The only thing left to work out is the checksum/manifest file which also had a format change. I'm hoping I'll have something ready in the next few days. :)

Any luck?

**Comment by bdew** [comment]
Here's my implementation of decompression for the new format in TS, shouldn't be too hard to port to java -  https://gist.github.com/bdew/69252923b4abdffd5b825b70756a5800

**Comment by Alpha-Obeisance** [comment]
> Well, I've made a breakthrough, and it looks like a solution for the compression will be fairly simple to implement. The only thing left to work out is the checksum/manifest file which also had a format change. I'm hoping I'll have something ready in the next few days. :)

Folks like you are pretty dang inspiring. I'm just a keyboard hamster; but I'm reading these comments and its only taken you a few days to figure all this out. That's crazy to me. I created an account just to thank you for motivating me to keep learning. And to thank you for this software. I really only use it for quick silver edits as I generally play alone and just don't have the time to grind out the quicksilver. 

I appreciate you. Fantastic work.

**Comment by cengelha** [comment]
> NomNom seemed to work fine.. but not as easy to use as Goat's .. so I am happy to wait for him to get his fixed if i wanna do any editing!

It's still in alpha and will be improve in the future :)

> I'll second that one and his has a working JSON editor....

NomNom has one too. Just not that nice tree on the left (yet).

@goatfungus If you need help with something let me know!

**Comment by goatfungus** [comment]
Nearly there, I've sorted out the manifest data now. I'm going to spend some time making sure that older saves and recently upgraded ones will produce the right output, and there are a few optimizations i want to do as well. It looks like this new save format (incl. manifests) is a big improvement to what was there before.

**Comment by Trigger94** [comment]
> Nearly there, I've sorted out the manifest data now. I'm going to spend some time making sure that older saves and recently upgraded ones will produce the right output, and there are a few optimizations i want to do as well. It looks like this new save format (incl. manifests) is a big improvement to what was there before.

That's great to hear, thanks for your work so far!
 
Is there any chance that you'll add settlement editing options in the future?

**Comment by Vypir** [comment]
> Nearly there, I've sorted out the manifest data now. I'm going to spend some time making sure that older saves and recently upgraded ones will produce the right output, and there are a few optimizations i want to do as well. It looks like this new save format (incl. manifests) is a big improvement to what was there before.

Thanks mate, let us know if we can help with testing.

**Comment by LadyAthena1** [comment]
> 
> 
> Nearly there, I've sorted out the manifest data now. I'm going to spend some time making sure that older saves and recently upgraded ones will produce the right output, and there are a few optimizations i want to do as well. It looks like this new save format (incl. manifests) is a big improvement to what was there before.

I just want to say thank you for all your hard work. I have been using this save editor for a very long time now, over a year. I made this account specifically to say thank you. (along with a few other people making stuff on github).

**Comment by Vypir** [comment]
> > Nearly there, I've sorted out the manifest data now. I'm going to spend some time making sure that older saves and recently upgraded ones will produce the right output, and there are a few optimizations i want to do as well. It looks like this new save format (incl. manifests) is a big improvement to what was there before.
> 
> I just want to say thank you for all your hard work. I have been using this save editor for a very long time now, over a year. I made this account specifically to say thank you. (along with a few other people making stuff on github).

Same, I also donated to his patreon page. :)  This editor is why I enjoy replaying NMS, so i don't have to do the grind again.

**Comment by goatfungus** [comment]
Update 1.8.0 should now be able to decompress the new save files. Enjoy.

**Comment by chrislet** [comment]
Confirmed works for me!

**Comment by Vypir** [comment]
> Update 1.8.0 should now be able to decompress the new save files. Enjoy.

Works great! Thanks mate!  You are a life saver!

**Comment by runlykhel** [comment]
thanks a bunch mate=)

**Comment by Mike-Blackwell** [comment]
Brendon, I too have confirmed that I was able to open my Frontier Saved PERMADEATH file with no issue(s) to note of yet... I also was able to access my JSON file with no noted issue(s). You Da Man! many thanxs from your user committee in your effort to solving the Frontiers update...

**Comment by Studiedfiber** [comment]
Thanks a lot goatfungus! your a life saver

**Comment by Break-Winder** [comment]
> Update 1.8.0 should now be able to decompress the new save files. Enjoy.

Amazing work, thanks for all your hard work.  I've been using this for years and it occurs to me that I'd like to donate to the cause if you accept that kind of thing. You more than deserve it!

**Comment by alzorglub** [comment]
> 
> 
> Update 1.8.0 should now be able to decompress the new save files. Enjoy.

Thanks ! You are the best 🥇

**Comment by Elmarts** [comment]
Sadly, the JSON editor seems to fail for me - I get "Error on line #1: 
unexpected end of file" as soon as I try to close the edit window.  To 
get out, I have to say No to changing the JSON file.  Everything else 
works fine though.  BTW, I'm running Creative mode in Steam under Linux 
Mint 19.3 Mate desktop in case that matters, although it happens in 
Regular mode as well.  In any case, other than not being able to adjust 
my units or quicksilver, I'm delighted with this editor.

-Elmar

**Comment by RealSkyMaster** [comment]
Thanks for the quick implementation of the update.
Unfortunately, the Base Info does not work in version 1.8.0, is that already known?

**Comment by justnice980** [comment]
> Thanks for the quick implementation of the update.
> Unfortunately, the Base Info does not work in version 1.8.0, is that already known?

I was just going to comment this. Base functions seem to be broken with the new update.

**Comment by Vypir** [comment]
> > Update 1.8.0 should now be able to decompress the new save files. Enjoy.
> 
> Amazing work, thanks for all your hard work. I've been using this for years and it occurs to me that I'd like to donate to the cause if you accept that kind of thing. You more than deserve it!

https://www.patreon.com/goatfungus

**Comment by Mike-Blackwell** [comment]
> Thanks for the quick implementation of the update.
> Unfortunately, the Base Info does not work in version 1.8.0, is that already known?

@RealSkyMaster the "Edit Raw JSON" option works, but your correct the "Bases & Storage" Base Info: tab seems to be barren of data  (not that I've used it much).

**Comment by Belui123** [comment]
> Update 1.8.0 should now be able to decompress the new save files. Enjoy.

Thanks ! You are the best. Can you tell me how to increase the stack size?

**Comment by goatfungus** [comment]
Stack sizes are controlled by the game itself, so you'll need a mod for that.
