### ISSUE TITLE
NMSSaveEditor not working with Frontiers! 

### ISSUE THREAD

**Issue by Studiedfiber** [goatfungus/NMSSaveEditor#405]
This is not working anymore since the update, i hope you update it, its my main program to use.

**Comment by Pontiac76** [comment]
Ticket already opened.  Look at #404

**Comment by Darksidjuice** [comment]
Hello, help us with the new update Frontier ! It doesn't work anymore !

**Comment by Darksidjuice** [comment]
But thanks a lot for your work, you're a boss !

**Comment by prodigyrick** [comment]
Love this program but they are all correct. Dang, need it asap!

**Comment by goatfungus** [comment]
Working on it.... looks like the save structure changed, so I need time to figure it out.

**Comment by JB2021-81** [comment]
> Working on it.... looks like the save structure changed, so I need time to figure it out.

Thank you very much I do appreciate your effort in getting the save editor fixed..￼

**Comment by JB2021-81** [comment]
I'm just wondering is there a way to wipe out the settlement debt quicker so I can get past all that and start building a colony that I can be proud of?￼ some of my colonies I have started up have an indefinite pay off time so it would be nice to be able to use the editor and wipe all that out.￼

**Comment by anonRTtty** [comment]
> Working on it.... looks like the save structure changed, so I need time to figure it out.

ok,i am expect to your exceedingly work，Thank you for your contribution

**Comment by JB2021-81** [comment]
Huh? 🤷🏻‍♂️🤦🏻‍♂️😂

**Comment by Darksidjuice** [comment]
Thanks a lot for your patience ! Good job boss !

**Comment by AndreDriesel** [comment]
How is the current status? 😅 can’t wait to get the editor again 😅

**Comment by goatfungus** [comment]
Update 1.8.0 should now be able to read the new save format. Enjoy.

**Comment by Darksidjuice** [comment]
Thanks alot for us ! It was so important ! Excellent job !
