### ISSUE TITLE
Feature Request: Add Expedition Loot like the Golden Vector

### ISSUE THREAD

**Issue by SirCathal** [goatfungus/NMSSaveEditor#406]
I know the most important thing now is to support the new save format and make the editor working again.
But after that, please add a option to claim the Expedition loot like the Golden Vector Ship.
It would be fantastic for people like me who missed the first Expeditions.

**Comment by RealSkyMaster** [comment]
There was a mod that made this possible. (With NexusMods) it is unfortunately not certain whether this will still work after the Frontiers update.

**Comment by Trigger94** [comment]
There are already easy methods to add expeditions stuff to your account (at least for the steam version). 
Go to your steam library SteamLibrary\steamapps\common\No Man's Sky\Binaries\SETTINGS and you'll find a file called "GCUSERSETTINGSDATA". Open it with your text editor and add the following lines in the property section:
                <Property name="UnlockedSeasonRewards" value="EXPD_FIREPACK01" />
		<Property name="UnlockedSeasonRewards" value="BLD_EXPD_BASE01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_HELMET01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_DECAL01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_BACKPACK01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_TITLE01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_BANNER01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_SHIP01" />
		
It should like the screenshot that i added. After that you can claim the expedition rewards on the anomaly for all your save files :)
![usPYTD7](https://user-images.githubusercontent.com/89928489/132025632-b71cb648-6c30-4f88-a934-005334e53fb4.png)

**Comment by Kunal926** [comment]
I was trying to get the streamlined jetpack yesterday and came by this save file 
https://drive.google.com/file/d/1MT-HV1sln62XPJkEu-qnajXQJnukADUw/view
 just copied and pasted it in 
C:\Users\UserName\AppData\Roaming\HelloGames\NMS\st_Numbers
 and claimed them from the anomaly later on works for any other save as well.

**Comment by SirOven** [comment]
@Kunal926 you did this yesterday? I tried it just now and it didn't work for me. Did you copy the individual files, or just the folder into C:\Users\UserName\AppData\Roaming\HelloGames\NMS\st_Numbers?

**Comment by Kunal926** [comment]
Individual files

**Comment by SirOven** [comment]
Yeah I just did that and nothing happened

**Comment by Kunal926** [comment]
What happens when you load into that save file?

**Comment by Kunal926** [comment]
I think you have to turn off internet and change the date i kept it at 5 march 2021

**Comment by SirOven** [comment]
So you change the date, disconnect internet and then launch the game?

**Comment by Kunal926** [comment]
yes

**Comment by SirOven** [comment]
K thanks, ill try that now

**Comment by Johnathon759** [comment]
Trying to do that property thing but it is not working, where exactly within the property area am I placing that text?

**Comment by Trigger94** [comment]
> Trying to do that property thing but it is not working, where exactly within the property area am I placing that text?

You need to scroll down to the "unlocked season rewards" and place it under there. Make sure that it looks like the screenshot that i posted including the "unlocked season rewards" line itself cause you have to remove a "/" from it if you didn't unlock anything previously.

**Comment by Johnathon759** [comment]
I gotta remove the quotes?
Or the /

**Comment by Trigger94** [comment]
> I gotta remove the quotes?
> Or the /

The /

Also make sure that the </Property> is the last line in that segment or it won't work correctly

**Comment by SirOven** [comment]
> 
> 
> > I gotta remove the quotes?
> > Or the /
> 
> The /
> 
> Also make sure that the Property line that you see in the screenshot at the bottom is there or it won't work correctly

Is this correct? 
![image](https://user-images.githubusercontent.com/90058491/132062025-60b0a74a-5fbf-4b39-b4a9-9548f31539a0.png)

**Comment by Trigger94** [comment]
> > > I gotta remove the quotes?
> > > Or the /
> > 
> > 
> > The /
> > Also make sure that the Property line that you see in the screenshot at the bottom is there or it won't work correctly
> 
> Is this correct?
> ![image](https://user-images.githubusercontent.com/90058491/132062025-60b0a74a-5fbf-4b39-b4a9-9548f31539a0.png)

Yes, that looks correct

**Comment by SirOven** [comment]
Thanks, and now I just close the document and launch the game?

**Comment by Trigger94** [comment]
> Thanks, and now I just close the document and launch the game?

Yeah, save the document and launch your game, you can pick the stuff up in the anomaly.

**Comment by SirOven** [comment]
Thanks for the help!

**Comment by Johnathon759** [comment]
Got it exactly like that, but its not showing anything for me to collect, everythings still locked.

**Comment by SirOven** [comment]
Yep, isnt working for me either

**Comment by Trigger94** [comment]
> Got it exactly like that, but its not showing anything for me to collect, everythings still locked.

Can you post a screenshot of your file?

**Comment by SirOven** [comment]
![image](https://user-images.githubusercontent.com/90058491/132062708-f41d7019-47f5-4d07-b28a-94386c33bb4e.png)

**Comment by Johnathon759** [comment]
![IMG_20210903_163302913_HDR](https://user-images.githubusercontent.com/37780247/132062697-23438645-8f64-462a-a4ec-3bb1ed5a80e0.jpg)

**Comment by Trigger94** [comment]
That is weird, you definetly put it in correctly so i don't see why it doesn't work for you guys. I've done this literally 2 days ago and it worked perfectly fine.

**Comment by Trigger94** [comment]
I just checked the patchnotes for the frontiers update, apparently they changed how the expedition unlocks work. Guess we'll have to find another way to do it now.

**Comment by SirOven** [comment]
ah bollocks

**Comment by Johnathon759** [comment]
Son of a biscuit...

**Comment by Johnathon759** [comment]
I've also come across quite a few bugs x3. the exosuits in pc seem to be broken, to where they be charged fully, yet got no charge.

**Comment by Shyressa** [comment]
Here is a copy of my save with all expedition 1 and 2 and all twitch drops. If you save it to your drive and load it in the game.. all the items will unlock.. i have already bought and claimed most.. so they should unlock for all other saves hopefully. If not.. well I tried to help.

https://drive.google.com/file/d/1L_TcefoKB8DPkmtJzW4sJBk9ID4g_g6s/view?usp=sharing

**Comment by Johnathon759** [comment]
What in the world do I do with your save? How do I get it to be my save?

**Comment by Johnathon759** [comment]
Your save is incompatible

**Comment by Biostar-Ten** [comment]
I seem to remember them being locked "For a While" after doing it this way a month ago. Few new games started, few old games reloaded and eventually they popped unlocked.
Like This:
</Property>
	<Property name="UnlockedSeasonRewards">
		<Property name="UnlockedSeasonRewards" value="EXPD_FIREPACK01" />
		<Property name="UnlockedSeasonRewards" value="BLD_EXPD_BASE01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_DECAL01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_TITLE02B" />
		<Property name="UnlockedSeasonRewards" value="EXPD_HELMET01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_BACKPACK01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_TITLE01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_SHIP01" />
		<Property name="UnlockedSeasonRewards" value="EXPD_BANNER01" />
		<Property name="UnlockedSeasonRewards" value="MYSTERY_TRACKER" />
		<Property name="UnlockedSeasonRewards" value="EXPD_DECAL02" />
		<Property name="UnlockedSeasonRewards" value="EXPD_BANNER02" />
		<Property name="UnlockedSeasonRewards" value="EXPD_SPEC02" />
		<Property name="UnlockedSeasonRewards" value="EXPD_TITLE02A" />
	</Property>
	<Property name="UnlockedTwitchRewards">
		<Property name="UnlockedTwitchRewards" value="TWITCH_009" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_001" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_002" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_003" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_004" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_005" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_006" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_007" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_008" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_010" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_011" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_012" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_013" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_014" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_015" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_016" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_017" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_018" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_019" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_020" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_021" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_022" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_023" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_024" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_025" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_026" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_027" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_028" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_029" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_041" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_030" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_040" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_031" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_043" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_032" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_042" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_033" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_045" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_034" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_044" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_035" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_036" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_037" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_038" />
		<Property name="UnlockedTwitchRewards" value="TWITCH_039" />
	</Property>

**Comment by Johnathon759** [comment]
Whatever you shared, is completely blank.

**Comment by SirCathal** [comment]
> 
> 
> Here is a copy of my save with all expedition 1 and 2 and all twitch drops. If you save it to your drive and load it in the game.. all the items will unlock.. i have already bought and claimed most.. so they should unlock for all other saves hopefully. If not.. well I tried to help.
> 
> https://drive.google.com/file/d/1L_TcefoKB8DPkmtJzW4sJBk9ID4g_g6s/view?usp=sharing

Your Save seems to be incomplete, the Game marked it as not compatible

**Comment by SirCathal** [comment]
> 
> 
> I was trying to get the streamlined jetpack yesterday and came by this save file
> https://drive.google.com/file/d/1MT-HV1sln62XPJkEu-qnajXQJnukADUw/view
> just copied and pasted it in
> C:\Users\UserName\AppData\Roaming\HelloGames\NMS\st_Numbers
> and claimed them from the anomaly later on works for any other save as well.

That save worked fine for all the Expedition 1 Stuff.
After loading it, I it was converted into a normal Save and after that, I could load my normal saves and claim all the Expedition one stuff. (I Play on GOG but that work with Steam saves)

**Comment by SirOven** [comment]
@SirCathal so did you just transfer the files across and load up a normal save and claim it. Or did you need to change the date, disconnect internet and create an Expedition game for it to work?

**Comment by SirOven** [comment]
> 
> 
> > I was trying to get the streamlined jetpack yesterday and came by this save file
> > https://drive.google.com/file/d/1MT-HV1sln62XPJkEu-qnajXQJnukADUw/view
> > just copied and pasted it in
> > C:\Users\UserName\AppData\Roaming\HelloGames\NMS\st_Numbers
> > and claimed them from the anomaly later on works for any other save as well.
> 
> That save worked fine for all the Expedition 1 Stuff.
> After loading it, I it was converted into a normal Save and after that, I could load my normal saves and claim all the Expedition one stuff. (I Play on GOG but that work with Steam saves)

^

**Comment by Kunal926** [comment]
Just transferred the files across. I did it after the frontiers update and it worked for me.

**Comment by Shyressa** [comment]
sorry... here is a zip with both files needed.. didnt realize it required both

https://drive.google.com/file/d/1m9K84yg1Bo77SBVjLyvWtRtxMaQhxQN_/view?usp=sharing

**Comment by SirOven** [comment]
> 
> 
> sorry... here is a zip with both files needed.. didnt realize it required both
> both should work like i said before.. just paste them into the save folder.. i would save yours first
> https://drive.google.com/file/d/1m9K84yg1Bo77SBVjLyvWtRtxMaQhxQN_/view?usp=sharing

Wow, thanks a lot. Will it be buggy if multiple people own the same base? Thanks for your help!

**Comment by Shyressa** [comment]
well.. once you load that save and travel to the anomaly and visit the quicksilver vendor.. maybe go thru the whole list once.. everything should unlock for your account i think.. then you should be able to use your own save again and still have access to it all there.. least i hope that will do it

**Comment by Shyressa** [comment]
per the other thread.. just using the save files doesnt work. you need the accountdata files to unlock all the entitlements, and it has to be done before starting the game. But you can use you own saved game.
I made a zip with both the accountdata and the save files.. so only transfer the account ones into your saved game folder and start the game with your own save and you should get all the entitlements.

https://drive.google.com/file/d/1ccefHtIBr68aNZ9-KlCTQgadZHQiReyt/view?usp=sharing

**Comment by Devilin-Pixy** [comment]
Saving has changed with Frontiers. It no longer uses the GCUSERSETTINGSDATA.MXML from the SETTINGS folder, but instead it uses a new save file called 'accountdata.hg' with a matching 'mf_accountdata.hg' pair on Steam, saved with all the other save files.

**Comment by DS-Karma** [comment]
> per the other thread.. just using the save files doesnt work. you need the accountdata files to unlock all the entitlements, and it has to be done before starting the game. But you can use you own saved game.
> I made a zip with both the accountdata and the save files.. so only transfer the account ones into your saved game folder and start the game with your own save and you should get all the entitlements.
> 
> https://drive.google.com/file/d/1ccefHtIBr68aNZ9-KlCTQgadZHQiReyt/view?usp=sharing

does this actually work and how would i go about moving the accountdata files to a microsoft store install? I do not even know where my account data file is in said directory as its like 9 folders of numbers.

**Comment by Bazzyliszek** [comment]
Thx Shyressa you saved me files worked soo good for me and i have unlocked expedition 2 items . exp 1 items i unlocked easrlier  with the help of Kunal926 . THX all .

**Comment by SirCathal** [comment]
> 
> 
> per the other thread.. just using the save files doesnt work. you need the accountdata files to unlock all the entitlements, and it has to be done before starting the game. But you can use you own saved game.
> I made a zip with both the accountdata and the save files.. so only transfer the account ones into your saved game folder and start the game with your own save and you should get all the entitlements.
> 
> https://drive.google.com/file/d/1ccefHtIBr68aNZ9-KlCTQgadZHQiReyt/view?usp=sharing

Ok, now with your accountdata.hg I found out how it works easy.
All you have to do is open your own c:\Users\<YourWindowsUsername>\AppData\Roaming\HelloGames\NMS\DefaultUser\accountdata.hg file with a Text Editor like Notead or better Notepad++
Then scroll down to the end of the File and search for: 
"d4U":
(Yes with the " included) 
After that entry is a [ bracket followed by text if you already have some expedition rewards or yust [ ] if you have none.
Now replace the [ ] brackets and all between with this Text:
["^EXPD_FIREPACK01","^BLD_EXPD_BASE01","^EXPD_HELMET01","^EXPD_TITLE02B","^EXPD_DECAL01","^EXPD_BACKPACK01","^EXPD_TITLE01","^EXPD_BANNER01","^EXPD_SHIP01","^MYSTERY_TRACKER","^EXPD_DECAL02","^EXPD_SPEC02","^EXPD_BANNER02","^EXPD_TITLE02A"]
That gives you alle Expedition 1 & 2 rewards.
Now, for Twitch (thanks again to @Shyressa  because I play on GOG and cant connect my account with twitch, and because of that, I cant collect them normally.
Search for the Text:
"<5B":
Again, you find an opening [ bracket and some text and then a closing bracket ] if you have some Twitch rewards or just [ ] if you don't have any of them.
Now replace the [ ] brackets and all between them with:
["^TWITCH_022","^TWITCH_013","^TWITCH_008","^TWITCH_038","^TWITCH_041","^TWITCH_030","^TWITCH_026","^TWITCH_032","^TWITCH_043","^TWITCH_045","^TWITCH_034","^TWITCH_021","^TWITCH_037","^TWITCH_025","^TWITCH_042","^TWITCH_033","^TWITCH_029","^TWITCH_012","^TWITCH_044","^TWITCH_035","^TWITCH_007","^TWITCH_020","^TWITCH_036","^TWITCH_024","^TWITCH_028","^TWITCH_006","^TWITCH_003","^TWITCH_011","^TWITCH_019","^TWITCH_023","^TWITCH_040","^TWITCH_031","^TWITCH_027","^TWITCH_002","^TWITCH_010","^TWITCH_005","^TWITCH_017","^TWITCH_016","^TWITCH_018","^TWITCH_039","^TWITCH_014","^TWITCH_015","^TWITCH_001","^TWITCH_004","^TWITCH_009"]
Now you have all Twitch rewards.

You don't have to use other saves, you can load your own and claim the rewards with any save you have in the anomaly.
 
You must do that change before you start the game and I disconnected the Internet, because if not, the cloud sync always overwrites my changes. Bus when the Game is running and you claimed your stuff, you can reconnect the Internet and syve your new game to the cloud. From now on it's permanent.

**Comment by DeadlyGamer5** [comment]
> 
> 
> > per the other thread.. just using the save files doesnt work. you need the accountdata files to unlock all the entitlements, and it has to be done before starting the game. But you can use you own saved game.
> > I made a zip with both the accountdata and the save files.. so only transfer the account ones into your saved game folder and start the game with your own save and you should get all the entitlements.
> > https://drive.google.com/file/d/1ccefHtIBr68aNZ9-KlCTQgadZHQiReyt/view?usp=sharing
> 
> Ok, now with your accountdata.hg I found out how it works easy.
> All you have to do is open your own c:\Users<YourWindowsUsername>\AppData\Roaming\HelloGames\NMS\DefaultUser\accountdata.hg file with a Text Editor like Notead or better Notepad++
> Then scroll down to the end of the File and search for:
> "d4U":
> (Yes with the " included)
> After that entry is a [ bracket followed by text if you already have some expedition rewards or yust [ ] if you have none.
> Now replace the [ ] brackets and all between with this Text:
> ["^EXPD_FIREPACK01","^BLD_EXPD_BASE01","^EXPD_HELMET01","^EXPD_TITLE02B","^EXPD_DECAL01","^EXPD_BACKPACK01","^EXPD_TITLE01","^EXPD_BANNER01","^EXPD_SHIP01","^MYSTERY_TRACKER","^EXPD_DECAL02","^EXPD_SPEC02","^EXPD_BANNER02","^EXPD_TITLE02A"]
> That gives you alle Expedition 1 & 2 rewards.
> Now, for Twitch (thanks again to @Shyressa because I play on GOG and cant connect my account with twitch, and because of that, I cant collect them normally.
> Search for the Text:
> "<5B":
> Again, you find an opening [ bracket and some text and then a closing bracket ] if you have some Twitch rewards or just [ ] if you don't have any of them.
> Now replace the [ ] brackets and all between them with:
> ["^TWITCH_022","^TWITCH_013","^TWITCH_008","^TWITCH_038","^TWITCH_041","^TWITCH_030","^TWITCH_026","^TWITCH_032","^TWITCH_043","^TWITCH_045","^TWITCH_034","^TWITCH_021","^TWITCH_037","^TWITCH_025","^TWITCH_042","^TWITCH_033","^TWITCH_029","^TWITCH_012","^TWITCH_044","^TWITCH_035","^TWITCH_007","^TWITCH_020","^TWITCH_036","^TWITCH_024","^TWITCH_028","^TWITCH_006","^TWITCH_003","^TWITCH_011","^TWITCH_019","^TWITCH_023","^TWITCH_040","^TWITCH_031","^TWITCH_027","^TWITCH_002","^TWITCH_010","^TWITCH_005","^TWITCH_017","^TWITCH_016","^TWITCH_018","^TWITCH_039","^TWITCH_014","^TWITCH_015","^TWITCH_001","^TWITCH_004","^TWITCH_009"]
> Now you have all Twitch rewards.
> 
> You don't have to use other saves, you can load your own and claim the rewards with any save you have in the anomaly.
> 
> You must do that change before you start the game and I disconnected the Internet, because if not, the cloud sync always overwrites my changes. Bus when the Game is running and you claimed your stuff, you can reconnect the Internet and syve your new game to the cloud. From now on it's permanent.

Just spent about an hour with the save editor finding this out, but these are the other twitch drops IE Ships, pets, and multi-tools.

"^TWITCH_GUN01","^TWITCH_GUN02","^TWITCH_GUN03","^TWITCH_GUN04","^TWITCH_GUN05","^TWITCH_PET01","^TWITCH_PET02","^TWITCH_PET03","^TWITCH_PET04","^TWITCH_PET05","^TWITCH_GUNUP01A","^TWITCH_GUNUP01B","^TWITCH_GUNUP01C","^TWITCH_GUNUP01D","^TWITCH_GUNUP01E","^TWITCH_SHIP01","^TWITCH_SHIP02","^TWITCH_SHIP03","^TWITCH_SHIP04","^TWITCH_SHIP05","^TWITCH_SHIP06","^TWITCH_SHIP07","^TWITCH_SHIP08","^TWITCH_SHIP08B","^TWITCH_SHIP09","^TWITCH_SHIP10",

And these are (most) of the expedition 1, 2, and 3 rewards, i couldn't find 3 such as the banner, bubble jetpack, and the "Title:Globemaster"

["^BLD_EXPD_BASE01","^BASE_CAVE2","^MYSTERY_TRACKER","^BLD_PLANET_HOLO","^BASE_CAVE5","^EXPD_DECAL03","^BASE_CAVE1","^BASE_CAVE4","^BASE_CAVE3","^BLD_FLYJAR","^EXPD_TITLE02B","^EXPD_HELMET01","^EXPD_EGG_03","^EXPD_DECAL01","^EXPD_BACKPACK01","^EXPD_TITLE01","^EXPD_BANNER01","^EXPD_SHIP01","^EXPD_DECAL02","^EXPD_SPEC02","^EXPD_BANNER02","^EXPD_TITLE02A"]

**Comment by zerodarkfire** [comment]
I would like to know if it's possible to get the special items too, "specialrewards", if anyone knows post here, and if anyone can also get the missing items from the expeditions, banner, bubble jetpack, and the "Title:Globemaster".

**Comment by SirCathal** [comment]
Thanks for implementing that Feature. It works fine, so I can Close that Issue.
