### ISSUE TITLE
Pre-"Version 1.30" saves can't be loaded anymore in "Frontiers"

### ISSUE THREAD

**Issue by philou-felin** [goatfungus/NMSSaveEditor#407]
Hi! I know this isn't an issue, but I want to know whether other people can confirm that.

I usually try to load my old saves from 2016 which follow the "mf_storageX.hg" and "storageX.hg" each time there's an update.

I tried doing it in 3.6 and it doesn't work.

Can anyone confirm this?

Is that's a thing, I think some kind of "upgrade" feature _could_ be a nice addition to NMSSaveEditor.

By the way, thank you for this program. I used it in the past just for fun and testing. I know this is all volunteering so I don't expect anything.

**Comment by Vypir** [comment]
Please see #404

**Comment by philou-felin** [comment]
> Please see #404

Thanks, Vypir, but I'm mostly off-topic. My problem isn't with NMSSaveEditor. I know Hello Games shook our world with save files and I can understand what it means for the maintainer/developer.

I'm just curious about my specific issue and I know this repository is followed by nerds like me.

**Comment by philou-felin** [comment]
old saves work after all. I managed to make mine work.
