### ISSUE TITLE
HELP? I have been trying to unlock expedition rewards. Microsoft Store...

### ISSUE THREAD

**Issue by DS-Karma** [goatfungus/NMSSaveEditor#408]
So I have searched around here and found a lot of great information to attempt to add in the expedition rewards to No Mans Sky.

I am using the Microsoft Store version of NMS.

I got into the WindowsApps and went into No Man's Sky\Binaries\SETTINGS to try to find "GCUSERSETTINGSDATA" but it is no where to be found. I also noticed that I do not have a Local save in %appdata% even though I just fresh installed and loaded the game up only playing for a few hours.

The only file there is SEASON_DATA_CACHE.JSON

So anyone have any clues to what I should do from here?

**Comment by LadyAthena1** [comment]
Never use Microsoft Store.

**Comment by goatfungus** [comment]
As of version 1.9+, MS Game Pass files can now be edited. Enjoy!
