### ISSUE TITLE
Feature Request: Galaxy Change

### ISSUE THREAD

**Issue by Giblejimmy** [goatfungus/NMSSaveEditor#41]
I don't know much about the game per-se but I do know I have no real interest in playing duck duck portal to try and get to the various universes. Any chance this is something we can change?

Also don't suppose there is some magical way to modify planets that you've found? Keep up the great work Goat, you've saved a lot of people a stupid amount of trouble!

**Comment by goatfungus** [comment]
Galaxy change is a feature coming soon....

Planet modifications using the terrain modification data may be possible, but it's currently broken in game and changes are never permanent. I won't be implementing any terrain modification in the editor until changes can be permanent or there would be complaints saying the editor "doesn't work".

If you mean modifications like changing the biomes, etc, these can't be done by the save file editor as they are part of the game data files. Instead you could try downloading other mods which are dedicated to that purpose.

**Comment by goatfungus** [comment]
Added in version 1.5.10... see the Coordinate Viewer dialog. It should dump you inside your ship in whatever galaxy you choose.
