### ISSUE TITLE
Microsoft Savegame Location Changed?

### ISSUE THREAD

**Issue by DS-Karma** [goatfungus/NMSSaveEditor#410]
I noticed when looking for my Savefile in C:\Users\Username\AppData\Roaming\HelloGames\NMS\DefaultUser it does not exist yet when turning off my WiFi it will still Load into all my savegames.

Any idea why?

**Comment by Shyressa** [comment]
save files are stored under C:\Users\%UserName%\AppData\Local\Packages\HelloGames.NoMansSky\SystemAppData\wgs\[random number]

**Comment by DS-Karma** [comment]
Really? Hmm its been awhile since I have played NMS and I swear that was where it was originally, thanks though... Ill go check it out.

**Comment by DS-Karma** [comment]
> save files are stored under C:\Users%UserName%\AppData\Local\Packages\HelloGames.NoMansSky\SystemAppData\wgs[random number]
> from here https://www.reddit.com/r/XboxGamePass/comments/h7xbth/no_mans_sky_saves_not_in_proper_location/
> 
> however steam saves will prolly still not work with windows store version

Any idea what set of numbers LAWL... i have 4 folders.

**Comment by DS-Karma** [comment]
Because I cannot open any of them.

**Comment by Shyressa** [comment]
no clue.. i dont use the windows store version.. but if you cant open them, then you need to search for some kind of registry key to allow you to take ownership of those folders so you can

**Comment by LordRhys** [comment]
For some reason it can no longer find my save game files, it keeps wanting to open some backup.zip file. Also I do not know if Steam is screwing up where it is saving but my only save files are dated back in July  2018 which was when I started playing, I see nothing with save dates of 9/5/2021 even though the game shows that date when I load the save.

**Comment by JB2021-81** [comment]
I think it's pretty stupid that Microsoft won't let users automatically have access to the save files for no man's sky on the game pass version. ￼ I've tried messing around with the save files for the game pass version before and it is a giant pain in the butt to work with and I am an intermediate modder so I do know what I'm doing but Microsoft has made it really hard.￼￼

**Comment by LordRhys** [comment]
I had to switch to NomNom which had no problem seeing my save game file, I prefer the format of NMSS but if it locked to the same save game slots that don't exist I can't use it.

**Comment by goatfungus** [comment]
I have set up a new experimental build which has MS Game Pass support here:
https://github.com/goatfungus/NMSSaveEditor/issues/444#issuecomment-920572374
