### ISSUE TITLE
Editor not seeing bases

### ISSUE THREAD

**Issue by dclrocks** [goatfungus/NMSSaveEditor#414]
The editor is not seeing player bases.  Was discovered when trying to move a base computer.
This is with version 1.8.0

**Comment by JB2021-81** [comment]
Yeah I just loaded up the editor and couldn't see anything at all in the bases tab￼

I was going to ask if it was possible to edit the settlements? The main thing I would like to do is wipe out the debt of the settlement that way I can start making money right away.￼￼￼

Either way thanks for getting the save files format issue fixed￼.

**Comment by JB2021-81** [comment]
I was going through add known products tab and the planetary chart for the settlements says empty next to it in parentheses￼. I'm hoping that this stuff still works but who knows?￼

**Comment by TheYeGh** [comment]
it work as usual :)
always the same - nev actualisation of game must have a new actualisation of NMEditor

**Comment by RealSkyMaster** [comment]
I can confirm. Also not shown in the Base Info for me

**Comment by Mike-Blackwell** [comment]
> After further digging around I found the settlement chart under the curiosity tab and above it is seeds of glass and below it is singularity core.

@JB2021-81 more clues please as to where the settlement chart lives?

**Comment by goatfungus** [comment]
This should be fixed now, in the 1.8.1 version.
