### ISSUE TITLE
Can't save changes

### ISSUE THREAD

**Issue by risan852** [goatfungus/NMSSaveEditor#415]
After I make any changes in the program, the changes just won't save. Whenever I want to close the menu, the program repeteadly ask if I want to save changes, when I put yes, the program do nothing. 

Best regards,
risan852

**Comment by risan852** [comment]
Here is the log:

[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/7116849/NMSSaveEditor.log)

**Comment by LadyAthena1** [comment]
Try turning off your anti virus. I found that mine was stopping it from saving.
