### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by ykokami** [goatfungus/NMSSaveEditor#416]
I downloaded the latest version plus java 8 but when I click on the .bat it opens a cmd window then closes

**Comment by goatfungus** [comment]
it should create a NMSSaveEditor.log file.... can you please attach it here and I'll have a look.

**Comment by ykokami** [comment]
I don't see any log file just the .bat, .jar, 4G.bat and the txt files.

**Comment by goatfungus** [comment]
Perhaps there is a security setting that isn't allowing you to run batch files.... we really need to see what is is displaying, but the window is closing as you say.

It is also possible that you do not have Java installed.

**Comment by ykokami** [comment]
I have java 8 Installed and up to date. it only opens a CMD window with nothing written on it then it closes right after even took a print to see  but its just empty.

**Comment by ykokami** [comment]
Also tried to read the .jar using C:\Program Files\Java\jre1.8.0_301\bin\ java.exe but nothing happened

**Comment by goatfungus** [comment]
Not sure if this is still happening, if so, open a new ticket.
