### ISSUE TITLE
Tech slot expansion not present in game

### ISSUE THREAD

**Issue by Grievousbee** [goatfungus/NMSSaveEditor#417]
So you can expand your tech slots to your hearts content using the editor and the saves are seen by the editor (I know this as I have various saves with 8x6 tech slots and can see all my enhancements in the editor) but when going in game the slots are at 7x2.
Also new saves cannot have the tech slots expanded at all, just like exocraft now cannot.

Is this related to the 'accountdata.hg' file now present do we think or is there some other error checking going one somewhere that is cross referencing another file somewhere?.

Gonna have to archive all my saves now as I am NOT losing everything in the tech slots.

**Comment by SirCathal** [comment]
What technology slots are you talking about?
The ones in the Exo Suite are limited to a maximum of 7x2. Direct editing of the savegame doesn't help either.
The multitool and freighter go up to 8x6
Those of the spaceship only go up to 7x4 here in the editor
With NomNom you can expand it to 8x6 and then continue to use it here. I have already submitted a feature request for this.
So far, all slot expansions have worked flawlessly.

**Comment by goatfungus** [comment]
Are you talking about the ship tech slots?
If they are 8x6 now then I can easily change it. I had set it at 7x4 because that used to be the limit. Can you please confirm?

**Comment by SirCathal** [comment]
Yes the ship tech slots can be 8*6 please change the limit from 7*4 to 8*6

**Comment by Grievousbee** [comment]
Sorry, yes the suit tech slots. It was possible to get them to 8x6 as that what I had and no Nomnom does not work either, in fact I cannot actually change the size in Nomnom.

I found out the multi tool went rather high in game as one of the expedition tools went over the expected 21 when I got a bit too eager on the use tool expansion button *lol*

Only one I am really concerned about max size wise it the suit though.

**Comment by Grievousbee** [comment]
AArrrgghh!!!
Now I can get the tech size changing in Nomnom!

Remains to be seen if itll actually stay there thougnbh or wether the game will write over it again.

**Comment by Grievousbee** [comment]
As I suspected, you can change the suit tech slot size in Nomnom, check using NMSse that its there but as soon as you load the game the expansion is not present. Its obvioulsy being sanity checked some where.

If it DOES work plese tell me how as I am now stumped.

**Comment by SirCathal** [comment]
No the Nano Suite Tech Slot Size is limited by the Game to 7x2.
That was different in a early game version but now that don't work.  You Can manually edit your Save Game but that would not be shown in the Game you maybe brick your save with that.
