### ISSUE TITLE
Bases not visible

### ISSUE THREAD

**Issue by apteryx66** [goatfungus/NMSSaveEditor#420]
First of all: Thank you for the tool; it's awesomely useful!
Just to confirm: v1.8.0 isn't reading bases. However, to be more precise, the SE isn't reading bases on one save game slot only. I have two slots (both on Normal): one for an older game that I haven't accessed since the Frontiers update. The bases in that game are visible in SE.
The second slot is for a game played prior to, and subsequent to the Frontiers update. It is the second save slot that isn't "seeing" the 14 bases in that game (15 with a Freighter). I can see the bases in the JSON file, though. The 2nd slot bases (backed up in the SE) are all present in the Bases folder, except the last base created after the NMS update.
In using the two .bat files I see that there are quite a few instances of issues about name mapping 'not found' for the second slot saves; but only one for the first slot.
I'm on PC and Steam saves (except for offline saves where Steam servers are having an off day)
Once again: Many thanks for the tool

**Comment by goatfungus** [comment]
Thanks for the detailed explanation, I'll have a look at this.

**Comment by goatfungus** [comment]
This should be fixed now, in the 1.8.1 version.
