### ISSUE TITLE
Feature Request(s)

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#422]
@goatfungus, I know you just got the Base Info working and here they go....
  1) Base Info: is it possible to tally all of the Bases Item counts so it possible to see the total parts count per Save File (since 16,000 seems to be the real max based on complexities)?
  2) Add a tab similar to Ships for Critters and their associated particulars?

And if we didn't say it enough thanxs! I see NMS Sky Masters just put a UTube re the latest NMSSaveEditor..

**Comment by goatfungus** [comment]
Thanks for the suggestions, I'll have a look :)

**Comment by goatfungus** [comment]
Creatures / Companions should be available in version 1.8.3 now.... Enjoy!
