### ISSUE TITLE
Account data unlocks

### ISSUE THREAD

**Issue by zerodarkfire** [goatfungus/NMSSaveEditor#423]
> 
> 
> > per the other thread.. just using the save files doesnt work. you need the accountdata files to unlock all the entitlements, and it has to be done before starting the game. But you can use you own saved game.
> > I made a zip with both the accountdata and the save files.. so only transfer the account ones into your saved game folder and start the game with your own save and you should get all the entitlements.
> > https://drive.google.com/file/d/1ccefHtIBr68aNZ9-KlCTQgadZHQiReyt/view?usp=sharing
> 
> Ok, now with your accountdata.hg I found out how it works easy.
> All you have to do is open your own c:\Users<YourWindowsUsername>\AppData\Roaming\HelloGames\NMS\DefaultUser\accountdata.hg file with a Text Editor like Notead or better Notepad++
> Then scroll down to the end of the File and search for:
> "d4U":
> (Yes with the " included)
> After that entry is a [ bracket followed by text if you already have some expedition rewards or yust [ ] if you have none.
> Now replace the [ ] brackets and all between with this Text:
> ["^EXPD_FIREPACK01","^BLD_EXPD_BASE01","^EXPD_HELMET01","^EXPD_TITLE02B","^EXPD_DECAL01","^EXPD_BACKPACK01","^EXPD_TITLE01","^EXPD_BANNER01","^EXPD_SHIP01","^MYSTERY_TRACKER","^EXPD_DECAL02","^EXPD_SPEC02","^EXPD_BANNER02","^EXPD_TITLE02A"]
> That gives you alle Expedition 1 & 2 rewards.
> Now, for Twitch (thanks again to @Shyressa because I play on GOG and cant connect my account with twitch, and because of that, I cant collect them normally.
> Search for the Text:
> "<5B":
> Again, you find an opening [ bracket and some text and then a closing bracket ] if you have some Twitch rewards or just [ ] if you don't have any of them.
> Now replace the [ ] brackets and all between them with:
> ["^TWITCH_022","^TWITCH_013","^TWITCH_008","^TWITCH_038","^TWITCH_041","^TWITCH_030","^TWITCH_026","^TWITCH_032","^TWITCH_043","^TWITCH_045","^TWITCH_034","^TWITCH_021","^TWITCH_037","^TWITCH_025","^TWITCH_042","^TWITCH_033","^TWITCH_029","^TWITCH_012","^TWITCH_044","^TWITCH_035","^TWITCH_007","^TWITCH_020","^TWITCH_036","^TWITCH_024","^TWITCH_028","^TWITCH_006","^TWITCH_003","^TWITCH_011","^TWITCH_019","^TWITCH_023","^TWITCH_040","^TWITCH_031","^TWITCH_027","^TWITCH_002","^TWITCH_010","^TWITCH_005","^TWITCH_017","^TWITCH_016","^TWITCH_018","^TWITCH_039","^TWITCH_014","^TWITCH_015","^TWITCH_001","^TWITCH_004","^TWITCH_009"]
> Now you have all Twitch rewards.
> 
> You don't have to use other saves, you can load your own and claim the rewards with any save you have in the anomaly.
> 
> You must do that change before you start the game and I disconnected the Internet, because if not, the cloud sync always overwrites my changes. Bus when the Game is running and you claimed your stuff, you can reconnect the Internet and syve your new game to the cloud. From now on it's permanent.

Just spent about an hour with the save editor finding this out, but these are the other twitch drops IE Ships, pets, and multi-tools.

"^TWITCH_GUN01","^TWITCH_GUN02","^TWITCH_GUN03","^TWITCH_GUN04","^TWITCH_GUN05","^TWITCH_PET01","^TWITCH_PET02","^TWITCH_PET03","^TWITCH_PET04","^TWITCH_PET05","^TWITCH_GUNUP01A","^TWITCH_GUNUP01B","^TWITCH_GUNUP01C","^TWITCH_GUNUP01D","^TWITCH_GUNUP01E","^TWITCH_SHIP01","^TWITCH_SHIP02","^TWITCH_SHIP03","^TWITCH_SHIP04","^TWITCH_SHIP05","^TWITCH_SHIP06","^TWITCH_SHIP07","^TWITCH_SHIP08","^TWITCH_SHIP08B","^TWITCH_SHIP09","^TWITCH_SHIP10",

And these are (most) of the expedition 1, 2, and 3 rewards, i couldn't find 3 such as the banner, bubble jetpack, and the "Title:Globemaster"

["^BLD_EXPD_BASE01","^BASE_CAVE2","^MYSTERY_TRACKER","^BLD_PLANET_HOLO","^BASE_CAVE5","^EXPD_DECAL03","^BASE_CAVE1","^BASE_CAVE4","^BASE_CAVE3","^BLD_FLYJAR","^EXPD_TITLE02B","^EXPD_HELMET01","^EXPD_EGG_03","^EXPD_DECAL01","^EXPD_BACKPACK01","^EXPD_TITLE01","^EXPD_BANNER01","^EXPD_SHIP01","^EXPD_DECAL02","^EXPD_SPEC02","^EXPD_BANNER02","^EXPD_TITLE02A"]

Edit: upon testing it seems some of the items are missing, i almost wonder if they're planned future drops, since there are no pets listed under the drops. I didn't know that, as well as a few extra ships. Weird.

_Originally posted by @DeadlyGamer5 in https://github.com/goatfungus/NMSSaveEditor/issues/406#issuecomment-913393725_

**Comment by zerodarkfire** [comment]
If you can figure out how to tag the missing items, put DeadyGamer5 here for us, thanks for the effort :)

**Comment by tehface** [comment]
would this work to unlock the Normandy ?

**Comment by AstroCat00** [comment]
I noticed that if you don't claim all your items right away, it seems the Expeditions stay available but the Twitch ones disappear, so you have to re-edit the file. One problem is getting all the items. Since you only get 3 tool and 6 ship slots you can't get them all a t once so you have to choose or grab the other items later.
What happens if you remove one of the rewards? Can you re-get it on the same save?

**Comment by Johnathon759** [comment]
this is not working with my steam save, I typed everything as it was supposed to be.. I do not understand why my save is being so rubbish right now

**Comment by Iwitrag** [comment]
Hello, I'm here to bring you all unlockable IDS, straight from the game files.

Season rewards (including all rewards from expedition 3):

EXPD_EGG_03 EXPD_TITLE03 EXPD_DECAL03 EXPD_BANNER03 BASE_CAVE1 BASE_CAVE2 BASE_CAVE3 BASE_CAVE4 BASE_CAVE5 BLD_FLYJAR BLD_PLANET_HOLO JETS_BUBBLE EXPD_SPEC02 EXPD_TITLE02A EXPD_TITLE02B EXPD_DECAL02 EXPD_BANNER02 MYSTERY_TRACKER EXPD_SHIP01 EXPD_TITLE01 EXPD_DECAL01 EXPD_BANNER01 EXPD_BACKPACK01 EXPD_HELMET01 BLD_EXPD_BASE01 EXPD_FIREPACK01

Twitch rewards

TWITCH_085 TWITCH_084 TWITCH_083 TWITCH_082 TWITCH_081 TWITCH_080 TWITCH_079 TWITCH_078 TWITCH_077 TWITCH_076 TWITCH_075 TWITCH_074 TWITCH_073 TWITCH_072 TWITCH_071 TWITCH_070 TWITCH_069 TWITCH_068 TWITCH_067 TWITCH_066 TWITCH_065 TWITCH_064 TWITCH_063 TWITCH_062 TWITCH_061 TWITCH_060 TWITCH_059 TWITCH_058 TWITCH_057 TWITCH_056 TWITCH_051 TWITCH_052 TWITCH_053 TWITCH_054 TWITCH_055 TWITCH_046 TWITCH_047 TWITCH_048 TWITCH_049 TWITCH_050 TWITCH_038 TWITCH_037 TWITCH_035 TWITCH_036 TWITCH_034 TWITCH_033 TWITCH_032 TWITCH_031 TWITCH_030 TWITCH_029 TWITCH_028 TWITCH_027 TWITCH_009 TWITCH_001 TWITCH_002 TWITCH_003 TWITCH_044 TWITCH_045 TWITCH_039 TWITCH_040 TWITCH_041 TWITCH_042 TWITCH_043 TWITCH_014 TWITCH_004 TWITCH_005 TWITCH_007 TWITCH_008 TWITCH_006 TWITCH_010 TWITCH_012 TWITCH_013 TWITCH_011 TWITCH_015 TWITCH_016 TWITCH_017 TWITCH_019 TWITCH_020 TWITCH_021 TWITCH_022 TWITCH_018 TWITCH_023 TWITCH_024 TWITCH_025 TWITCH_026

Enjoy

**Comment by goatfungus** [comment]
Version 1.8.2 (just released) now has the ability to edit the account data file. This also has a UI for unlocking all the Season/Twitch rewards. Enjoy.

**Comment by DeadlyGamer5** [comment]
> 
> 
> Version 1.8.2 (just released) now has the ability to edit the account data file. This also has a UI for unlocking all the Season/Twitch rewards. Enjoy.

For some reason the twitch drops aren't showing up on my second character. Weird.

**Comment by goatfungus** [comment]
Yeah, that is weird.... are they a one-time use?

**Comment by DeadlyGamer5** [comment]
I don't think so. it's not working for my friend who has never used them, either.

**Comment by Iwitrag** [comment]
I can claim twitch rewards only when I start NMS without internet access

**Comment by DeadlyGamer5** [comment]
> 
> 
> I can claim twitch rewards only when I start NMS without internet access

Yeah, that seemed to be it. weird, since on my other character it worked fine while online.

**Comment by Iwitrag** [comment]
> > I can claim twitch rewards only when I start NMS without internet access
> 
> Yeah, that seemed to be it. weird, since on my other character it worked fine while online.

According to packet sniffer there is some communication happening with twitch servers when entering anomaly. Probably some checks for linked account and assigned game content.

**Comment by goatfungus** [comment]
Ok, I'll put a disclaimer message on the UI so that users are aware of this. Thanks for the info.
