### ISSUE TITLE
Not picking up the newer manual save?

### ISSUE THREAD

**Issue by temp-999** [goatfungus/NMSSaveEditor#424]
PC, Win 10 21H1, using 1.8.1.

When I open NMSSE and click on Game Slot: only the Auto Save file shows. I have both Auto and Manual save files for Normal and the Manual is more recent.

I tried to add images but don't have the knack.

Here's the log:
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_271
[DEBUG] Working Dir: C:\Users\######\Desktop\Gaming\No Man's Sky Folder\NMSSaveEditor
[INFO] Starting Editor...
[DEBUG] Save Path: C:\Users\######\AppData\Roaming\HelloGames\NMS\st_######
[DEBUG] Mem Usage: 129/1896 MB
[DEBUG] Latest version: "1.8.1"
[DEBUG] Current version: "1.8.1"

**Comment by tuvitor** [comment]
Having the same issue in 1.8.2

**Comment by ykokami** [comment]
at least you got to open it up... I can't it just open a CMD window that closes itself a second later. I have the lastest java already downloaded so I just don't know what to do =/

**Comment by temp-999** [comment]
Close enough.
