### ISSUE TITLE
Where is the settlement code in the save file?

### ISSUE THREAD

**Issue by freetaurus** [goatfungus/NMSSaveEditor#426]
I have a problem in a construction job of settlement.

I choose the task and it start in the game,but I can not find anyplace to put the material.

So I want change this mistake in the save file. Where I can find the code?

**Comment by goatfungus** [comment]
I believe settlements are a kind of Mission.... they appear in the missions section in the JSON Editor but I'm not sure how it all works yet.

**Comment by Intinet1** [comment]
Wanted to find something about settlemants too, found it in the SettlemaentsStatesV2 folder,where there are 100 nummbered folders inside.
best way to find your settlement is to search Username , then ther are the normal stats  that respond to number of citicens , happynes, produktivety, maintenance then 3 more one of those is probably sentinels but im not shure. 
And manny other stats. 
in 3 sifferent saves the slot is always different for what settlement is used.

**Comment by Devilin-Pixy** [comment]
@freetaurus 
> So I want change this mistake in the save file. Where I can find the code?

This can not be fixed through the save file. It should however by now have been fixed with the released patches. If not, report this to Hello Games' Zendesk
