### ISSUE TITLE
The choose save file window is empty

### ISSUE THREAD

**Issue by RZDun** [goatfungus/NMSSaveEditor#427]
When I run nmssaveeditor.jar, the choose save file window is empty. There are no files or folders in the folder, but I can see the archive file in Windows Explorer. How can I solve this problem?
<img width="425" alt="捕获" src="https://user-images.githubusercontent.com/45137671/132492526-96cc3dd4-ede1-49af-b503-16b56eccb9c6.PNG">
<img width="359" alt="捕获" src="https://user-images.githubusercontent.com/45137671/132492734-3c408ea7-127d-447d-b00a-0102213d69b8.PNG">

**Comment by goatfungus** [comment]
This should be fixed in the latest version, 1.9.2.
