### ISSUE TITLE
No data in JSON file.

### ISSUE THREAD

**Issue by Leisha-Lockwood** [goatfungus/NMSSaveEditor#428]
Hi since 1.8.2 updated this morning I cant edit my JSON file.  All that appears is UserData and nothing else

**Comment by Tashton91** [comment]
The save files got changed by Hello Games since they also gave us 15 save slots instead of 5. So the save editor isn't working at the moment.

**Comment by Leisha-Lockwood** [comment]
Is this since the 1.8.2 update to SE this morning? Because it has been working once they updates for frontiers up until this update today to 1.8.2

**Comment by Tashton91** [comment]
Yeah I think it was my own fault that mine wasn't working as I hadn't redownloaded the updated version for Frontiers cause I'm a moron. I think it actually worked for me earlier when I fixed a part on a ship out of curiosity.

**Comment by Leisha-Lockwood** [comment]
I can confirm it is all working. Just download the new update and it’s working well

**Comment by goatfungus** [comment]
Please bear in mind that there are now 2 different JSON editors in version 1.8.2...

1) Under the "Edit" menu.... this one edits the currently selected save file.
2) Under the "Account" menu... this one edits the new account data file that was added in Frontiers.

Both of these files serve different purposes in the game, but the editor will let you modify any of them.

**Comment by Leisha-Lockwood** [comment]
Thank you. Yes I saw that after I deleted and reinstalled SE last night. There was an issue but it was solved by reinstalling save editor. This software is amazing! Absolutely love it and love the developers commitment to keeping it updated

**Comment by Mike-Blackwell** [comment]
`EDIT: I'm wondering if it would be more intuitive to remove the "Account" menu entirely and put a button on the Account tab instead? Ideas?`

Yes please as the "Account is in a tab all the way to end...

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
