### ISSUE TITLE
Java not recognized

### ISSUE THREAD

**Issue by Richy386** [goatfungus/NMSSaveEditor#429]
The system cannot find the file specified.
'java' is not recognized as an internal or external command,
operable program or batch file.

I have java 8 installed so i have no idea why it is not opening the application and why this is popping up on my CMD prompt when i try to open the editor via both batch apps any help?

**Comment by ykokami** [comment]
I have the same problem but no one answered me yet... I used earlier versions of this editor but this one seems to be really troublesome. it should take a few days before it is stable but still would love is someone could help.

**Comment by NobleCa** [comment]
Having the same issue as well. Did an uninstall and reinstall just to see if that would help, but no dice.

**Comment by goatfungus** [comment]
Try editing the .bat file and put in the full path to your java installation.
