### ISSUE TITLE
Milestone for extreme survival not updating in game

### ISSUE THREAD

**Issue by collinbrady** [goatfungus/NMSSaveEditor#43]
The extreme survival milestone was matching what I saw ingame as per what was shown in the save editor. Upon improving the score (from 0.6 to 4.9), nothing has changed in game. I'm also seeing the new score (4.9) when I look at the save editor again since I've played a bit even though it's still showing the old score of 0.6 in the actual game.

Did they change the hooks for these stats?

**Comment by goatfungus** [comment]
I don't think so.... you just need to land on an extreme planet to get the counter to start rolling. Only then will it register the milestone.

I do intend to "fix" this sometime, but this is the workaround.

**Comment by collinbrady** [comment]
Ah no way - I'll give it a try and report back. Thanks!

**Comment by goatfungus** [comment]
I'm assuming this is working now? Will close this issue, and if it's still a problem just reopen with your findings.
