### ISSUE TITLE
Companion Request

### ISSUE THREAD

**Issue by SuicidalFrisson** [goatfungus/NMSSaveEditor#430]
Hello can you please add the ability to import and export pets using the same mechanics as ship export/import? I have been doing it manually and it would be an absolute awesome feature to have. Thank you!

**Comment by goatfungus** [comment]
Now that I have a bit of time, that's next on my list :)

**Comment by SuicidalFrisson** [comment]
When I get my next check I am gonna go and sub to your patreon, you are an absolute legend. Thank you

**Comment by goatfungus** [comment]
This functionality should be available in version 1.8.3... Enjoy!
