### ISSUE TITLE
Curiosities not working for Rewards

### ISSUE THREAD

**Issue by Biostar-Ten** [goatfungus/NMSSaveEditor#435]
In  the save editor <add item> under curiosities are all of the twitch ships and Rewards ships and weapons.
I can get them into inventory and <details> says "on a planet, you can summon this ship" same with the weapons. Doesn't work, Says, "You only have one ship" or "You only have one weapon"
Do I have to put them in the raw Json file?

**Comment by goatfungus** [comment]
Normally, you would add the rewards to your account file, then when you're in-game go to one of the vendors in the Anomaly to activate them.

**Comment by Biostar-Ten** [comment]
Thanks, just wondering what they were for.
