### ISSUE TITLE
version 1.8.3 issues with saving edits

### ISSUE THREAD

**Issue by areithropos** [goatfungus/NMSSaveEditor#438]
In the new version the save file seems to not get loaded correctly. At least not everything gets loaded or is editable.

![Screenshot 2021-09-10 174404_1 - Copy](https://user-images.githubusercontent.com/30437782/132883873-2a46da30-03de-4238-a4dd-14d416241eb9.png)

**Comment by nms2020org** [comment]
similar problem here, "Bases & Storage" tab only loads empty slots. Menu "Edit" is grayed out.

**Comment by Vypir** [comment]
same issue

**Comment by goatfungus** [comment]
Can you send a copy of your log file?

**Comment by Vypir** [comment]
I already rolled back to 1.8.2.  1.8.3 didn't allow me to access ships or the edit menu, nor were the button on the first tab for refreshing and saving active.  It did save on exit though.

The log file got refreshed when I rolled back
________________________________

**Comment by Vypir** [comment]
Okay I reinstalled 1.8.3 in a separate folder.  Here is the log file.
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/7146802/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
Hmmm... it appears that NMS writes two types of seed values for pets, raw numbers and string data. I've only accounted for string data in the editor, so I'll tweak it to read both.

**Comment by goatfungus** [comment]
Ok... should be fixed in version 1.8.5.

**Comment by Mike-Blackwell** [comment]
Brendon, ver 1.8.7 seems to have fix 1.8.5 issues nothing to note
