### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#439]
Brendon, I see you closed issue #422 with the creature tab incorporation but I figured I'd reopen with the other outstanding request..

1) Base Info: is it possible to tally and display as a Total of all Bases Item counts within a SaveFile (within the Base Info tab), you currently display each base parts count which is great (since the total of 16,000 seems to be the real max based on complexities)?

**Comment by goatfungus** [comment]
Do you mean the total of all bases?
I think the editor shows the count for each individual base.

**Comment by Mike-Blackwell** [comment]
Total of all bases. It helps when one is building, whilst the indivisible Bases allows one to figure which one(s) are eating up parts.

Sent from my iPad

On Sep 10, 2021, at 4:24 PM, Brendon Matthews (GoatFungus) ***@***.***> wrote:

﻿

Do you mean the total of all bases?
I think the editor shows the count for each individual base.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgoatfungus%2FNMSSaveEditor%2Fissues%2F439%23issuecomment-917189259&data=04%7C01%7C%7Ca6c8ba0363e44663014108d97498f211%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637669022505007762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B74w3LZPJRaGW%2F6A5OoT%2FUZGsHiCa2lkUqWxUQztJ%2F0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHIA4VAQOHZGYDG7LR52B63UBJSOTANCNFSM5DZ44RZA&data=04%7C01%7C%7Ca6c8ba0363e44663014108d97498f211%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637669022505007762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A%2BaMNDyVmx7aVhqWsTu7UU0dkXl3wIF0Sl789tQooDU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca6c8ba0363e44663014108d97498f211%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637669022505017753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XJcacnjUypvwNieD9REsG%2FyHoqKX%2FTr6ygTo25d7e1I%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca6c8ba0363e44663014108d97498f211%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637669022505017753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5AexiqKpVNEWe6WJVSVS3nwBnnTgnE9SEbth%2FA6byH8%3D&reserved=0>.

**Comment by ykokami** [comment]
I am not being able to open it up can someoen please help me? I installed it plus java 8. it only opens a CMD window then it closes a second later... I created an Issue here but nobody tried to help me yet, Seen other people with similar problems commenting here but no help on in.

**Comment by goatfungus** [comment]
@ykokami I have added a comment on your original issue.

**Comment by Mike-Blackwell** [comment]
Brendon, is this request doable? I know everyone wants something... its interesting how your app with the advent of Frontier has become alive with interest.

**Comment by goatfungus** [comment]
Not sure if this is still needed? Cleaning up
