### ISSUE TITLE
Suggestion: Auto update feature?

### ISSUE THREAD

**Issue by xSINIQx** [goatfungus/NMSSaveEditor#44]
Title says it all, I'm a frickin lazy gamer. downloading a new version every day or so is unacceptable! (jk)
but seriously think about it, it shouldn't be that hard for you to implement. 
Loving the editor, keep up the good work! :)

**Comment by goatfungus** [comment]
Great idea, only I'm a frickin lazy coder!
I have thought about it though, so it might be available before NMS 1.6 ;)

**Comment by goatfungus** [comment]
Update: I am working on a lightweight c++ console wrapper, but might take a little time to ensure I cover all installations.

**Comment by goatfungus** [comment]
I have added a very basic auto-update feature to version 1.5.15, and it works if you run it from one of the updated batch files (not the jar file directly). It's an interim measure until i get the console wrapper finished.

**Comment by diegobh** [comment]
Thank you very much!

I was waiting for the feature to change items amount on ships/vehicles to what i want not to all stack size and its implemented :D 

Now just the auto update feature so this will be perfect!!!

wonderful work!!!

**Comment by BrynM** [comment]
+1 on this request, but failing an autoupdate it might be easy to just whip up a basic packager. Not sure what OS you're on for development, but if it's *nix or Mac, [this](https://github.com/mmckegg/msi-packager) is a great tool for creating Windows `msi` installer packages and not having to run Windows. Going the other direction is sadly a lot harder using OSS tools.

Packaging might be an easier goal, but that's simply my third-party opinion. Happy you update so often as it is. :)

**Comment by goatfungus** [comment]
Current auto-update feature seems to be working ok, so I think I will sideline the c++ wrapper at this stage. I also have too many other things to do. I'll revisit this at a later date.
