### ISSUE TITLE
Ver 1.8.5

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#440]
Brendon, it looks like something broken with the "Account" tab in this release the cmd.exe screen seems to be looping

What's that saying "No good deed goes unpunished!"

**Comment by Viexi** [comment]
Same issue here

**Comment by Spectre-Mike** [comment]
I have same problem. Also for some reason it only pulls up my first multi-tool. 
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/7146930/NMSSaveEditor.log)

**Comment by Mike-Blackwell** [comment]
Same here with multi-tool (only the first seems to show)

**Comment by Viexi** [comment]
@goatfungus has pushed a new fix that has solved the issue for me :)

**Comment by goatfungus** [comment]
Multitool is still broken... working on yet another fix!

**Comment by goatfungus** [comment]
Ok.... try version 1.8.7. It should be all good now :)
