### ISSUE TITLE
Power lines too long, not connecting any longer after base restore

### ISSUE THREAD

**Issue by councilbluffs** [goatfungus/NMSSaveEditor#441]
Hope that I can explain this clearly; maybe you can replicate it in game:
If I use the save/restore function under 'Bases', when I visit the base in-game, all of the power lines seem to be longer or extended, so that the connections are no longer where they should be.  For example, if there is a battery and a solar panel, the power cord between them extends past the connection point on each object.   Also, if you copy the JSON in the editor and paste it into Blender, you can also see that the cords are extended and not in the right place.   However, if you edit the power lines in Blender then re-paste them into the JSON file and save with NMS Editor, then when you open the game, the power lines are all correct. Seems to be something with the saved base file or restore function, since if you make a new one, they are in the correct place.  I just began experiencing this post-Frontiers. Any base that I haven't opened in the Editor is unaffected.  Thank you.

**Comment by goatfungus** [comment]
This is a weird issue, but I think it has been resolved already. Cleaning up
