### ISSUE TITLE
Normal/Community Expedition switch

### ISSUE THREAD

**Issue by Richard127** [goatfungus/NMSSaveEditor#443]
Hi. I edited my save with your excellent software, which I have used for a long time now, without problem. However, my Normal save is now showing as a community expedition save. It's also behaving weirdly in that it tells me a main phase (1-5 in Cartographers) is complete but individual elements show as not completed (you can only complete a phase when all its elements are completed). I'm also getting expedition notifications all the time now, which is frustrating. My main concern is that I will lose my main save when the expedition is finished. I do have a Cartographers save, which is finished but that seems OK. My base computer has also reverted to telling me I have building upgrades available, although I had all building parts months ago. It seems that some of the community expedition save has leaked through to the Normal save (I had also edited the Expedition save at some point).

Main thing that makes me feel it was NMSSE is that when I open it and look at the problem save it says that the main save is Normal . However, when I open it with Nom Nom Save Editor, it tells me it's a community expedition (which is what I see in the game). I've included some screen grabs. I hope this is resolvable. If you don't believe NMSSE is responsible, let me know and if you can see any options for me to turn it back to a Normal save.

![NMS_2021 09 12-00 21](https://user-images.githubusercontent.com/36739322/132966245-4e3b384e-8d14-47f4-b2a3-c41f2e6f6e5a.jpg)

**Comment by goatfungus** [comment]
Interesting issue... well, i can say for certain that NMSSE does not interfere with the game file version number, which used to be responsible for determining the type of save file. However, there was a change made very recently in the game where the manifest file (which sits alongside the save file) now contains the game type and other information. I updated NMSSE so that it is able to handle this information, but I'm not sure whether Nom Noms editor can do this yet.

Steps you could try:
1) Open your save with NMSSE and click the Save button (this will overwrite the manifest file)
2) Open the game up again and see what it displays on the menu screen

**Comment by goatfungus** [comment]
Another thing you could check, in the JSON Editor, what does the Version number say? This should be right at the top of the file.

**Comment by goatfungus** [comment]
Can you send me a copy of your save and manifest file, and i will figure out the difference.

**Comment by Richard127** [comment]
Thanks for your quick reply. I've managed to fix the problem. I used the
backups that the editor makes to restore an earlier version of the save and
it's gone back to normal. Should have tried that last night before
panic set in (lol, I was very tired by then). I'm giving you access to the
corrupted save file via my Google Drive as I thought you might be
interested in what happened, as would I. God alone knows what happened. I
have only lost an evening's play time, so things could have been worse.
Thanks again for your excellent editor. Can't imagine NMS on PC without it.

Here's the save files. Hope it has what you need, as I have no idea what
the Manifest file is. Let me know if you need anything else.
NMS corrupted save file
<https://drive.google.com/drive/folders/1OtE9d0h6QTT5Jpa-t1N4gXgtKHr5dYef?usp=sharing>

**Comment by Richard127** [comment]
Just in case anyone else lands here. This bug was acknowledged and fixed by Hello games and only involves normal saves that were converted from previous expedition 2 saves .
