### ISSUE TITLE
Exocraft inventory slots not enabling.

### ISSUE THREAD

**Issue by Vypir** [goatfungus/NMSSaveEditor#446]
Exocraft inventory slots not enabling.
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/7150166/NMSSaveEditor.log)

Here is my log file, I don't see anything pertaining to the slot expansion, but I tried to do them individually and it didn't let me, I also tried the expand all slots command in the menu.

Thanks :)

**Comment by goatfungus** [comment]
Exocraft slots are fixed in game, so any changes you would make in the editor would be lost. I disabled the function for Exocraft.
