### ISSUE TITLE
Name Mapping Not Found

### ISSUE THREAD

**Issue by Raevyn-Darke** [goatfungus/NMSSaveEditor#447]
Hi, new user. I loaded my NMS save file, but was unable to save file/account. I noticed this in the command file:

  WARNING: name mapping not found: D=h
  WARNING: name mapping not found: ?6B

Am I doing something wrong? Thanks.

**Comment by goatfungus** [comment]
Cleaning up. This is a common warning which just means that the editor found new stuff in the save file it doesn't know about.
