### ISSUE TITLE
Really big help needed with surveying the planet

### ISSUE THREAD

**Issue by Watchman3001** [goatfungus/NMSSaveEditor#449]
Good evening. Right now, I have a really big problem, cause I decided to survey my home planet (with the base) completely, so all flora, fauna, and minerals. So, everything went well, until... Well, I have 16 out of 17 minerals (according to in-game counter). No, I already wasted literally hours, nights, just roaming around the planet and looking under my feet. My planet has no water, and surface/caves are already explored. So, I gave up, and was really surprised that I can't mark this last mineral as surveyed (or maybe know details about it, it's location) in save editor.

So, maybe you, as a professional, may help me with this thing? Somehow find it via code, or tell where is it supposed to spawn? I can provide my save files, or anything else you need. Don't want to bother you, but that is REALLY important to me, I am already turning crazy becdause of that. Thank you for your support, in advance

**Comment by goatfungus** [comment]
There is no way to help you, sorry. The game is procedurally generated, and the methods it uses to create planets is a closely guarded secret by Hello Games.
