### ISSUE TITLE
How to delete Items that cant delete in game ?

### ISSUE THREAD

**Issue by ivanNMSplayer** [goatfungus/NMSSaveEditor#450]
![1](https://user-images.githubusercontent.com/90747173/133377084-27c5a359-7034-422b-8ec2-70d90279c786.jpg)
 
is there a way that I can delete this item?
I added this blueprint in my normal game to test something, but i can delete this item inside the game, is there a way that i can delete this using NMS Save Editor? 

Thankssss

**Comment by xaminmo** [comment]
You should be able to right click and at the bottom of the list is "Remove item".
Be sure to add in a normal hyperdrive of some sort to replace it.
