### ISSUE TITLE
Some new mappings I found in the save data (NMS 3.67)

### ISSUE THREAD

**Issue by Devilin-Pixy** [goatfungus/NMSSaveEditor#452]
Below the naming for the new mappings found

D=h = InventorySubIndex
hiD = NextBuildingUpgradeIndex
:Qn = NextBuildingUpgradeClass
xru = NextBuildingUpgradeSeedValue

If you would be so kind to include these again ;-)

On a side note:
Monkeyman is now releasing a mappings.json with each MBINCompiler version released.
https://github.com/monkeyman192/MBINCompiler/releases
Just wanted to let you know, as you may find it useful.

Keep up the good work!

**Comment by goatfungus** [comment]
I appreciate the help, I'll pop these in the next release.
