### ISSUE TITLE
Settlement Stat changing

### ISSUE THREAD

**Issue by ScoutKatan** [goatfungus/NMSSaveEditor#454]
Not really an issue but maybe a suggestion to be used.
Would be cool if you could change the stats of your settlements (happiness, maintanence) similar to the menu that frigates have where you can change its traits
ill attach an image

![image](https://user-images.githubusercontent.com/76965290/133867006-d8bf4bc3-2fb9-4c7f-84af-af33b5b6dc4b.png)
![image](https://user-images.githubusercontent.com/76965290/133867027-fd598742-1926-4056-8bd6-517f8dd4bba3.png)

**Comment by Scorp969** [comment]
in edit - Edit Raw json  - player state data - settlement states V2 - find your settlement name at the bottom there you can change a lot of the stats under stats/perks (backup your save) i just dont know nams of stuff that can be put there so its trial and error
those stats will look different becouse they are in default  not affected by perks there

**Comment by goatfungus** [comment]
I have added a settlement tab to version 1.9.5. It doesn't yet support traits, but everything else should be working including production.
