### ISSUE TITLE
Select the NMS folder will cause the selecting menu to "crash" and unable to open any save files

### ISSUE THREAD

**Issue by Invalidcod3** [goatfungus/NMSSaveEditor#457]
I downloaded the latest virsion, extract it to a new folder, and open it, this happened.
![java_Jgro1c68wn](https://user-images.githubusercontent.com/90977246/133894512-adc3a0c3-4ac0-4dec-9f41-570a6915ceda.png)
The selection menu is complete empty and just nothing, it seems crashed as soon as I increase/decrease the window.
![java_6FXFwun9P2](https://user-images.githubusercontent.com/90977246/133894562-05477752-bad4-4a75-9e55-535e9538c6c9.png)
I tried change the language, didn't work.
Checking the new updates for OS and the graphic card for the latest versions, didn't work either.
Checking the starter if there is any relations to the file selection, didn't work too.
Closed the virus scanner didn't work.
I also using the VM, it worked.
So I tries to remove the Hellogame folder to somewhere else, but it is still unable to access either.
But if you copy your game save to somwhere else, it can open the save file.
I move the Hellogame folder to the place where it used to be, and select it manually. When I opened the NMS folder, the menu crashed either, I just don't know why. Other players can use it quite well.
I tried the ealier visions of the editor, it can't open either. 
The NMS folder is set to be "Read Only", but the selection menu can access other "Read Only" folders normally.
Here is the log file after I opening it.
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/7190843/NMSSaveEditor.log)
However, before the game updated to the frontier virsion, I can use the save editor to access the NMS folder normally, but after updated the game and the editor, it didn't work anymore.

**Comment by goatfungus** [comment]
The editor uses the Steam API to find your username, this process happens when you navigate to the steam account folder, and usually after a few seconds when it has found what it needs it will show the saves.

I have thought about removing that feature, but was going to use it to lock out base editing for bases owned by other users so it has been left there in the meantime. I'll will come up with a better solution when i find it.

**Comment by goatfungus** [comment]
I have released a new version which should fix this problem.
