### ISSUE TITLE
Frontiers - unable to see all save games

### ISSUE THREAD

**Issue by bittwiddlers** [goatfungus/NMSSaveEditor#458]
This is running the latest Frontiers with the latest editor version 1.8.7

I have two "older" style games in slot 1 and 3 that I can open fine. My usual game, Permadeath in slot 2, is not show on the File Open dialog at all. I can see the files (numbers 3 and 4) is the directory and it loads fine in NMS.

**Comment by goatfungus** [comment]
Can you please send me a copy of your NMSSaveEditor.log and the game files themselves?

**Comment by bittwiddlers** [comment]
just emailed

**Comment by goatfungus** [comment]
I have just released a new version, 1.9.1, which should fix this issue.

**Comment by bittwiddlers** [comment]
Looks like it works fine now. Thank you
