### ISSUE TITLE
Exocraft

### ISSUE THREAD

**Issue by Leisha-Lockwood** [goatfungus/NMSSaveEditor#459]
The answer to this is probably no.  I have edited my JSON file to give my exocraft 48 slots each.  Been through each vehicle line by line and in SE I have all 48 slots open and enabled for every vehicle.  I go into my game, build my craft and the vehicle doesnt have the 48 slots.  Ive tried everything I can think of including filling every one of the 48 slots to "force" the game to recognise the new configuration and it still wont. Im assuming that there is something in the coding of the game that prevents SE from modifying the configuration.  I was hoping that either there could be a bypass to this or an overwrite to the game code in SE so the configuration will stick to the game or if you know where the game code which relates to exocraft is and can tell me so I can edit the code for my own game to enable the change.

**Comment by Scorp969** [comment]
exosuit technology and exocrafts reverts back when changed you need mods from nexus for that didnt see(find) working exocraft mod for a while now 
for exosuit  ( https://www.nexusmods.com/nomanssky/mods/2006 )
in edit enable test mode it will allow you to change other inventory sizes over limit
