### ISSUE TITLE
Reset Missions, or progress with Base NPC

### ISSUE THREAD

**Issue by Vlasovas** [goatfungus/NMSSaveEditor#46]
In Bases & Storages, make it possible to reset the NPC missions from the base of the 4 types separately, be it armorer, farmer, Overseer, or Scientist, or be able to restart progress separately among the 4 NPC's as if you had not hired him yet!

Reason: Bug missions not complete, in other cases the game does not count what was done and the mission can not be delivered! 
In my case the mission to destroy 3 Depots, did not count the 3 that I destroyed and I can not pass this mission or deliver
Being able to either resume everything or reset the mission with that master we are not trapped without being able to evolve!

**Comment by Unbelievablee** [comment]
Thats a great suggestion. I have a few questlines bugged and this feature could help me immensely.

**Comment by Rianon** [comment]
Totally agreed, need this too.

**Comment by goatfungus** [comment]
This is similar to issue #36 
When I figure out all the ins and outs of missions, I plan to add the ability to change your mission progress.

For now though, I'll close this issue to keep the list tidy.
