### ISSUE TITLE
Extra Warning Messages during NMSSaveEditor intialization sequence

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#461]
Brendon,
I noticed that at the end of loading ones savefiles we seem to get the following warning (see below)

```
  using name mappings: NMS 3.6
  WARNING: name mapping not found: hiD
  WARNING: name mapping not found: :Qn
  WARNING: name mapping not found: xru
  Finished.
```
Firstly what is it and is it a problem?

**Comment by goatfungus** [comment]
It just means there are new structures in the save file that were added. It's not an issue, you can carry on with this sort of warning.

**Comment by Mike-Blackwell** [comment]
Brendon, Thanxs for the comeback and edumacation (sic) per chance is there anyway of knowing what they might be... I guess with the numerous HG releases there's bound to be changes....
