### ISSUE TITLE
Feature Request: Ship Slots 0 - 5

### ISSUE THREAD

**Issue by pomarf** [goatfungus/NMSSaveEditor#462]
There is a guide on how to do it here: https://www.reddit.com/r/NoMansSkyTheGame/comments/hupw2j/guide_how_to_change_default_ship_spawn/

But I was wondering if this is something that might be possible via a drop-down menu or something inside the "Ships" tab.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
