### ISSUE TITLE
PS4 Save Support - Testing Required

### ISSUE THREAD

**Issue by goatfungus** [goatfungus/NMSSaveEditor#463]
If anyone out there has a PS4 save file (memory.dat) that I can test out, especially one from after Frontiers, please post it in a comment here. I'm nearing a solution for this and just need some data to test.

**Comment by louanfontenele** [comment]
Here is my PS4 Save Games:

[sce_sdmemory.zip](https://github.com/goatfungus/NMSSaveEditor/files/7229137/sce_sdmemory.zip) (memory.dat)
[savedata02.zip](https://github.com/goatfungus/NMSSaveEditor/files/7229136/savedata02.zip) (savedata02.hg)
[savedata03.zip](https://github.com/goatfungus/NMSSaveEditor/files/7229138/savedata03.zip) (savedata03.hg)

**Comment by louanfontenele** [comment]
@goatfungus Do you need someone to test? Anything sends me the trial version I test here on my PS4.

**Comment by louanfontenele** [comment]
No Mans Sky PS4 - Version 3.67

[NoMansSky-PS4-3.67.zip](https://github.com/goatfungus/NMSSaveEditor/files/7230652/NoMansSky-PS4-3.67.zip)

**Comment by louanfontenele** [comment]
No Mans Sky PS4 - Version 3.67
[savedata02.zip](https://github.com/goatfungus/NMSSaveEditor/files/7230876/savedata02.zip)
[savedata03.zip](https://github.com/goatfungus/NMSSaveEditor/files/7230877/savedata03.zip)

**Comment by goatfungus** [comment]
Just released a new version, 1.9.5, with support for PS4 saves that have been exported from Save Wizard.

**Comment by Callmehec** [comment]
Hello, i have been using it for the past few days and i noticed that Multi-Tools are not being edited. In fact i have a few multi tools and it cant even read them, i also tried on a different game type and it cannot edit the multi-tool.

Also a quick question, is there a way to unlock expeditions rewards on PS4?. i looked around and cannot find the info.

**Comment by garrydaowl** [comment]
> Hello, i have been using it for the past few days and i noticed that Multi-Tools are not being edited. In fact i have a few multi tools and it cant even read them, i also tried on a different game type and it cannot edit the multi-tool.
> 
> Also a quick question, is there a way to unlock expeditions rewards on PS4?. i looked around and cannot find the info.

I'm also wondering how as well as account page is greyed out unfortunately for PS4 saves

**Comment by jimmgc** [comment]
Hi. Can any of you guys post some instructions? I have the latest save editor and save wizard but cannot get it to at least open in save editor. Not sure what I'm doing wrong. Extracted file from save wizard but doesn't open in save editor. Please post how a "how to" to make it to work on save editor.

**Comment by louanfontenele** [comment]
In few days i'll post a tutorial here, how to use it....

**Comment by Pd69bq** [comment]
k, I think I figured out how to use it on PS save files. currently, there are two different types of save files on the PS, there's a older format which is auto and manual saves "all-in-one", and exported filename is "memory.dat"

and there's a newer format after v3.6.2 with "player.state.X" commented under the file in PlayStation. auto save and manual save r separated, and exported filename becomes "savedataXX.hg", and this is the compatible format for the save editor

**Comment by cyberpunk2350** [comment]
> and there's the newer "PlayerState.X" format after v3.6.2, same as steam version, auto saves and manual saves r separated, and decrypted/exported file names become "savedataXX.hg", and _this is the compatible format_

I can confirm that this works with version 1.9.7
thank you!

**Comment by stoneylsd** [comment]
> Just released a new version, 1.9.5, with support for PS4 saves that have been exported from Save Wizard.

I'm using savewizard on PS4 and it won't find my savefile no matter if it is in .JSON or .hg, any ideas? I am not quite sure what else to try

**Comment by capndank** [comment]
I knownthis is mostly for ps4 but what about xbox/microsoft version


I cant find any back up saves or anything to work on my saves on the editor i have logged into nms on the comutor several times and the xbox and nothing has saved to the save editor i cant find anything besides default user and cache and they are both empty but my nms has the same save files on my pc from my xbox.

I am super confused can anyone please help me out!

**Comment by JackMickey** [comment]
I've succeeded in modifying the PS4 save file (.hg) with NMS save editor as well as NomNom and currently have it backed up on my laptop. My question is how do I import the modified .hg file back into Save Wizard?

**Comment by goatfungus** [comment]
Cleaning up old issue
