### ISSUE TITLE
ROLOAD FILES FAIL

### ISSUE THREAD

**Issue by Mrlandy** [goatfungus/NMSSaveEditor#464]
Since the new update couple days ago . ive been trying to click on '' No''  when the save editor ask me if i wanna reload so i can keep the same inventory and nothing work , now ive also tried to click on ' yes '' and nothing seems to work. everytime i log out the game to get some stuff on save editor , i have to close save editor and open it again and look into my backup save to get one with a full inventory. Thank you for helping me with that issue !! :)  heres what save editor show and here's the log 
![Capture](https://user-images.githubusercontent.com/91294923/134597609-916e2c4c-644f-44bd-9f5c-2630834bbaaf.PNG)
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/7221313/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
Oooh, you're right.... I'll fix this ASAP.

**Comment by Mrlandy** [comment]
THANK YOU SO MUCH WOW !

**Comment by goatfungus** [comment]
This issue is fixed in version 1.9.3. Enjoy!

**Comment by Mrlandy** [comment]
you're doing god work , tysm
