### ISSUE TITLE
Player Title unlock?

### ISSUE THREAD

**Issue by Zacplin** [goatfungus/NMSSaveEditor#467]
We can now find the unlocked titles under the account save file. Perhaps we can have the option to unlock them all?

I will provide a list in the text file below (in alphabetical order). I don't really know what they correspond to thought. 

[nms titles.txt](https://github.com/goatfungus/NMSSaveEditor/files/7230776/nms.titles.txt)

I only have rift-walker and one of "the timeless" titles locked, and I don't have the "iteration 1" title. If people can finish filling the list above, it would be appreciated.

**Comment by goatfungus** [comment]
Good idea... when I've finished messing around with support for PS4 I'll get right on it :)

**Comment by Markedone3314** [comment]
> We can now find the unlocked titles under the account save file. Perhaps we can have the option to unlock them all?
> 
> I will provide a list in the text file below (in alphabetical order). I don't really know what they correspond to thought.
> 
> [nms titles.txt](https://github.com/goatfungus/NMSSaveEditor/files/7230776/nms.titles.txt)
> 
> I only have rift-walker and one of "the timeless" titles locked, and I don't have the "iteration 1" title. If people can finish filling the list above, it would be appreciated.

Hey I love the save editor its amaxzing, I was looking through the Wiki and I think the Iteration-1 title is "T_OLD" and the Rift-Walker title is "T_WEEKEND"

hopefully this helped, and maybe you can add a nice GUI for unlocking the titles in the Save editor.

I would also like to ask if we can get the pre order Xbox helmet as well.

Keep up the good work.

**Comment by Xarumondx** [comment]
i also would like to be able to unlock titles due to a few of them being buggy for me and not popping im the kind of guy who is about to completely restart just to hopefully unlock them.  But i found this save editor and i've heard its available now but im completely oblivious on how to do this thanks!!!

**Comment by lyravega** [comment]
Ahhahah... for some reason, the default title was locked for me... you know, the one without anything, just your name. Had to edit my save and add T_DEFAULT to the unlocked list. 

Man, I need to start a new save and transfer my existing tools/ships/etc... to it to get rid of old save issues.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
