### ISSUE TITLE
About version 1.9.3 

### ISSUE THREAD

**Issue by Maverick1000** [goatfungus/NMSSaveEditor#468]
Does this version work  with the frontiers save game files? Reason for this question I am getting "There was an error saving the file."    The jar application is able to open the file, read it and show information in the tab windows.

**Comment by goatfungus** [comment]
Yes it does, though a few people have said that antivirus can stop this from working, so if you add it to your exceptions you should be ok.

**Comment by Maverick1000** [comment]
I forgot to tell you running Windows 10. I have not install any antivirus, unless Window 10 install one be default.

**Comment by Maverick1000** [comment]
Determine that it was not an antivirus issue, it had do with not running it on a drive that has Windows 10 installed.  Unless your application id hard coding same variables 

So I think you should look at what your code to see what is doing when running the jar file on a drive that does not have Windows 10 or the path with save games.

**Comment by goatfungus** [comment]
Can you send me a copy of you NMSSaveEditor.log file?

**Comment by Maverick1000** [comment]
The drive that has Windows 10 and the path to the save game files, has a log and config file for your editor, but my D: drive, which has the issue, the config and log file are never created.  So I am unable to sending you anything.   As for your Java Save Editor program are you assuming that who ever download it,  would always run it on the same drive that the save game files are located.   Trying running your jar file in debug mode on a drive that has no path to your No Man Sky save game folder, to see why it would show “There was an error saving the file”.   Sent from Mail for Windows From: Brendon Matthews (GoatFungus)Sent: Tuesday, September 28, 2021 9:54 PMTo: goatfungus/NMSSaveEditorCc: Maverick1000; AuthorSubject: Re: [goatfungus/NMSSaveEditor] About version 1.9.3 (#468) Can you send me a copy of you NMSSaveEditor.log file?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by goatfungus** [comment]
I'm running it myself on a different drive, and don't have this problem.

I believe that it is Java being blocked access to write to any drive on your PC. Other people have had this issue in other threads and resolved it themselves by allowing Java access. I might have to dig through the messages to find what they did, but this sounds like the same problem. Once you allow access it will work fine.

**Comment by goatfungus** [comment]
Similar problem was mentioned here:
https://github.com/goatfungus/NMSSaveEditor/issues/369

In that case, the user found out that it was AVG that was blocking it, and all they had to do was add an exception.

**Comment by Maverick1000** [comment]
Thanks for the suggestions. As it stand as long I run the application on the Windows 10 drive, it is has no issue with saving the changes that I make.
