### ISSUE TITLE
The edited save is not showing into the game

### ISSUE THREAD

**Issue by luisbleriot** [goatfungus/NMSSaveEditor#469]
Hello, first of all thanks because of your work with this proyect. My english is a little bit poor but I will try to explain my error.

When I want to edit my save, for example adding some wiring loom or whatever and finally I save that modification of the save. When I turn on the game, that save is not detected by the game. But the original save yes it is

**Comment by goatfungus** [comment]
Which version of NMS are you running? Steam / PS4 / XBox?

**Comment by goatfungus** [comment]
Also, make sure that you log right out of the game before trying to load the save.... the game itself will not detect changes while you are playing.

**Comment by luisbleriot** [comment]
Im using GOG version (PC) and I always close the game before using your editor

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
