### ISSUE TITLE
Another seed type for primary color?

### ISSUE THREAD

**Issue by LeopoldHock** [goatfungus/NMSSaveEditor#47]
Hey!

I did some playing around with the capital ship seeds and it seems that the "model type" seed only changes the ship's actual shape now, whereas the "home seed" changes its secondary color. This suggests there is a third seed now in NEXT that controls the ship's primary color. Did you find something like that in the files? Would be really cool if we could change the primary color directly, as there doesn't seem any way to change it right now through the two seed types.

**Comment by goatfungus** [comment]
Those are the only two seeds I've found for it. Maybe there aren't very many primary colours in-game for freighters? I am not sure. If you find the reason in your testing feel free to post it here and reopen this issue.

**Comment by LeopoldHock** [comment]
You're right, those are the only two seeds in there. I'm not sure, maybe it's a bug with NEXT. It's highly unlikely that I every seed I tried generated the same primary color. I'll wait a little, maybit it's a known issue at HG.

**Comment by LeopoldHock** [comment]
Change the home seed.

**Comment by sasha830s** [comment]
LeopoldHock, but how? can more accurately describe the process. If you mean a 16-digit number, what exactly is the number responsible for the color? sorry, I do not know how to do this and I do not know English. Thank you.

**Comment by LeopoldHock** [comment]
Yeah, the 16-digit number is a "seed" and stands for a specific color. It doesn't matter what you change, because every digit you change will result in a different seed ant thus a different olor. Just change the last digit to a letter, for example A. Save and check the color. Don't like it? Change it to a B, C, D and so on. Repeat until you until the color is to your liking.

**Comment by sasha830s** [comment]
thanks, but any changes lead to the replacement of the ship itself, not the color. This is an exotic ship, it remains for them, but with another wing, etc.

**Comment by LeopoldHock** [comment]
This thread was about freighters, not standard ships. I looked through the save file and it seems that standard ships still have one seed that controls both the model and the color, so no changing the color without changing the ship model.
