### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by Captsalt** [goatfungus/NMSSaveEditor#470]
When attempting to D/L ver 1.95, I get a virus warning and the file will not download. I'll turn off my Webroot antivirus and try again. PLEASE confirm the file is clean. Thank you,
Don McMahon

**Comment by goatfungus** [comment]
The file is totally clean. Sorry for the false positives.

**Comment by m0lz** [comment]
Its only webroot giving this false positive thinking its adware, everything else finds no issues ..
https://www.virustotal.com/gui/file/b6aff7ff4eee580c88401b7040d53a7a57e5c8da37347310c918cd07cf5986e3

**Comment by roadapathy** [comment]
Virus total said it's perfectly clean. I have never seen anything with no false positives until this one. :-D LOL

I'm glad somebody brought this up though because I need to get use to using Virustotal. I normally just use Linux so I forget Window's minefield.
