### ISSUE TITLE
Feature Request: Ability to edit planet and system discoveries

### ISSUE THREAD

**Issue by Melonization** [goatfungus/NMSSaveEditor#471]
As the title says, I'm asking this because somebody came to a perfect system I just found (I don't know how) and uploaded the system without editing the name, which really annoys me because they just left and they dont care about the system, but now I'm stuck in a system which the game says is somebody elses.
Thanks!

**Comment by ukmerlin** [comment]
Discoveries are not save editable. They are uploaded to NMS discovery servers where everyone can see them.
