### ISSUE TITLE
Thanks and question about Twitch and base timer

### ISSUE THREAD

**Issue by tribolus** [goatfungus/NMSSaveEditor#472]
First of all, thank you for developing this. I had a fleet that was stuck on expedition and wouldn't return. The editor allowed me to correct the timer so I've got my fleet ship back.

I also have a problem with my base computer not giving me the option to download the next set of blueprints, its almost like the timer on that has stopped, any idea on where in the save file I could kick that to get it working again?

My final question is on twitch rewards, how can I activate them? Is it to tick the option in the editor, save, open the game in off line mode (no internet connection) claim the rewards save and re-open with an internet connection?

**Comment by goatfungus** [comment]
I'm not entirely sure about the timer for blueprints, sorry.

As for Twitch, yes.
- Save and exit the game completely when you're inside the anomaly.
- Tick the unlocks in the editor.
- Start the game up with no internet connection, and claim the rewards.

The rewards will eventually drop from your account settings file once it syncs back up with Twitch, but what you've claimed should remain in your save file.
