### ISSUE TITLE
Freighter storage listed under base storage, not differentiated

### ISSUE THREAD

**Issue by Philomorph** [goatfungus/NMSSaveEditor#476]
Thanks for the great tool!

I hadn't played NMS in a while, so when I came back in a few weeks ago I was happy to see that they added storage vaults for your freighter that are separate from your base vaults.

In the editor, these appear to just be listed along with your base storage, with nothing to indicate which is which.

Is this on purpose, or planned for an update?

**Comment by roie-r** [comment]
The _Freighter storage unit_ points to the same storage as the planet-base _Storage Container_ - They are **not** separate.

**Comment by roie-r** [comment]
Yes, they are distinct base parts, but that's besides the point... **ID: CONTAINER0** (base storage 0, which can't be placed in a freighter) and **ID: S_CONTAINER0** (freighter storage 0, which can't be placed in a planetary base) both lead to the same place in your save: **Chest1Inventory**.

**Comment by xaminmo** [comment]
Recommend this be closed because there is nothing for the NMS editor to do here.
