### ISSUE TITLE
Linux compatible?

### ISSUE THREAD

**Issue by Johnathon759** [goatfungus/NMSSaveEditor#477]
Was wondering if there will ever be a Linux version. As I love this editor. Very handy on some things.

**Comment by IndiumDrive** [comment]
Which distro do you use? I tried mint and proton and couldn't get NMS to boot up.

**Comment by jms1989** [comment]
The editor runs great on linux except now seems to only be offered as a self-extracting exe which is no good for us linux users. why do we need wine or a windows vm to extract something that already runs with java? :/ 

all I do is set the execute bit on the jar and just double click it from dolphin or nemo.
