### ISSUE TITLE
Save stopped showing in NMSSE

### ISSUE THREAD

**Issue by BeardedGrizzlyGaming** [goatfungus/NMSSaveEditor#478]
Playing on PC on the Game Pass Version. Slot 2 stopped showing in nmsse, but still shows in game and is playable.

**Comment by voxtechX** [comment]
I have this issue as well i think its because i edited the json file but im not too sure

**Comment by capndank** [comment]
I cant find any back up saves or anything to work on my saves on the editor i have logged into nms on the comutor several times and the xbox and nothing has saved to the save editor i cant find anything besides default user and cache and they are both empty but my nms has the same save files on my pc from my xbox.

I am super confused can anyone please help us out!

**Comment by capndank** [comment]
I figured something out
