### ISSUE TITLE
feature request ! add learn all know technology and product 

### ISSUE THREAD

**Issue by lima12** [goatfungus/NMSSaveEditor#48]
i did push this one up yesterday but somehow didn't see it on the issue board ! 
yes adding one by one at a time is kinda frustrated ! 
also there is a bug when press learn all word will not show up in discovery ingame ! 
and may i ask if there anyway to change the save gamemode ?

**Comment by goatfungus** [comment]
Originally this was intended to add missing blueprints that the game didn't grant correctly because of a bug in-game. I will need to do a bit more digging in the game files to find out which ones are actually buildable before this is done, but I'll add it to the list.

**Comment by lima12** [comment]
thank for your hard work !

**Comment by Gussifriz** [comment]
You already can add every technology and product at the same time ! Clic on "Add technology" then select the first one, go to the last and use shit + left clic. It will select every things between first and last, and then just clic on "add".. Done !

**Comment by lima12** [comment]
btw do we have option to choose the exact tech upgrade rank ? i mean i have to seek every star to find the S rank for my ship ! maybe in JSON file  ?

**Comment by Gussifriz** [comment]
Product > Consumable for the techs upgrade rank ^^
Search better

**Comment by lima12** [comment]
thank <3

**Comment by Gussifriz** [comment]
Np, good game ! Have fun breaking the game lol <3

**Comment by Gussifriz** [comment]
@goatfungus I think you can close the issue, except if you really want to implant the "add all technology / product" button lol

**Comment by lima12** [comment]
yea i will close it
