### ISSUE TITLE
Missing name mappings for NMS 3.7

### ISSUE THREAD

**Issue by QuestionableChanges** [goatfungus/NMSSaveEditor#482]
Expedition 4 brought NMS 3.7

I cannot manually edit the JSON, changes don't apply.
Also on loading the save game this error shows up:

Reading save file...
  Slot: Slot 6 - EXPEDITION - Oct 22, 19:49
  Filename: save11.hg
  using name mappings: NMS 3.6
  WARNING: name mapping not found: oEc
  WARNING: name mapping not found: qs?
  WARNING: name mapping not found: O?u
  WARNING: name mapping not found: 7fn
  WARNING: name mapping not found: ;MW
  WARNING: name mapping not found: mVE

**Comment by jwolfm98** [comment]
Adding to this - Updated last night to the newest patch (Pc Version through steam)
Error output is:
Initializing environment...
Starting Editor...
Reading metadata for accountdata.hg
Reading metadata for save7.hg
  Version: 1
  TotalPlayTime: 44:09
Reading metadata for save8.hg
  Version: 1
  TotalPlayTime: 44:10
  using name mappings: NMS 3.6
  WARNING: name mapping not found: rfa


What I do know is that it worked, multiple times, until I went a little deeper in the save file editing. I re-rolled some seed values on ships, made a lot of upgrades to freighters, languages. Eventually I must have hit something that wasn't added.

**Comment by goatfungus** [comment]
Generally this isn't a problem. If the editor doesn't know about a particular mapping it will simply leave it as-is and you can carry on editing as normal.

Anyway, I have just uploaded a new version with all the mappings I could find, so it should be all good to go.

**Comment by jwolfm98** [comment]
I see! Yeah it worked just fine. I thought it was a problem because I had
disabled a connected monitor in windows display settings and never saw the
gui appear.

Turns out there's some bug where it still defaulted the gui to appear on
the disabled monitor, so not visible at all - which sounds like a windows
thing to me, not the program.

**Comment by ClockwiseCounterclockwise** [comment]
Hello, Game keeps crashing when warping to one of my bases, and ran the editor.  Came up with the following:

Reading save file...
  Slot: Slot 2 - NORMAL - Nov 27, 11:39
  Filename: save4.hg
  using name mappings: NMS 3.6
  WARNING: name mapping not found: >CR
  WARNING: name mapping not found: EG=
  WARNING: name mapping not found: apf

Any assistance is appreciated.
