### ISSUE TITLE
This is not a issue NVM IT IS

### ISSUE THREAD

**Issue by Mrtrex525** [goatfungus/NMSSaveEditor#485]
What file do I need if its the save game I dont know where that is.
It would really help if you could tell me

**Comment by goatfungus** [comment]
Sounds like you have moved your save files from where they should be under C:\Users\USER\AppData\Roaming to your D drive. If you move them back again you should have all your save data back.

The editor cannot move any folders around, so you can't really blame anyone else for this mistake.
