### ISSUE TITLE
Apparently I don't have permission to open the file

### ISSUE THREAD

**Issue by Brickticks** [goatfungus/NMSSaveEditor#488]
Downloaded latest version, went to open it, and it said I didn't have permission to open the file.  Help?

**Comment by goatfungus** [comment]
It may be that the exe is blocked by your antivirus or something.

You should be able to download the ZIP version directly [here](https://github.com/goatfungus/NMSSaveEditor/raw/master/NMSSaveEditor.zip).

Open this with 7zip or any other zip extraction program and extract all the contents to some place on your computer. Then you should be good to go.
