### ISSUE TITLE
Wiring not copying correctly with base copy/backup

### ISSUE THREAD

**Issue by biffrapper** [goatfungus/NMSSaveEditor#489]
In latest Frontiers I copy a base and then import to a new save and none of the wiring connections are functional anymore.  I have to rewire the entire base part by part in order for this to work.  For a base that has hundreds of wires... this is a nightmare.

Why are the connections not being carried over?

It is as if every single wire has become disconnected.

edit:  after further examination it seems every wire attachment point, the plug end, has been shifted by one unit to the left or right of the socket, so they have been moved past the sockets of whatever light or device they were connected to.  Curiously the wires themselves remain connected to one another, so they retain cohesion.  It is only with the physical objects that the problem exists.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
