### ISSUE TITLE
Recent Updates Prevents Saves from Opening Properly

### ISSUE THREAD

**Issue by kevindunn1981** [goatfungus/NMSSaveEditor#492]
Last night NMS received an update on STEAM. Now when I open the editor it provide access only to backups and not the most recent files. Please help.

**Comment by capndank** [comment]
I cant find any back up saves or anything to work on my saves on the editor i have logged into nms on the comutor several times and the xbox and nothing has saved to the save editor i cant find anything besides default user and cache and they are both empty but my nms has the same save files on my pc from my xbox.

I am super confused can anyone please help me out!

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
