### ISSUE TITLE
Save game to old?

### ISSUE THREAD

**Issue by Shuvi-Hub** [goatfungus/NMSSaveEditor#496]
I keep it short.
I used the editor and saved every thing but NMS does say the save is to old...
I have observed that the size has dropped from 1.21 MB to 145 KB

for example:
[save.zip](https://github.com/goatfungus/NMSSaveEditor/files/7654164/save.zip)

(I just maxed all inventories)

and this is my real one:
[save.zip](https://github.com/goatfungus/NMSSaveEditor/files/7654169/save.zip)

**Comment by Devilin-Pixy** [comment]
Usually when NMS says the save is too old, it requires loading the save and then saving again to have it updated to the latest version.

Your 'real' save says it has version 4645, which is a 'normal' mode save, but indeed not the latest version (currently 4647).

So try the above to update the save, then use the Save Editor again after
