### ISSUE TITLE
After opening save my object count for bases is minimal

### ISSUE THREAD

**Issue by pneuma22** [goatfungus/NMSSaveEditor#498]
After touching my nms with the save editor just by opening the save file it caused this on every slot related to the same save that is. I can make a base but I get about 45 objects before I can't place anymore which before that the count was 3000 objects. Definitely, an error going on with the editor upon opening the file. I actually only copied slot 1 edited and save as slot 2. It looks like the opening of the file is what did it as it can't read a lot of the new stuff that needs to be translated. I troubleshot a bit and found a backup of my save in an acronis file so that fixed alot of my issues.
I Also Noticed some weird ship dynamics problems when taking off after opening and saving with the save editor. Very strange issues.  Granted I should have known with the error upon opening it I shouldn't have saved the file to a slot.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
