### ISSUE TITLE
INFO: Ship Deletion behavior

### ISSUE THREAD

**Issue by rtjunkie** [goatfungus/NMSSaveEditor#50]
So I purchased my game-limit of 6 ships recently, and sought to replace one of my original ships with a new one. However, instead of flying my old rust-bucket around so I could Trade it, I chose to simply delete it and purchase a replacement outright when I found one. Interestingly, prior to this deletion, I had renamed this ship in-game to "Bob". Once I deleted the ship, all was well, and I had a free slot open to make a new purchase. 

Once I found a suitable ship, upon purchasing it, I saved my game and shut it down so I could edit the new ship in the Editor. Surprisingly, this new ship was named "Bob"! I didn't notice the modified name in-game before I closed it, so I'm not sure if my renamed title was added directly to the ship, or if it somehow only appeared in the Editor as leftover data. The original ship I deleted was in Slot [1], and the new replacement ship went to Slot [6] with the old name. I need to play with this a bit more to see if there's any further detail to the behavior, but I thought you might find this potentially valuable since it might show how the game is handling certain data fields within the JSON. 

-Nate

**Comment by rtjunkie** [comment]
I referenced this issue from my original issue, #42, due to some new discoveries. Please also check my reply in that thread, since I couldn't figure out if there was a method to reopen that issue. Thanks!

**Comment by goatfungus** [comment]
Ship deletion doesn't physically delete ship data, as the game expects there to be EXACTLY 6 ship slots. Instead it resets the seed value, which the game detects as an open slot. When buying a new ship, the game appears to reorder the ships, and the newly purchased ship appears at the end of the list.

I ran this test multiple times and bought new ships. Everything was working as intended. If this isn't happening now then it might be an update to the game itself that is causing the break. Maybe I should wait til all the game bugs are sorted before i retest and tackle this one again.

**Comment by rtjunkie** [comment]
Ah, good info! I'll do some testing on my side as well and see if I can narrow down how this appeared. I'm sure it's either mostly trivial or completely benign.

**Comment by goatfungus** [comment]
Just wondering if there's anything left on this one, so I could close the issue?

**Comment by rtjunkie** [comment]
Wasn't able to produce a repeatable result, so yeah.
