### ISSUE TITLE
Can Not Save No responding

### ISSUE THREAD

**Issue by TerrenceXW** [goatfungus/NMSSaveEditor#500]
After i Save file and stuck
![image](https://user-images.githubusercontent.com/10952441/147668560-0df2f036-cdf9-44ee-85d7-a9542432dc52.png)

**Comment by myisman2** [comment]
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/7789112/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
