### ISSUE TITLE
Save game issue.

### ISSUE THREAD

**Issue by Sa1nT3012** [goatfungus/NMSSaveEditor#501]
When i load into Save Editor this is the log im getting..

Initializing environment...
Starting Editor...
Reading metadata for accountdata.hg
Reading metadata for save.hg
  Version: 524294
  TotalPlayTime: 0:06
Reading metadata for save3.hg
  Version: 1
  TotalPlayTime: 8:22
Reading metadata for save4.hg
  Version: 1
  TotalPlayTime: 7:43
  using name mappings: NMS 3.6
Loading saves for Slot 2...
Reading save file...
  Slot: Slot 2 - NORMAL - Jan 10, 23:25
  Filename: save4.hg
  using name mappings: NMS 3.6
  WARNING: name mapping not found: >CR
  WARNING: name mapping not found: EG=
  WARNING: name mapping not found: apf
Finished.

When i try to go back to a previous save it keeps reloading the last save. i noticed that when i warped in my freighter and i went to go hop in one of my ships, the skin was changed so i came to save game editor and this is the issue im getting.. no matter what save i go to, start a new game, i keep getting the same 3 warnings.

**Comment by xaminmo** [comment]
The >CR, EG=, and apf are the same name mappings I'm missing.  This should not usually break anything.  It's new things in the game that are not known what they are yet.

**Comment by Mistic92** [comment]
I got it today too and can't load autosave.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
