### ISSUE TITLE
Support for No Mans Sky Sentinel Update 3.8

### ISSUE THREAD

**Issue by louanfontenele** [goatfungus/NMSSaveEditor#506]
Please, can you update the Save Editor for 3.8 (Sentinel Update)?

**Comment by Mike-Blackwell** [comment]
Yes please, Goatfungus are you still supporting?

**Comment by areithropos** [comment]
Of course, it is dearly needed 💕

**Comment by Chariot-Rider** [comment]
I'm not updating the game until the save editor has been updated.

**Comment by stoneylsd** [comment]
Hoping it is updated as well but no rush 😊, can't rush greatness

**Comment by Dev-Will-R** [comment]
Just wanna add to the numbers here, I'd love for it to be updated as well!

**Comment by Mike-Blackwell** [comment]
Has anyone heard anything recently from Brendon (Goatfungus)? looking at the various user posts I do not see any of his reply's.

**Comment by goatfungus** [comment]
Hi all,
I have added support for 3.8 now... it just takes a few days to get each new release ready.
Let me know if there are any issues.

**Comment by capndank** [comment]
I cant find any back up saves or anything to work on my saves on the editor i have logged into nms on the comutor several times and the xbox and nothing has saved to the save editor i cant find anything besides default user and cache and they are both empty but my nms has the same save files on my pc from my xbox.

I am super confused can anyone please help me out!
