### ISSUE TITLE
Mult-Tool tab  not working

### ISSUE THREAD

**Issue by stoneylsd** [goatfungus/NMSSaveEditor#507]
In the multi tool section it will only let me see one multi tool , and any editing I do in the editor to my multi tool, are not saving. Any suggestions?

**Comment by D3mensional** [comment]
I am getting the same issues. I get the Error "WARNING: name mapping not found: Xs1"

**Comment by stoneylsd** [comment]
> I am getting the same issues. I get the Error "WARNING: name mapping not found: Xs1" 

Same thing also will not let me export or import any multi tools , I'm sure it will get fixed ,

**Comment by goatfungus** [comment]
"WARNING: name mapping not found: Xs1"
This is only a warning message, it's nothing to do with the multitool error you are seeing. It just means the game has introduced a new field somewhere in the save file that the editor doesn't know about, but it will still work fine with the warning.

I'll have a look into the multitool error now, and see what i can find.

**Comment by goatfungus** [comment]
I have double checked the normal multitools as well as the new Royal ones and I'm not having any trouble changing the stats. Are you sure you saved and reloaded the game?

**Comment by D3mensional** [comment]
I am positive that i did, only one (most recent acquired not even most recent used) out of 6 of my multitools would appear and all technology would be missing from the multitool.

**Comment by Mike-Blackwell** [comment]
Brendon, there seems to be something slightly different associated with the Royal multi-tool, I found that if I try to create/save a Royal multitool from scratch via the SaveEditor that it reverts to a legacy multitool when viewed within game play. The only way I found to make it work is to secure a Royal thru game play (via Sentential tower access) which is a C class, then in SaveEditor change the class to S and increase the slots and only insert conventional modules, save it and whala you now have a fully expanded tool but if you have X class modules inserted it for some reason reverts back to conventional multitool... Only initial observation(s)

**Comment by Pd69bq** [comment]
> In the multi tool section it will only let me see one multi tool , and any editing I do in the editor to my multi tool, are not saving. Any suggestions?

I am getting the same issue, it seems the multitool tab reads data from "weapon inventory" but the actual data is under "multitools'

**Comment by BattleGrown** [comment]
For me, I obtained a Royal Multitool from in game, saved & closed - launched NMSSE. Maximized slots, changed to S class, upped the stats to 20-20-50 and moved all my technologies from the previous multitool to this one. When I went in game Royal multi tool had no technologies and it was still C class, and the other multitool vanished. I exited game & reverted changes but still it is the same.

**Comment by D3mensional** [comment]
> 

I second this. exactly what happened to me

**Comment by astewart67** [comment]
> I have double checked the normal multitools as well as the new Royal ones and I'm not having any trouble changing the stats. Are you sure you saved and reloaded the game?

I play NMS on both PC (Steam) and PS4.  It seems to work fine on PC saves, I see all the multi-tools.  However, with a PS4 save, exported via Save Wizard, it only shows one multi-tool.  Pd69bq's workaround for the PS4 saves works for me also, and as he said, it seems that when reading a PC save, it's reading the "MultiTools" key, but when reading the PS4/Save Wizard exported save, it's reading the "WeaponInventory" key.

Hope this helps.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
