### ISSUE TITLE
Royal MT requires additional change

### ISSUE THREAD

**Issue by meachware** [goatfungus/NMSSaveEditor#509]
>>>> Thank You for continuing your support for this <<<<<

Looking through the RAW JSON I was able to swap a non-Royal MT into a Royal but not only do you need the SEED but the model (FILENAME) has to be changed to "MODELS/COMMON/WEAPONS/MULTITOOL/ROYALMULTITOOL.SCENE.MBIN"

Under [Multitools] - [Index] - [Resource] - [Filename]

Note: non Royal MT's use this Filename: "MODELS/COMMON/WEAPONS/MULTITOOL/MULTITOOL.SCENE.MBIN"

**Comment by Mike-Blackwell** [comment]
Gregory, thanxs for the deciphering the MT nuance..

**Comment by Mike-Blackwell** [comment]
I believe that there is another piece of the puzzle, if you simply add the above to a GameSave that hasn't accomplished the Sentinel Royal MT download (which suggests that some other attribute is set) then visit it in the game it isn't a Royal MT but a MT even if the filename has ROYALMULTITOOL.SCENE.MBIN ... I tried it on a normal save which did not give me an Roryal MT.

**Comment by meachware** [comment]
The field “IsLarge” (from memory) is something I also tested as the Royal one are TRUE. For my tests I will bet all mine were set to TRUE

**Comment by Mike-Blackwell** [comment]
I'm thinking that since the mission requires a data download (recipe) it must be hiding somewhere within the knownProducts e.g. "^SPEC_BB_TRACK01"..? Just speculating.

**Comment by meachware** [comment]
I’m knee deep in Lost Ark at the moment but will def look into comparing 2 saves to hopefully determine the key/flag required to activate Royal MT’s. 

Once again, I really can’t thank you enough for keeping this up to date.

**Comment by meachware** [comment]
Okay, fresh save and once I defeated the 5* Walker just changing the filename worked so now I have to find out what changes occur with the Sentinel battle.

I'll update with results

**Comment by Mike-Blackwell** [comment]
U Da Man! thanxs.. worked like a champ!

Seeds:
1.  0x380C70F18C0F1B9 – Royal Multi-tool White & Gold
2.  0xDE39140354B235DF – Royal Multi-tool White & Silver
3.  ?? - Red
4.  ?? - other colors

**Comment by meachware** [comment]
um yeah... no - "we" (the NMS community) owe YOU a HUGE thanks!!

**Comment by Mike-Blackwell** [comment]
Hopefully your giving Brendon (aka Goatfungus) the HUGE thanxs!

**Comment by meachware** [comment]
Why YES, yes of course…. (Insert John Travolta looking around.gif)

**Comment by Mike-Blackwell** [comment]
Or from Saturday Night Live - Tommy Flanagan; "Yea... that's the ticket!"

**Comment by goatfungus** [comment]
I have added a new Type field to multitools now, so you should be able to use "Standard" or "Royal" multitools interchangeably, providing all the bugs in the game are resolved.

**Comment by Mike-Blackwell** [comment]
Brendon, many thanxs for the update, the modification should simplify the interchangeably, mike

**Comment by kittenarmy** [comment]
> I have added a new Type field to multitools now, so you should be able to use "Standard" or "Royal" multitools interchangeably, providing all the bugs in the game are resolved.

Is there a bug in the current stable version of NMS that is causing it not to work? I tried importing a Standard mulitool (effectively making my 4th MT), changed the type to Royal and put a known ship seed, and save. But the MT doesn't appear at all when I load the game. I double-checked my save file to confirm it has the Royal MT.

**Comment by meachware** [comment]
> > I have added a new Type field to multitools now, so you should be able to use "Standard" or "Royal" multitools interchangeably, providing all the bugs in the game are resolved.
> 
> Is there a bug in the current stable version of NMS that is causing it not to work? I tried importing a Standard mulitool (effectively making my 4th MT), changed the type to Royal and put a known ship seed, and save. But the MT doesn't appear at all when I load the game. I double-checked my save file to confirm it has the Royal MT.
> 
> I did not find the Royal MT in game before so maybe this is needed?

Sounds like you imported an older version of MT.
I’ve used this new feature on 5 saves and multiple MT’s & it worked each time. 

I suggest that you purchase a new MT in game,then use the editor to set both the seed & Royal.

GL

**Comment by kittenarmy** [comment]
> > > I have added a new Type field to multitools now, so you should be able to use "Standard" or "Royal" multitools interchangeably, providing all the bugs in the game are resolved.
> > 
> > 
> > Is there a bug in the current stable version of NMS that is causing it not to work? I tried importing a Standard mulitool (effectively making my 4th MT), changed the type to Royal and put a known ship seed, and save. But the MT doesn't appear at all when I load the game. I double-checked my save file to confirm it has the Royal MT.
> > I did not find the Royal MT in game before so maybe this is needed?
> 
> Sounds like you imported an older version of MT. I’ve used this new feature on 5 saves and multiple MT’s & it worked each time.
> 
> I suggest that you purchase a new MT in game,then use the editor to set both the seed & Royal.
> 
> GL

Yes I did. Thank you I will try it now!
