### ISSUE TITLE
copy Ships?

### ISSUE THREAD

**Issue by HandofBobb** [goatfungus/NMSSaveEditor#51]
Is there any way to copy a Ship from another Save?  I pretty much had to restart with NEXT to figure out how the game works now, but I really miss my old ship.  I guess with the Editor I can fix up any ship I find to have the same Slots and Equipment, but I honestly haven't seen my ship's appearance since pre-Atlas Rises.

**Comment by Seranthor** [comment]
Load your old save... find the seed number.... close out of that... load new save... change active ship seed number to the old one.... save... play.

**Comment by GKboki** [comment]
@HandofBobb 
99% of the equipment of your old ship would not work in NEXT, and the old seed would not work with NEXT.

**Comment by HandofBobb** [comment]
@Seranthor 
Well, I tried that, and it doesnt seem to work currently, I guess the partslist has changed or something.
This is what my old ship looked like
https://steamcommunity.com/sharedfiles/filedetails/?id=935836718

and this is what it looks like now, when I load my old save:
https://steamcommunity.com/sharedfiles/filedetails/?id=1463561351
-pretty much the same, though I don't think she looks quite as nice.

but when I tried copying the seed to my new save, this is what I ended up with:
https://steamcommunity.com/sharedfiles/filedetails/?id=1463552061
-quite different, as you can see.

@GKboki 
yeah, obviously, all the old equipment was obsolete, but I can fix that with the editor.  I was hoping I could reproduce the look of the old ship, but it seems some parts have been shuffled around and the seed does not get the same results.

**Comment by goatfungus** [comment]
Try changing the "ShipUsesLegacyColours" item in the JSON editor, or if you don't mind waiting, I'll add a toggle for it in the next update.

**Comment by goatfungus** [comment]
I have added the toggle in version 1.5.11.
For old seed values tick the box, for new seed values leave it unticked.
