### ISSUE TITLE
win11无法安装

### ISSUE THREAD

**Issue by ligen-edward** [goatfungus/NMSSaveEditor#517]
已经装了Java，然后运行弹出选择路径的界面，任何按钮都没反应，也无法关闭

**Comment by Pd69bq** [comment]
你寫中文應該很少有人能夠回答你 彈出窗口就是要你選擇存檔的位置 如果你沒有辦法選的話 直接寫在NMSSaveEditor.conf文件中也可以
`GameSaveDir=drive\:\\folder`

**Comment by ClayCoffee** [comment]
@Pd69bq It doesn't work
