### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by rednight69** [goatfungus/NMSSaveEditor#518]
Possibly a theme option of light and dark mode?

**Comment by JB2021-81** [comment]
> Possibly a theme option of light and dark mode?

Yes that would be awesome because it is pretty hard to look at some of the menus as it is right now.

**Comment by Xeno1177** [comment]
Add my vote to this.  Being visually impaired, it's kind of an accessibility feature for me.

**Comment by goatfungus** [comment]
This has been added to the latest version, enjoy

**Comment by rednight69** [comment]
My eyes thank you so much for this!
