### ISSUE TITLE
Issue: Header errors in zip

### ISSUE THREAD

**Issue by Bigtuna00** [goatfungus/NMSSaveEditor#52]
Been meaning to report this for a while, I get this error every time I install a new release, not sure when it started:

![capture](https://user-images.githubusercontent.com/1865112/43563339-939e5194-95d6-11e8-9925-18593fdc7a45.PNG)

**Comment by jfessard** [comment]
I tested the 1.5.9 zip file with 7-zip version 18.05 and had no errors. (extracted fine too)

**Comment by Rianon** [comment]
Same here, always got this warning. It extracts fine, just warning.

**Comment by goatfungus** [comment]
Not sure what is causing that, but I'll look at upgrading the zip binaries in the build process and see if that helps. It may just be a false-positive in 7zip though, not really sure.

**Comment by Starkiller4011** [comment]
Could also provide the source code for those who want to build from source. Would be nice.

**Comment by jfessard** [comment]
@Starkiller4011 check out #49 and #71, it's been answered already

**Comment by goatfungus** [comment]
I have replaced the zip file with a self-extracting installer now, so this is no longer an issue.
