### ISSUE TITLE
After saving in editor, the file that needs to be re-encrypted by save wizard is left unchanged

### ISSUE THREAD

**Issue by NUKELEUR** [goatfungus/NMSSaveEditor#523]
Platform - PS4

I can load my save file into the editor and make changes, but when I save and re-encrypt it in Save Wizard, it acts as though nothing was altered by the editor. The save path and save itself loads up just fine in the editor but seems as though the file itself is unaltered. There are backups after every time i save but its almost as though the modded saves are not replacing the original. If this is a known issue ill happily wait for a fix. If i could get some help i'd appreciate it. Thank you.

**Comment by Pd69bq** [comment]
I can guarantee you that the save editor works just fine, I've used it several times this week. you can do a simple test, just change the name of your multitool or starship, save it, import back in AM, after SW completed its encryption procedure, open it in AM again, export then open it up in HxD or other Hex editor to see if your changes haven been saved

**Comment by NUKELEUR** [comment]
Ok, I tried what you said and your right when you said that the Save Editer
seems to work just fine, it seems that everything just to falls apart when
SW re-encrypts it. It looks as if it doesn't impliment any of the changes
what so ever. I made a new manuel save (just incase), and only changed the
name of the multitool. But it just defaults back to the random name it
started with. Would you happen to know a fix or a work around perhaps?
