### ISSUE TITLE
Is there a way I can change the game mode?

### ISSUE THREAD

**Issue by Macalanu** [goatfungus/NMSSaveEditor#529]
I m wondering if there is any way possible that I can change the game mode.

**Comment by JB2021-81** [comment]
I don't think that would be possible because this save editor only changes assets inside a save game and that's it.

**Comment by Bubblepiao** [comment]
可以做到，除了远征模式

**Comment by Devilin-Pixy** [comment]
Make sure to have a backup just in case. You will have to edit the 'Version' in the save using the Raw JSON editor.

Current game mode versions for Outlaws 3.85 are as follows:

```h
     Normal   4650
   Creative   5162
   Survival   5674
    Ambient   6186
 Permadeath   6698
Expeditions   662570
```

These values will usually change with major update releases.

**Comment by Bubblepiao** [comment]
编辑原始json，开头version数字4650是普通模式，其他模式的值就像楼上说的那样，修改数字之后保存就可以了

**Comment by Bubblepiao** [comment]
远征模式有一些不确定的事情发生，最好别更改为远征模式

**Comment by bsides230** [comment]
> Make sure to have a backup just in case. You will have to edit the 'Version' in the save using the Raw JSON editor.
> 
> Current game mode versions for Outlaws 3.85 are as follows:
> 
> ```c
>      Normal   4650
>    Creative   5162
>    Survival   5674
>     Ambient   6186
>  Permadeath   6698
> Expeditions   662570
> ```
> 
> These values will usually change with major update releases.

WTF is ambient mode? Is that new? I change my creative to normal and back every once in a while to play on GFN and never heard of ambient mode.

**Comment by Devilin-Pixy** [comment]
> WTF is ambient mode? Is that new? I change my creative to normal and back every once in a while to play on GFN and never heard of ambient mode.

Ambient mode has for as far as I am aware always been hidden. It is a free exploration experience with the player not having any input, with the game controlling a disembodied camera; which periodically switches worlds. This game mode is currently broken however, only showing a white screen. It has worked for some time in the past though.

**Comment by manves** [comment]
> > WTF is ambient mode? Is that new? I change my creative to normal and back every once in a while to play on GFN and never heard of ambient mode.
> 
> Ambient mode has for as far as I am aware always been hidden. It is a free exploration experience with the player not having any input, with the game controlling a disembodied camera; which periodically switches worlds. This game mode is currently broken however, only showing a white screen. It has worked for some time in the past though.

It doesn't seem like changing the json version for the save type doesn't seem to move the version from survival to normal

**Comment by satya164** [comment]
This is how I did very recently: https://www.reddit.com/r/NoMansSkyTheGame/comments/w78me8/changing_game_mode_with_save_editor_in_no_mans/

Maybe it'll help you.

**Comment by Devilin-Pixy** [comment]
@satya164 The way you describe it will not work, because importing the save data 'includes' the game mode value (Version).

@manves Make a backup first, just in case! You will have to edit the 'raw JSON data' to change the "Version" right at the top. This value will change over time and is specific to the game mode. Below are the 'current' values for the game modes listed (Endurance 3.94+):
```
Normal      4651
Creative    5163
Survival    5675
Ambient     6187
Permadeath  6699
Expeditions ???? (soon)
```
After editing and confirming changes, make sure to save again to have it actually saved to the file

**Comment by satya164** [comment]
@Devilin-Pixy changing the version field has no effect for me in the latest versions. i have also seen others have the same issue. https://www.reddit.com/r/NoMansSkyTheGame/comments/pt550m/is_it_still_possible_to_switch_from_survival_to/

**Comment by goatfungus** [comment]
I think this is possible in the game itself now.

**Comment by lululock71** [comment]
Editing the save like this doesn't seem to work anymore.

Yes, the game now offers ways to edit difficulty more granularly, but changing a permadath mode save into a normal one is still not possible within the game.

**Comment by wkitty42** [comment]
> Editing the save like this doesn't seem to work anymore.
> 
> Yes, the game now offers ways to edit difficulty more granularly, but changing a permadath mode save into a normal one is still not possible within the game.

probably best to open a new issue since this one was closed as completed 3 years ago... today's fix would have to be different than whatever this old one was...
