### ISSUE TITLE
Ship Cargo Inventory Missing?

### ISSUE THREAD

**Issue by PixiePunchPie** [goatfungus/NMSSaveEditor#535]
Hey! I LOVE YOUR APP!!! It's freking amazing and I use it in EVERY playthrough from Day 1 to Day 1 million!

I think I got the most recent download but the Cargo for Ship Inventory seems to be missing. Did I get the wrong one?

Thanks!

**Comment by njmill** [comment]
#534 has already been opened for the outlaw update.

**Comment by Fevix** [comment]
This app has not yet been updated for the Outlaws update.

**Comment by goatfungus** [comment]
See #534. Outlaws update is in progress.

**Comment by PixiePunchPie** [comment]
Thank you!
