### ISSUE TITLE
Is there a way I can change the ship Maneuverability?

### ISSUE THREAD

**Issue by Fieldmoon** [goatfungus/NMSSaveEditor#537]

**Comment by Infinality** [comment]
I've wanted this same thing, but I believe this is hardcoded in the game, rather than the config.

**Comment by woodstockfury** [comment]
> You can change this by enabling mods. There is one for example for living ships: https://www.nexusmods.com/nomanssky/mods/1598

How do you "enable mods?"
Thank you!

**Comment by kittenarmy** [comment]
> > You can change this by enabling mods. There is one for example for living ships: https://www.nexusmods.com/nomanssky/mods/1598
> 
> How do you "enable mods?" Thank you!

There's a text file called DISABLEMODS.TXT in your game directory (mine is in `C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky\GAMEDATA\PCBANKS`). Rename or delete this, and follow the install instructions on Nexus.
