### ISSUE TITLE
No Mans Sky update?

### ISSUE THREAD

**Issue by William2143** [goatfungus/NMSSaveEditor#538]
Hey there how's it going man, so I know the NMS update just came out so it's gonna be a while but I was just wondering if at all possible if we could get a very rough estimate of when your awesome editor will be updated to support the new NMS update? Also as a side note, how do you edit PC Game Pass saves?

**Comment by HillBillyBong** [comment]
> Hey there how's it going man, so I know the NMS update just came out so it's gonna be a while but I was just wondering if at all possible if we could get a very rough estimate of when your awesome editor will be updated to support the new NMS update? Also as a side note, how do you edit PC Game Pass saves?

C:\Users\username\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs
Thats the location of the save games, just change you username into the one youre logged in to.

I really hope theres a update soon and maybe add squad modifications.

**Comment by Patola** [comment]
Anyone tried editing an expedition 6 savegame with the current code? Does it work, even if minimally?

**Comment by HillBillyBong** [comment]
> Anyone tried editing an expedition 6 savegame with the current code? Does it work, even if minimally?

Most things work. There's just some unresponsive tabs.

**Comment by Fevix** [comment]
#534 is already open for this.
