### ISSUE TITLE
Move item dialog execute on double-click [suggestion]

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#54]
Hi, I've a minor (very minor) improvement to suggest.
How about making the 'Move Item' dialog execute its action on double-clicking the target container in the list (in addition to the 'Move' button)... Just making the process a bit smoother.

**Comment by goatfungus** [comment]
Makes sense. Good suggestion.
I'll get onto this when I have a chance.

**Comment by goatfungus** [comment]
Added in version 1.5.10.
