### ISSUE TITLE
please update the save editor for the Outlaws update

### ISSUE THREAD

**Issue by Zorvalk** [goatfungus/NMSSaveEditor#541]
look man i really want to get the rewards for the 6th expedition and im too lazy to do it myself. thats it. thats all i want.

**Comment by dtupper** [comment]
Duplicate of #534

**Comment by KiARC** [comment]
> look man i really want to get the rewards for the 6th expedition and im too lazy to do it myself. thats it. thats all i want.

I've explained how to do it in #534 and the current version works fine for it.

**Comment by goatfungus** [comment]
Look for updates on #534
