### ISSUE TITLE
Can't edit inventory technology slot to 8x6

### ISSUE THREAD

**Issue by Carl-Oyster** [goatfungus/NMSSaveEditor#545]
The slot can only be extended to 7x2 but not 8x6. Edit directly from the json file can temporary extend the slot, but when you enter the game it remains 7x2. Does anyone have a solution?

**Comment by goatfungus** [comment]
Its a limitation of the game itself, which is why the editor only allows expansion to 7x2. If you want to expand it further, you would need an actual mod for the game itself.
