### ISSUE TITLE
[Suggestion] Add ability to edit squadron ship and pilot seeds

### ISSUE THREAD

**Issue by Aikiro42** [goatfungus/NMSSaveEditor#546]
Add ability to edit squadron ship and pilot seeds

Squadron ship info are located in the `PlayerStateData.S50` array. Each index of this array contains a `>r:` field, which describes the pilot, and the `:dY` field, which describes the ship.

**Comment by goatfungus** [comment]
Yup, I'm currently working on this feature, but it might take a few days to fully test it out.

**Comment by goatfungus** [comment]
This feature is now available in the latest version, please try and let me know if there are any issues.
