### ISSUE TITLE
All files coming up as invalid or not compatible with Windows 11

### ISSUE THREAD

**Issue by DLittleBFG** [goatfungus/NMSSaveEditor#547]
Like the title says....
For jar file -->Error: Invalid or corrupt jarfile
For zip --> The compressed (zipped) Folder (path here).zip is invalid
For exe --> This app can't run on you PC.  To find a version for your PC, check with the software publisher.

I'm totally doing that last one.  ;)

**Comment by alicanertop** [comment]
I am able to use directly zip, i didnt get error. I m using w11

**Comment by meachware** [comment]
> I am able to use directly zip, i didnt get error. I m using w11

Yup, me too for the past many months.
OP try a different browser, reboot PC, really seems like on your end - GL

**Comment by JB2021-81** [comment]
I'm on W11, no errors at all.

**Comment by DarwinUang** [comment]
downgrade maybe? idk

**Comment by dclrocks** [comment]
Well no matter how many times I try, change settings in compatibility mode, or anything....it's not running.  Is there something that I am missing, outside of just going back to Windows10?

**Comment by meachware** [comment]
The version of Windows is irrelevant, perhaps the only limitation is that whatever OS you use is the 64bit version.

I use the Java version of Minecraft so my Java is nearly always up to date. So besides any 64bit Windows OS, Java is the only other requirement.

Those that cannot run the Editor, please post what version of Java you have or simply make sure it’s updated and functioning properly.
