### ISSUE TITLE
Shroud of Freedom (^SPEC_HOOD01) (Workaround found)

### ISSUE THREAD

**Issue by meachware** [goatfungus/NMSSaveEditor#548]
Doesn't actually allow you to wear (or even unlock) the item in the customization station.

Long story: doing research trying to get my Expedition save to get the Hood but couldn't get the mission (Under a Rebel Star) to kick off.

Made a new save folder and ran a new normal save up to getting access to the Anomaly. Made both saves and flew until I kicked off the UaRS mission. Compared the two json (export) files & could see where the mission was added. Kept going fully documenting the mission, items obtained and subsequent actions up until I landed at the Outlaw station. This was the final step before obtaining the hood; you talk to NPC's and on the 4th one you get the hood.

Well try as I might I added all the items to try and "jump" into the mission midway but nothing worked. 

Um, yeah then I thought, oh crap, it's probably already in the Save Editor, and of course it was!
(but didn't work on any of the saves I tried (normal, survival and of course Expedition)).

I'll keep crunching the json diff's but I think I've got to take my "before-mission" data and compare it to my "obtained hood" data to see the full impact. I hope my Notepad++ doesn't implode :)

Will post updates, of course

**Comment by meachware** [comment]
UPDATE:
A simple edit of the JSON data to add: "^SPEC_HOOD01",
to the  "KnownSpecials" key fixed it on my Expedition save.

Perhaps the Editor isn't putting the data in the correct section. I have no idea, just spit balling here.

**Comment by goatfungus** [comment]
I do have a fix for this, which will be released in the next version.

**Comment by Mike-Blackwell** [comment]
Brendon, did you per chance issue new version to fix this making this comment moot? Question does this fix related to the other saves?
