### ISSUE TITLE
Expedition rewards in account data doesn't work.

### ISSUE THREAD

**Issue by X66Herobrine66X** [goatfungus/NMSSaveEditor#554]
When I try to unlock expedition rewards in the editor, they're still locked when I go in game. I have to disconnect from the internet just like twitch rewards for it to work. There's been conflicting reports about this in the creative and sharing discord, it doesn't work for me and another person, but a third guy says it works fine for him.

**Comment by X66Herobrine66X** [comment]
Yea, this still isn't fixed to this day.

**Comment by goatfungus** [comment]
The game itself will try to download/upload your account settings if connected to the internet, so disconnect before playing or all your changes will simply be overwritten when the game starts up.
