### ISSUE TITLE
Does it work with Xbox Game Pass?

### ISSUE THREAD

**Issue by KarmaIsLame** [goatfungus/NMSSaveEditor#556]
My friend has No Man's Sky with game pass and we're wondering if there is a way the editor will work with the game pass version of the game.

**Comment by Unc1eben** [comment]
I can confirm that it works with the xbox/PC game pass on the PC. I have used this while i had gamepass on my pc.

**Comment by Unc1eben** [comment]
> My friend has No Man's Sky with game pass and we're wondering if there is a way the editor will work with the game pass version of the game.

I can confirm that it works with the xbox/PC game pass on the PC. I have used this while i had gamepass on my pc.

**Comment by KarmaIsLame** [comment]
> 

yep, we figured it out. thank you though!

**Comment by darkconsole** [comment]
what is the trick then? both dropdowns are empty.

![image](https://user-images.githubusercontent.com/9095897/165200605-e913b78f-4fda-4d71-b0d0-fba5f56bd09b.png)
