### ISSUE TITLE
PS4 not working

### ISSUE THREAD

**Issue by louanfontenele** [goatfungus/NMSSaveEditor#561]
@goatfungus the ps4 save file is not working.
[savedata04.zip](https://github.com/goatfungus/NMSSaveEditor/files/8603590/savedata04.zip)

here is my save file

**Comment by XxUnkn0wnxX** [comment]
the ps4 save does work however if you have done any manual edits, I've noticed after making my multi tool 48 slot the save editor fails to open it. since the editor fails to set multi-tool slots in the 1st place.

**Comment by WindowsXPSux** [comment]
I had the same issue but after some testing it seems NMSSaveEditor only works with a fresh PS4 save exported from Save Wizard. If I export the save edit with NMSSaveEditor it's fine but if I export, edit save with NomNom first it will no longer be able to be edited by NMSSaveEditor. So fresh saves only from what I can tell, hope this helps anyone

**Comment by MrMfG** [comment]
everything works for me at the moment, even with 48 slot multi

**Comment by Batavii** [comment]
I have the same issue on the ps4. Everything works perfect and I love this editor in combintion with save wizard. The only thing not working is any chances in the multi tool. Slots and parts wont 'stick'. I also have issues with the cargo slot of my Freighter. This wont stick to. Any sugestions?

**Comment by jonnygriffin** [comment]
How do I export my save file from Save Wizard?

**Comment by Batavii** [comment]
Right click on the save file, open in advanced, export the file, do not close this window, open the expoted file in nmseditor, save the file and import the file back, apply, done.

**Comment by jonnygriffin** [comment]
Thank you, that made it so I can export the file, but now when I load it in nmseditor everything is blank and nothing loads...What am I doing wrong? Sorry I'm not very good at this stuff and appreciate your help.

**Comment by jonnygriffin** [comment]
I got it, thanks so much!

**Comment by Batavii** [comment]
Good! Have fun!
