### ISSUE TITLE
Trojan virus - False positive

### ISSUE THREAD

**Issue by AlexoFlexo** [goatfungus/NMSSaveEditor#568]
Upon trying to download the save editor it is flagged as having a trojan virus "Trojan:Script/Oneeva.A!ml"

**Comment by HWGUY9110** [comment]
I got the same thing

**Comment by mpatterson42** [comment]
I got the same thing as well.

**Comment by philipgp28** [comment]
it is a false positive

**Comment by DarwinUang** [comment]
false positive, ive used this thing multiple times and never got the error

**Comment by goatfungus** [comment]
Weird.... there is no virus in this application, but I've seen people complain about false-positives before.

**Comment by NetworkDiskSomething** [comment]
bro, both my anti virus and windows antivirus are preventing me from running or just downloading the EXE.
