### ISSUE TITLE
Making any modifications to multi-tools deletes all of them

### ISSUE THREAD

**Issue by Ryuhouji** [goatfungus/NMSSaveEditor#569]
Anytime I try to make any change to multitools, including deleting unwanted/unused ones, the game instead thinks I have no multi-tools. I did try regenerating the seeds on the existing multi-tools, but it didn't help. Unsure what the issue is, Can replicate repeatedly.

**Comment by MrMfG** [comment]
you can change the multitool inv size via json maunal. this works: You Need:

[{"X":0,"Y":0},{"X":1,"Y":0},{"X":2,"Y":0},{"X":3,"Y":0},{"X":4,"Y":0},{"X":5,"Y":0},{"X":6,"Y":0},{"X":7,"Y":0},{"X":0,"Y":1},{"X":1,"Y":1},{"X":2,"Y":1},{"X":3,"Y":1},{"X":4,"Y":1},{"X":5,"Y":1},{"X":6,"Y":1},{"X":7,"Y":1},{"X":0,"Y":2},{"X":1,"Y":2},{"X":2,"Y":2},{"X":3,"Y":2},{"X":4,"Y":2},{"X":5,"Y":2},{"X":6,"Y":2},{"X":7,"Y":2},{"X":0,"Y":3},{"X":1,"Y":3},{"X":2,"Y":3},{"X":3,"Y":3},{"X":4,"Y":3},{"X":5,"Y":3},{"X":6,"Y":3},{"X":7,"Y":3},{"X":0,"Y":4},{"X":1,"Y":4},{"X":2,"Y":4},{"X":3,"Y":4},{"X":4,"Y":4},{"X":5,"Y":4},{"X":6,"Y":4},{"X":7,"Y":4},{"X":0,"Y":5},{"X":1,"Y":5},{"X":2,"Y":5},{"X":3,"Y":5},{"X":4,"Y":5},{"X":5,"Y":5},{"X":6,"Y":5},{"X":7,"Y":5}]

for 48 slot multi
go into game install all the technology, go into saveedit repair via json (manual) - do nothing within the edit tool.
