### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by Crankypoet** [goatfungus/NMSSaveEditor#57]
Not sure what it means. Bet you do. Enjoy.
![screenshot_1](https://user-images.githubusercontent.com/42076390/43662528-77281b3a-9766-11e8-9ab8-ab4321ac6b43.jpg)

I clicked the bat file.
The jar did not work

**Comment by goatfungus** [comment]
You are using Java 7 or 6.... need to download Java 8.

**Comment by Crankypoet** [comment]
Yes. that helped. Than you!
