### ISSUE TITLE
Cannot access Discovery or Account tab

### ISSUE THREAD

**Issue by modemman11** [goatfungus/NMSSaveEditor#570]
Frequently (but not all the time) when attempting to access either the Discovery or Account tab, it does not show the tab properly. Instead, it shows an afterimage of whatever the previous tab I was on. If I move my mouse pointer around, the checkboxes of the Account or Discovery tab will appear, but with no labels, so I have no idea what I would be clicking on. I have attached screenshots of the issue and of the command prompt window throwing errors. All other tabs work fine and whatever the issue is, it has happened across several versions of the app. Occasionally it'll work fine, but I have to fiddle with closing and reopening the app numerous times, or rebooting my PC, then MAYBE it'll work correctly.

![Screenshot 2022-05-14 193151](https://user-images.githubusercontent.com/89714762/168451373-1dce9424-8ff1-4375-abda-93eccf723a8d.jpg)
![Screenshot 2022-05-14 193223](https://user-images.githubusercontent.com/89714762/168451374-6a780cff-f2fc-4edf-813c-cacd894f7a52.jpg)

**Comment by Devilin-Pixy** [comment]
I could be wrong, but I feel you may not have Java 8 64-bit installed looking at the trace log

**Comment by kuwas** [comment]
@goatfungus @modemman11 Issue here is administrator privilege.

Java needs to be run on administrator privileges on Windows. I'm not really a Windows guy so not 100% sure how to default the batch with the right privilege, but opening a command prompt with "Run as administrator" and calling `java -jar NMSSaveEditor.jar` manually works.

**Comment by modemman11** [comment]
@kuwas 
> Java needs to be run on administrator privileges on Windows for certain operations I guess. I'm not really a Windows guy so not 100% sure how to default the batch with the right privilege, but opening a command prompt with "Run as administrator" and calling `java -jar NMSSaveEditor.jar` manually works.

That would only make sense if it NEVER worked. As stated in the original text, sometimes it does work fine, and when it does, I am not running as admin. Only closing and reopening the program. 

@Devilin-Pixy 

>I could be wrong, but I feel you may not have Java 8 64-bit installed looking at the trace log

An interesting thought. I checked Control Panel uninstall programs screen and had Java 8 331 installed, but it did not explicitly state if it was 32 or 64 bit, so the trend with other software that doesn't specify seems to be to assume 32 bit. I uninstalled and reinstalled the latest version (Java 8 333), and this time it _does_ explicitly state 64 bit in the control panel listing. I can access the tabs just fine for the moment, but given the intermittent nature of the issue, I'd be reluctant to say that that was the issue.

**Comment by kuwas** [comment]
> @kuwas
> 
> > Java needs to be run on administrator privileges on Windows for certain operations I guess. I'm not really a Windows guy so not 100% sure how to default the batch with the right privilege, but opening a command prompt with "Run as administrator" and calling `java -jar NMSSaveEditor.jar` manually works.
> 
> That would only make sense if it NEVER worked. As stated in the original text, sometimes it does work fine, and when it does, I am not running as admin. Only closing and reopening the program.
> 
> @Devilin-Pixy
> 
> > I could be wrong, but I feel you may not have Java 8 64-bit installed looking at the trace log
> 
> An interesting thought. I checked Control Panel uninstall programs screen and had Java 8 331 installed, but it did not explicitly state if it was 32 or 64 bit, so the trend with other software that doesn't specify seems to be to assume 32 bit. I uninstalled and reinstalled the latest version (Java 8 333), and this time it _does_ explicitly state 64 bit in the control panel listing. I can access the tabs just fine for the moment, but given the intermittent nature of the issue, I'd be reluctant to say that that was the issue.

Try the admin command prompt method and see if it has consistent success.

I also noticed that the account page doesn't work if you open the "account" file, but it works fine if you access it after opening the "save" file. I'm also using a completely fresh "account" and "save" file.
