### ISSUE TITLE
Several odd issues...

### ISSUE THREAD

**Issue by criscrosaplesos** [goatfungus/NMSSaveEditor#571]
Editor does not recognize save files unless you save both from exiting ship and at beacon...
After using the editor and saving, it fucked my file and it initiates a new save.. even when loading from the save that say 150+hours on it...   So basically the whole thing is not working right now.

**Comment by AnalyticalBear** [comment]
> Editor does not recognize save files unless you save both from exiting ship and at beacon... After using the editor and saving, it fucked my file and it initiates a new save.. even when loading from the save that say 150+hours on it... So basically the whole thing is not working right now.

Always back up your save before editing.
Unfortunately you learnt this the hard way.

I've had some oddity before but usually just jumping in and out of my ship is enough.
