### ISSUE TITLE
Update for Leviathan expedition: Rewards & Twitch drops

### ISSUE THREAD

**Issue by AnalyticalBear** [goatfungus/NMSSaveEditor#574]
The leviathan expedition and update has launched.
Can the save editor be updated to include the new expedition rewards and any twitch drops?

Thanks

**Comment by William2143** [comment]
Bruh the update just came out, give the guy a break. Hey Goatfungus keep up the awesome work man.

**Comment by leyrex** [comment]
^ Feel the same. Great work man no rush!

**Comment by AnalyticalBear** [comment]
> Bruh the update just came out, give the guy a break. Hey Goatfungus keep up the awesome work man.

Bruh, I am just flagging an update came out, not rushing the man.

Being a developer myself if there's anything I can do to assist I am open to helping out.

**Comment by huiwangye** [comment]
just wait,此外谢谢创作者。

**Comment by goatfungus** [comment]
I just released another update, should include all the unlockables and items for leviathan.
If anyone gets any mapping warnings showing up, post them here and I'll get around to adding them over the next few days.

Enjoy!

**Comment by leyrex** [comment]
> I just released another update, should include all the unlockables and items for leviathan. If anyone gets any mapping warnings showing up, post them here and I'll get around to adding them over the next few days.
> 
> Enjoy!

Thank you for your work.

**Comment by cubesteak** [comment]
TY for your continued support for the game!  Very kind of you...

**Comment by Patola** [comment]
How to edit/add expedition rewards? Only directly (e.g. editing a Frigate to be the Leviathan) or is there any way to unlock something to be redeemable with the Quicksilver Vendor?
