### ISSUE TITLE
Invalid Maximum Heap Size - Debug 4G

### ISSUE THREAD

**Issue by Nimarus84** [goatfungus/NMSSaveEditor#58]
I noticed my Java wasn't the latest version that was updated last month. After updating it, much of my previous problem was fixed. If I run the Debug.bat, I can edit my save and edit JSON. However, if I run the Debug-4G.bat, I get this message:

> Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to continue . . .

> 

My computer has:

Intel Core i7-6700K CPU @ 4.00GHz, 4008 Mhz, with 4 Cores and 8 Logical Processors
16GB RAM (I plan to get another 16GB card inserted someday because...why not?)
Nvidia GeForce GTX 950 2GB (Kind of sucks for NMS I know)

Thanks a lot for all the work on this editor. It's a lifesaver!

**Comment by Nimarus84** [comment]
I take that back, much of my earlier problem is still there. I click on Edit Raw JSON and it freezes. Then, I get the same error that I mentioned in a previous issue.

**Comment by goatfungus** [comment]
That is really weird.... I have an almost identical system to you, and 16G ram is more than enough for the editor to run in the Debug-4G mode. I can even crank it up to -Xmx32G if I really wanted to (using paging file), and Java doesn't usually complain.

I suspect you might still be using an older JVM, or it hasn't updated properly?

**Comment by Nimarus84** [comment]
OMG, thanks for pointing that out. I mistakingly installed the wrong Java it seems. I installed the 64-bit version and everything appears to be working again.

**Comment by goatfungus** [comment]
Sweet! Glad it's solved. I'll close this one then.
