### ISSUE TITLE
I think I'm doing something wrong?

### ISSUE THREAD

**Issue by Axious729** [goatfungus/NMSSaveEditor#580]
Hay the save editor isn't working for me on outlaw. I'm assuming this is because of the update? Its interfacing and the save is showing up in the game but non of the data is changed. If its me (very likely) can I get some help figuring it out?

**Comment by LegoEngineer003** [comment]
> Its interfacing and the save is showing up in the game but non of the data is changed. 

If you made changes with the editor to a save but it didn't register in the game, you might not have hit the 'Save Changes' button on the Main tab.
