### ISSUE TITLE
"Unable to Register Storage" Error

### ISSUE THREAD

**Issue by SwitchySylvar** [goatfungus/NMSSaveEditor#581]
Editor has been non functional since 1.10.2. Keep trying to reselect the save file path, have tried to use fresh save wizard exports, even tried fresh save editor install, but repeatedly throws the error below and shows no selectable options in the drop down menus. Even when using the 4G bat file. 

SS and log attached

![Screenshot (423)](https://user-images.githubusercontent.com/106476258/170869290-80866398-afa4-4cc7-a450-06b09574350c.png)
[Copy of NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/8793383/Copy.of.NMSSaveEditor.log)

**Comment by goatfungus** [comment]
That usually means that the folder path could not be found. Check your NMSSaveEditor.conf file and make sure that the GameSaveDir is correct.

If you are using steam, this should be set to something like this:
`GameSaveDir=C\:\\Users\\Brendon\\AppData\\Roaming\\HelloGames\\NMS\\st_XXXXXXXXXXXXXX`

Please note: the double slashes (\\) are important for separating the file paths.
