### ISSUE TITLE
Utilising the MBINCompiler generated mappings

### ISSUE THREAD

**Issue by monkeyman192** [goatfungus/NMSSaveEditor#583]
After seeing some people raising issues about this, I have realised that you may not know that as part of the MBINCompiler releases I have included a `mapping.json` file which contains all the names of mappings from the obfuscated version to the non-obfuscated versions (eg. see the latest one here: https://github.com/monkeyman192/MBINCompiler/releases/download/v3.90.0-pre2/mapping.json)

Not sure if you can integrate this easily somehow with your code, but I figured I'd mention it here so that you are aware as it may make the update process much easier 😄

**Comment by goatfungus** [comment]
Oh yes, thanks for that. I'll see what I can do :)

**Comment by goatfungus** [comment]
Hey @monkeyman192,
I had a look at the mapping.json file and noticed a few potential issues. Firstly, there are some values missing, some of which might be data values from older versions of the game that are no longer in use but are still present in some saves. Secondly, there is a duplicate key. See below:

Missing JSON Values:
	ScreenshotUp = fJB
	DepthOfFieldStrengthSetting = wKU
	SectionsData = uK6
	SunDirSet = OCG
	DiscovererUID = 2jw
	DepthOfField = ?sW
	ScreenshotRight = KLP
	SecondaryStats = :Je
	DiscoveredState = OYB
	PlanetaryMappingData = ym>
	PlayerWeaponName = rBG
	DiscovererPlatform = J3C
	NeedsHighCreatureLevel = wmu
	FoVSet = ARP
	DepthOfFieldAmount = 14a

Duplicates:
	RocketLockerInventory = V86
	FireteamSessionCount = V86

As part of my build process, I already have a step for extracting the strings from the EXE file and performing the checksum, but I'm still reliant on the save file containing all of the keys. This means I have to physically load up the game and resave to capture the new format, but obviously this doesn't always include every newly added key.

To improve this, I am thinking of adding a new step to read and compare the latest mapping.json release from your project with the mapping file I have in the editor (if that's ok with you of course). If there are new values it would do a checksum to validate the result and add them to the internal list. This means I would be able to preserve any older mappings that no longer appear in-game, while also being able to visually see what has changed.

Does this sound ok to you?

**Comment by monkeyman192** [comment]
I can have a bit of a look into the missing ones. If they are from an old version there is nothing I can do about that. The ethos of MBINCompiler has always been to only provide compatibility for the specified version for the sake of simplicity, so the mapping will follow the same idea and it's up to save tool authors to use the info how they see fit (ie. merge it, whatever)
It is interesting about that duplicate key though! Do you have values for what obfuscated value they map to?

And yep, the whole point of me adding that file is to make life easier for anyone making a save file editor as you can pull that file and use the info found within. The idea was some save file editors wouldn't need to actually ship with that data and could instead pull it at run time to reduce overhead of updating (like what AMUMMS and such do with the MBINCompiler/libMBIN binaries)

**Comment by goatfungus** [comment]
The duplicate key is here:
{"Key":"V86","Value":"RocketLockerInventory"}
{"Key":"V86","Value":"FireteamSessionCount"}

As for the runtime pull idea, I think that would be a good option if a mapping isn't found in the shipped data, so I'll look at including that in the next release too. Thanks for your help.

**Comment by monkeyman192** [comment]
Yeah, I saw that in the first comment! haha.
I meant, do you have these in your mapping already? Just wondering if the game has something built in to realise that there is a collision and maybe modify the generated Key so that there is no collision. (ie. the keys for these values are actually different to what I have in the mapping)

**Comment by goatfungus** [comment]
Yup, all of these are in the mapping already, which I've just continually added to over the years since the key generation was introduced. Nothing was ever removed as it could have had disastrous affects on older saves.

I have written a quick app which compares the keys in your version with all the keys in mine, and the values are all identical except for the missing ones, so I don't think there are any major issues there.

The only question is regarding that one collision, and I think it's because "RocketLockerInventory" is used in normal save files, whereas "FireteamSessionCount" is used in the account settings file. Since they don't get stored in the same physical file there isn't an issue with the mapping providing you treat each file separately.
