### ISSUE TITLE
Can't claim the Organic frigate (Leviathan)

### ISSUE THREAD

**Issue by Chariot7000** [goatfungus/NMSSaveEditor#584]
I unlocked the leviathan thought save editor but I can't redeem it on the QS Vendor. It's unlocked on the shop but when I click on it to claim it, nothing happens. Does someone now how to fix this?

**Comment by EremesNG** [comment]
See this https://github.com/goatfungus/NMSSaveEditor/issues/609#issuecomment-1191389066
