### ISSUE TITLE
The editor is stuck

### ISSUE THREAD

**Issue by zcvxvx** [goatfungus/NMSSaveEditor#585]
![image](https://user-images.githubusercontent.com/106616424/171230346-7f435f2f-187b-4e3b-a3b5-7e13520861ab.png)
When I run the editor, stuck in this "choose save path" window, can not click and can not close, tried to re-download the editor, also reinstalled the java8, can not solve this problem.

**Comment by NarseGC** [comment]
请问您有解决这个问题吗？如果有希望能分享一点建议。

**Comment by Devilin-Pixy** [comment]
@zcvxvx Update the save editor by downloading the latest version 1.11.5 (FRACTAL)
You are still running an old version 1.10.2 (OUTLAWS)

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
