### ISSUE TITLE
Cannot Access Squad or account tabs

### ISSUE THREAD

**Issue by Mike316316** [goatfungus/NMSSaveEditor#587]
The account and squad tab is remaining greyed out? Am I doing something wrong. Apart from that this is an awesome bit of work. Thanks.

**Comment by goatfungus** [comment]
Account will be greyed out if the editor could not find your accountdata file. This is separate from your normal save files but is stored in the same folder usually.
Squadron tab will be greyed out if your save file is older and does not have the new features that were added in Outlaws.

To solve both problems, you should load your save file in the game itself and do another quicksave. The game should then save everything in the new format.

**Comment by Aeramis** [comment]
I am on PS4. Can I not access the Account Tab because of this?

**Comment by Aeramis** [comment]
> Account will be greyed out if the editor could not find your accountdata file. This is separate from your normal save files but is stored in the same folder usually. Squadron tab will be greyed out if your save file is older and does not have the new features that were added in Outlaws.
> 
> To solve both problems, you should load your save file in the game itself and do another quicksave. The game should then save everything in the new format.

I am on PS4. Can I not access the Account Tab because of this?
