### ISSUE TITLE
how do i use ps4 saves

### ISSUE THREAD

**Issue by Famalama1234** [goatfungus/NMSSaveEditor#588]
hi im pretty dumb when it comes to all this save data and file stuff, i have save wizard with advanced mode so i can download all the hex data, but how do i edit my ps4 save with this tool, whenever i look in my ps4 save files on my usb i dont see any hg files so im kinda confused

edit: also would be appreciated if someone could enlighten me as to how u convert the edited data onto your ps4 data on sw

**Comment by Bugster21** [comment]
Hi 😁extract the save wizard save (double click No man's sky- Right click SAVEDATA -Advanced mode- Export to file(up in right corner), open in goat, fix what need to fix, and import file again to save wizard(Right corner), press 4 (or first number under data)
And save. Works for me 😁👍
