### ISSUE TITLE
font scaling issue

### ISSUE THREAD

**Issue by sicwan** [goatfungus/NMSSaveEditor#59]
new "Improved font scaling" makes the text smaller and a little hard to read//blurry? hard to describe, but here's a screen shot [https://gyazo.com/6f8e57dc35d095c668c4e23784511d2b](https://gyazo.com/6f8e57dc35d095c668c4e23784511d2b) [https://gyazo.com/2dd028d6d264e1849f3115105843c332](https://gyazo.com/2dd028d6d264e1849f3115105843c332)

**Comment by goatfungus** [comment]
Can't see the screenshots... page not found

**Comment by goatfungus** [comment]
In the meantime, I have reverted some of the change and have uploaded again.
NOTE: It's still labelled the same version, so won't show in the editor as needing an update.

**Comment by roie-r** [comment]
Same here... the new font is too small; not blurry for me but still small.
Why not add a font selector and let users choose their own :)

**Comment by goatfungus** [comment]
Have you downloaded it since my last comment, or still using the older one?

**Comment by roie-r** [comment]
I did use the latest b version.
It's clear enough, I guess, but too small
![nms_editor_font](https://user-images.githubusercontent.com/41163747/43676814-b0a6b764-9800-11e8-80bb-61c238d24cc8.jpg)

``

**Comment by sicwan** [comment]
I fixed the URL, should be visible now

**Comment by goatfungus** [comment]
Oh, you mean the inventory text!
Yes, I did reduce this so that we could fit longer names. If that's the only problem then we're good, because I plan to add a scaling the the whole thing at some point.

What did the original 1.5.11 version look like?

**Comment by roie-r** [comment]
The original 1.5.11 was small overall - menus included, and the inventory font was even smaller and blurry.
![nms_editor_font2](https://user-images.githubusercontent.com/41163747/43680393-541ea28a-9842-11e8-8b40-e6825399c963.jpg)

**Comment by goatfungus** [comment]
Ewww.... both look crap, but good to see some improvement.

The problem I'm having is that some systems are using different fonts and sizes based on the windows theme. So if I increase the font size in the app some people will see excessively large fonts and lots of overlap, so while it might look perfect for some it would be almost unusable for others. Maybe I'll put in a few options in the config file for people to change if they need to.

**Comment by goatfungus** [comment]
Ok, I have reverted the font scaling change and added a new "InventoryFontScale" value for people who find the text in the inventory too small to read. All other fonts are back to how they were in 1.5.10 and earlier.
