### ISSUE TITLE
Missing Known Products from save editor

### ISSUE THREAD

**Issue by AnalyticalBear** [goatfungus/NMSSaveEditor#590]
I was just checking my save game and I noticed there are missing products from the "Add Product" button.

These also show up in my Known Products list with no Name and Category.

^EXPD_BACKPACK01
^EXPD_BACKPACK05
^EXPD_BANNER01
^EXPD_BANNER02
^EXPD_BANNER03
^EXPD_BANNER04
^EXPD_BANNER05
^EXPD_BANNER06
^EXPD_BANNER07
^EXPD_CAPE06
^EXPD_CAPE07
^EXPD_HELMET01
^EXPD_PETCUST05
^EXPD_TITLE07
^EXPD_WORMHAT
^FREIGHT_PAINT
^JETS_BUBBLE
^JETS_SENT
^JETS_WORM
^SHIP_PIRATE
^SHIP_ROGUE

**Comment by AnalyticalBear** [comment]
![image](https://user-images.githubusercontent.com/103867139/171552183-57cf3a8b-5611-4c29-b820-69648ae95a97.png)

**Comment by Amstragram-crypto** [comment]
I confirm the issue
