### ISSUE TITLE
Save editor does not display any of my autosaves.

### ISSUE THREAD

**Issue by Lazyshadow04** [goatfungus/NMSSaveEditor#591]
![Nms 1](https://user-images.githubusercontent.com/106788344/171768191-39f4a3c7-d743-44dc-9017-c9eeb3bd7586.png)
![Nms 2](https://user-images.githubusercontent.com/106788344/171768209-6983e9f1-e099-4b29-8b52-18e1676e2623.png)

As you can see, it doesn't recognize that I have an autosave (or any others) at or near 16:40 on June 2nd. I lost a lot of progress due to shutting my computer off right after an autosave, so now it doesn't even recognize that the autosave is there. 

Edit: Apparently it is "Incompatible with the current version of nms" even though I turned my computer off shortly after. Could there be a way to upload a save file if it isn't detected and port the data over to another one that fits the version requirements? I still have that save, but it isn't being detected by the game.

**Comment by Lazyshadow04** [comment]
![nms3](https://user-images.githubusercontent.com/106788344/171770833-7fee6cb9-7097-4a06-b0d1-7d0a666e40df.png)
![nms4](https://user-images.githubusercontent.com/106788344/171770840-558f508a-83fd-47d4-a3c3-f91937cb8c1f.png)

What's even worse is that "save3", an autosave, is more recent than the manual save by 2 days. It still says that it is "Incompatible with the current version of nms." I was hoping to recover an autosave before that, but it might not be possible. 

If you have Discord, I might be able to send you the entire cache, I still have no clue how that's the case, but maybe you could figure it out.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
