### ISSUE TITLE
missing legacy building parts tab build menu normal save

### ISSUE THREAD

**Issue by Dimitell** [goatfungus/NMSSaveEditor#592]
Up until a few days ago the tab was there. I have mods installed. My expedition save has the legacy tab working. I am not sure what i did to the normal save i have not edited the json file on either save.

thank you 

Dimitell

**Comment by ukmerlin** [comment]
You should always check with no mods running first. It is most likely that. The updates almost always have items added that messes up the "purchase" table and therefore the associated "use" tables.
