### ISSUE TITLE
Version 1.5.11 question/concern

### ISSUE THREAD

**Issue by Seranthor** [goatfungus/NMSSaveEditor#60]
Type font now in 1.5.11 is blurred, smaller and nearly unreadable... Is there a way I can adjust this?

**Comment by Seranthor** [comment]
1.5.10

**Comment by goatfungus** [comment]
I reverted it back, try downloading again.

**Comment by Seranthor** [comment]
11b is still a bit smaller than I'd like.. but its not blurry like 11... and reading your notes on #59 then I'll just watch there... Thanks for all your hard work.
