### ISSUE TITLE
Xbox Gamepass Expedition save

### ISSUE THREAD

**Issue by k5jat** [goatfungus/NMSSaveEditor#600]
I tried loading in an expedition save from earlier in the month. All was well and things edited nicely, until I brought it into the game. The game wiped and restarted the save, so it's a blank slate. Now the new save doesn't even show in the list.

**Comment by Aroax** [comment]
don't suppose you were able to resolve this in the end were you? I'm facing the same...

**Comment by k5jat** [comment]
I noticed that if the game is up and using the save, it's not visible for NMSSaveEditor. Once I'm out of the game, it takes a minute or so to be able to access it. I'm guessing this is because of the way the Xbox version handles the files, because the Steam version doesn't do that. Not sure what happened with the save wipe, but it hasn't happened since.

**Comment by k5jat** [comment]
Bah, it closed... Reopening

**Comment by Aroax** [comment]
Thanks for coming back on this - I didn't have the game open so my experience wasn't quite the same, but it's certainly possible that perhaps I was being impatient/too hasty if things require a few minutes either side of changes...

Doubled down on the loss and am currently mid-re-installation haha

**Comment by k5jat** [comment]
Yeah, I was mad and uninstalled for about a day. lol I hope it gets fixed soon. Seems like something rare since we seem to be the only ones who've been affected.
