### ISSUE TITLE
Save Editor not opening save file

### ISSUE THREAD

**Issue by katekyy** [goatfungus/NMSSaveEditor#601]
I was setting save path to `../DefaultUser/`, `../DefaultUser/cache/` and I even set it to smth like this: `../DefaultUser/cache/[file.dds]` but it still won't work.

When I open one of those dirs then editor looks like this:
![screenshot](https://user-images.githubusercontent.com/74244551/174483539-40af56fe-813b-4ab1-a701-960c4ca5f3a5.png)

> Platform: PC (Xbox GamePass)
> Game Version: Frontiers 

> <ins>**EDIT:**</ins>
> I tried changing JRE versions to all I have but that didn't work too.
> Here's my logs from changing version from Oracle JRE to Azul JRE: [NMSSaveEditor.log](https://pastebin.com/6REThmVe)

**Comment by Sprymars** [comment]
Did you ever find a fix for this?

**Comment by katekyy** [comment]
> Did you ever find a fix for this?

Unfortunately, no.

**Comment by JGamerBR21** [comment]
Game Pass:
US: go to --> AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\ [File name of huge random numbers]
BR: entra na pasta ---> AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\ [arquivo com um monte de números aleatórios]
![image](https://user-images.githubusercontent.com/101447625/234337837-057f8de7-d470-4dc0-af4e-57766493aab4.png)
@goatfungus
