### ISSUE TITLE
Save format not up to date with latest in game, and game crash with corrupted saves

### ISSUE THREAD

**Issue by dringdahl** [goatfungus/NMSSaveEditor#603]
If you edit and then reload a save in game, summoning your freighter or the anomaly will cause a game crash. It also will say the save is out of date if you are in multiplayer so you can not reload the save.

**Comment by raffel080108** [comment]
Cannot confirm this, I edited a few things like game mode, known words and also some inventory items and my game works just fine. Maybe you incorrectly used something or have a corrupted download - I would suggest reinstalling the save editor and trying again
(Using Latest version at the time of July 6th 2022)

**Comment by dringdahl** [comment]
Sorry for the late reply.

After some more testing, here are the steps I took to reliably recreate the issue:
1. load save in game
2. save game but do not exit game
3. edit game save on another screen or via alt-tab
4. load edited game save in game
5. save game in game
6. exit game
7. start game and load that last save and you should experience a game crash when summoning your freighter or the anomaly

Unfortunately, I did this testing before the latest update and only now had the time to get back to update the issue (my dad passed away two weeks ago). I do not know if the issue is still present in the latest update. I will check when I have time.

**Comment by raffel080108** [comment]
I did this exact procedure countless times while using the save-editor and I have never experienced my game crashing, ever. This must be specific to your Computer or installation of the game. Maybe try reinstalling the game and try to update anything system-/OS-related.

**Comment by dringdahl** [comment]
With the updates to both the game and the save editor, and @raffel080108 not being able to reproduce the issue, I guess we can close this issue for now. I'll refresh everything on my end if I experience further issues before I open another issue.
