### ISSUE TITLE
Cannot unlock expedition items via Account Tab

### ISSUE THREAD

**Issue by PykeSongOTheday** [goatfungus/NMSSaveEditor#604]
Hello there! 

This tool has done much for me, and I cannot thank you enough. 

However, I am experiencing an issue with the Account Tab. I'm trying to unlock some seasonal expedition rewards, such as the Outlaw Cape. Whenever I tick the boxes and click Save changes, nothing is unlocked in the game. Is this a bug?

Thanks.

**Comment by PykeSongOTheday** [comment]
Nevermind! Got it working.

**Comment by loyal-thunder** [comment]
@PykeSongOTheday how? i'm having the exact same problem 3 years later.......
