### ISSUE TITLE
idk whats going on, If i save a game, it wont show up in the editor...?

### ISSUE THREAD

**Issue by criscrosaplesos** [goatfungus/NMSSaveEditor#605]
Ive since moved to steam but really would like access top my old saves. wtf is going on? use to work just fine, then after the new NMS launcher that MS has nothing works with your editor.

**Comment by h8rt3rmin8r** [comment]
This save editor has been broken for about three weeks now. Not sure when the NMSSaveEditor developer(s) might get around to running the necessary updates. I'm just disappointed that we won't likely be able to use this editor before the current in-game event is over.
