### ISSUE TITLE
Endurance Update

### ISSUE THREAD

**Issue by louanfontenele** [goatfungus/NMSSaveEditor#608]
Please update the save editor to the new version: Endurance Update.

**Comment by raffel080108** [comment]
Chill bro, the version just came out. You gotta give the dev time

**Comment by goatfungus** [comment]
I'm already onto it.
This is quite a massive update in regards to save file changes, so it will take some time to get everything sorted.

Your patience is appreciated :)

**Comment by grazzolini** [comment]
Do we know if there's any issue in using the editor as it is now? At least just to refill stacks and things like that. Or it's not a good idea to use it for now?

**Comment by raffel080108** [comment]
> Do we know if there's any issue in using the editor as it is now? At least just to refill stacks and things like that. Or it's not a good idea to use it for now?
I just tested it by changing a few things (added, recharged, modified some things) and everything seems to be working fine. 
I would still (generally too) have a data-backup in case anything happens. This is simple to do, by just copying your user folder at %appdata%\HelloGames\NMS (it should be a folder with a long number in the name - DONT RENAME IT!)
You just can't access anything new yet, of course, such as adding new build parts manually or editing the newly added freighter cargo inventory, for example.

**Comment by perpetualyawn** [comment]
> Issue with the new update in case this helps u with your good work Mr fungus..... having gone into the editor just to fill my stack of frigate salvaged data ( :) ) the freighter now has the exterior of the freighter rendered inside of the flight deck... It's pretty mangled.... Anyway thanks for your good work...

Confirmed. On every save although oddly not my latest save where the flight deck is rendered fine.

**Comment by grazzolini** [comment]
It is my understanding this save editor also create backups of your saves. But yes, I also did a copy. I asked because I get several warnings when opening the tool:

```
  WARNING: name mapping not found: tIM
  WARNING: name mapping not found: pQJ
  WARNING: name mapping not found: FdP
  WARNING: name mapping not found: G;q
  WARNING: name mapping not found: 1@y
  WARNING: name mapping not found: =rR
  WARNING: name mapping not found: SQw
  WARNING: name mapping not found: Naj
  WARNING: name mapping not found: fH7
  WARNING: name mapping not found: oBB
  WARNING: name mapping not found: 3NI
```

**Comment by raffel080108** [comment]
Everything works fine with my freighter rendering, haven't noticed anything out of the ordinary

**Comment by areithropos** [comment]
> Do we know if there's any issue in using the editor as it is now? At least just to refill stacks and things like that. Or it's not a good idea to use it for now?

I edited a pet, thus edited the RAW JSON file, there was no problem with that.

@goatfungus 
Is there a way to alter all the stats of the squadron pilots and their vessels? Or is that somewhere in the JSON file? If I remember correctly there was no option in the UI of the editor (only if you happen to know it, else I take a look myself)

**Comment by Jackalan23** [comment]
If somebody sees the update get released before I do could they @ me? I would be immensely grateful. - Jack

**Comment by Jackalan23** [comment]
@Jackalan23

**Comment by Mike-Blackwell** [comment]
General observation, it seems that the new release tries to use the ladder(s) for ramps which also messes up some of your previous freighter build components (e.g. it skew things either up or down from their original origins). So if your able to keep a previous copy of your freighter base and delete all up/down ramps in that JSON, reintroduce this updated freighter base file back in your game and you should be able to have all of your original freighter setup along with working electricity if you had it before.

**Comment by goatfungus** [comment]
I have just uploaded a new version, 1.10.5, which includes a number of changes for the Endurance update. This adds the Freighter Cargo inventory as well as the new Living Frigate types, but there may still be things missing which I plan to get to in the next week or so.

I haven't really had any time for a comprehensive test of the new game version yet, so please make sure you backup your save data. I'll also go back through these issue thread comments when I get a chance (I've only had a brief skim), so feel free to add here other comments/missing features that relate to the Endurance update and I'll get to them as soon as I am able.

Enjoy!

**Comment by boredfatcow** [comment]
what do i download, all i see is the changelog file, which i have no clue what to do with or where to put it, thank you for the update!

**Comment by goatfungus** [comment]
It should auto-update if you are running the editor from the .bat file.

If it doesn't automatically update, follow the main install instructions here:
https://github.com/goatfungus/NMSSaveEditor#installation

**Comment by goatfungus** [comment]
> General observation, it seems that the new release tries to use the ladder(s) for ramps which also messes up some of your previous freighter build components (e.g. it skew things either up or down from their original origins). So if your able to keep a previous copy of your freighter base and delete all up/down ramps in that JSON, reintroduce this updated freighter base file back in your game and you should be able to have all of your original freighter setup along with working electricity if you had it before.

On quick examination of the item listings, it looks like the game devs have repurposed some of the item IDs for different things now. This would mean that if you tried to import a previous base into a new save you'd get some pretty screwed up things happening. I'm not sure what all the replacements are yet, but for now I'd hold off trying to import old bases.

**Comment by areithropos** [comment]
He did some magic again! 😍

**Comment by boredfatcow** [comment]
> It is my understanding this save editor also create backups of your saves. But yes, I also did a copy. I asked because I get several warnings when opening the tool:
> 
> ```
>   WARNING: name mapping not found: tIM
>   WARNING: name mapping not found: pQJ
>   WARNING: name mapping not found: FdP
>   WARNING: name mapping not found: G;q
>   WARNING: name mapping not found: 1@y
>   WARNING: name mapping not found: =rR
>   WARNING: name mapping not found: SQw
>   WARNING: name mapping not found: Naj
>   WARNING: name mapping not found: fH7
>   WARNING: name mapping not found: oBB
>   WARNING: name mapping not found: 3NI
> ```

same, also i can't see my home bases still on base tab.

**Comment by grazzolini** [comment]
> I have just uploaded a new version, 1.10.5

Thanks. It seems it is working fine for simple stuff, like inventory management, but I still do get some warnings:

```
  WARNING: name mapping not found: tIM
  WARNING: name mapping not found: SQw
  WARNING: name mapping not found: Naj
```

Thank you for your time and amazing work on this save editor.

**Comment by h8rt3rmin8r** [comment]
About to hop in and test things out. Very glad to see development moving forward. Keep up the good work.

**Comment by Mike-Blackwell** [comment]
> > General observation, it seems that the new release tries to use the ladder(s) for ramps which also messes up some of your previous freighter build components (e.g. it skew things either up or down from their original origins). So if your able to keep a previous copy of your freighter base and delete all up/down ramps in that JSON, reintroduce this updated freighter base file back in your game and you should be able to have all of your original freighter setup along with working electricity if you had it before.
> 
> On quick examination of the item listings, it looks like the game devs have repurposed some of the item IDs for different things now. This would mean that if you tried to import a previous base into a new save you'd get some pretty screwed up things happening. I'm not sure what all the replacements are yet, but for now I'd hold off trying to import old bases.

Brendon, understand your concern and warning as your more closer to the code than user me! I can only talk re my previous freighter build which seems to have come out the other end in tack with minor changes and inclusions of the some of the new eye candy. 

I did find out that you must keep both "AIRLCKCONNECTOR" (one for going down to the hanger area (old) and the other to enter the bridge area as this somehow provides power to freighter items.

**Comment by Jackalan23** [comment]
@goatfungus Many thanks for keeping this awesome and often life saving tool updated, you are a legend.

**Comment by boredfatcow** [comment]
Pics of base and freighter section, can't back up, restore or move computer base.

![freighter](https://user-images.githubusercontent.com/109712166/180587395-5c396254-f45c-4bea-a3d8-b2e87862b329.png)
![base](https://user-images.githubusercontent.com/109712166/180587397-faba995e-e628-46e7-b6a0-121220f9a8e4.png)

**Comment by goatfungus** [comment]
As of the fix released this morning, you should be able to see the bases again. Also, Living frigates have been renamed "DeepSpaceCommon" to fix the issue where they couldn't be loaded.
