### ISSUE TITLE
Cannot claim Normandy or Leviathan Frigates

### ISSUE THREAD

**Issue by Sigvuld** [goatfungus/NMSSaveEditor#609]
When I go to claim these frigates on a character capable of claiming them (AKA can get frigates, etc.) I get the prompt to accept the Frigate proper on my screen for about a second before it closes itself. I cannot claim them because of this - is there anything that can be done? I've tried it on offline and online.

**Comment by BensDream** [comment]
Following - also experiencing this

**Comment by earl-Peter** [comment]
same here

**Comment by gggg336** [comment]
It is a game bug, nothing to do with the editor.

**Comment by Sigvuld** [comment]
I've noticed that today, actually - some people are starting to mention it in the forums for the game itself!

**Comment by Sigvuld** [comment]
Just as a temporary solution for those suffering from this same bug - someone in the Steam discussions for NMS had a solution, and it worked for me!

Go to the anomaly, try to add the frigate in question, have it fail/close the menu on you, MAKE SURE YOU DO THIS PART FIRST, then head back to your freighter. Go to the command room, use the console in the center to inspect your frigate, and select one of your fleet to inspect more closely. 

When you do, the frigate you tried to redeem earlier will have its menu for accepting it overlayed over the inspection menu, and allow you to add it to your frigate without issue! I was worried it would replace the frigate it overlayed, but it just added to the fleet like normal!

**Comment by earl-Peter** [comment]
Thanks
