### ISSUE TITLE
Git Hub NMSSaveEditor

### ISSUE THREAD

**Issue by RDouglass1** [goatfungus/NMSSaveEditor#610]
New Freighters have a Cargo Panel Now. SaveEditor does not Recognize it.

**Comment by Horonelius** [comment]
Gonna have to wait until he gets around to updating it.

**Comment by raffel080108** [comment]
> New Freighters have a Cargo Panel Now. SaveEditor does not Recognize it.

Chill bro, the version just came out. You gotta give the dev time

**Comment by goatfungus** [comment]
Please refer to #608
