### ISSUE TITLE
Unable to select save file for the first run

### ISSUE THREAD

**Issue by Shine7th** [goatfungus/NMSSaveEditor#616]
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_341
[DEBUG] Working Dir: E:\SteamLibrary\steamapps\common\No Man's Sky
[INFO] Starting Editor...
[DEBUG] Mem Usage: 513/7593 MB
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
[STDERR] 	at java.util.ComparableTimSort.mergeHi(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.mergeAt(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.mergeForceCollapse(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.sort(Unknown Source)
[STDERR] 	at java.util.Arrays.sort(Unknown Source)
[STDERR] 	at sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
[STDERR] 	at sun.awt.shell.ShellFolder.get(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.WindowsFileChooserUI$DirectoryComboBoxModel.addItem(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.WindowsFileChooserUI$DirectoryComboBoxModel.access$800(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.WindowsFileChooserUI.doDirectoryChanged(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.WindowsFileChooserUI.access$1100(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.WindowsFileChooserUI$11.propertyChange(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.fire(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
[STDERR] 	at java.awt.Component.firePropertyChange(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.setCurrentDirectory(Unknown Source)
[STDERR] 	at nomanssave.eo.b(Unknown Source)
[STDERR] 	at nomanssave.Application.r(Unknown Source)
[STDERR] 	at nomanssave.Application.p(Unknown Source)
[STDERR] 	at nomanssave.K.run(Unknown Source)
[STDERR] 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
