### ISSUE TITLE
Glitch Base info not showing > = no base

### ISSUE THREAD

**Issue by Mortadis** [goatfungus/NMSSaveEditor#619]
Hello, nice work dude 
Thx for updating :)
though, the new game editor does not seem to show the bases info > it looks like i have never done a base but i am standing in mine at the moment.
Is there anyway to fix it or this feature is just not in the editor anymore ?

**Comment by Mortadis** [comment]
![Capture d’écran 2022-07-23 143510](https://user-images.githubusercontent.com/109858107/180605137-f2bdad15-806a-440a-a699-bbaa788e9848.png)

**Comment by b0bulat0r** [comment]
I've noticed the same issue for Freighter Bases,
![image](https://user-images.githubusercontent.com/109917504/180658915-ccf014c6-7bcb-45e6-b90f-cd0b5c1f7fc0.png)

![image](https://user-images.githubusercontent.com/109917504/180658928-1f504992-712e-4e9a-8244-230167038189.png)

on my old save prior to the last update you can see it shows my base objects and it lets me export or restore my base
on a new save I started in this new game, I built a new freighter base with the new update parts and wanted to back it up but the option is greyed out,

I spent forever on my first base pre-update and I had used this editor before to copy it from one save to another and it worked fine, now that the freighters have all changed significantly I wanted to be able to do the same thing again, but can't seem to

(Basically I ran mods which haven't been updated yet and so I played the new update in a new un-modded save) I'd like to be able to copy my freighter into my modded save once the mods I use get updated, 

I spent 8 hours yesterday building my new freighter so I really hope this feature gets fixed again :)

**Comment by goatfungus** [comment]
The new version 6 bases should now be visible in the editor. I'm not sure what would happen if you try importing an older base into the newer save file format though, I guess we'll have to wait and see.
