### ISSUE TITLE
Start up Issue

### ISSUE THREAD

**Issue by AlliedKnight** [goatfungus/NMSSaveEditor#620]
While Opening the Save Editor in the CMD Screen I'm getting a Message that says "WARNING: Unable to register storage." 
I was using it early this morning and soon after had an Update to Java. Not sure if its related. but i notice afterwards i was getting that message 
While its not stopping the Editor from opening, when I load my save file it doesn't open

![20220723_141353](https://user-images.githubusercontent.com/109880955/180626635-58cc4488-9276-4283-a316-c2cb92a2339b.jpg)

**Comment by Lycodion** [comment]
Maybe -> https://github.com/goatfungus/NMSSaveEditor/issues/581
