### ISSUE TITLE
Cannot use features - missing creature/pet type

### ISSUE THREAD

**Issue by Ajdamekk** [goatfungus/NMSSaveEditor#624]
Cannot save, edit "Bases & Storage", "Settlements", "Discovery", "Milestones / Reputation" and cannot use everything in the edit tab because it is greyed out. Also in the log there is a bunch of Java stuff with Unknown Source. I tried updating Java nothing helped.

![image](https://user-images.githubusercontent.com/109871368/180659176-9fccf76a-837c-4736-9892-353912447c02.png)

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_341
[DEBUG] Working Dir: C:\Users\-----\Desktop\NMSSaveEditor-master\stuff
[INFO] Starting Editor...
[INFO] Reading metadata for accountdata.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 2354456
[DEBUG] Unknown1: 4139
[INFO] Version: 1
[INFO] TotalPlayTime: 26:23
[DEBUG] Unknown4: ef
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 2333008
[DEBUG] Unknown1: 4139
[INFO] Version: 1
[INFO] TotalPlayTime: 18:34
[DEBUG] Unknown4: 75
[INFO] Reading metadata for save3.hg
[DEBUG] DecompressedSize: 1323331
[DEBUG] Unknown1: 4139
[INFO] Version: 2
[INFO] TotalPlayTime: 0:00
[DEBUG] Unknown4: 7ff7
[INFO] Reading metadata for save5.hg
[DEBUG] DecompressedSize: 1328729
[DEBUG] Unknown1: 4139
[INFO] Version: 2
[INFO] TotalPlayTime: 0:02
[DEBUG] Unknown4: ef
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\-----\AppData\Roaming\HelloGames\NMS\st_7656-------------
[INFO] Reading account data...
[INFO] using name mappings: NMS 3.94 (account)
[DEBUG] Mem Usage: 257/3801 MB
[DEBUG] Latest version: "1.10.5"
[DEBUG] Current version: "1.10.5"
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - NORMAL - Jul 24, 16:59
[INFO] Filename: save.hg
[INFO] using name mappings: NMS 3.94 (savegame)
[WARNING] name mapping not found: tIM
[WARNING] name mapping not found: 7:k
[INFO] Finished.
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: No enum constant nomanssave.structures.h.LandJellyfish
[STDERR] 	at java.lang.Enum.valueOf(Unknown Source)
[STDERR] 	at nomanssave.structures.h.valueOf(Unknown Source)
[STDERR] 	at nomanssave.structures.g.cc(Unknown Source)
[STDERR] 	at nomanssave.ao.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[STDERR] 	at nomanssave.an.a(Unknown Source)
[STDERR] 	at nomanssave.Application.s(Unknown Source)
[STDERR] 	at nomanssave.Application.e(Unknown Source)
[STDERR] 	at nomanssave.Application.a(Unknown Source)
[STDERR] 	at nomanssave.I.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Ajdamekk** [comment]
Still does not work after downloading the 1.10.6 save editor update.

**Comment by SinOfAzure** [comment]
> Still does not work after downloading the 1.10.6 save editor update.
if you updated to experimental uninstall and reinstall no man sky (without experimental) and it will fix it

**Comment by Draco856** [comment]
I also have this same issue, and it seems the same failure point as well, except I'm not using Steam. I'm using my Xbox Version. Here's the Error log portion, the rest remains almost exactly the same the only differences being there are a whole lot more lines from accounting all the save locations.

[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: No enum constant nomanssave.structures.h.LandJellyfish
[STDERR] 	at java.lang.Enum.valueOf(Unknown Source)
[STDERR] 	at nomanssave.structures.h.valueOf(Unknown Source)
[STDERR] 	at nomanssave.structures.g.cc(Unknown Source)
[STDERR] 	at nomanssave.ao.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[STDERR] 	at nomanssave.an.a(Unknown Source)
[STDERR] 	at nomanssave.Application.s(Unknown Source)
[STDERR] 	at nomanssave.Application.e(Unknown Source)
[STDERR] 	at nomanssave.Application.a(Unknown Source)
[STDERR] 	at nomanssave.I.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by okolovmark** [comment]
with old saves its working, with new no

**Comment by Devilin-Pixy** [comment]
`[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: No enum constant nomanssave.structures.h.LandJellyfish`

Same issue seen in #627 Likely caused by the not yet supposed to be available Companion (^EXP_EGG08 = Helios Egg)

**Comment by goatfungus** [comment]
I have added the 2 new creature types to the editor now.

Enjoy!
