### ISSUE TITLE
1.10.6 is not working anymore

### ISSUE THREAD

**Issue by MrMfG** [goatfungus/NMSSaveEditor#625]
most tabs are grey (not clickable)
only way to save is close the programm

can you make version 1.10.5 available?

**Comment by ChaosPaladin** [comment]
https://github.com/goatfungus/NMSSaveEditor/tree/1bf7e3ac2cab0f9fd15f1a79c223f202cd589a9d

**Comment by Devilin-Pixy** [comment]
Likely same issue as #624 / #627

**Comment by goatfungus** [comment]
See #624
