### ISSUE TITLE
1.10.6 New name mappings not found

### ISSUE THREAD

**Issue by m0lz** [goatfungus/NMSSaveEditor#626]
New 1.10.6 version still has a few mapping not found ..

Slot: Slot 1 - NORMAL - Jul 25, 16:23
Filename: save.hg
using name mappings: NMS 3.94 (savegame)
WARNING: name mapping not found: tIM
WARNING: name mapping not found: 7:k

**Comment by Devilin-Pixy** [comment]
@goatfungus You're prolly interested as well, although these should be included in the mappings with a next MBINC update:
```
tIM = AmountAccumulators
7:k = FreighterDismissed
```

Cheers

**Comment by Devilin-Pixy** [comment]
2 more I just came across:
```
SQw = WhaleEvent
Naj = OverriddenReward
```

**Comment by m0lz** [comment]
Got a few more, this is from the new expedition save ..

  WARNING: name mapping not found: 4In
  WARNING: name mapping not found: HXT
  WARNING: name mapping not found: UVd
  WARNING: name mapping not found: lFr
  WARNING: name mapping not found: DqZ
  WARNING: name mapping not found: amP
  WARNING: name mapping not found: 0xI
  WARNING: name mapping not found: yID
  WARNING: name mapping not found: WmI
  WARNING: name mapping not found: IsL
  WARNING: name mapping not found: MMA
  WARNING: name mapping not found: AeI
  WARNING: name mapping not found: rER

**Comment by Devilin-Pixy** [comment]
For those who wish to know what they map to ahead of a new update:
```
4In = CreatureId
HXT = MinRelativeScale
UVd = MaxRelativeScale
lFr = SpecificBiome
DqZ = StartingTrust
amP = TimeSinceLastEgg
0xI = TimeSinceBirth
yID = IdToUseInMissionData
WmI = IsOptional
IsL = DecryptMissionSeed
MMA = RequireInteractionRace
AeI = NeedsPrimePlanet
rER = AnyInfestedBiome
```

**Comment by m0lz** [comment]
Another new name mapping from todays NMS 3.99 update, and a resulting Normal save ..

WARNING: name mapping not found: kPy
