### ISSUE TITLE
some tabs locked cant click them

### ISSUE THREAD

**Issue by Bwerken** [goatfungus/NMSSaveEditor#629]
![image](https://user-images.githubusercontent.com/95764578/180867815-dd8e0382-086a-43f1-8774-d960cfe7ce4e.png)
Guys what can i do at this situation. Before i could use these tabs but now i cant even click on them. Just locked like that. And also cant click edit, save or save as etc.

**Comment by Devilin-Pixy** [comment]
See #624 / #625 / #627

Most likely caused by having added the not yet available expeditions companion

**Comment by goatfungus** [comment]
See #624
