### ISSUE TITLE
can’t repair broken slots properly

### ISSUE THREAD

**Issue by syspal** [goatfungus/NMSSaveEditor#63]
Save editor can’t repair broken slots properly. It repairs, but the broken item is still there. In the game the slots not accepted as repaired and cant by used any more.
Was OK in 1.38 but doesn’t work with NEXT.

**Comment by rtjunkie** [comment]
You'll need to right-click and delete the broken tile items...then they'll be freed up in-game.

**Comment by syspal** [comment]
Some times it is to easy to find the solution.
Thank you
