### ISSUE TITLE
Saving a file from Save Editor breaks Power Inverter wiring

### ISSUE THREAD

**Issue by Randy1919** [goatfungus/NMSSaveEditor#631]
When I save an Endurance Savegame from the Savegame Editor, it switches the input and output of the Power-Inverters, breaking them. This happens to all Power-Inverters in the whole savefile, including all bases. This makes proximity-switch triggered doors not work anymore.

The Freighter also turns upside down for some reason, though that's not really a big issue since it still works fine.

**Comment by goatfungus** [comment]
That is really strange, technically the editor doesn't touch base objects unless you import them using the restore function (not advised at the moment). Are you sure this didn't happen when the game was first loaded up after the Endurance update or subsequent patches?

**Comment by Randy1919** [comment]
Yes I'm sure, I cecked multiple times, if I load the game, everything is fine, if I open the same savefile in the Save Editor, don't make any changes, save in the Save Editor and load this savegame, Power Inverters and teleport connections are broken. If I restore the very same save from the backup, everything works fine again.

**Comment by biffrapper** [comment]
Perhaps this bug is related to the wiring not saving/restoring correctly using the base backup function?

**Comment by Randy1919** [comment]
Maybe, I didn't use the base backup function, but maybe it's the same underlaying issue.

**Comment by goatfungus** [comment]
This should be fixed in the latest version.
