### ISSUE TITLE
There was an error saving the file.

### ISSUE THREAD

**Issue by TheSolusPrime** [goatfungus/NMSSaveEditor#638]
Whenever I try to save my edits, regardless of whether I actually edited something or not I get a pop-up saying "There was an error saving the file." Editor worked just fine up until yesterday and I have no idea what caused this.

**Comment by ssbanks2000** [comment]
I get this as well. Playing on PC.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
