### ISSUE TITLE
Freighter Bases Not Backing up properly since the new stairs were added.

### ISSUE THREAD

**Issue by Jackenheimer** [goatfungus/NMSSaveEditor#642]
1) Thank you for making this powerful, awesome tool!

2) I have a somewhat big Freighter base 3 floors tall. I backed it up and then tried to restore it on a new save. the floors are separated now by one level with decorations / plants floating in between the levels. I tried it again with an autosave just to see if it was a fluke. The issue replicated again.
![20220805113231_1](https://user-images.githubusercontent.com/88523511/183111770-40742d42-a812-4dc2-b557-9867c9d595b2.jpg)
![20220805113421_1](https://user-images.githubusercontent.com/88523511/183111799-c78e65b6-44d3-47c5-8666-6e958d37833d.jpg)
.

**Comment by goatfungus** [comment]
Not sure what would cause this, as the object positions don't get altered between backup/restore. If this still happens on new freighters open another ticket.
