### ISSUE TITLE
All frigates fuel requirements 50 tonnes

### ISSUE THREAD

**Issue by trowieuk** [goatfungus/NMSSaveEditor#643]
All frigates I go to recruit are 50 tonnes fuel requirements instead of the normal 2-16 range...
I have no mods, I have an old save before using save editor and the fuel is fine. 
Is there anything I could look at in the save files regarding fuel requirements seed/range?
![HpnBLhT](https://user-images.githubusercontent.com/45860444/183436550-4b354ac7-d288-4e51-87d9-6f43d01d6dc7.jpeg)

**Comment by goatfungus** [comment]
No idea sorry. I would suggest adding fuel in your inventory and you should be ok.
