### ISSUE TITLE
Error message today discovered 18-08

### ISSUE THREAD

**Issue by ubronan** [goatfungus/NMSSaveEditor#645]
Hi
I tried to edit my save and when entered data it gave this error instant when i changed values
The other issue i found is that the increase of my personal storage refused to be edited i changed the values but nothing happened
It just came back the same standard plus the owned ones by the visit on space stations
I also tried adding some units and it came back as before with the 13 million i had before
Anyway it shows in the added screenprint
![error](https://user-images.githubusercontent.com/111531848/185470402-326d662d-310e-4c7f-ac4f-71be5079080b.jpg)

**Comment by ubronan** [comment]
Also when i add more than 2 billion units the game freezes as i try to talk after scrapping ships to sell the upgrades 
It simply starts babbling forever and ever nothing works it freezes up

**Comment by Devilin-Pixy** [comment]
Those 'warnings' are not errors, and will usually not cause any issue. These are just new names found for data fields used in the save, which have yet to be 'mapped' to something we can easily understand. Until this is done with an upcoming release, the save editor will just use the short 'key' names instead. Nothing to worry about.

Here's what those new data fields (keys) map to for those interested:
```
tIM = AmountAccumulators
7:k = FreighterDismissed
kPy = ??? (not present for some weird reason)
```

> Also when i add more than 2 billion units the game freezes as i try to talk after scrapping ships to sell the upgrades It simply starts babbling forever and ever nothing works it freezes up Only option is kill the game to get out which means you lost all progress

This sounds like it has nothing to do with the save editor, unless this only happens after an edit was made, in which case your edit may have been faulty? You should likely report this to Hello Games instead
