### ISSUE TITLE
mapping issue

### ISSUE THREAD

**Issue by Kokopelli-Bob** [goatfungus/NMSSaveEditor#646]
I have 10 saved games, this one just came up with, Slot: Slot 8 - NORMAL - Aug 22, 10:37
  Filename: save16.hg
  using name mappings: NMS 3.94 (savegame)
  WARNING: name mapping not found: tIM
  WARNING: name mapping not found: 7:k
  WARNING: name mapping not found: SQw
  WARNING: name mapping not found: Naj
  WARNING: name mapping not found: yID
  WARNING: name mapping not found: WmI
  WARNING: name mapping not found: IsL
  WARNING: name mapping not found: MMA
  WARNING: name mapping not found: AeI
  WARNING: name mapping not found: rER
This game will not load, the rest seem to be fine.
Is there a way to fix this to get the game back
Thanks

**Comment by Devilin-Pixy** [comment]
For those mappings, see #626 and #645

For your game saves, make sure to have the correct path, to then select whichever slot through the drop-down
