### ISSUE TITLE
Mapping issues became larger after NMS secret updates

### ISSUE THREAD

**Issue by ubronan** [goatfungus/NMSSaveEditor#648]
Hello again sadly 
NMS makers are on the hunt for stuff what gives people who like moving fast forward in the game a really NASTY surprise 
As the first i used worked perfect i could open up more slots and do whatever, now almost nothing works anymore.
I can no longer add slots, and since that 3.99 version which is not even formerly existing the rest fails now as well
I see a huge list of mapping errors 
Which are still not resolved from the first post i did, so i know now that the previous post ment that the upgrade slots where locked and no longer  could be unlocked.
So i gave up trying, now the list is huge and i found i can not add money, and much more is no longer possible .
I understood i should be able to add items into the slots as well.... well i cant in no way i am able todo so it is all locked
I am not sure if needed for you, i play the steam version and in the dutch language 

![mapping errors expanded](https://user-images.githubusercontent.com/111531848/186853388-94ffa457-e35e-4243-bc7e-35438c6e028c.JPG)
d

**Comment by m0lz** [comment]
ubronan - See also this topic https://github.com/goatfungus/NMSSaveEditor/issues/626
