### ISSUE TITLE
Suggestion: Frequently Asked Questions (GitHub)

### ISSUE THREAD

**Issue by WalnutBunny** [goatfungus/NMSSaveEditor#65]
For instance, in the Freighter menu, there's options for "Home Seed" and "Hyperdrive". Frigates have "Home Seed", the Multitool has Damage, Mining, and Scan values, Ships have Damage, Shields, and Hyperdrive values, in addition to type and class.

It's not really indicated what all these values mean, and searching doesn't really get you anywhere.

**Comment by goatfungus** [comment]
A lot of the stats (Damage/Mining etc) appear like that in-game, so I don't think they really need to be explained. As for the others that are more behind the scenes I will probably add an FAQ section to github at some point, I just haven't had time yet.

**Comment by goatfungus** [comment]
I have started a basic FAQ, located [here](../blob/master/FAQ.md). I'll plan to keep adding to this over time.
