### ISSUE TITLE
Version 4.0

### ISSUE THREAD

**Issue by JB2021-81** [goatfungus/NMSSaveEditor#658]
This update totally reworks the savegame system. I can't even see my custom save in the app right now. I hope G.F. can fix this soon. I want to unlock all of the available inventory slots, get better freighters, etc., Also noticed a ton of stuff got nerfed & Stasis Devices are almost worthless now. You need 100's to get a few billion credits now.

**Comment by JonDum** [comment]
This doesn't help or add anything, please delete.

GF is already aware of the changes and is working on it

**Comment by olderbuffalo** [comment]
To say nothing of the fact the prior post was about 4.0 compatibility and has a response from goatfungs.

https://github.com/goatfungus/NMSSaveEditor/issues/657#issuecomment-1272008266

**Comment by goatfungus** [comment]
See https://github.com/goatfungus/NMSSaveEditor/issues/657
