### ISSUE TITLE
Custom mode shows up as empty slot, only tabs available are main and account

### ISSUE THREAD

**Issue by dfgdgdgfd** [goatfungus/NMSSaveEditor#660]
Is the editor not 4.0 ready or something?

**Comment by JanWerder** [comment]
Please look here for the latest news regarding 4.0: https://github.com/goatfungus/NMSSaveEditor/issues/657

**Comment by dfgdgdgfd** [comment]
Apologies, for some reason I thought the name of the current editor matched the current version name of the game.  There have been that many names for versions...
