### ISSUE TITLE
Save is considered "EMPTY" in the new update.

### ISSUE THREAD

**Issue by Xiarno** [goatfungus/NMSSaveEditor#662]
As explained in the title. Cannot select the new save.
Save is in Relaxed mode.
![image](https://user-images.githubusercontent.com/24660485/194757397-f51fc5d1-b667-4ce1-b8df-7bf92fd4c1b0.png)

When selecting, the saves showed up but the editing tabs are not unlocked.
![image](https://user-images.githubusercontent.com/24660485/194757417-cddda733-0d86-4566-bfb3-f0f31b780b9d.png)

**NMS Save Editor** is in version `1.11.0`
**No Man Sky** is in version `4.03`
Windows 10

**Comment by ShikaRoddy** [comment]
Same, won't let me edit.

**Comment by artig4n** [comment]
Any new game with "Custom" settings shows as Empty and cannot be edited.

**Comment by ShikaRoddy** [comment]
> Any new game with "Custom" settings shows as Empty and cannot be edited.

So reverting back to normal would fix it then?

**Comment by Richard127** [comment]
Any save that I have played since Waypoint update shows as "Empty". Saves that I haven't played yet show up as normal. Basically, like others have commented, I can't edit any save that has been played since waypoint.

**Comment by Xiarno** [comment]
> Any new game with "Custom" settings shows as Empty and cannot be edited.

This is not a custom save. It is a relaxed save.

**Comment by GCDragonfli** [comment]
I'm have the same isue .. The only save showing is from back in several days ago when I logged into game to see what was changed.
I started a 2 New games today 10/09/22 .. 1 with custom settings and 1 with Normal setting and neither will show up .. Just the old one. Thank you

**Comment by goatfungus** [comment]
Custom and Relaxed game modes were added in 4.0... I haven't yet bolted them into the editor... coming soon...

**Comment by GCDragonfli** [comment]
​Thank you and have a good one.😌
________________________________

**Comment by Dragonsire** [comment]
"Save As" seems to create an Empty Save

**Comment by artig4n** [comment]
Thanks again :)

**Comment by Richard127** [comment]
Working great now. Legendary support and a NMS essential tool. Many thanks.
