### ISSUE TITLE
Saves won't show

### ISSUE THREAD

**Issue by Droid8Apple** [goatfungus/NMSSaveEditor#663]
I went in to the folder manually, made a copy of my actual most recent save, and that still won't allow it to be seen by editor. 

I saw the editor update so I'm not sure what is wrong as it should be the latest version. 

I see others are having issues as well but from a quick glance it they're saying the save shows as empty - which I suppose mine could be as well, but either way. Better safe than sorry and figured I'd report it here. 

![Screenshot 2022-10-09 114053](https://user-images.githubusercontent.com/115415660/194766037-8d886bd4-f626-4ff9-a185-4b258f65790f.png)

Please take a look, when you can, Sir Goatfungus.

**Comment by FabreFactionIRL** [comment]
Try a clean install, that worked for me.
Download the EXE from the master repo and install in a new location (i.e. not over the top of a previous install of NMS Save Editor)
Run the BAT and see how you get on.
