### ISSUE TITLE
Exosuit Tech locked to 3 rows

### ISSUE THREAD

**Issue by Xakorik** [goatfungus/NMSSaveEditor#665]
Can't increase the exosuit tech slots beyond 3 rows in the editor even though the game now allows it to go to 6 rows.

It does work in Test mode though.

**Comment by goatfungus** [comment]
Will fix in next update :)

**Comment by goatfungus** [comment]
Update 1.11.2 should fix this now :)

**Comment by Xakorik** [comment]
Thanks for the quick fix, I'll download the update now
