### ISSUE TITLE
Getting an error message in my "cmd.exe"

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#666]
Brandon, 

1) I'm noticing that at the end of load my save files I get the following message is this something to worry about?

![image](https://user-images.githubusercontent.com/30412372/194785663-857a7a99-f007-490b-a2da-6b32f5135fa7.png)

2) also, I noticed that the Account tab is not available for my Version 4 save files, am I missing something?
3) It seems that for those pre-4.0 filesaves they look like the previous version files e.g. I have General, Tech, and Cargo tabs for most things, so if I decide to maximize the inventory spaces they only show a max of 48 for General and Cargo but Tech is ~21 slots. Once I've save my pre-4.0 save files to the latest version then I'm able to maximise the tech and Cargo spaces as one would expect for a version 4.0 savefile.

**Comment by goatfungus** [comment]
Can you please send me a copy of the log file? NMSSaveEditor.log
You should be able to find this in the same folder as the editor, and it will have a bit more info about the error itself.

**Comment by Mike-Blackwell** [comment]
Brendon, I've attached the log per your reqest

[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/9747864/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
This is the same error as #664 so I will comment there.
