### ISSUE TITLE
Base Info / Vehicles

### ISSUE THREAD

**Issue by Nyrdin** [goatfungus/NMSSaveEditor#668]
NMS Waypoint (Normal Mode) - NMSSaveEditor v1.11.1
2 Issues:

1. I can't open the Base Info (drop down menue is empty)
    Info: I have 1 base in each galaxy
2. In Vehicles (here Roamer)
    All items displayed as "Unknown Tech"

Finally: THANK YOUR for your work on this amazing tool!

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
