### ISSUE TITLE
Finding Squadron in JASON

### ISSUE THREAD

**Issue by Bugster21** [goatfungus/NMSSaveEditor#669]
Hi do anybody know why Squadron is grayed out for me (on ps4 save) I have full Squadron. Or how to find it in the JSON 
Thanks 😁

**Comment by MGJerry** [comment]
I don't know if the PS4 save file is similar to PC, but if it is, that should be in PlayerStateData/SquadronPilots
![image](https://user-images.githubusercontent.com/85227828/225838118-fef259ca-8576-4d47-b158-a96809d10b85.png)
