### ISSUE TITLE
Unlocking account rewards doesn't work.

### ISSUE THREAD

**Issue by X66Herobrine66X** [goatfungus/NMSSaveEditor#672]
When I try to unlock expedition rewards in the editor, they're still locked when I go in game. There's been conflicting reports about this in the creative and sharing discord, it doesn't work for me and another person, but a third guy says it works fine for him.

**Comment by Robobuilder1** [comment]
I'm having the same issue when I tried it

**Comment by NekoiNemo** [comment]
I tried it with the latest editor and it worked, including the stupid Twitch crap (as long as i was offline for that one). What were your steps?
