### ISSUE TITLE
Bases not showing in app

### ISSUE THREAD

**Issue by Pale-RiderX** [goatfungus/NMSSaveEditor#676]
NMS Waypoint (Normal Mode) - NMSSaveEditor v1.11.2
1 Issue:

I cannot import, export or see any bases on the drop down.  I saw this was reported in the previous version, but I'm still having this issue in your latest just so you know.

Thank you so much for all of your work that goes into this and the enhanced experiences in game I've been able to achieve because of it!

**Comment by briang** [comment]
Confirming this issue

NMSSaveEditor v1.11.2 and NMS 4.04 Experimental

Base menu is empty

I'd also like to thank you for the excellent work you've put into this save editor

**Comment by Dragonsire** [comment]
yup same...main feature I use so hope to have fixed at some point.

**Comment by spideruk07** [comment]
i am having the same issue but its only on the new saves, i have saves i haven't converted yet and you can access all bases in them its just on the waypoint updated saves, thanks for this awesome tool
