### ISSUE TITLE
Switch save support please

### ISSUE THREAD

**Issue by Atomic646** [goatfungus/NMSSaveEditor#679]
anyway we can get switch save support?

**Comment by fennectech** [comment]
i can provide samples of a waypoint save from switch

**Comment by SirCathal** [comment]
how do you export them? (I'm new to the Switch)

**Comment by Atomic646** [comment]
> 

You need a hacked switch, run jksv homebrew to back up save to sd card, then put on pc

**Comment by fennectech** [comment]
EPIC!  <3   thank you!   no more fighting with pc saves to get them onto the switch
