### ISSUE TITLE
[Issue] File too large exception/can't open

### ISSUE THREAD

**Issue by crypt1cx** [goatfungus/NMSSaveEditor#68]
Can't open the .jar file and can't open with the batch files.

Fixed this with adding the complete path to "java -jar *C:\User\** NMSSaveEditor.jar"

**Comment by crypt1cx** [comment]
Might have something to do with file associations in win10. Glad I don't have Win10 (and never gonna get), since this is my friends issue, which I helped him kinda solve.

**Comment by goatfungus** [comment]
Sounds like either you're trying to run it under the wrong working directory, or Java hasn't been installed properly and is not on your PATH variable. I think the title is a little misleading, but since you've found your own workaround I'll close this.
