### ISSUE TITLE
Unable to backup or restore freighter/freighter base. Buttons greyed out in save editor. 1.11.2

### ISSUE THREAD

**Issue by crashhawk65** [goatfungus/NMSSaveEditor#681]
The freighter base is in the game but I can't back it up when I edit it.

**Comment by ukmerlin** [comment]
For now do NOT back up restore any bases in NMSE even when the function returns if you have power items installed. There is an issue with it breaking wiring.

**Comment by crashhawk65** [comment]
Any idea when this function will return?
