### ISSUE TITLE
Bases aren't showing up in Bases tab

### ISSUE THREAD

**Issue by criscrosaplesos** [goatfungus/NMSSaveEditor#682]
Json shows persistent player bases, but using the Bases tab shows nothing.

**Comment by Mike-Blackwell** [comment]
Brendon, I have the same issue, I can see my storage Chest 0-9 and Ingredients but no base is currently showing in the NMSSAVE Editor tab, as Cris has mention they are available within the Raw JSON data.

**Comment by NZzer0** [comment]
me too, same issue, no bases at all. 
JSON is fine, all 250 bases show there no probs.

**Comment by Cheater42** [comment]
same

**Comment by LeppardEVE** [comment]
same

**Comment by christensennn** [comment]
same

**Comment by goatfungus** [comment]
This is fixed now.
