### ISSUE TITLE
Attempting to import an exported 4.0 ship results in an error

### ISSUE THREAD

**Issue by tanareed** [goatfungus/NMSSaveEditor#685]
Since 4.0 dropped and the editor was updated for it, I haven't been able to successfully export and then re-import a ship. I get a simple "An error occurred during import." popup warning, and nothing happens.

I am attaching the [NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/9790973/NMSSaveEditor.log) file in case that helps.

**Comment by xEden95x** [comment]
It clearly says it's not updated for 4.0

**Comment by tanareed** [comment]
Sorry, then.
