### ISSUE TITLE
Mappings not avaliable.

### ISSUE THREAD

**Issue by LuigiCotocea** [goatfungus/NMSSaveEditor#687]
Currently Missing mappings:
[DEBUG] Mapping not available: bGK
[DEBUG] Mapping not available: ORx
[DEBUG] Mapping not available: WA4
[DEBUG] Mapping not available: rri
[DEBUG] Mapping not available: tIM
[DEBUG] Mapping not available: e4G
[WARNING] name mapping not found: 4I:
[WARNING] name mapping not found: c=Q
[WARNING] name mapping not found: SQw
[WARNING] name mapping not found: Naj
[WARNING] name mapping not found: 4In
[WARNING] name mapping not found: HXT
[WARNING] name mapping not found: UVd
[WARNING] name mapping not found: lFr
[WARNING] name mapping not found: DqZ
[WARNING] name mapping not found: amP
[WARNING] name mapping not found: 0xI
[WARNING] name mapping not found: yID
[WARNING] name mapping not found: WmI
[WARNING] name mapping not found: IsL
[WARNING] name mapping not found: MMA
[WARNING] name mapping not found: AeI
[WARNING] name mapping not found: rER
[WARNING] name mapping not found: 4I:
[WARNING] name mapping not found: c=Q
[WARNING] name mapping not found: SQw
[WARNING] name mapping not found: Naj
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/9793960/NMSSaveEditor.log)

**Comment by AstroCat00** [comment]
I get this same error.

**Comment by alexpi4** [comment]
me too !  and icon erros

**Comment by Devilin-Pixy** [comment]
These are just warnings about 'mappings' that have been found but not yet translated to something 'understandable'.
In most cases these will not cause any issues.

DEBUG Only
```
bGK HazardDrain
ORx HazardDrainDifficulty
WA4 StackSizeGroup
rri InventoryStackSizeGroup
tIM AmountAccumulators
e4G HazardProtectionDrainMultiplier
```
Expedition
```
SQw WhaleEvent
Naj OverriddenReward
```
Detected on load
```
4I: HardestUsedPreset
c=Q SettingsLocked
=4m HasLoopedIndicies
6nS Difficulty
E7u DifficultyPreset
?<y PersistentBaseDifficultyFlags
bSn DifficultySettingPreset (replaced/removed f:D)
JiM DifficultyMinimums    
To; FinalRewardSwitchAlt
4In CreatureId
HXT MinRelativeScale
UVd MaxRelativeScale
lFr SpecificBiome
DqZ StartingTrust
amP TimeSinceLastEgg
0xI TimeSinceBirth
yID IdToUseInMissionData
X;? RewardSwitchAlt
WmI IsOptional
IsL DecryptMissionSeed
MMA RequireInteractionRace
AeI NeedsPrimePlanet
rER AnyInfestedBiome
aVB SeenStories
yF< PagesData
```

**Comment by SabreRunner** [comment]
I just saw how much is different in 4.04 and avoided using the program until it updates.
