### ISSUE TITLE
Warnings on loading Waypoint 4.04 Save Game

### ISSUE THREAD

**Issue by SabreRunner** [goatfungus/NMSSaveEditor#689]
This is what I see.
`Reading save file...
  Slot: Slot 3 - CUSTOM - Oct 19, 21:50
  Filename: save5.hg
  using name mappings: NMS 4.0 (savegame)
  WARNING: name mapping not found: 4I:
  WARNING: name mapping not found: c=Q
  WARNING: name mapping not found: SQw
  WARNING: name mapping not found: Naj
Finished.`

**Comment by AstroCat00** [comment]
![image](https://user-images.githubusercontent.com/40003647/198160697-06b9af57-bf53-4144-b473-740504f37d97.png)

**Comment by Devilin-Pixy** [comment]
See: #687
