### ISSUE TITLE
Inventory slot not fully working

### ISSUE THREAD

**Issue by walter-exit** [goatfungus/NMSSaveEditor#69]
Hi,

Good mod. Thanks for the hard work.

I noticed today that after expanding and enabling some extra slots in a ship, that the slots do not work like expected. For example; when a hyperdrive is put in such a slot, the galaxy map shows you cannot jump because you lack fuel. Yet, the hyperdrive in the slot is 100% charged. This is confirmed when using the recharge-menu to try and charge the hyperdrive anyway; it says its fully charged.

So perhaps there is more to creating a slot than what is done right now by the editor, for the game to fully pick up on it? Or maybe its my specific circumstances? I'd love to hear what you think about it.

**Comment by goatfungus** [comment]
That's a known bug in NMS, not related to the editor. This can usually be fixed by dismantling the hyperdrive and building a new one.
