### ISSUE TITLE
new type of inventory slots with patch 4.05

### ISSUE THREAD

**Issue by areithropos** [goatfungus/NMSSaveEditor#690]
With the latest patch 4.05 they introduced supercharged slots in inventories.

**Comment by BattleGrown** [comment]
I wanna supercharge all my slots, please make it happen lol

**Comment by JB2021-81** [comment]
YES. I want to do the same.

**Comment by JB2021-81** [comment]
So, what exactly DOES super-charging a slot do?

**Comment by posthy** [comment]
There's already mod https://www.nexusmods.com/nomanssky/mods/2558, might help

**Comment by Merriner** [comment]
> There's already mod https://www.nexusmods.com/nomanssky/mods/2558, might help

Would still be nice to be able to change the position of your slots.

**Comment by SirCathal** [comment]
Would be great to support the supercharged slots. Changing the Position and adding more would be fine.

**Comment by cbfnmsteam** [comment]
> I wanna supercharge all my slots, please make it happen lol

I can not agree u more

**Comment by AVeryTastyRaspberry** [comment]
> There's already mod https://www.nexusmods.com/nomanssky/mods/2558, might help

This mod only supercharges Exosuit and Escrocraft.   It doesn't do it for Multitool or ships.   Oddly enough the mod page does say it cannot mod ships or multitools, but, should be able to do through a save editor.

Would be great if this could be a feature in the future.

**Comment by Thygoo** [comment]
You can just edit them using the the Edit RAW JSON in Edit. I did that and got all slots supercharged, as well as multi weapons, freighter, ships, exosuit, and all vehicles.

**Comment by Thygoo** [comment]
![18421e4159927-screenshotUrl](https://user-images.githubusercontent.com/116932471/198812859-b4f3d035-f4ac-45f6-8910-5ad30dcf718b.jpg)

**Comment by MGJerry** [comment]
Yep just like @Thygoo said, you can just manually supercharged all tech slots using "Edit Raw JSON"

Here's a smol dummy guide for anyone who likes / don't know how to do it:

Copy the text in this [pastebin](https://pastebin.com/TyYNWDv9) to any of your wanted "SpecialSlots" location:
(They are all in the "PlayerDataState" btw)

Exosuit: Inventory_TechOnly
Multitools (if you edit your Current one, makes sure to do it to the same one in the Owned section)
 - Current: WeaponInventory
 - Owned: Multitools\(slot number)\Store
Freighter: FreighterInventory_TechOnly
Exocrafts: VehicleOwnership\(slot number)\Inventory_TechOnly
Starships: ShipOwnership\(slot number)\Inventory_TechOnly

Enjoy :3

**Comment by Thygoo** [comment]
``> Yep just like @Thygoo said, you can just manually supercharged all tech slots using "Edit Raw JSON"
> 
> Here's a smol dummy guide for anyone who likes / don't know how to do it:
> 
> Copy the text in this [pastebin](https://pastebin.com/TyYNWDv9) to any of your wanted "SpecialSlots" location: (They are all in the "PlayerDataState" btw)
> 
> Exosuit: Inventory_TechOnly
> 
> Multitools (if you edit your Current one, makes sure to do it to the same one in the Owned section)
> 
> * Current: WeaponInventory
> * Owned: Multitools \ (slot number) \ Store
> 
> Freighter: FreighterInventory_TechOnly
> 
> Exocrafts: VehicleOwnership \ (slot number) \ Inventory_TechOnly
> 
> Starships: ShipOwnership \ (slot number) \ Inventory_TechOnly
> 
> Enjoy :3
> 
> Edit: fricked up the comment formatting, lul :P Edit 2: again, I should really start using Preview before making comments
Sorry to Quote you but your Pastebin was incorrect since you only put X Coordinates, so I went in and made sure to index the codes correctly for future reference.

These Codes you just have to Copy over SpecialSlots (Make sure to copy over the whole line before the comma)

<img width="300" alt="Screenshot 2022-10-29 135042" src="https://user-images.githubusercontent.com/116932471/198845986-ea35f00e-5972-4b24-960e-b51d5916e60c.png">


Exosuit: Inventory_TechOnly
Freighter: FreighterInventory_TechOnly
[https://pastebin.com/SSsPtJFG](url)

Starships: ShipOwnership
Exocrafts: VehicleOwnership
Multitools: Multitools
[https://pastebin.com/X8dy23FY](url)

The Save Editor doesn't like when codes are not indexed correctly. 

Thank you MGJerry for the Thumbs up. Hope @goatfungus adds this feature to the editor in the future. But this is the only workaround for it.

**Comment by MGJerry** [comment]
@Thygoo yeah thanks for fixing that.
I used a smol python script to generate that, and guess I sent the broken one text file :P
I really should start double-checking stuff befor posting :')

**Comment by SirCathal** [comment]
Good to know, but a feature tu supercharge slots inside the Editor would be much better.
Maybe @goatfungus can implement that to the rightclick menu of the slots.
A Menu Function to supercharge all slots inside a inventory would be great too.

**Comment by boyuanfang** [comment]
Here is a little python script for converting all slots into special slots:

```
import json
import os

def generate(all_slots):
    base = {
        "Type": {
            "InventorySpecialSlotType": "TechBonus"
        },
        "Index": {
            "X": 0,
            "Y": 0
        }
    }

    result = []
    for slot in all_slots:
        new = base.copy()
        new['Index'] = slot
        result.append(new)
    return json.dumps(result, indent=2)

script_dir = os.path.dirname(os.path.abspath(__file__)) #<-- absolute dir the script is in
input_file = 'input.json'
output_file = 'output.json'

f = open(os.path.join(script_dir, input_file))
j = json.load(f)
f.close()

# Writing to sample.json
with open(os.path.join(script_dir, output_file), 'w') as outfile:
    outfile.write(generate(j))

print('done')
```

**Comment by AvenonX** [comment]
For whatever reason, I'm having troubles adding supercharged slots to my exocraft but have had no issues whatsoever with adding them to just about everything else. Am I missing something?

**Comment by christensennn** [comment]
> Good to know, but a feature tu supercharge slots inside the Editor would be much better. Maybe @goatfungus can implement that to the rightclick menu of the slots. A Menu Function to supercharge all slots inside a inventory would be great too.
Agree.

**Comment by Ryland0** [comment]
> For whatever reason, I'm having troubles adding supercharged slots to my exocraft but have had no issues whatsoever with adding them to just about everything else. Am I missing something?

Same here. None of my ECs will take the update. I've limited the number of slots to 30 and removed the inactive slots. Nothing works.

**Comment by WatcherCCG** [comment]
> Good to know, but a feature tu supercharge slots inside the Editor would be much better. Maybe @goatfungus can implement that to the rightclick menu of the slots. A Menu Function to supercharge all slots inside a inventory would be great too.

Seconding this. The raw JSON can be confusing at times, and a single error can brick the whole thing. If it is possible, this suggestion would be most appreciated.

**Comment by goatfungus** [comment]
Sorry for the delay, I've been really busy on other projects.

I have mostly completed this feature now and it will be in the next release. I just need to test a few more things with the latest NMS version.

**Comment by BattleGrown** [comment]
You are doing god's work many thanks
