### ISSUE TITLE
Add New File name in File Main Tab

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#691]
Brendon, is it possible to add a field in the File Details tab that would allow us to view and change the file name to our liking for each Game Slot save. The value is in the PlayerStateData > SaveName. I've been able to manually change the file name to something that makes sense, but it doesn't show up until I so an actual manual save in game???

**Comment by goatfungus** [comment]
This should be already covered by a recent feature in the game
