### ISSUE TITLE
after run exe. i can't do anything

### ISSUE THREAD

**Issue by bigmonsteryun** [goatfungus/NMSSaveEditor#697]
the "choose save path" window have not response,i can't do anything at chooes save path

**Comment by kobs57** [comment]
All of a sudden (probably after a HG update) I can no longer save the changes I made in the save editor.
The save changes in the main window seem to work, but when I close it's asking me if I want to save and it loops there, asking me if I want to save and nothing is saved

**Comment by NarseGC** [comment]
Have you solve the problem that the editor stuck at "choose save path" window? I'd like some advise if it doesn't bother you.

**Comment by kobs57** [comment]
Yes, the problem was solved with the new save editor update, eeverything works well now

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
