### ISSUE TITLE
Missing export and import functions (and asking for new ones)

### ISSUE THREAD

**Issue by SirCathal** [goatfungus/NMSSaveEditor#698]
Please reactivate the possibility to exoport and re-import bases. Especially the freighter bases. Because when changing freighters, it is more than helpful to be able to transfer them so easily.

Furthermore, it would be fantastic if you could also export and import the contents of the cargo containers, the vehicles and the suit.

**Comment by goatfungus** [comment]
This should now be fixed in version 1.11.9.
