### ISSUE TITLE
Memory Leak when switching saves/opening JSON

### ISSUE THREAD

**Issue by Lenni009** [goatfungus/NMSSaveEditor#699]
I switched between save JSONs very often, and over time (probably about 10-20 save switches) the editor hogged over 4GB of ram, with the usual out of memory signs like extreme slow downs when opening the raw JSON of a save, etc.

**Comment by Devilin-Pixy** [comment]
Just asking to make sure, but you are using the Java 8 64-bit version?

**Comment by stevedwray** [comment]
I'm not subscribed but I still get these emails

**Comment by Lenni009** [comment]
Yes, Java 8 Update 341 (64-bit) to  be exact.
