### ISSUE TITLE
don't try to move games from one slot to another with 1.11.2

### ISSUE THREAD

**Issue by wkitty42** [goatfungus/NMSSaveEditor#701]
i have a few slot holes and i wanted to move some of my saved games around... i tried moving the game in slot 5 to slot 2 and lost it... poof! gone... i almost lost a 2nd one when i realized that slot 2 still showed as empty and slot 5 was also empty... ahhhhhh!!! thank deity i had a manual backup of my game's save directory and could easily undo the mess...

eagerly awaiting 1.11.3+ to appear...

**Comment by Devilin-Pixy** [comment]
This is not something the Save Editor can do, so I have no clue what you have done.

You will have to rename the save files themselves, making sure you do so correctly. There are files for auto and manual saves, as well as platform specific metadata files in some cases. On Steam for example, this will result in 4 files per slot, where slot 3 would be mf_save5.hg, mf_save6.hg, save5.hg, and save6.hg.

**Comment by wkitty42** [comment]
sure it can... moving something on a computer involves one of two processes...
1. copy and place with new name followed by deleting the original files
2. rename from old name to new name...
in some cases, copying/moving also requires some editing of the file contents if they contain references to the file in some manner...

basically what i did was the first form... i used the save editor's copy function and told it to paste into one of the empty slots... my next step would have been to either use the save editor's save delete option to delete the original save OR i would have simply selected another save to copy over top of the old save files i had copied... either way i could have gone, in the end i would have had at least one set of saves to just delete...

my want/need to move the save files to fill the slot holes is a personal ADD/ADHD/OCD thing... plus i cannot help but to see it in my external records where i record which game is being played in which slot... HG giving us the ability to name our games really helped but i still maintain my external records and seeing those empty/missing file names is... well... it makes me twitch...

**Comment by meachware** [comment]
To help or not - the "Save As" feature has been in the editor for many revisions and it USED to work fine. Around 3.9 (totally guessing but I DID report the issue here) the function was broken and has not worked since. I just tried it again with the current version (1.11.5 and game v4.12.1) and while it looks like it is going to work, it does not and only copies over 1 of the 4 save files.

Performing this manually is the ONLY viable work around

Please consider this as an open issue - thank you
