### ISSUE TITLE
WAYPOINT (4.0)

### ISSUE THREAD

**Issue by Djoeliejoes** [goatfungus/NMSSaveEditor#703]
Will there be an update for the newest NMS update?

**Comment by AstroCat00** [comment]
Yeah, curious as well.

**Comment by MGJerry** [comment]
Wait, ain't the current version (released 28 days ago as of I'm writing this comment) compatible with 4.0.x updates???

**Comment by apendrag0n3** [comment]
Someone needs to update the Readme.md - as it still references Frontiers - but the editor is WAY beyond that now

**Comment by MGJerry** [comment]
@apendrag0n3 if you look at the pull requests, the top 4 (including mine) are about doing exactly that

It's goatfungus's project so he chooses when to update it I guess
(I mean at least he is keeping the editor up-to-date which is very poggers)

**Comment by apendrag0n3** [comment]
@MGJerry - and THAT is the "important" part! :-)

**Comment by masternetra** [comment]
It currently functions for the latest update but currently the editor doesn't see much less allow you to add/remove supercharged slots in the tech slots.
