### ISSUE TITLE
[BUG] Wrong items stack sizes

### ISSUE THREAD

**Issue by MGJerry** [goatfungus/NMSSaveEditor#704]
New limit for unopened technology modules
![image](https://user-images.githubusercontent.com/85227828/200893196-c17df608-6a07-4c86-b949-1f50e600ce4a.png)
(left & middle: stack made in-game, right: stack made with editor)

Wrong item stack size in freighter
Survival difficulty:
![image](https://user-images.githubusercontent.com/85227828/200892663-75f61ee7-f8f8-42f4-97c4-b8db09277423.png)
(left: stack made in-game, right: stack made with editor)

Normal difficulty:
(dunno, I don't play / have a save in this difficult)

**Comment by goatfungus** [comment]
This should now be fixed in version 1.11.9.
