### ISSUE TITLE
Poor performance when pasting long JSON strings

### ISSUE THREAD

**Issue by Lenni009** [goatfungus/NMSSaveEditor#705]
If you have a big unformatted block of JSON in a single line string, for example from bases, and paste that code into the JSON editor, it becomes unresponsive and freezes for several minutes. [this tool](https://nmscd.com/BaseReorder/) can be used to reorder bases, and it causes that issue when pasting the output JSON back into the editor.

**Comment by Devilin-Pixy** [comment]
Don't use minified JSON? Even though technically perfectly valid JSON, I can understand the editor to expect a more specific format. It is basically un-minifying/beautifying your JSON as the output needs to be shown in a clear format.

**Comment by Lenni009** [comment]
If you tell me how I tell JavaScript to properly indent and add linebreaks to the JSON string, I'd be happy to do that. But since the JSON.stringify() method returns one single line of JSON, I currently have no choice other than using NomNom (with which I haven't run into any issues so far with my usage)

**Comment by Devilin-Pixy** [comment]
That is implemented natively with JSON.stringify()

**Comment by Lenni009** [comment]
Good to know, thanks!
