### ISSUE TITLE
Json Edits not saving

### ISSUE THREAD

**Issue by AvenonX** [goatfungus/NMSSaveEditor#708]
I've meddled with the Json editor to add supercharged slots to most of my gear (starship, multitool, suit, etc) but when it comes to making any modifications to the exocraft, none of the changes I make stick even if I've saved correctly. I'll make the changes, save, boot up the game and find nothing with the exocraft changes, and then reopen the Json editor and find all my edits are gone. Am I missing something?

**Comment by Devilin-Pixy** [comment]
This can not be done through Save Editing, it requires a mod to bypass restrictions on Exocraft
