### ISSUE TITLE
File browser UI for JSON Import is blank

### ISSUE THREAD

**Issue by bumpy-flapjack** [goatfungus/NMSSaveEditor#709]
When starting the editor v1.11.2 and selecting a game slot for my Steam save game, I go to Edit->Import JSON... itÄs not possible to browser for anything because the file browser UI won't display any actual items. See screenshot.
My Win10 OS is installed to SSD drive G:\, so is Java 8.

![image](https://user-images.githubusercontent.com/119008737/203852732-2ab10430-1440-4e2d-b5f1-288d5158ff0a.png)

**Comment by Devilin-Pixy** [comment]
As a workaround you can use a trick:
type `*.*` and click Open for it to show everything and bypass the specified JSON format

**Comment by goatfungus** [comment]
Should be fixed.
