### ISSUE TITLE
Unable to add or see supercharged slots

### ISSUE THREAD

**Issue by Lazyshadow04** [goatfungus/NMSSaveEditor#710]
As the title says, with the addition of the Waypoint update, supercharged slots have been added. It would be nice to see where those slots are, and add more.

Maybe a feature can be added where you can right-click on a technology slot (exosuit, exocraft, multitool, starship, etc.) and make it supercharged.

**Comment by K-E-R-A-D** [comment]
noticed

it's too bad couldn't add supercharged on tech slots with this save editor :(

**Comment by masternetra** [comment]
+1 would also like the ability to see and add/remove supercharged spots as well.

**Comment by Rylna** [comment]
+1 that as I would like to as well.

**Comment by goatfungus** [comment]
Sorry for the delay, somehow I missed this one.
I have added the supercharged feature into the editor now.
