### ISSUE TITLE
bases not visible anymore

### ISSUE THREAD

**Issue by KBurd67** [goatfungus/NMSSaveEditor#711]
I just updated and haven't used the editor in a while - but went to do something (add some slots which I was able to) - but noticed my bases have disappeared from the editor.  They're still in the game and my ship base seems to be present - just not planet ones.  Is there something I should do?  I'm not especially concerned - but if I wanted to do anything with them - I can't now.

**Comment by MGJerry** [comment]
Other people also got this issue and reported it already (#668, #676 & most recently #682). GoatFungus gonna fix it eventually, so next time please check if the bug is reported yet before making a new one.

**Comment by KBurd67** [comment]
Thanks - just logged on to this github - but thanks.

**Comment by MGJerry** [comment]
I mean you could always try using the raw json editor (slightly annoying to use, but more options) if you really have to edit something.

**Comment by BONEGUNN** [comment]
how do you use the raw json editor to save a current base and copy said base into a new base computer at a new location?

**Comment by MGJerry** [comment]
> how do you use the raw json editor to save a current base and copy said base into a new base computer at a new location?

@BONEGUNN If my memories serve me correct, all saved bases should be in PlayerStateData/PersistentPlayerBases.
For ease of access, remember the name of the base, and you should be able to locate its index with that.

Edit: example below
![image](https://user-images.githubusercontent.com/85227828/225837057-d99de615-2796-425f-af50-8df2f96d9880.png)

**Comment by goatfungus** [comment]
This will be fixed in the next update, sorry for the delay.

**Comment by goatfungus** [comment]
This should now be fixed in version 1.11.9.
