### ISSUE TITLE
[Suggestion] complete name mapping is included with MBINCompiler

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#712]
The [MBINCompiler](https://github.com/monkeyman192/MBINCompiler/releases) project includes the full name mapping in every release. No need  to work for it :)

**Comment by goatfungus** [comment]
Sometimes the structures in MBINCompiler take a bit longer to be published, so now I only use that as a reference. I have added other features in my code generation tools which allow me to export the name mappings a lot quicker now.
