### ISSUE TITLE
the Chinese language will become a pile of garbled code in 1.11.3

### ISSUE THREAD

**Issue by China-AltF4** [goatfungus/NMSSaveEditor#713]
The Chinese language will become a pile of garbled code in old version 1.11.2,  but this problem has not been solved in  new version 1.11.3.
![屏幕截图 2022-12-10 003716](https://user-images.githubusercontent.com/117169376/206749106-ba30f4e3-a318-4063-b714-5f7bc73af402.jpg)

**Comment by goatfungus** [comment]
This should be working now in 1.13+
