### ISSUE TITLE
Export import options non active

### ISSUE THREAD

**Issue by Snoopy81S** [goatfungus/NMSSaveEditor#717]
Please reactivate the possibility of export and import bases, contents of the cargo containers, exosuit, ships, vehicles. Especially the freighter bases. Because when changing freighters and etc., it's more than helpful to be able to transfer them so easily.
Furthermore, it would be fantastic if you could also export and import mentioned above the contents of the cargo.

**Comment by BONEGUNN** [comment]
I second this notion..... I'd be willing to pitch in some cash with others who are having this issue if it helps speed the process at all. What you do for the community is priceless and always appreciated

**Comment by BONEGUNN** [comment]
does anybody read these?

**Comment by Snoopy81S** [comment]
I

> does anybody read these?

I think, the answer is - "No".

**Comment by goatfungus** [comment]
Yes, I do read these. Sorry for the delay, I've had a lot going on.

I had to disable export and import features because the layout of all the inventories changed in game and older structures did not import correctly. I'll see what I can do to make this work again, but can't promise too much.

**Comment by goatfungus** [comment]
This should now be fixed in version 1.11.9.
