### ISSUE TITLE
Can't save the data, and therefore any modification I make to the save

### ISSUE THREAD

**Issue by Louigolas** [goatfungus/NMSSaveEditor#719]
So when i try to save and leave, the editor apparently can't save the data. I got this lines in the logs when I do it:

[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
[STDERR] 	at java.util.ArrayList.elementData(Unknown Source)
[STDERR] 	at java.util.ArrayList.get(Unknown Source)
[STDERR] 	at nomanssave.util.f.getValue(Unknown Source)
[STDERR] 	at nomanssave.util.f.at(Unknown Source)
[STDERR] 	at nomanssave.Application.t(Unknown Source)
[STDERR] 	at nomanssave.Application.v(Unknown Source)
[STDERR] 	at nomanssave.Application.k(Unknown Source)
[STDERR] 	at nomanssave.F.windowClosing(Unknown Source)
[STDERR] 	at java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
[STDERR] 	at java.awt.Window.processWindowEvent(Unknown Source)
[STDERR] 	at javax.swing.JFrame.processWindowEvent(Unknown Source)
[STDERR] 	at java.awt.Window.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

I don't know what to do ad i already updated JAVA, Windows, The game and the editor. Pls help

**Comment by goatfungus** [comment]
This should be already fixed, if the problem persists please raise another ticket.
