### ISSUE TITLE
Fractal (version 4.1)

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#721]
Looks like we will be needing Brendon magic touch to fix NMSSave Editor as it seems not to recognize every thing with the new game saves.

**Comment by kobs57** [comment]
Yep, big update and things aren't working

**Comment by GrumpyKoala1966** [comment]
Problem I'm having is after removing the "DISABLEMODS txt" file,  ALL my ships are miniature when I put back the "DISABLEMODS txt" file the ships are correct size, so I'm wondering if this is HG making it harder to use Mods, I'm still not sure if this is affecting me only as can't find anyone else reporting this issue.?

**Comment by Mike-Blackwell** [comment]
So is this a glitch that can be temporarily taken advantage of aka miniature ships?
