### ISSUE TITLE
Base Info is greyed out.

### ISSUE THREAD

**Issue by BONEGUNN** [goatfungus/NMSSaveEditor#724]
Just as the title says, there is no access to the Base Info for saving, exporting etc. Sadly, it makes the game useless for my gameplay.

Would anyone be willing to chip in with me to donate some money to this kind sir to make it worth his time to rectify?

He has elevated the game play to a point that I wouldn't play without his editor. I know many feel the same way. 

Let's shine some light his way.

**Comment by GrumpyKoala1966** [comment]
BONEGUNN Do you mean your own base or Settlement Base?
I just checked my settlement base and all information is showing..

**Comment by Shinjigami25** [comment]
I have the same Issue, that the Base and Storage Tab is accessable, yet everything in it is empty / greyed out. I wanted to use this function to get beyond the base building part, as i don't have talent in that sort of stuff. So i wanted to use a seed for a base.
So i put up a base reclamation terminal an nothing more. 
Has anyone else encountered that Problem? Would something more be needed?

**Comment by BONEGUNN** [comment]
> BONEGUNN Do you mean your own base or Settlement Base? I just checked my settlement base and all information is showing..
> 
> P.S. make sure that "DISABLEMODS txt" file is removed
> 
> To be honest if it's to do with Settlement Base I'd not worry, I can't get "S" class with 200 people, next to no outgoing's and great missions with loads coming in.. I gave up long ago..

I'm typing about the base and storage tab. I can access the tab but all options are greyed out.

**Comment by goatfungus** [comment]
I have made some improvements in the latest version, please try again.
