### ISSUE TITLE
Won't start up

### ISSUE THREAD

**Issue by coFNailz** [goatfungus/NMSSaveEditor#725]
I downloaded the update and it'll work once then I have to re download it. Was like that a few times and now it won't start up at all

**Comment by GrumpyKoala1966** [comment]
Have you got game running when trying to start it or have you got a minimized page running?
All else fails reboot your computer and try again..

**Comment by GrumpyKoala1966** [comment]
Well I virtually replied straight away and no reply, so I guess he/she got it working..

**Comment by coFNailz** [comment]
I closed the game out. Nothing minimized. It shows a bit flashed some text
then closes.  Tried rebooting computer. Got it to load one more time after
re downloading it a few times but once I closesd it to go into game to
check what I did carried over I closed the game, went back to the save
editor and it wouldn't open again

**Comment by Devilin-Pixy** [comment]
It would help if you could provide some additional info.
Please provide the log file from the save editor folder after reproducing the issue.

**Comment by coFNailz** [comment]
Solved
