### ISSUE TITLE
Multitool & Ships repair slots ???

### ISSUE THREAD

**Issue by lawgiver69** [goatfungus/NMSSaveEditor#73]
When using the save editor some of my multitool & ship slots with equipment already in the slot states the slot needs repair. Using latest revision 1.5.13 Next and i'm using experimental if that makes a difference.

**Comment by goatfungus** [comment]
Screenshot available?

In most cases when equipment is broken and in need of repair, you simply right-click on it and choose the "Repair" option. The only thing that changed in 1.5.13 was the new ability to repair broken shots from salvaged ships.

**Comment by goatfungus** [comment]
For that particular function the editor looks for a value labelled "BrokenTechnology" or something, which is meant only for slots that were broken on salvaged ships. Was this a salvage that you repaired in game earlier? If so, maybe the game didn't clear the "Broken Technology" flag.

**Comment by goatfungus** [comment]
I really hate it when the game doesn't do what it's meant to, and this appears to be one of those cases. When exactly did you salvage the ship? Was it before NMS 1.52 when they allegedly fixed a bug with partially repaired tech?

**Comment by lawgiver69** [comment]
Can't be 100% sure, while i salvaged the ship probably before 1.52 it was a grind repairing the slots from then on. But as you already know there's so many bugs in the game and my slots/equipment do seem to be working. 

I have found a second ship i'm currently repairing, i'll see how that goes. ;-)

**Comment by goatfungus** [comment]
Is it possible that you used the editor previously to delete the broken tech? That was a workaround I had suggested, but it would have left the slots in a broken state not registered by the editor.

**Comment by lawgiver69** [comment]
It's possible, i might have moved them still in a broken state to another slot which may have left the original slot requiring repair and plonking an item in the damaged slot even though the game itself didn't see it as damaged. Not 100% sure but ????

I have repaired the damaged slots and added the item/upgrade back. Again thanks for the replies mate, a dedicated gentleman you are sir. ;-)

**Comment by goatfungus** [comment]
Try setting the "SpecialSlots" list to "[]" to clear any broken slots.

<img width="261" alt="untitled" src="https://user-images.githubusercontent.com/41274031/43861055-c9227af6-9ba9-11e8-9c90-856fe8e11288.png">

**Comment by lawgiver69** [comment]
That seems to have worked. Haven't fired up the game as just about to go to bed, work in the morning! :(

Will check when i get home tomorrow just to be sure but looks good in the editor, equipment is still in the correct slots and doesn't show the repair option anymore.

Cheers mate! ;-)
