### ISSUE TITLE
Supercharged slots not shown or selectable.

### ISSUE THREAD

**Issue by Antilitist** [goatfungus/NMSSaveEditor#731]
I have noticed that I can't see supercharged slots and I am unable to designate slots I wish to be supercharged. 

Not sure if this is and issue or a request for enhancement.

Either way, thanks for your work and dedication to the editor.

~Anti

**Comment by MGJerry** [comment]
This is not currently a feature of the editor.
If you really want to do it, there're ways to do it in #690 
Both Thygoo's text and boyuanfang's script works fine

**Comment by WatcherCCG** [comment]
Is there any plans to add it to the editor? I believe the other popular editor has added such a feature. Not everyone will want to dig through the raw JSON.

**Comment by MGJerry** [comment]
Tbh it's highly unlikely, but it's up to goatfungus, it's his repo afterall. If you check the changelogs and commits, most of what he does nowadays is bugfixes and patches for version updates. New features are few and far between.

**Comment by goatfungus** [comment]
I have added the supercharged slots feature to the editor now, sorry for the delay.
