### ISSUE TITLE
"Error: cannot create backups folder" and exit on launch

### ISSUE THREAD

**Issue by renbear67** [goatfungus/NMSSaveEditor#732]
I'm getting an error on launch of the .bat file.
```
Initializing environment...
Error: cannot create backups folder
Press any key to continue . . .
```

I'd be happy to provide any files or logs, but I'm not sure what would be relevant. I'm running Windows 11.

**Comment by Devilin-Pixy** [comment]
A full log after reproducing the issue, would be useful

**Comment by goatfungus** [comment]
It's likely that you're opening the zip file as a read-only "folder" in windows. To resolve this, extract the contents of the zip file to a writable folder and you should be good to go.
