### ISSUE TITLE
NMS save editor Isssue

### ISSUE THREAD

**Issue by mrchatter** [goatfungus/NMSSaveEditor#737]
Sometime in the last week the editor went crazy.
I even format drive and reinstalled game thinking it was an issue on my side.
I have reloaded game and it works but when I try to use the editor it only loads some of the tabs at the top.
here is a list I get from the editor. If someone could help it would be greatly appreciated.
I have a few tabs that are all greyed out such as bases and storage, settlement, discoveries, 
![Screenshot 2023-03-12 232031](https://user-images.githubusercontent.com/127705949/224608134-ee464202-2000-48f5-95c7-eead7b041501.png)
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/10953549/NMSSaveEditor.log)

**Comment by mrchatter** [comment]
yea looks like #726 and #727 are having same issue

**Comment by GrumpyKoala1966** [comment]
This save editor version seems to be working fine for me, wish I could help you folks..

**Comment by snejivan** [comment]
join. i have the same problem. I have one save working without failures, the other produces the same error. the interesting thing is that if I switch from a working to a non-working save, then I can edit these tabs, but the settlements will remain uneditable (the settlement will be from a different save slot)

**Comment by snejivan** [comment]
join. i have the same problem. I have one save working without failures, the other produces the same error. the interesting thing is that if I switch from a working to a non-working save, then I can edit these tabs, but the settlements will remain uneditable (the settlement will be from a different save slot)

**Comment by mrchatter** [comment]
ok I figured it out all you have to do is in the editor go to companions and delete the robo pet and everything works well
