### ISSUE TITLE
Using save editior make NMS become "unstable" as i like to call it (crashes more frequently)

### ISSUE THREAD

**Issue by BraveCaperCat2** [goatfungus/NMSSaveEditor#739]
I have the save editor working now, but after i edit my save(s) the game starts to become unstable (it crashes more frequently) it never does this when i save my NMS game although before Version 3.9, the Endurance Update, playing for long periods of time caused the game to crash - plus sometimes loading up no man's sky (before version 3.9) the game looks like [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2813265905) (that's a space station before 3.9) could these issues (without mods and nms and before 3.9) be somehow related to our NMSSE (No Man's Sky Save Editor) which i have to admit helped me ALOT in ALOT of circumstances (utopia expedition, nothing else) plus before i got from 8GB RAM to 36GB RAM it was crashing EVEN MORE FREQUENTLY then this. (utopia expedition again)

**Comment by goatfungus** [comment]
I don't think the editor would be causing this as it only modifies the save file and doesn't interfere with any other running process.

**Comment by BraveCaperCat2** [comment]
> I don't think the editor would be causing this as it only modifies the save file and doesn't interfere with any other running process.

and it only started happening after I used the editor, so it is the only possible culprit (or just the amount of RAM I had at the time, I have 4X as much now)
