### ISSUE TITLE
Requests: Mission completion for Base + Clone Save~change gamemode

### ISSUE THREAD

**Issue by Giblejimmy** [goatfungus/NMSSaveEditor#74]
So first things first, and thanks for before goat with my last request, looking to see if you can give us the ability to just complete all base missions so we can rapidly unlock things but without just rapidly unlocking them (vehicles whatnot).

Also wondering if we could get a way to clone a save and change its game mode say if I want to play with a friend who is on normal but I want to keep all of my Survival I can clone my save and play with them.

**Comment by goatfungus** [comment]
Changing mission state is a complicated process, but it's already requested in #36.

To "clone" a save, just choose "Save As" and select which slot you want to overwrite.

I think playing with a friend uses their save file, not yours, but if you really want to change game-mode on one of your exiting saves, just copy their version number into your save file (should be 2nd line in the JSON editor). Really easy to do.
