### ISSUE TITLE
solving the problem with broken tabs

### ISSUE THREAD

**Issue by snejivan** [goatfungus/NMSSaveEditor#740]
![Снимок экрана (5)](https://user-images.githubusercontent.com/128461284/226598115-9e203a29-b98f-4e3a-b3ae-e999d460dd06.png)

I tried to remove the robot egg (pet from the latest rewards) and everything worked for me again

**Comment by mrchatter** [comment]
> ![Снимок экрана (5)](https://user-images.githubusercontent.com/128461284/226598115-9e203a29-b98f-4e3a-b3ae-e999d460dd06.png)
> 
> I tried to remove the robot egg (pet from the latest rewards) and everything worked for me again

How do i remove the reward. I do not have a good save to use. .. not sure can i just delete or is there a better way

**Comment by goatfungus** [comment]
This should be fixed now, I have added the missing types in the editor.
