### ISSUE TITLE
Can' press "Reload", "Save Changes" and "Save As"; cant access "Milestones / Reputation"

### ISSUE THREAD

**Issue by NetworkDiskSomething** [goatfungus/NMSSaveEditor#741]
Yo, yesterday the program worked fine. I could save the changes and access everything. today I somehow cant save changes anymore for unknown reasons. In addition to that, the secondary Window where all the commands and responds of the program can be seen says : 
[WARNING] name mapping not found: ... like 10 times.

please help

**Comment by GrumpyKoala1966** [comment]
Just checked mine and is working as intended.

**Comment by NFKnight** [comment]
I've had this issue as well.  It seems inconsistent.  Everything will work fine now and again.

**Comment by goatfungus** [comment]
A lot of this should be resolved in the new version.
