### ISSUE TITLE
4.2 Update and Utopia Stuff

### ISSUE THREAD

**Issue by SirCathal** [goatfungus/NMSSaveEditor#745]
Please add support for the new Features,
like
- new Sentinel Ship Type
- new Sentinel Multitools
- the special Utopia Speeder
- and that we have 12 Ship Slots now.

I found an issue, when I export my Utopia Speeder and Import it into another save, then only the tech stuff is imported.
the normal cargo is missing.

**Comment by goatfungus** [comment]
I am in the process of adding all this, but need to progress into the game a bit more to be able to see what the new stuff looks like. If anyone has a save file with one of the new sentinel ships and a new multitool on it, can you please send it through to me so I can work it out.

**Comment by goatfungus** [comment]
I have released an update which should add most of these features into the editor.

I am not sure about the Utopia Speeder. I believe it's an expedition reward/unlock, but not sure how it gets added to the save file. In order to get this to work I will need to see a save file with the Utopia Speeder on it.

**Comment by goatfungus** [comment]
I have found the Utopia Speeder info and have added it to the editor now.

**Comment by SirCathal** [comment]
Great Work, the only thing that is not known by the Editor is the special Switch Ship.
It works like the Utopia Speeder or the Golden Vector.
The type is a reference to a special resource and the Seed is ignored and set to 0x1.
But the Ship is in the Game on any platform.
I attached the Switch Ship that I use with my GOG Account then you can add that.
@goatfungus  I Tested it on GOG, Steam and XBox
[!v42_GOG__Horizon_Vector_NX_Switch.zip](https://github.com/goatfungus/NMSSaveEditor/files/11182792/v42_GOG__Horizon_Vector_NX_Switch.zip)

The only Problem with all Ships is, when I export them, only the tech inventory is exported.

Some Versions ago, the cargo Inventory was exported to, I use this to move stuff between saves, because there is no Option to Export/Import the 10 Storage Containers and the Exosuite (Which booth would be cool)

One Utopia Item that is unknown has the ID "^EGG1" 
It is the flying Robo Pet that you could get as reward.

I have it in the switch Ship but as written above, the cargo is not exported.
