### ISSUE TITLE
Exosuit Supercharge

### ISSUE THREAD

**Issue by abbadabadu** [goatfungus/NMSSaveEditor#746]
Although I see option for supercharge multitool and ship tech slot, don't see one for exosuit. Please add it if possible. And Thanks for your great work.
Edit : And if possible then a option to supercharge all slots together.

**Comment by K-E-R-A-D** [comment]
![javaw_EfeuTzy90M](https://user-images.githubusercontent.com/39189775/230652528-0b893ae6-9fd9-4a4c-89b9-e80b6aa4b8f5.png)

welp, it's missing apparently...

**Comment by goatfungus** [comment]
I based the supercharge feature off details from another posting which didn't mention suit tech...

I'll look to add supercharge to suit tech today, and include a "Supercharge All" option. Thanks for the suggestion.

**Comment by goatfungus** [comment]
I've just released a new version that adds the missing pieces for the supercharge feature. Thanks for raising this.

**Comment by BattleGrown** [comment]
Thank you!

**Comment by abbadabadu** [comment]
Thank You very much.
