### ISSUE TITLE
Add items-Ship Technology

### ISSUE THREAD

**Issue by radink** [goatfungus/NMSSaveEditor#747]
When you right click to add an item to the ship technology inventory, all of the pulldowns are blanks. Seems to be the only place this happens.

**Comment by goatfungus** [comment]
That's strange... what kind of ship is it?

**Comment by radink** [comment]
It’s happening only on my utopia speeder i think.

**Comment by goatfungus** [comment]
Can you send me a copy of the JSON for it?
You should be able to find the ship under the ShipOwnership section in the JSON Editor.

**Comment by goatfungus** [comment]
Nevermind, I have found the details myself and have fixed the issue in version 1.11.8

**Comment by radink** [comment]
Thanks! Appreciated!
