### ISSUE TITLE
Cannot save changes

### ISSUE THREAD

**Issue by Croslink** [goatfungus/NMSSaveEditor#748]
I am able to load my save just fine, change whatever I desire (in my case I've change my MT name) but the editor won't save. I have Java 8 64bit installed. 

Initializing environment...
Starting Editor...
Reading metadata for accountdata.hg
Reading metadata for save.hg
  Version: 1
  TotalPlayTime: 57:39
Reading metadata for save2.hg
  Version: 1
  TotalPlayTime: 57:38
Reading metadata for save3.hg
  Version: 720902
  TotalPlayTime: 1:47
Reading metadata for save4.hg
  Version: 720902
  TotalPlayTime: 1:43
Reading account data...
  using name mappings: NMS 4.2 (account)
WARNING: invalid switch detected: 12
WARNING: invalid switch detected: 12
WARNING: invalid switch detected: 12
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - CUSTOM - Apr 7, 19:00
  Filename: save.hg
  using name mappings: NMS 4.2 (savegame)
  WARNING: name mapping not found: SQw
  WARNING: name mapping not found: Naj
  WARNING: name mapping not found: ?n7
  WARNING: name mapping not found: heA
  WARNING: name mapping not found: tj1
  WARNING: name mapping not found: yqB
  WARNING: name mapping not found: Qb3
Finished.
Setting multitool name: M4A1S
Formatting JSON...
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at nomanssave.util.f.getValue(Unknown Source)
        at nomanssave.util.f.as(Unknown Source)
        at nomanssave.Application.t(Unknown Source)
        at nomanssave.Application.v(Unknown Source)
        at nomanssave.Application.b(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by justnice980** [comment]
Same issue here. Changes do not apply.

**Comment by goatfungus** [comment]
Please send a copy of the log file... it should have more detail.

**Comment by justnice980** [comment]
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_361
[DEBUG] Working Dir: G:\No Man's Sky\NMSSaveEditor-master
[INFO] Starting Editor...
[DEBUG] Mem Usage: 515/7617 MB
[DEBUG] Latest version: "1.11.6"
[DEBUG] Current version: "1.11.6"
[INFO] Loading storage: C:\Users\Justin\AppData\Roaming\HelloGames\NMS\st_76561197999921788
[INFO] Reading metadata for accountdata.hg
[DEBUG] Extra: 280
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5718493
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:53
[DEBUG] Extra: 280
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5718561
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:53
[DEBUG] Extra: 280
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\Justin\AppData\Roaming\HelloGames\NMS\st_76561197999921788
[INFO] using name mappings: NMS 4.2 (account)
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - CUSTOM - Apr 7, 15:24
[INFO] Filename: save2.hg
[INFO] using name mappings: NMS 4.2 (savegame)
[WARNING] name mapping not found: ?n7
[WARNING] name mapping not found: heA
[WARNING] name mapping not found: tj1
[WARNING] name mapping not found: yqB
[WARNING] name mapping not found: Qb3
[INFO] Finished.
[INFO] Ship 3 - Cargo: all slots enabled
[INFO] Setting ship name: lamb
[INFO] Setting squadron slot 1 enabled: false
[INFO] Setting squadron slot 3 enabled: false
[INFO] Setting squadron slot 2 enabled: false
[INFO] Setting squadron slot 2 enabled: true
[INFO] Setting squadron slot 3 enabled: true
[INFO] Setting squadron slot 1 enabled: true
[INFO] Setting squadron slot 1 NPC seed: 0x14B6632E1DA684F8
[INFO] Setting squadron slot 2 NPC seed: 0xD27F70A09BD2EBE7
[INFO] Setting squadron slot 3 NPC seed: 0xAEFB5F4F45D8264D
[INFO] Setting squadron slot 2 ship seed: 0x3812E125F2108519
[INFO] Setting squadron slot 3 ship seed: 0x3812E125F2108519
[INFO] Setting squadron slot 3 ship type: Robot
[INFO] Setting squadron slot 2 ship type: Robot
[INFO] Setting squadron slot 1 ship type: Robot
[INFO] Setting squadron slot 1 ship seed: 0x3812E125F2108519
[INFO] Setting squadron slot 1 rank: 3
[INFO] Setting squadron slot 3 rank: 3
[INFO] Setting squadron slot 2 rank: 3
[INFO] Setting squadron slot 0 rank: 3
[INFO] Setting squadron slot 1 ship seed: 0xB844C98FD4752CA2
[INFO] Setting squadron slot 1 ship seed: 0x3812E125F2108519
[INFO] Formatting JSON...
[INFO] using name mappings: NMS 4.2 (savegame)
[INFO] Loading saves for Slot 1...
[INFO] Finished.
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5719099
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:53
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Formatting JSON...
[INFO] using name mappings: NMS 4.2 (savegame)
[INFO] Loading saves for Slot 1...
[INFO] Finished.
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5719099
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:53
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5716901
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:53
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5717479
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:54
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5717932
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:54
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5718031
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:54
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - CUSTOM - Apr 7, 15:29
[INFO] Filename: save2.hg
[INFO] using name mappings: NMS 4.2 (savegame)
[WARNING] name mapping not found: ?n7
[WARNING] name mapping not found: heA
[WARNING] name mapping not found: tj1
[WARNING] name mapping not found: yqB
[WARNING] name mapping not found: Qb3
[INFO] Finished.
[INFO] Starting JSON Editor...
[INFO] Starting JSON Editor...
[INFO] Formatting JSON...
[INFO] using name mappings: NMS 4.2 (savegame)
[INFO] Loading saves for Slot 1...
[INFO] Finished.
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5717237
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:54
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5718028
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:54
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5718051
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:54
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5718049
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:54
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5718459
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:55
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - CUSTOM - Apr 7, 15:36
[INFO] Filename: save2.hg
[INFO] using name mappings: NMS 4.2 (savegame)
[WARNING] name mapping not found: ?n7
[WARNING] name mapping not found: heA
[WARNING] name mapping not found: tj1
[WARNING] name mapping not found: yqB
[WARNING] name mapping not found: Qb3
[INFO] Finished.
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5718455
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:56
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5718490
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:56
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5701952
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:57
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5702025
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:57
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Loading saves for Slot 1...

**Comment by Croslink** [comment]
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_361
[DEBUG] Working Dir: D:\Games\steamapps\common\No Man's Sky
[INFO] Starting Editor...
[INFO] Reading metadata for accountdata.hg
[DEBUG] Extra: 280
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 7505588
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 57:39
[DEBUG] Extra: 280
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 7504565
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 57:38
[DEBUG] Extra: 280
[INFO] Reading metadata for save3.hg
[DEBUG] DecompressedSize: 7230684
[DEBUG] Unknown1: 4138
[INFO] Version: 720902
[INFO] TotalPlayTime: 1:47
[DEBUG] Extra: 24
[INFO] Reading metadata for save4.hg
[DEBUG] DecompressedSize: 4078156
[DEBUG] Unknown1: 4138
[INFO] Version: 720902
[INFO] TotalPlayTime: 1:43
[DEBUG] Extra: 24
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\Daniel\AppData\Roaming\HelloGames\NMS\st_76561198028783332
[INFO] Reading account data...
[INFO] using name mappings: NMS 4.2 (account)
[WARNING] invalid switch detected: 12
[WARNING] invalid switch detected: 12
[WARNING] invalid switch detected: 12
[DEBUG] Mem Usage: 515/7626 MB
[DEBUG] Latest version: "1.11.6"
[DEBUG] Current version: "1.11.6"
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - CUSTOM - Apr 7, 19:00
[INFO] Filename: save.hg
[INFO] using name mappings: NMS 4.2 (savegame)
[WARNING] name mapping not found: SQw
[WARNING] name mapping not found: Naj
[WARNING] name mapping not found: ?n7
[WARNING] name mapping not found: heA
[WARNING] name mapping not found: tj1
[WARNING] name mapping not found: yqB
[WARNING] name mapping not found: Qb3
[INFO] Finished.
[INFO] Reading save file...
[INFO] Slot: Slot 1 - CUSTOM - Apr 7, 19:00
[INFO] Filename: save2.hg
[INFO] using name mappings: NMS 4.2 (savegame)
[WARNING] name mapping not found: SQw
[WARNING] name mapping not found: Naj
[WARNING] name mapping not found: ?n7
[WARNING] name mapping not found: heA
[WARNING] name mapping not found: tj1
[WARNING] name mapping not found: yqB
[WARNING] name mapping not found: Qb3
[INFO] Finished.
[INFO] Setting multitool name: M4A1S
[INFO] Formatting JSON...
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
[STDERR] 	at java.util.ArrayList.elementData(Unknown Source)
[STDERR] 	at java.util.ArrayList.get(Unknown Source)
[STDERR] 	at nomanssave.util.f.getValue(Unknown Source)
[STDERR] 	at nomanssave.util.f.as(Unknown Source)
[STDERR] 	at nomanssave.Application.t(Unknown Source)
[STDERR] 	at nomanssave.Application.v(Unknown Source)
[STDERR] 	at nomanssave.Application.f(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.doClick(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by goatfungus** [comment]
Looks like something changed with the active multitool selection in the game.

Try editing the JSON and finding the ActiveMultioolIndex value... that's where the -1 comes from. Change it to 0 and you should be good to go. I'll add a fix shortly.

**Comment by justnice980** [comment]
> Looks like something changed with the active multitool selection in the game.
> 
> Try editing the JSON and finding the ActiveMultioolIndex value... that's where the -1 comes from. Change it to 0 and you should be good to go. I'll add a fix shortly.

Mine is already at 0 and I have the same results.

**Comment by goatfungus** [comment]
> Mine is already at 0 and I have the same results.

Yours might be a different issue... are you getting the error:
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1

**Comment by justnice980** [comment]
> 

I'm not actually seeing any specific kind of error. For all intents and purposes, the logfiles seem to indicate that it's working, but when I reload the game, all the changes are not there. This is the log from my most recent attempt to change the squadron values. 

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_361
[DEBUG] Working Dir: G:\No Man's Sky\NMSSaveEditor-master
[INFO] Starting Editor...
[INFO] Reading metadata for accountdata.hg
[DEBUG] Extra: 280
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5701952
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:57
[DEBUG] Extra: 280
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5702025
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:57
[DEBUG] Extra: 280
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\Justin\AppData\Roaming\HelloGames\NMS\st_76561197999921788
[INFO] Reading account data...
[INFO] using name mappings: NMS 4.2 (account)
[DEBUG] Mem Usage: 515/7617 MB
[DEBUG] Latest version: "1.11.6"
[DEBUG] Current version: "1.11.6"
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - CUSTOM - Apr 7, 15:40
[INFO] Filename: save2.hg
[INFO] using name mappings: NMS 4.2 (savegame)
[WARNING] name mapping not found: ?n7
[WARNING] name mapping not found: heA
[WARNING] name mapping not found: tj1
[WARNING] name mapping not found: yqB
[WARNING] name mapping not found: Qb3
[INFO] Finished.
[INFO] Starting JSON Editor...
[INFO] Setting squadron slot 1 ship seed: 0x3812E125F2108519
[INFO] Setting squadron slot 3 ship type: Hauler
[INFO] Setting squadron slot 3 ship seed: 0x3812E125F2108519
[INFO] Setting squadron slot 2 ship seed: 0x3812E125F2108519
[INFO] Setting squadron slot 2 ship type: Robot
[INFO] Setting squadron slot 3 ship type: Robot
[INFO] Setting squadron slot 1 ship type: Robot
[INFO] Setting squadron slot 1 rank: 3
[INFO] Setting squadron slot 0 rank: 3
[INFO] Setting squadron slot 2 rank: 3
[INFO] Setting squadron slot 3 rank: 3
[INFO] Formatting JSON...
[INFO] using name mappings: NMS 4.2 (savegame)
[INFO] Loading saves for Slot 1...
[INFO] Finished.
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 5702265
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:57
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save2.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5719512
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:57
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Loading saves for Slot 1...
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5703186
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:58
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 5703178
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 128:58
[DEBUG] Extra: 280
[INFO] Save file reloaded from storage: save.hg
[INFO] Loading saves for Slot 1...

**Comment by goatfungus** [comment]
Do you have the game running while the editor is running?
I generally need to exit to the main menu (at least) for any changes to be picked up.

**Comment by Croslink** [comment]
> Looks like something changed with the active multitool selection in the game.
> 
> Try editing the JSON and finding the ActiveMultioolIndex value... that's where the -1 comes from. Change it to 0 and you should be good to go. I'll add a fix shortly.

It's working now. Thank you for your time and quick reply :)

**Comment by goatfungus** [comment]
I've just released a new version which should address the IndexOutOfBounds error if it happens again.
