### ISSUE TITLE
Bases & Storage Tab: Base Info dropdown only shows first four bases

### ISSUE THREAD

**Issue by TwoHeadedBoy** [goatfungus/NMSSaveEditor#75]
Seems like the base info only shows the first four bases. I've got six in total, but the first four only ever show up in the dropdown.
![nmssaveeditor_01](https://user-images.githubusercontent.com/887366/43816617-39e09b5c-9a9b-11e8-873e-6541295dca5b.PNG)
![nmssaveeditor_02](https://user-images.githubusercontent.com/887366/43816618-39faae8e-9a9b-11e8-80a9-5e6ce2c6c85e.PNG)

**Comment by goatfungus** [comment]
Chalk this one up to a copy&paste error on my part. Fixed in 1.5.14.

**Comment by TwoHeadedBoy** [comment]
Heck yeah! Thanks!
