### ISSUE TITLE
Feature Request: Special Switch Ship Type (Example attached)

### ISSUE THREAD

**Issue by SirCathal** [goatfungus/NMSSaveEditor#750]
Since the other case is already closed, I'll make a single new one for the Switch ship.

The Switch exclusive spaceship is available on all platforms. It is like the Golden Vector or the Utopia Speeder an own spaceship class which can be included unchangeable by direct reference to a resource file. The seed is ignored and set to 0x1.

As an example I have attached the Switch ship here as an export. It can be easily imported, but so far the class is not recognized and you can not change another ship to the type Switch.
Would be great if you could add that. 

[!v42_GOG__Horizon_Vector_NX_Switch.zip](https://github.com/goatfungus/NMSSaveEditor/files/11182872/v42_GOG__Horizon_Vector_NX_Switch.zip)

**Comment by goatfungus** [comment]
I just want to call this out as an example of a perfect feature request. Not only have you clearly outlined what you want, but have also included a JSON payload which makes it so much easier to understand the requirements. Thanks!

This looks pretty easy, so I'll add it in the next release.

**Comment by SirCathal** [comment]
Thank you very much,

**Comment by goatfungus** [comment]
I have added this ship type in the latest version, 1.12.0.

**Comment by SirCathal** [comment]
Thank you, it works fine for me.
