### ISSUE TITLE
Feature Request: Ability to enter negative values for starship Maneuverability "Base Stat" bonus

### ISSUE THREAD

**Issue by X3n0n3x** [goatfungus/NMSSaveEditor#753]
Currently when entering a negative value for starship Maneuverability in the save editor, it instead defaults to 0.
I know that in normal gameplay you would never encounter a starship with negative maneuverability, however in a mod I've made I use negative Maneuverability values for certain starship classes to widen the gap between highly and poorly maneuverable ships. In practice, negative values here just do a % reduction to the ship's base maneuverability stat, instead of a % improvement when using a positive value.

Currently the game only seems to update the actual Maneuverability stat by reading from INVENTORYTABLE.MBIN when either the ship is increased in class, or a save file from pre-Waypoint is loaded, so adding this ability to the save editor would make things much easier for me testing it (and possibly useful for people wanting to try out ships with very poor stats for fun / challenge runs?)

Either way, thank you so much for making this tool, and I'm very excited the Maneuverability stats were even added to the save editor at all since it's already been a great help.

**Comment by goatfungus** [comment]
This is probably a are use-case as well, but the JSON Editor should still allow you to put in negative values for each stat if you know where too look. Just make sure you apply the stat to ALL inventory containers, including tech and cargo.
![image](https://user-images.githubusercontent.com/41274031/230745627-a95fda91-416f-4536-a47b-b48672a2f4de.png)

**Comment by X3n0n3x** [comment]
Thanks again for the info!
