### ISSUE TITLE
Feature Request: Methods to bulk disable inventory slots

### ISSUE THREAD

**Issue by X3n0n3x** [goatfungus/NMSSaveEditor#754]
As I've made a mod which reduces the inventory size of most entities (exosuit, multi-tools, starships, freighter, base storage containers, etc.) I'm sometimes in the position of updating an older game save of mine to match the new limits of this mod. This means disabling many currently enabled inventory slots (all ships, tools, and the 10 storage containers for each save file), and while it is very easy & convenient to expand inventories by using "Resize Inventory" to the approximate size, selecting "Enable all slots" and then manually disable several slots as needed, doing the reverse is not really possible and needs to be done manually, one slot at a time. 
Additionally, sometimes I accidentally mis-click on "Enable all slots" when trying to enable a single slot, and then have to manually disable all those slots one by one.

Some possible ways to make downsizing inventories easier:

- Allowing the "Resize Inventory" command to automatically disable slots outside of the newly designated bounds, so long as no items/tech are in them. Currently, this command always fails if any Enabled slots are outside the newly designated bounds, even if those slots contain no items/tech.
- Adding a new "Disable all slots" function which works the reverse of the "Enable all slots" function, but leaves any slots currently holding items/tech as enabled.

I realize this is probably not a very common use case, so understand if it's not a priority. Greatly appreciate the work on this tool either way!

**Comment by goatfungus** [comment]
Pretty uncommon use case, but would be a situation where the JSON Editor would come in handy:

To disable all slots, you can go into the Inventory container and set Slots = [] and ValidSlotIndices = [].
![image](https://user-images.githubusercontent.com/41274031/230745484-b7275eb2-142f-4438-847b-af1823d6a934.png)

The resize inventory function is largely redundant now that the game automatically sizes them.

**Comment by X3n0n3x** [comment]
Thank you, I'll take a look at the JSON editor!
