### ISSUE TITLE
MultiTool Names Not Brought Into Editor

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#756]
The editor has a place for the tool name which is blank even though they have names.
I think the editor works for changing the name of the tool but it would be useful to properly identify which tool up front.

**Comment by goatfungus** [comment]
Multitool names are generated by a stored procedure in the game unless you choose to override it. I can't display the generated name in the editor because it is not stored in the save file, only your custom one is.

**Comment by ukmerlin** [comment]
Ah ok thanks, figured it out, will rename them all.....
