### ISSUE TITLE
Supercharge All Slots / One Slot Does Not Supercharge Anything

### ISSUE THREAD

**Issue by SRT-DUKE** [goatfungus/NMSSaveEditor#758]
I edit my save in this order:
Open save
Tab over to Ship
Right Click on a slot
Supercharge All Slots / One Slot
Save Changes 
Load Save

With this only the default 1-2 slots are supercharge from what the game provides.
Am i missing something or is there more to it?  Images are post edit.
![image_2023-04-09_100900993](https://user-images.githubusercontent.com/130296570/230777575-ef802b93-b646-44ec-916f-824052e35ef8.png)
![image_2023-04-09_100924915](https://user-images.githubusercontent.com/130296570/230777597-654b3102-a415-4202-95a3-1ff4892a7cd2.png)

**Comment by SRT-DUKE** [comment]
UPDATE: MultiTool supercharge works perfectly

**Comment by SRT-DUKE** [comment]
UPDATE: Starship supercharge works... intermittently,  I used it on my golden vector which now i think is bugged in some way.  It may be because it's custom since i did not actually earn it?  

I tried on one of my random ships and it added all the extra slots and supercharged it. Weird but hey it works.  I will leave this open in case you have more insight on why this may have happened.

**Comment by goatfungus** [comment]
It is possible that special ship types like Golden Vector have an override in the game itself, and this would not surprise me. Would anyone else be able to confirm this?

**Comment by GrumpyKoala1966** [comment]
All my slots on Gold Vector  (did not earn it) and Sentinel ships slots are all fully supercharged for me..

**Comment by SirCathal** [comment]
All Ship Types (including, the Golden Vector, the Utopia Speeder and the Switch Ship), the Exo Suite and the Multitools  work for me with supercharge all Slots.

The only thing that not work are the Vehicles like Roamer, Nomad etc.  But they are specail like there inventory. They seems to be hardcoded in the Game.

**Comment by ukmerlin** [comment]
I think this could be a timing issue since the game now periodically does its own save, you would need to know which one to reload and which one was edited.
