### ISSUE TITLE
Java memory error

### ISSUE THREAD

**Issue by cjg67** [goatfungus/NMSSaveEditor#759]
Hello,

Thank you for creating this wonderful editor, I have used it a number of times.

With this release however I am not able to use it.  I can open my saves, I can view things with the editor, but it gives the following error:

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "D3D Screen Updater"
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

I have changed nothing on my computer, other than downloading this version of the editor.

**Comment by cjg67** [comment]
Hello,

Sorry about the bug post.

I have just solved it by upgrading java.  I have not had to do that since using the editor.  No idea what may have changed, unless you also updated to a newer java version when you created this update.

**Comment by goatfungus** [comment]
I didn't change anything in the java version I'm using, but there were a lot of changes this time so it could be that. Glad its working for you now though.
