### ISSUE TITLE
changes not appearing in game at all? or just straight up corrupting the save

### ISSUE THREAD

**Issue by roflnomish** [goatfungus/NMSSaveEditor#761]
so this could be because Im using the experimental build atm, but before today the editor was working absolutely fine, but today I've had non stop issues with the editors changes either not showing up in game at all, or just straight up breaking the save so when I try to load the save in game it just gets stuck on a white screen.

**Comment by goatfungus** [comment]
I have resolved quite a few issues since this issue was raised, and I don't really have enough information to identify the real cause. I'm going to close this for now, and if you have more information, such as the save file data and log, feel free to reopen.
