### ISSUE TITLE
Multiplayer is almost gone, if not dead entirely.

### ISSUE THREAD

**Issue by DeoxTew** [goatfungus/NMSSaveEditor#762]
I can't see anyone in the Space Anomaly, and I have been unable to join my friend in his instance. It says Multiplayer is enabled, even showing up the cross-platform play message in the chat box upon loading into my save file.

**Comment by SirCathal** [comment]
Maybe you are playing in a different Game mode? 
I had no Problem to Join my Friends even Cross Plattform (PC GOG and XBox)
This is no issue with the Editor.
