### ISSUE TITLE
Wrong stack size for technology upgrades

### ISSUE THREAD

**Issue by Kolthor** [goatfungus/NMSSaveEditor#763]
Since update 4.0 (Waypoint), procedurally-generated technology modules now stack in the inventory. The stack size is 10 for Personal and Ship inventories, and 20 for Freighter and Chest inventories.

NMSSaveEditor is not aware of the new stack sizes, and insists on creating them with MaxAmount = 1, both when adding the modules to an empty slot, and moving a stack from one inventory to another.
Enabling test mode does not allow changing stack size.

![NMSSaveEditor_MoveStackOfModules](https://user-images.githubusercontent.com/25927780/231466732-1cc96d74-7f6f-48ef-96ca-f307b5e85a71.gif)

**Comment by goatfungus** [comment]
There is likely some kind of multiplier in the game that I haven't taken into account for these items. I'll look into it.

**Comment by goatfungus** [comment]
This should now be fixed in version 1.13.0
