### ISSUE TITLE
Feature Request: Please display the new Save Name in the Dropdown List

### ISSUE THREAD

**Issue by SirCathal** [goatfungus/NMSSaveEditor#764]
Since Version 4 we can give our savegames a Name.

Please add that Name to the dropdownlist when opening a save.
I would make it easier to identify the correct saveslot.

![grafik](https://user-images.githubusercontent.com/69156692/231741771-364fe18c-104e-432a-a3bb-423faa5b2cef.png)

**Comment by goatfungus** [comment]
I'll look into it over the next few weeks after I get back from holiday :)

**Comment by goatfungus** [comment]
I have added the save name and description to the main UI in version 1.13.0

**Comment by SirCathal** [comment]
Works fine for GOG and Steam, but the Windows Store/Xbox Saves are without the Names
