### ISSUE TITLE
I can't check my Archive path

### ISSUE THREAD

**Issue by NAVI-LY** [goatfungus/NMSSaveEditor#766]
When I'm ready to use NMSS, I can't select my save and my choose save pash interface is unresponsive
![O WZJV AWS95Y{V``QOWZ60](https://user-images.githubusercontent.com/125477940/232195819-cb126ba8-c81a-4da8-a186-85877cb31826.png)

**Comment by GrumpyKoala1966** [comment]
Click on Yellow Folder with "st76561199025748631 then press ok

**Comment by goatfungus** [comment]
I have a fix coming out for this soon, i just need more time to test.

**Comment by goatfungus** [comment]
This should be fixed now.
