### ISSUE TITLE
Storage slots larger sized than Cargo and Tech slots

### ISSUE THREAD

**Issue by wkitty42** [goatfungus/NMSSaveEditor#769]
when i open the editor, i generally grab the bottom of the frame and stretch it down so i can see all 120 Cargo slots in my ships and freighter... the width is fine to show all of the slots in each row... however, when i switch to the Base/Storage tab, the boxes for each slot are larger so they spill off the right side and i have to grab the right side of the frame and drag it outward to be able to see all of the slots on each row...

**Comment by wkitty42** [comment]
here's two comparison images so you can better see what i mean about the Storage bins slots being larger... the first image is from my freighter and the second one is where i simply click on the Base/Storage tab...
![NMS-red-inventory-items-Screenshot_20230423_062115](https://user-images.githubusercontent.com/4641713/233834368-46ce3dd5-1682-4ec1-b508-b138196f38da.png)

![NMS-Storage-bins-different-size-Screenshot_20230423_062237](https://user-images.githubusercontent.com/4641713/233834373-0d197a5a-40ad-4021-a394-3c3344428f59.png)

**Comment by goatfungus** [comment]
The editor should remember your last window sizes, so it's up to you to size it how you like initially.

**Comment by wkitty42** [comment]
On 4/23/23 4:42 PM, Brendon Matthews (GoatFungus) wrote:
> The editor should remember your last window sizes, so it's up to you to size it 
> how you like initially.

ummm... i run only the .jar file because i'm a full linux stable... i've never 
been able to have the next execution of the editor start at the size i set it 
to... i do also close the editor via the 'X' in the window frame... is this the 
wrong thing to do?
