### ISSUE TITLE
how to delete/remove slots mistakenly added?

### ISSUE THREAD

**Issue by wkitty42** [goatfungus/NMSSaveEditor#770]
some months back, i inadvertently added another row of slots to the Base Storage units in one of my saves... i didn't realize i now had 6 rows instead of the allowed 5 rows... the game only shows 5 rows and i want to remove the ones i inadvertently added so i don't accidentally use them while in the editor... sadly, i don't find any option in the GUI to easily remove slots...

**Comment by Blockshaker246** [comment]
Use the raw json edit

**Comment by Blockshaker246** [comment]
Use the same thing you used to expand it

**Comment by wkitty42** [comment]
> Use the raw json edit

yeah, i didn't want to have to attempt that... too easy to get lost in there...

**Comment by wkitty42** [comment]
> Use the same thing you used to expand it

well, that's the thing... i don't remember if i just checked the "Enabled" box on each of them or if i also used the "Resize Inventory" option at the top to change the size from 10x5 to 10x6...

in looking at my 12 saved game slots, it seems that all of them have the Storage boxes set to 10x6 with the 6th row being disabled and greyed out... i definitely don't remember changing the Storage in all of my saves... only one of them...

that's probably what confused me to start with when i enabled that 6th row in the save i'm talking about... so i'm still also kind of confused as to whether the Storage boxes are supposed to be sized to "10x5" or to "10x6 with the 6th row simply disabled"...

**Comment by Blockshaker246** [comment]
You must have resized at some point because I used unlock all and they all seem to work for me. However I will say the storage system is massive and I feel like if this is truly an issue in the editor for you. You might find it easier to just free up some space in your storage slots

**Comment by Blockshaker246** [comment]
Also the raw edit is really simple atleast in terms of deleting some slots you just gotta remove the one with the correlating xy cords which would be all cords x0-9 with the y coord of 5.

**Comment by Blockshaker246** [comment]
Anyways since I'm here and can't get in contact with anyone who uses the editor. I have a question are you able to edit your multitools or do all the changes just revert to normal for you aswell.

**Comment by Blockshaker246** [comment]
Another thing for tech slots atleast I believe anything you put in let's call them "extra" slots still effect said technology you just can interact with those extra slots in game

**Comment by wkitty42** [comment]
On 4/21/23 2:33 PM, Blockshaker246 wrote:
> You must have resized at some point because I used unlock all and they all seem 
> to work for me. However I will say the storage system is massive and I feel like 
> if this is truly an issue in the editor for you. You might find it easier to 
> just free up some space in your storage slots

no, i didn't resize because all of my Storage bins show 10x6... even my new 
Utopia save and i know i have not resized in it at all...

i do, also, have plenty of free slots in that save's Storage bins... it was just 
one save (my #5 i think) where i goofed and enabled the dark grey ones that i 
should not have enabled...

on the multitool thing, i have not done anything with the save editor in them... 
there's very few things that i use the editor for so a lot of stuff i'm 
unfamiliar with... sorry...
