### ISSUE TITLE
Help with multitool

### ISSUE THREAD

**Issue by Blockshaker246** [goatfungus/NMSSaveEditor#772]
@Thygoo could you export your multitool and send it to me or help me figure out why no changes I make using the editor stay when I save(this is only with multitool)

**Comment by Blockshaker246** [comment]
Or if anyone can tell me why I can't get multitool edits to stay

**Comment by Thygoo** [comment]
I haven't played in a few months so I haven't updated my save file but I will once I have free time sometime this week. Sorry for the late response.

**Comment by Thanjar** [comment]
I can add to this, seems to be related to deleting a multitool, deleted 2 and when I returned to my save the two others that I had where completely wiped, but didn't when I only moved some upgrades and still had all 4 multitools, I have not tested tampering with the stat values, but I don't think that is a reason of this issues.

**Comment by goatfungus** [comment]
This should finally be resolved in version 1.13.3, but old corrupted saves may still have errors. My best advice is to restore from backup if that's the case.
