### ISSUE TITLE
1.13.0 invalid token

### ISSUE THREAD

**Issue by Ron691969** [goatfungus/NMSSaveEditor#775]
1.12.0 worked great earlier today. Updated to 1.13.0 and I get Error parsing JSON: Invalid token.

Thanks for all you do :)

**Comment by goatfungus** [comment]
Can you send me a copy of the save file that causes the error?

**Comment by Ron691969** [comment]
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/11302856/NMSSaveEditor.log)

**Comment by Ron691969** [comment]
sent

**Comment by goatfungus** [comment]
Where did you send it?

**Comment by Ron691969** [comment]
replied to the email

**Comment by goatfungus** [comment]
Please send to goatfungus@gmail.com

**Comment by Ron691969** [comment]
sent

**Comment by russ81072** [comment]
I have the same error code coming up on my permadeath and survival saves

**Comment by Tantalau** [comment]
I also have the same problem after downloading latest update

**Comment by Ron691969** [comment]
1.13.1 seems to fix it!
Thanks tons!

**Comment by Tantalau** [comment]
1.13.1 does fix the problem but now i can't remove a supercharged slot.I can only add superchaged slot but can't seem to remove it.
