### ISSUE TITLE
Not saving edits correctly

### ISSUE THREAD

**Issue by GixCC** [goatfungus/NMSSaveEditor#777]
I switched s class upgrade modules to x-grade and edited the Item seeds on photon cannon. Saved. Opened game and ship then had both the s grade modules and the x grade modules installed, and overloaded.  Repeated the edits, and same outcome.

**Comment by goatfungus** [comment]
This should be fixed in version 1.13.2, please try again and if the problem persists I'll need more information (logs, etc)
