### ISSUE TITLE
Supercharged slots 'locked'.

### ISSUE THREAD

**Issue by AlucardTheRed9** [goatfungus/NMSSaveEditor#778]
The technology slots can be set to supercharged versions, but cannot be set back to default. 

Slightly problematic, as I am trying to test out how adjacency and supercharged bonuses work together (seems like some sort of cap?).

**Comment by ascornpire** [comment]
Same issue

**Comment by goatfungus** [comment]
This should be fixed in version 1.13.2, please try again.
