### ISSUE TITLE
Targeted access to json tree [feature suggestion] 

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#78]
Hi, how about a feature to help find things in that _huge_ save file?
If I'm at 'Ships' tab, looking at the tech inventory of ship[2], I'd want to see the json window opening at _that_ folder in that long list.
Possibly, add it as a second menu option under 'Edit raw json'.

**Comment by goatfungus** [comment]
I think I get what you mean... unfortunately, some of the data is actually spread across multiple parts in the save file. For example: ships use "ShipOwnership", "CurrentShip", and "ShipUsesOldColours" sections. If you can only edit one of these sections, people will be missing other relevant parts and question why the JSON editor "doesn't work".

I think using the JSON editor should remain an advanced user function. It doesn't need to be easy to use it just has to be functional, and with the tree navigation and search function it's about as good as we can get.
