### ISSUE TITLE
named Storage bins

### ISSUE THREAD

**Issue by wkitty42** [goatfungus/NMSSaveEditor#780]
in-game we can give our Storage bins a custom name... can you please add the custom name to the bin's in the lists where the are shown like has now been done with the save slots and their custom names? this would go a long way to helping us keep up with which storage bin we are working with... i'm forever moving things to the wrong Storage bin because i forget which number is the proper one i want...

**Comment by goatfungus** [comment]
Good idea. I'll add this in the next update.

**Comment by goatfungus** [comment]
This should now be present in version 1.13.3. There is currently no option to change the name yet, but maybe I'll add that in future.
