### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by x2De** [goatfungus/NMSSaveEditor#782]
When pressing Edit Raw JSON se crashes and has to be closed from Task manager

**Comment by x2De** [comment]
[INFO] Starting JSON Editor...
[DEBUG] Path not found: JSONEditor.X
[DEBUG] Path not found: JSONEditor.Y
[DEBUG] Path not found: JSONEditor.Width
[DEBUG] Path not found: JSONEditor.Height
[DEBUG] Path not found: JSONEditor.Divider

**Comment by astralscarf** [comment]
When attempting to import/export ship files se freezes and has to be closed from Task  Manager. Issue not present yesterday, just started today.

**Comment by goatfungus** [comment]
This might be related to the issue i fixed in version 1.13.2, please try again.

**Comment by x2De** [comment]
> it hasn't unfortunately :(

**Comment by astralscarf** [comment]
It seems to be fixed on my end. 

> EDIT: se freezes when exporting ship with any amount of tech slots filled. export/import works fine when tech slots are blank. Notice power usage for SE in Task Manager goes from very low to very high when this happens.
> 
> When attempting to import/export ship files se freezes and has to be closed from Task Manager. Issue not present yesterday, just started today.

Seems to be fixed now, at least for me, thank you! I can export and import ship and multitool templates without it freezing.

**Comment by x2De** [comment]
> It seems to be fixed on my end.
> 
> > EDIT: se freezes when exporting ship with any amount of tech slots filled. export/import works fine when tech slots are blank. Notice power usage for SE in Task Manager goes from very low to very high when this happens.
> > When attempting to import/export ship files se freezes and has to be closed from Task Manager. Issue not present yesterday, just started today.
> 
> Seems to be fixed now, at least for me, thank you! I can export and import ship and multitool templates without it freezing.

after you just posted that it works for you i re tested the JSON edit  and it now works too

**Comment by goatfungus** [comment]
Ok, i'll close this one. If there are any more issues, reopen this ticket.
