### ISSUE TITLE
Can't Import

### ISSUE THREAD

**Issue by astralscarf** [goatfungus/NMSSaveEditor#785]
Can't import edited json file. Warning "an error occurred importing the save data." This happens even if I'm trying to import an unedited save file I exported just to experiment with.

**Comment by goatfungus** [comment]
Weird. Was the file exported before 1.13.0 version?
Can you send me the JSON file so I can have a look?

**Comment by astralscarf** [comment]
> Weird. Was the file exported before 1.13.0 version? Can you send me the JSON file so I can have a look?

No, it was me messing around trying to export, edit, and import back in the same save file from today. It was during the same time I was having issues (separate post) exporting ship templates but it seems fine now (?). I probably was entering it wrong into the file. Eventually I found it easier to use a .fb3 file. Regardless, I haven't had the error pop back up since this morning.

**Comment by goatfungus** [comment]
It is possible the last update fixed it, but if you encounter this issue again please reopen this ticket.
