### ISSUE TITLE
Messing with the multitools causes all of them to be deleted

### ISSUE THREAD

**Issue by LiothGold** [goatfungus/NMSSaveEditor#788]
Like the title says, messing with the multitools deletes all of them and you're left with a multitool called 'Silly Weapon' that has no slots, fires once per click, and does no damage at all.

**Comment by goatfungus** [comment]
What exactly did you do?
I need to be able to reproduce the issue on my own save and have never had this issue.

**Comment by LiothGold** [comment]
> What exactly did you do? I need to be able to reproduce the issue on my own save and have never had this issue.

Straight up deleted the Multitools I didn't want. I placed a specific upgrade 'in' the two Multitools I wanted to keep, and deleted the ones that didn't have that, which was the  Waveform Recycler.

**Comment by goatfungus** [comment]
Ah, i think i have figured it out... finally!
I should have a fix for this in the next version.

For now, try doing the following:

1. export the multitools you want to keep using the "Export" function
2. delete all but the last multitool using the editor (you must always have one)
3. import the multitools using the "Import" function
4. delete the last multitool

This will put all your multitools in the correct order without having any blanks in between.

**Comment by goatfungus** [comment]
This should now be fixed in version 1.13.4.
