### ISSUE TITLE
NOT an Issue:  JSON File?

### ISSUE THREAD

**Issue by GalanVaurek71** [goatfungus/NMSSaveEditor#79]
Just curious if there are any tutorials or links that may explain a bit on how to edit the JSON file w/o messing it up?

Trying (hoping) to figure out how to edit the starting planet stats...  Would that even be possible?

**Comment by goatfungus** [comment]
Not possible to edit start planet stats, as you are randomly plonked down at a different planet with every new game. Planets themselves can't be changed, but you can start on a different planet.

The JSON editor will detect syntax errors, but you can still screw it up by deleting the wrong thing, or putting in an invalid value somewhere. Unfortunately none of the save file format is documented anywhere, and I doubt it ever will be, especially considering it changes with every major release.
