### ISSUE TITLE
loading save issue no tabs open

### ISSUE THREAD

**Issue by Ghostinthewind** [goatfungus/NMSSaveEditor#795]
![Screenshot 2023-04-24 164355](https://user-images.githubusercontent.com/131693612/234048161-4233043e-c39f-46b6-ba46-e21a583115b4.png)

loads only exosuit, multitools are empty, cannot select any other tab ( starship, frieghter etc ) this is a PS4 save was working fine in the 1.12 version

**Comment by goatfungus** [comment]
This should now be fixed in version 1.13.4.
