### ISSUE TITLE
JSON editing 

### ISSUE THREAD

**Issue by spideruk07** [goatfungus/NMSSaveEditor#796]
Hi the JSON editing is not working, I load the save go to edit JSON and it just sits there doing nothing, please help

**Comment by Devilin-Pixy** [comment]
Might be same/similar issue as in issue #797. See there for more details and testing done.

For now, until the issue has been fixed, I suggest to load the save in-game, then visit a less populated system when it comes to the amount of bases. Save there and then try to use the raw JSON editor again.

**Comment by goatfungus** [comment]
See #797
