### ISSUE TITLE
Can't read ps4 save wizard files - FIXED

### ISSUE THREAD

**Issue by batman2077** [goatfungus/NMSSaveEditor#799]
before it was only allowing me to edit exosuit but when I downloaded new version it just gave me the error. Using save wizard on ps4

**Comment by goatfungus** [comment]
Need more information.

Please provide the log produced by the application and a copy of your save file so I can check.

**Comment by batman2077** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/131725543/234163208-71057932-6bb1-4978-bf4f-77acdc9e88e4.png)

**Comment by batman2077** [comment]
[savedata03.zip](https://github.com/goatfungus/NMSSaveEditor/files/11316097/savedata03.zip)

**Comment by batman2077** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/131725543/234164981-fd22d062-92c0-4a77-8c13-46119f158014.png)

**Comment by goatfungus** [comment]
The game itself uses a special algorithm to convert the real names of things to 3-character keys which it uses in all the save files. For example: the first name in the file is "Version" which gets written out as "F2P".

Your save file appears to have a mixture of mapped names and unmapped names, and at least one of these mappings is incorrect according to the algorithm ("MultiTools" should be "Multitools"). This makes me think that Save Wizard is trying to map the names itself, and it's mapping list is horribly out of date.

Is there any way to get Save Wizard to export the file WITHOUT applying it's own mappings to the output?

**Comment by goatfungus** [comment]
Ok, well I made some progress myself. I have changed the name mapping system in the editor to be able to process partially mapped files, like the one you sent me. In this case when it writes the save file, it will write it out in the same partial format that it started with. It's pretty messy, so use with caution.

**Comment by batman2077** [comment]
thanks it's working good now I can see all the tabs also.
