### ISSUE TITLE
Issue - out of bounds? unable to open save file

### ISSUE THREAD

**Issue by ghost** [goatfungus/NMSSaveEditor#8]
I get an issue, where I cannot open a savegame from NEXT, but I can open an old save from before NEXT. When trying to open the NEXT savegame, an error occurs:

`[INFO] Latest version: "1.5.2"
[INFO] Current version: "1.5.2"
[INFO] Loading slots: (hidden)
[INFO] Loading saves for save 1...
[INFO] Reading save file...
[INFO]   Path:(hidden)
[INFO]   Slot: Slot 1 - NORMAL
[INFO]   Filename: save2.hg
[INFO] Parsing JSON...
[INFO] Finished.
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: setSelectedIndex: 1 out of bounds
[INFO] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[INFO] 	at nomanssave.cl.a(Unknown Source)
[INFO] 	at nomanssave.Application.i(Unknown Source)
[INFO] 	at nomanssave.Application.g(Unknown Source)
[INFO] 	at nomanssave.Application.p(Unknown Source)
[INFO] 	at nomanssave.K.run(Unknown Source)
[INFO] 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[INFO] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[INFO] 	at java.awt.EventQueue.access$500(Unknown Source)
[INFO] 	at java.awt.EventQueue$3.run(Unknown Source)
[INFO] 	at java.awt.EventQueue$3.run(Unknown Source)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[INFO] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[INFO] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[INFO] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[INFO] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[INFO] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[INFO] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[INFO] 	at java.awt.EventDispatchThread.run(Unknown Source)
`

Opening the older savegame works fine, however. I used the atlas rising savegame editor before, and it worked just fine... until I downloaded the new version of the save editor and opened it, then it stopped working.

**Comment by HaPet74** [comment]
Update: at this point, I doubt something is wrong with the savegame editor... since I created a new game, and apparently the savegames are 1m characters in size difference. I'll update as I find out more.

**Comment by HaPet74** [comment]
Update: I have managed to replicate the error. Currently isolating it. (Using raw editor)

**Comment by HaPet74** [comment]
**Update: Error occurs when setting primary ship to 1, apparently.**

**Comment by HaPet74** [comment]
Update: Problem solved by buying a new ship.

**Comment by goatfungus** [comment]
So the game is setting the primary ship to 1 when there is only one ship? Well that's a pain in the butt. I'll see if I can mitigate this issue for other users in the next update.
