### ISSUE TITLE
wrong data with archived techs

### ISSUE THREAD

**Issue by SplinterGU** [goatfungus/NMSSaveEditor#801]
![image](https://user-images.githubusercontent.com/95715426/234448704-ae06abbd-bb2c-4a5b-84f9-88aacc66c8bd.png)
![image](https://user-images.githubusercontent.com/95715426/234449490-04d18f6b-8d14-402f-817c-ae9957caab59.png)

**Comment by SplinterGU** [comment]
![image](https://user-images.githubusercontent.com/95715426/234449672-80fc4bc8-fffb-4c15-9a60-650803c282d5.png)

**Comment by goatfungus** [comment]
This is part of the reason why I had to overhaul the JSON read/write functionality in the editor. The game itself produces these weird codes and I'm still not sure what to make of them, but at least now the editor doesn't corrupt the data on save.

I have deliberately left them as-is and uneditable in the UI, and if/when I finally figure out what each and every code means I'll make the editor display appropriate information. For now though, we'll just have to live with the fact that the editor can't display these items as we would like it to.

**Comment by SplinterGU** [comment]
thanks! I'll check later, maybe I can figure out what this code means... I think, I have some idea... thanks!

**Comment by SplinterGU** [comment]
well, I already check this... this "weird codes" (6 bytes) are tech code for archived tech... this are same for each tech, for example, all "illegal hazard protection for exosuit" are "\x80\x83GH\r\xB7" and then this code add a # and the id... for example "\x80\x83GH\r\xB7#12306"

for Analisis Visor, the code is "\x80\x80S\x98\n0010\xD1", as this tech don't have id, then id is 00000 (5 zeros), for example "\x80\x80S\x98\n0010\xD1#00000"

maybe you need add a new jsonmap???.txt for those codes

(sorry for my bad english)

**Comment by goatfungus** [comment]
> maybe you need add a new jsonmap???.txt for those codes

I have been trying to generate these from the game files so that if anything is added I'll automatically pick up any new ones... but so far no success. As a last resort I will end up creating a special mapping file for them as you've suggested.

**Comment by goatfungus** [comment]
I have just released a new version which should add most of the techbox items (Update 1.13.9). I had to resort to generating my own list, so hopefully I've got everything covered.
