### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by Destroyher** [goatfungus/NMSSaveEditor#804]
I would really like to request dark mode in this app. I have vision impairments and have a really hard time reading anything over a white background. I use this app daily for my content creation. I dont know if its possiible or difficult to add but I hope that you will consider it. 

Thankyou all,
Destroyher nms : Random youtuber.

PS. Love all the work you have done on this project. Question" Ive been searching for the ID's for the new Currupt Spider. Id like to make it a pet as I found how to do with the Walker.

**Comment by BeardedBushman** [comment]
I support this request, "Dark Mode" is prefeered option for me too.

**Comment by goatfungus** [comment]
I'm working on this, and should have an update later in the week.

**Comment by Destroyher** [comment]
Thankyou

**Comment by goatfungus** [comment]
Dark mode should now be available in version 1.14.0... go to View->Settings and you should be able to change the Look & Feel.

**Comment by BeardedBushman** [comment]
Thankx a lot goatfungus !
