### ISSUE TITLE
Question: Does Exporting a ship export the ENTIRE ship?

### ISSUE THREAD

**Issue by Darena-Bryant** [goatfungus/NMSSaveEditor#812]
...Or does it just export the equipment on board? I have an 'ideal' setup I want to just be able to drop into all my ships. Is that what would happen if I tried to import one I'd saved, or would it just overwrite the ship type and appearance as well?

**Comment by goatfungus** [comment]
Currently the export function for ships includes the following:
- Appearance, Type, etc
- Technology items

There is a further export option which also allows you to export normal cargo inventory as well.

If you import any ship it will ADD the ship to your list, so nothing gets overwritten.
