### ISSUE TITLE
Last item no longer stays populated when adding item

### ISSUE THREAD

**Issue by ascornpire** [goatfungus/NMSSaveEditor#813]
Previously, when adding an item to inventory the last item added would stay populated for fast inventory adding. Currently, after adding an item, the 'add item' menus is completely empty except for the 'Type'.

**Comment by GrumpyKoala1966** [comment]
Working fine for me..

**Comment by ascornpire** [comment]
Version 1.13.9?

**Comment by GrumpyKoala1966** [comment]
Yes using Version 1.13.9 The only issue I've noticed is I can't replicate stack size eg: Starship AI Valves only allows 100 before it was 10,000 but the info remains.

**Comment by ascornpire** [comment]
Interesting. Either way, it seems the issue topic'd remains for me. I guess I can try to post video, not sure what other specs would be useful to diagnose. Maybe later I'll try to restart my PC.

**Comment by ascornpire** [comment]
Solution: The auto populate only occurs when the search function is used. If you just use the drop downs, the item does not stay populated on next add.
