### ISSUE TITLE
Add/Change Item

### ISSUE THREAD

**Issue by parian02** [goatfungus/NMSSaveEditor#817]
Trying to change an item produced by a settlement to something more useful.  But Search box for new item appears duplicated? and overlapping another copy of itself.  And search seems to fail at all times. Tested trying to add a regular inventory item and the same happens.

**Comment by GrumpyKoala1966** [comment]
Just tried it at my end and seems to be working fine.

**Comment by parian02** [comment]
Here's a partial screenshot.  The Add Item box comes up nicely, but as soon as I move the mouse, it gets messy.  In fact,
continuing to move the mouse around causes all kinds of distortions with items on the main window.  
![search](https://user-images.githubusercontent.com/101817747/236590360-d43a84e5-59fb-4748-a5c9-d8be49dae64d.jpg)

**Comment by parian02** [comment]
In fact,. just noticed that I don't have to do anything with the mouse.  Once the Add Item windows pops up, it'll change all by itself in about 2 seconds...

**Comment by GrumpyKoala1966** [comment]
H'mmm like I said I'm not having that issue, not sure what could cause that, I'm also running Windows 11.. Hope you find out what the issue is..

**Comment by parian02** [comment]
Well, I've tested everything I can think off.  Cleaned mouse, rebooted, reinstalled Java - nothing fixes this problem.  It's been fun using the editor for certain things, but sadly doesn't work for me anymore.  So closing this out unresolved.
