### ISSUE TITLE
crash after use

### ISSUE THREAD

**Issue by H4K3R5** [goatfungus/NMSSaveEditor#82]
i've used the save editor with NMS for a while with no issues but i noticed the other day after i tried to copy my frights, to make myself a larger ingame fleet the game when i run it will be stuck on the logo screen and will crash when i click the mouse. i've tried reloading my game, uninstalling and reinstalling and loading a backup from the editor with no luck..      does anyone know how i can fix this issue?

**Comment by goatfungus** [comment]
I think that's a general issue with larger fleet size, nothing to do with the editor. I get the same problem on a save where I have not used the editor at all. On this save I bought all the frigates normally up to max, and built 5 command centers so i could do all 5 missions at once. Occasionally when selecting a frigate i get a complete game freeze, and have to kill the game completely.

Hopefully HG fixes this issue soon.

**Comment by H4K3R5** [comment]
my problem is that the game will not work
it starts up and crashes
