### ISSUE TITLE
macOS dark, json editor, found text color highlight is too bright

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#821]
With the new dark mode (which is great), the macOS dark - json editor - found text color highlight is much too light for a dark mode.
![found_text](https://github.com/goatfungus/NMSSaveEditor/assets/41163747/8906599b-4f6d-4e40-a0b7-2af147e5a778)

**Comment by goatfungus** [comment]
The new dark modes are not perfect, and there are still some styles that need to be updated, but thanks for reporting this.

**Comment by goatfungus** [comment]
This should be improved now.
