### ISSUE TITLE
Editor won't load save

### ISSUE THREAD

**Issue by kamronshepard** [goatfungus/NMSSaveEditor#823]
I have tried the following two directories:

C:\Users\username\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\00090000046E8E5F_29070100B936489ABCE8B9AF3980429C\834DCE4F1403452B8CD20AFF5DD00360

and

C:\Users\Kamron\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\00090000046E8E5F_29070100B936489ABCE8B9AF3980429C\83E48E953FD647548226747A96E2098F

using both the bat and jar files. Neither shows anything under Game Slot or Save File.

[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/11523716/NMSSaveEditor.log)

**Comment by MGJerry** [comment]
Hmm, that's weird. From the log, I can see that no save were detected, and you are indeed on the latest version of the editor.

Can you tell me which platform you are using?
