### ISSUE TITLE
QOL Feature Request: display game-generated names for items without manually given names

### ISSUE THREAD

**Issue by wkitty42** [goatfungus/NMSSaveEditor#826]
ok, so like Frigates... if they are not manually given a name, the editor shows their name as "type [index]"... eg: Mining [0], Normandy [1], Combat [3], etc... funnily enough, The Leviathan doesn't get an "[index]" added to its game-generated name...

anyway, the problem comes when doing things like maintaining a spreadsheet of their stats... this because the game sorts the Frigates as they rank up and writes this sorted order to the save file... then the editor displays the Frigates in this sorted index order... if the editor would display the game-generated name of the item, we could more easily see which ship is which without having to manually name them even if the manual name is exactly the same as the game-generated name...

i'm mainly asking for this with the Frigates but it would also work nicely for our star ships, multitools, and exocraft... additionally, it would be nice to see the game-generated name for the Freighter instead of just an empty field...

ASIDE: yes, i know we cannot give the Normandy another name in-game so maybe it doesn't need the "[index]" addition?
also, IIRC, we can rename The Leviathan which i seem to have done in a few saves to add "traits symbols" to their name (eg: "The Leviathan-ETC" for Explore as 1st/main Trait, Trade as 2nd, and Combat as 3rd from the list of Traits the Frigate has)... i did this because you can change Living Frigate's Traits by feeding them different things and trying to remember which is which when sending them out on expedition missions is just ugh...

**Comment by wkitty42** [comment]
an image would probably help explain more...

![NMS-Frigates-list-Screenshot_20230527_082531-1](https://github.com/goatfungus/NMSSaveEditor/assets/4641713/839c4b66-450d-4634-8507-e46e18d62df6)

**Comment by goatfungus** [comment]
If you click on "The Leviathan" and look at the Name field on the right you'll see a clue.

If the name field is blank the game itself will use procedural generation to create the display name of the ship. This is something that is not possible in the editor since the procedural algorithms are a closely kept secret by Hello Games. I am not going to even attempt to decipher any of the procedural generation algorithms in NMS just to improve QOL in the editor as that would be literally thousands of hours of work.

**Comment by wkitty42** [comment]
oh, ok... i thought the generated ships' names would be stored in the save file with the ships' other data... i didn't realize that the game would have to calculate the names each time we load the save... it was an idea, though... thanks!
