### ISSUE TITLE
Name mapping not found since  a few days

### ISSUE THREAD

**Issue by ubronan** [goatfungus/NMSSaveEditor#829]
I suddenly got since two or three days  name mapping errors, I forgot to write the previous errors down but here the latest 
Apparently the list gets longer and longer
The makers of the program do not understand that after playing hundreds of times people get fed up by the endless grinding for nothing.
I spend hundreds of hours and i admit i got fed up with the nasty grinding for days.
Anyway these are the today popping up WARNINGS ;)

XEk
G0<
Qwu
HtR
O;Y
=Wk

**Comment by SplinterGU** [comment]
confirm! I'll add 2 more...

  WARNING: name mapping not found: SQw                                      <<< this one
  WARNING: name mapping not found: Naj                                        <<< this one
  WARNING: name mapping not found: XEk
  WARNING: name mapping not found: G0<
  WARNING: name mapping not found: Qwu
  WARNING: name mapping not found: HtR
  WARNING: name mapping not found: O;Y
  WARNING: name mapping not found: =Wk

**Comment by SplinterGU** [comment]
SQw = WhaleEvent
Naj = OverriddenReward
XEk = SeasonStartMusicOverride
G0< = CommunityProgressTitle
Qwu = ShipIsAtDifferentBuildingToPlayer
HtR = BuildingRadiusShipOffsetMultiplier
O;Y = PageIdx
=Wk = LastSeenEntryIdx

(references from MBINCompiler)

**Comment by goatfungus** [comment]
Thanks for your help @SplinterGU. I'll add these in the next update.
