### ISSUE TITLE
Expand Inventory issues

### ISSUE THREAD

**Issue by GalaxyYoyo77** [goatfungus/NMSSaveEditor#83]
When I try to expand my inventory the program just ignore me and do nothing, and if I try to change the numbers the width and height slot the program just change again as default.

**Comment by goatfungus** [comment]
What are you trying to expand it to, and which inventory in particular?

**Comment by GalaxyYoyo77** [comment]
Any inventory, can be the personal inventory, technology inventory, weapon inventory, it does not let me expand any inventory.

**Comment by NekoEnzeru** [comment]
I am having this same issue when trying to expand to 6x8.  No change to the inventory size in the editor window.  I loaded the game after changing it in the editor and no change there either.  There's no indication in NMSSaveEditor.log that any attempt to expand inventory size.
Also failed to expand freighter inventory.

**Comment by goatfungus** [comment]
Ah, maybe it's not indicating that the file has changed and therefore not saving it.
Solution for now: Go back to main tab and click "Save Changes".

I'll look at a fix for next release.

**Comment by goatfungus** [comment]
I'm going to assume that you got this working and close the issue. If not, please feel free to reopen with some screenshots.
