### ISSUE TITLE
Suggestion All items category on Add Item

### ISSUE THREAD

**Issue by diegobh** [goatfungus/NMSSaveEditor#84]
HI!!!

I've just one think to suggest for this fantastic tool.
Could you add only one category that list ALL Products on the same combobox, please?
The fight starts first to find out what type is and after which  Category.

Thank you!

**Comment by travisnewman** [comment]
Seconded. I love the categories but some items I'm not sure where to check.

**Comment by ukmerlin** [comment]
Yes indeed this would be much easier also if it could auto fill as you type.

**Comment by goatfungus** [comment]
I have added a search field to the dialog in 1.5.17.
