### ISSUE TITLE
Feature Request: export ships - export cargo as well

### ISSUE THREAD

**Issue by rkaerner** [goatfungus/NMSSaveEditor#848]
The export ship function is great but - from my point of view - it would be perfect exporting the cargo in a ship as well so I can use the save editor to get items transported from one save to another. Yes, I know the I could get every item in every quantity but I don't want to cheat like hell.

**Comment by MGJerry** [comment]
This is in fact an already-implemented feature (there's literally a check box when you press "Export")
![image](https://github.com/goatfungus/NMSSaveEditor/assets/85227828/2ab4dd3f-c32a-4a3f-a8eb-cb6c05076b0d)


Also, this was answered 2 months ago in #812 . I really suggest looking for a similar issue/suggestion before making a new one.

**Comment by rkaerner** [comment]
seems that I need an optometrist.... thank you for helping me out with this.
