### ISSUE TITLE
How does the game track time played?

### ISSUE THREAD

**Issue by Elivai** [goatfungus/NMSSaveEditor#85]
Certain events are set to trigger after x amount of time playing the game, and won't repeat until you play for that long. Is time played attached to the save file by any chance? Any way to let us change that? Perhaps as part of the save editor? ;)

**Comment by goatfungus** [comment]
Some events and missions are tied to your system time, and others an internal game timer. Since this would be all wrapped up in mission progress #36 , I'm doing to close this as a duplicate.

**Comment by nmsain03** [comment]
i still dont know how to trigger the event please help
