### ISSUE TITLE
Missing Singularity Helmet

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#857]
In light of no NMSSaveEditor for Singularity update, can someone provide the necessary Singularity Helmet particulars for the two new robotic ones, as this dummy only got one and didn't realize after finishing the expedition that I should gone back to an earlier save....

I'm thinking it in the settings file "GCUSERSETTINGSDATA.MXML" `<Property` name="SeenProducts" value="S10_???" />"`

**Comment by Mike-Blackwell** [comment]
Whilst I'm on the Helmut kick, what's needed for the Xbox "X" Helmut?

**Comment by MGJerry** [comment]
> Whilst I'm on the Helmut kick, what's needed for the Xbox "X" Helmet?
Literally without [this wiki page](https://nomanssky.fandom.com/wiki/Xbox_Booster_Pack#Additional_information) mentioning if this was possible, I would probably said no, but you actually can. It's in the Discovery tab and you probably need to claim it at the QuickSilver Shop to get it (don't know if it require MS/Xbox Game Pass version to claim, I'm currently too busy with finals to test it)
![image](https://github.com/goatfungus/NMSSaveEditor/assets/85227828/49ef57e2-0481-4b6f-98e2-9bfe1d2e92d7)

The best answer I can give for the first question is look around for the item id of that helmet on reddit or the NMS discord server (like I said, too busy so I didn't even play the expedition, so I can't even give you an id if I want to). Even better, if you can get the save of someone's who has it, you probably can find it in the raw json.

**Comment by goatfungus** [comment]
Sorry for the delay, the latest update should also contain the Singularity changes now too.
