### ISSUE TITLE
And now for something completely different!

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#858]
Brendon (@goatfungus), is it somehow possible to allow a user within each gamesave to have all building parts available e.g. freighter parts whilst on planets or is this only a MOD thing?

**Comment by Devilin-Pixy** [comment]
Having building parts available where you'd normally not have access to those, indeed requires a mod. You can however edit parts into your save data for the base you are creating, but I would not recommend doing so without knowing how. It would also be quite a lot of work, where proper tools/mods make this a whole lot easier.

**Comment by Mike-Blackwell** [comment]
@Devilin-Pixy thanxs for the comeback, I kind of suspected that. I noticed that some mods had freighter parts available in game play and others didn't, not sure why but I was able to confirm it e.g. gBase vs Beyond Base build.

**Comment by Devilin-Pixy** [comment]
@Mike-Blackwell Oh yes, there are several build mods, each with their own implementation and ways of doing things. A good thing to pay attention to, is likely the use of custom parts, or vanilla parts only.

Note: I have actually seen some players create a 'default' base with all the unavailable parts/objects, to copy the JSON around to new bases they start. As you can then 'copy/move' parts and possibly no longer require the use of a mod, if you'd prefer to go that route.
