### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by NMS-D** [goatfungus/NMSSaveEditor#860]
Nothing happens at startup, but it looks like in the screenshot. I don't understand what to do. The buttons don't work.
![000](https://github.com/goatfungus/NMSSaveEditor/assets/138398683/3bdcfc76-d462-45ed-b477-0a392670bb4a)

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_371
[DEBUG] Java Architecture: x86
[DEBUG] Operating System: Windows 11
[DEBUG] Working Dir: C:\Users\...\000
[DEBUG] Look and Feel: FlatLaf Light
[INFO] Starting Editor...
[DEBUG] Mem Usage: 16/260 MB
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
[STDERR] 	at java.util.ComparableTimSort.mergeHi(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.mergeAt(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.mergeCollapse(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.sort(Unknown Source)
[STDERR] 	at java.util.Arrays.sort(Unknown Source)
[STDERR] 	at sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
[STDERR] 	at sun.awt.shell.ShellFolder.get(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.addItem(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.access$800(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI.doDirectoryChanged(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI.access$1100(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI$5.propertyChange(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.fire(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
[STDERR] 	at java.awt.Component.firePropertyChange(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.setCurrentDirectory(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.<init>(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.<init>(Unknown Source)
[STDERR] 	at nomanssave.ej.<init>(Unknown Source)
[STDERR] 	at nomanssave.ej.b(Unknown Source)
[STDERR] 	at nomanssave.Application.k(Unknown Source)
[STDERR] 	at nomanssave.Application.p(Unknown Source)
[STDERR] 	at nomanssave.v.run(Unknown Source)
[STDERR] 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)
[DEBUG] Latest version: "1.14.2"
[DEBUG] Current version: "1.14.2"

**Comment by GrumpyKoala1966** [comment]
Been working fine for months, try selecting a path you might get somewhere..  Facepalm.

**Comment by NMS-D** [comment]
I sent a screenshot. nothing works in the program at all. there are no
buttons to select the path.

пн, 3 июл. 2023 г., 08:53 GrumpyKoala1966 ***@***.***>:

**Comment by Devilin-Pixy** [comment]
Make sure you get the 64-bit version, because you have the 32-bit (x86).
You can get 64-bit from here: https://www.java.com/en/download/manual.jsp
Install it and try again. Once it is running, as shown in the screenshot, make sure you browse to the correct location for your save files, which should then show for the 'Save Path' and then also have the drop-down working to select a save slot.

**Comment by NMS-D** [comment]
точно 64 бита. Работает версия 1.11.2, правда торговые суда генерируются не корректно. Версия 1.14.2 работает как на скриншоте, то есть не как. Не понимаю что значит "правильно указали", я не могу указать. Ctrl+O не работает.

**Comment by NMS-D** [comment]
> Убедитесь, что у вас 64-битная версия, потому что у вас 32-битная (x86). Вы можете получить 64-битную версию отсюда: https://www.java.com/en/download/manual.jsp Установите ее и повторите попытку. Как только он запустится, как показано на снимке экрана, убедитесь, что вы указали правильное место для файлов сохранения, которое затем должно отображаться для «Пути сохранения», а затем также иметь раскрывающийся список для выбора игрового слота.

ровно 64 бита. Версия 1.11.2 работает, но торговые корабли генерируются некорректно. Версия 1.14.2 работает как на скриншоте, то есть не так. Я не понимаю, что значит "правильно указано", не могу уточнить. Ctrl+O не работает.

точно 64 бита. Работает версия 1.11.2, правда торговые суда генерируются Серьезно. Версия 1.14.2 работает как на скриншоте, то есть не как. Не понимаю, что означает "правильно назначенные", я не могу указать. Ctrl+O не работает.

**Comment by NMS-D** [comment]
> Убедитесь, что у вас 64-битная версия, потому что у вас 32-битная (x86). Вы можете получить 64-битную версию отсюда: https://www.java.com/en/download/manual.jsp Установите ее и повторите попытку. Как только он запустится, как показано на снимке экрана, убедитесь, что вы указали правильное место для файлов сохранения, которое затем должно отображаться для «Пути сохранения», а затем также иметь раскрывающийся список для выбора игрового слота.

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_371
[DEBUG] Java Architecture: amd64
[DEBUG] Operating System: Windows 11
[DEBUG] Working Dir: C:\Users\.........\NMSSaveEditor-master
[DEBUG] Look and Feel: FlatLaf Light
[INFO] Starting Editor...
[DEBUG] Mem Usage: 250/3676 MB
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
[STDERR] 	at java.util.ComparableTimSort.mergeHi(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.mergeAt(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.mergeCollapse(Unknown Source)
[STDERR] 	at java.util.ComparableTimSort.sort(Unknown Source)
[STDERR] 	at java.util.Arrays.sort(Unknown Source)
[STDERR] 	at sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
[STDERR] 	at sun.awt.shell.ShellFolder.get(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.addItem(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.access$800(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI.doDirectoryChanged(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI.access$1100(Unknown Source)
[STDERR] 	at javax.swing.plaf.metal.MetalFileChooserUI$5.propertyChange(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.fire(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
[STDERR] 	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
[STDERR] 	at java.awt.Component.firePropertyChange(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.setCurrentDirectory(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.<init>(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.<init>(Unknown Source)
[STDERR] 	at nomanssave.ej.<init>(Unknown Source)
[STDERR] 	at nomanssave.ej.b(Unknown Source)
[STDERR] 	at nomanssave.Application.k(Unknown Source)
[STDERR] 	at nomanssave.Application.p(Unknown Source)
[STDERR] 	at nomanssave.v.run(Unknown Source)
[STDERR] 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)
[DEBUG] Latest version: "1.14.2"
[DEBUG] Current version: "1.14.2"

**Comment by NMS-D** [comment]
Я нашёл решение своей проблемы. Возможно вам стоит добавить это как рекомендацию для случая когда программа не находит сохранение или не видит их.  Вот что я сделал:

**Comment by NMS-D** [comment]
при сравнении файлов NMSSaveEditor.conf из программы версии 1.11.2, которая у меня работает, и версии 1.14.2, которая не реагирует но открывается как на скриншоте 1.
Открыв оба файла программой Notepad++, я просто скопировал всё что есть из версии 1.11.2 в нерабочий файл. Возможно, лучше просто его заменить, это одно и тоже.  И программа стала работать. Но немного не корректно. Похоже русские буквы отображаются некорректно.



![(1)](https://github.com/goatfungus/NMSSaveEditor/assets/138398683/6b0d4a82-4d3f-4a37-84ac-8d7e278855fa)


![(2)](https://github.com/goatfungus/NMSSaveEditor/assets/138398683/7df666fd-7e3d-4d0a-9ade-54fe2c9ce3df)

**Comment by NMS-D** [comment]
проблема была в том, что новая программа почему-то не давала выбрать папку сохранения.

**Comment by NMS-D** [comment]
вот мои файлы
[(NMSSaveEditor.conf).txt](https://github.com/goatfungus/NMSSaveEditor/files/11951108/NMSSaveEditor.conf.txt)

[(NMSSaveEditor.log).txt](https://github.com/goatfungus/NMSSaveEditor/files/11951132/NMSSaveEditor.log.txt)

**Comment by NMS-D** [comment]
Если кратко:

запускаете файл .jar.  
Видите окно как на скриншоте (1). 
Скачиваете любую старую версию которая запустится, например 1.11.2. 
Проверяете что она работает как на скриншоте (2). 
Закрываете старую программу.
Открываем ваш файл NMSSaveEditor.log из старой версии, и сравните с моим файлом. (3)
Если наши файлы совпадают, то просто вставляете старый файл в папку с новой версией.
Запускаете новую версию и выбираете сохранение. У вас будет как на скриншоте (4)

![(1)](https://github.com/goatfungus/NMSSaveEditor/assets/138398683/383a465d-173e-461a-aaf4-75ca39595409)

![(2)](https://github.com/goatfungus/NMSSaveEditor/assets/138398683/8e011525-ca2c-473a-8bce-e627d1594fdb)

![(3)](https://github.com/goatfungus/NMSSaveEditor/assets/138398683/706529bd-be3e-4dfd-8ebb-dc8641edfba0)

![(4)](https://github.com/goatfungus/NMSSaveEditor/assets/138398683/5a230e9a-913d-4aac-84dc-d2bda8fce169)

**Comment by NMS-D** [comment]
Надеюсь вам это поможет.)

**Comment by Devilin-Pixy** [comment]
@NMS-D I am happy to see you managed to get it to work. The info provided is hopefully useful for @goatfungus to understand what caused this issue to prevent it with future releases.

**Comment by calcifer11E** [comment]
@NMS-D can you walk me through that step by step? I tried to follow what you did but I got lost very quickly and I also do not have version 11 (as I only started playing a short time ago).

**Comment by goatfungus** [comment]
Thanks for this info... as a result I have added a check to ensure that the error doesn't happen again. Will be included in the next version.
