### ISSUE TITLE
Dosent detect my second slot (Windows store version)

### ISSUE THREAD

**Issue by HandSomeNissan** [goatfungus/NMSSaveEditor#862]
A few days ago it did detect my second slot, Now it just shows slot 1 which is not what i want. Is there any fix?

**Comment by ubronan** [comment]
Your second slot for what ? It is handy if you explain what slot and where

**Comment by HandSomeNissan** [comment]
apperantly its because i left about 5 seconds after saving, which it then dosent detect it. it was a community expedition slot. i just have to wait a minute after saving, which is a bit annoying but yeah. solved
