### ISSUE TITLE
I noticed 2 kinda secret updates 

### ISSUE THREAD

**Issue by ubronan** [goatfungus/NMSSaveEditor#863]
These updates installed pretty fast 
Now when i open my save it shows name mapping not found:  ?6B

I do not know if more are changed as i lost several times alot of my collected items
And had to start famring them legit after 4 times loosing alot i now fixed them with the save editor 
I admit i could not find the culpritt for the losses till i disabled the scan and range mod after i removed that the game is fine now

**Comment by ubronan** [comment]
I found i can no longer add storage on certain ships like before it is completely locked 
I tried to send some rewards for your work but the site did not accept my card as it is a debit card :(
Which they clearly do not like.

**Comment by goatfungus** [comment]
Not sure what would cause storage locks like that. Possibly another mod?
The name mapping warning is no biggie, it just indicates that there are parts in the save file that the editor doesn't know about.

**Comment by ubronan** [comment]
I noticed much more locks with the latest update
Locks on adding storage space and locks on amounts in inventory
I used the gbase expansion mod so the new so called improvement made me quit NMS
These devs hate when people use tools or expansions which are not legal for their taste
