### ISSUE TITLE
Is there an option to download NMSSaveEditor Beyond 2.0 in the application form for my No Man's Sky Desolation Patch?

### ISSUE THREAD

**Issue by KUNGFUJEDIMASTER24** [goatfungus/NMSSaveEditor#864]
I also wanted to know if there is an option for backwards compatibility for previous versions of No Man's Sky or a setting in the application that can accommodate previous save files to be edited.

**Comment by goatfungus** [comment]
I have occasionally split off older versions of the editor onto a separate branch, but these are no longer maintained.

For beyond: https://github.com/goatfungus/NMSSaveEditor/blob/expeditionsPrisms/README.md
