### ISSUE TITLE
Save JSON Disc Naming & Sub Folders

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#866]
Hi, trying to save the file as a JSON and drives are shown with no label and once selected no sub-folders are shown.
![NMSE1](https://github.com/goatfungus/NMSSaveEditor/assets/27774213/7f2e32c6-3912-48c4-9a78-fa5f5b104756)
![NMSE2](https://github.com/goatfungus/NMSSaveEditor/assets/27774213/9a76d3a0-71ae-4861-b1be-9613b9a6dfae)

**Comment by goatfungus** [comment]
Try double-clicking... some older versions of Java don't display disk labels properly.
