### ISSUE TITLE
Wont open json format and overloading cpu

### ISSUE THREAD

**Issue by iEx055** [goatfungus/NMSSaveEditor#87]
He wont read one of my save file(json only,other things works fine)
There it is:
[cheat_save.zip](https://github.com/goatfungus/NMSSaveEditor/files/2280532/cheat_save.zip)

**Comment by iEx055** [comment]
Using lastest 4GB version ofc..,
Console saying just that:
Parsing JSON...
Finished.

**Comment by iEx055** [comment]
Opened it an after...half hour and it has an error.
Tried to delete the first teleport, program asks want I save or not?
If I'm clicking yes - it gives the error:
http://puu.sh/BcDQ2/f4566f0434.png
If I'm clicking no - it overloads my CPU again x.x
P.S. i just want to remove some bases and teleports >.<

**Comment by goatfungus** [comment]
Your screenshot shows that the changes you made are not correctly formatted (and I can see the missing stuff on line #1). Luckily the editor detects this or your save would have been reset by the game. You have to be very careful when using the JSON editor, and it is labelled "advanced users only" for a good reason.

The JSON editor part is pretty heavy on RAM usage, how much RAM does your system have?

**Comment by iEx055** [comment]
12 gb,Giving 8GB to NMSSE.
Funny thing i am a coder on source engine(csgo mostly) and this thing creeps me out,i dont have any syntax errors,but it says like i have(to be exact i think editor while trying to save is checking only opened folder atm of saving,not the full save,cuz i wasnt editing something on line 1-100,somewhere at 100k+)...

**Comment by iEx055** [comment]
doesnt think i will give any tip there.
