### ISSUE TITLE
What is Account tab and how to unlock it?

### ISSUE THREAD

**Issue by SpaceLegends** [goatfungus/NMSSaveEditor#871]
Account tab is grayed out.

My save data are from PS4. (if asked about how old my dats is. mostly 2020 or 2019)

I'm not sure what does account tab do or it's never used? Unless units and currency are there? Which I was having hard time to find it. (Not using save wizard cheat because it give 999million but only want a 4billion if you have the cheat code for it)

**Comment by goatfungus** [comment]
Account data was added to the editor in September 2021, so if your save data is older than that you'll have to update your game to a newer version to be able to use it.

**Comment by SpaceLegends** [comment]
> Account data was added to the editor in September 2021, so if your save data is older than that you'll have to update your game to a newer version to be able to use it.

My game is up to date on PS4. and recently used it weeks ago but account tab is still grayed out.
