### ISSUE TITLE
Update for Echo 4.4?

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#872]
Brendon, are we going to see an update for the recent Echo release? it seems that the last update was the Interceptor but we've since missed the subsequent update and its Discoveries along with Echo's any prognosis. thanxs in advance...

**Comment by KarmaIsLame** [comment]
bro the updates barely been out for 2 days, give him some time, usually takes a few days to a week to get it up-to-date.

**Comment by Enejuto** [comment]
and you can still just modify the new items (bit buggy but it works) and new mulitools (the updates content) fine, be patient lmao

**Comment by goatfungus** [comment]
I've just released an update with (hopefully all) Echoes features. Enjoy.
