### ISSUE TITLE
It won't open file/path

### ISSUE THREAD

**Issue by TheSoullessTyrant** [goatfungus/NMSSaveEditor#880]
Whenever I launch the editor it just gives me the main screen with the boxes blank and saying no path selected. Whenever I go and click open file/path it throws the error
![image](https://github.com/goatfungus/NMSSaveEditor/assets/143594893/29277db9-11fc-46cb-8307-46010f0b5649)

**Comment by goatfungus** [comment]
Try deleting your NMSSaveEditor.conf file, or renaming it as something else. I do have a fix for the issue, but it's not released yet.

**Comment by goatfungus** [comment]
I have released an update with a fix for this. Should be all good now.
