### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Neokom1978** [goatfungus/NMSSaveEditor#889]
I'm having a problem when saving a game in an Echoes update - after saving the Save Editor throws an error when trying to open raw json:

Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space...

Checked twice - when resaving the game from a previous update to Echoes

Thanks in advance

**Comment by Neokom1978** [comment]
And, if possible, give a link to the Editor version for the Interceptor .. maybe it will work there. I read about the problem with large files, but, my save has long been large - on previous versions of the editor they were handled normally

**Comment by Devilin-Pixy** [comment]
@Neokom1978 Could you make sure to have the 64-bit version of Java 8 installed. This is usually the reason for OutOfMemoryError. A download link is provided on the main page, requirements.

The current version of the Save Editor works fine with the latest updates. If a save needs updating to a newer version of the game, please do so within the game. Just jump in/out of ship, and the save should be current version to work fine with the editor

**Comment by Neokom1978** [comment]
Thank you!!! Problem solved! :)
