### ISSUE TITLE
Star Silk - is this a craftable product that has to be learned ?

### ISSUE THREAD

**Issue by abiemann** [goatfungus/NMSSaveEditor#89]
Hi, I checked whether your app can unlock "Star Silk", but it doesn't seem to.

Star Silk is needed for building:
Decoration -> Interior Decoration -> any of the "Chair" items.

Thanks !

**Comment by goatfungus** [comment]
See issue #86.
Star Silk is one of the items where HG have screwed up their name translations for, not sure which one but Icon should help.
