### ISSUE TITLE
NMSSaveEditor does not work with NMS The Abyss

### ISSUE THREAD

**Issue by Usalabs** [goatfungus/NMSSaveEditor#893]
I tried the editor for NMS The Abyss, and it doesn't do a solitary thing, yes it changes the save files, but as soon as the game has loaded the auto save, everything is reverted back to before the file was edited, which means there's a backup file somewhere that stores the current game, and if the save game file(s) have been changed, then the backup is loaded back into the save game,  I tested this by changing the save game file 'save.hg' for the first slot, and changed the exosuit to have all enabled slots, then I clicked on 'Save changes', then started NMS, I clicked 'Play', then selected the only saved game in the slots, and when it all loaded, my character was not on the space station, but on a completely randon planet, the exosuit did not have all slots enabled, so I then switched to the editor, and it showed a small box, 'the file has been changed externally, would you like to reload?'  which tells me, there definately is another file somewhere that over-writes the save game file when that file has been changed.  So, when I reloaded, and checked the exosuit, all but the default slots were disabled, so either there's a nother file somwhere, or the version of the editor is not compatible with the version of NMS game files?  The save game files are version 2, if the latter, then where can I find the version of the editor for NMS The Abyss?

**Comment by Devilin-Pixy** [comment]
@Usalabs You likely want to check the different branches. One of the old branches is for Next/Visions, which is from around the time of 'The Abyss'. Make sure to have backups, just in case.
https://github.com/goatfungus/NMSSaveEditor/tree/nextVisions

**Comment by Usalabs** [comment]
> @Usalabs You likely want to check the different branches. One of the old branches is for Next/Visions, which is from around the time of 'The Abyss'. Make sure to have backups, just in case. https://github.com/goatfungus/NMSSaveEditor/tree/nextVisions

Great it worked, thanks.

**Comment by Usalabs** [comment]
With help, I found the right editor for my version of NMS.
