### ISSUE TITLE
Saving Activates Modified Confirmation

### ISSUE THREAD

**Issue by StormFX** [goatfungus/NMSSaveEditor#90]
I'm not sure if this intentional, but the method that detects that the save file was modified also detects its own modifications, causing it to ask for a reload confirmation after saving it.   (1.5.16)

**Comment by goatfungus** [comment]
Oooh, didn't check that! lol
I'll get onto it shortly.

**Comment by goatfungus** [comment]
Should be fixed now... sorry :)
