### ISSUE TITLE
Freighter wont change

### ISSUE THREAD

**Issue by bcmmbc122333** [goatfungus/NMSSaveEditor#91]
I keep trying to change my freighter in NMS but every time I change it and reload the game it stays on the same ship. I have tried saving differently, I have tried warping to a new system and teleporting it in and nothing helps. Any suggestions?

**Comment by goatfungus** [comment]
What do you mean "change your freighter"? What exactly are you tying to do?

**Comment by bcmmbc122333** [comment]
I am trying to use a different seed to get a new freighter. I have only tried model seeds. It worked the very first time I tried but not any time after.

**Comment by goatfungus** [comment]
Seed should work fine, what exactly are you expecting to change?

**Comment by bcmmbc122333** [comment]
the color and shape of the ship. Neither change.

**Comment by travisnewman** [comment]
Based on our conversation in #80 it looks like the home seed controls colors now.

**Comment by goatfungus** [comment]
Yeah.... there is also a known bug in the game where the primary colour seems to change if you warp your freighter to another system, so I would say none of this has anything to do with the editor. The only options you have for changing the model/colour/npcs are covered by the 2 seed fields in the editor, and that's about all you really have control over even if you change things in the raw JSON, so I'm going to close this issue.

**Comment by travisnewman** [comment]
@goatfungus will probably know better than me what all it does, but that’s the seed of the system where the freighter was found. So it at minimum controls which NPCs are on your ship and for some reason it changes the colors. I haven’t seen any other changes personally.
