### ISSUE TITLE
Publish source code

### ISSUE THREAD

**Issue by mfoulks3200** [goatfungus/NMSSaveEditor#911]
Hello!
I came across your project when wanting to translate my switch save to my new Steamdeck. It's a great project, and looks really well put together, but I noticed you haven't included any source code in the repository— just the compiled binaries. If you were to share the source code of the project in the repo, then others (such as myself) would be able to contribute code and features to the project as well.

**Comment by mfoulks3200** [comment]
I am aware of the requirements for this project. I'm a developer for a major software company, working in Typescript and Java professionally.

As for access to the source code— GitHub is intended to be a file hosting platform, the entire point of creating a project here is to share your code, and allow others to contribute. To that end, there are a lot of tools built in to facilitate some of the issues you mentioned, like pull requests, which can ensure that no code makes it into the codebase that the owner hasn't explicitly reviewed.

**Comment by cjg67** [comment]
I am well aware of all the tools built into github as I have used a number of them.  
There is no requirement for any person posting to github to actually provide source code.  I appreciate that you are another IT professional, but you are also failing to understand that for some people who post here, any extra amount of time that they need to take to review anything that others provide, takes away from what they want to do with their app.  Also, take a look at the current pull requests, and you will see that a number of them are very old, as the owner has not actually authorized any of them.

**Comment by Troughy** [comment]
It's a shame that there are only 2 working save editors for NMS, both of them closed source (but both of them are on Github! A place intended to share source code, not precompiled binaries.)
