### ISSUE TITLE
Windows 11 new save corrupted.

### ISSUE THREAD

**Issue by RaylanVox** [goatfungus/NMSSaveEditor#919]
i freshly installed NMS and started a brand new save. then tried to use the editor but it gives me an error saying save file corrupted. i have the current version of java installed. and I've even tried doing a new fresh save, I'm not on any experimental build, I'm on the current live version of the game but the editor will not let me edit the save, the info for the modified time and date and everything is correct for the save but it keeps saying save file corrupted. I've tried all versions of the editor but it keeps doing the same thing. the editor opens fine but then tells me the error.

**Comment by RaylanVox** [comment]
![a9ce24ec1760521790e57528de28a0af](https://github.com/goatfungus/NMSSaveEditor/assets/119615345/04bd3a0b-69aa-4e7f-9451-d0a3107b15ec)

**Comment by RaylanVox** [comment]
![b3db9eb7148c075df4f675c92d65e18e](https://github.com/goatfungus/NMSSaveEditor/assets/119615345/b37b88bb-6752-4bd1-a39e-e91b94febc9a)

**Comment by davemager** [comment]
No Man's Sky, public version on Steam was updated about two hours ago. If you've opened (or created) any save since then, it will indeed show as corrupted. We are patiently waiting for an updated version of the NMSSE that can read the new save file format introduced with this new version.

**Comment by RaylanVox** [comment]
ah ok, i did not realize the game was just updated today. i will wait for the new version. thanks for the info
