### ISSUE TITLE
Corrupt save file message 

### ISSUE THREAD

**Issue by HedgeHog2222** [goatfungus/NMSSaveEditor#920]
On the latest NMS update (14/02/24) toy now get a Save file corrupted message when opening the saved file. Guess they changed the format!

Please can you fix it so your wonderful program works again

**Comment by ArWeGer** [comment]
Same here.

**Comment by tomaz136** [comment]
same here 14.02.2024 steam Omega update .Please help .
![Posnetek zaslona](https://github.com/goatfungus/NMSSaveEditor/assets/160073323/0f51b5fe-8745-4b2f-83c4-3f87f03eebe1)
![Posnetek zaslona](https://github.com/goatfungus/NMSSaveEditor/assets/160073323/aa84f8e2-cda2-4fa1-b319-b506f45a9cf6)

**Comment by ThunderStruck5966** [comment]
Same here..

**Comment by ThunderStruck5966** [comment]
![Screenshot 2024-02-15 090748](https://github.com/goatfungus/NMSSaveEditor/assets/126310462/eb0bf1a5-33ad-4d38-8b39-d9619e319ee4)

**Comment by ThunderStruck5966** [comment]
> If you accessed the beta for Omega the save editor will be unable to access the new version of the saves. Currently with the update that was launched today the game saves are equal to that beta save and will be corrupt if you try to access the save file after launching the save in game.

What should I do, I'm back in Public Branch now..? So even with this update the game is is still in Beta form?

**Comment by cjg67** [comment]
I am wondering if the release of the update on steam was actually a mistake, as hello games have not updated the release log or the news section of their site.
Steam force quit my game and then there was the 7 gig update required.  Had to wait for a bit for amumss to get updated as there has been some changes, as some of the mods I used would not recompile, but everything is now back to being usable.
I have not yet attempted to open a save using the editor.

**Comment by ThunderStruck5966** [comment]
I think I'll go back to last working save on Feb 12th 2024, and wait for a while..

**Comment by HedgeHog2222** [comment]
I hope Fungus is still active and will fix this

**Comment by ThunderStruck5966** [comment]
Sadly Nom Nom is in the same boat as Save Editor..

**Comment by Farrest95** [comment]
If a solution is found, post here!

**Comment by goatfungus** [comment]
Currently working on this, see #923 for updates.
