### ISSUE TITLE
goatfungus says save file is corrupted this comes after nms last update 

### ISSUE THREAD

**Issue by RaYaAn7762** [goatfungus/NMSSaveEditor#921]
goatfungus says save file is corrupted this comes after nms last update. the save directly prior works fine as do all other save files pre nms update, but once the save is run in nms and is saved in nms when loaded in goatfungus it says save is corrupted, the save works absolutely fine in nms. it does not seem to actually be a save corruption issue but more likely that hello games has perhaps changed something about how the game save is saved or read and written to. ( goatfungus needs update) today's date is Feb 14 2024, this started occurring starting last night.. also you have created a stellar program it is very much appreciated.

**Comment by cjg67** [comment]
If you had actually bothered to read before posting, this has already been posted multiple times.
There has been a number of changes made by hello games to the code.  It is pointless trying to use the editor with the changes that have been made, as an entirely new section has been added and they have totally re-written part of the code.
Do not start a new post when one has already been made regarding an issue.  You are not special, it just makes you a complete asshole for doing so.

**Comment by Mike-Blackwell** [comment]
Let's get to the root of the problem, is there an update in the works and if so when as it seems like there's hasn't been any activity as of 6 months ago.

**Comment by RaYaAn7762** [comment]
I hope so as it is an excellent application, however it may be awhile. it has been my experience in the modding and editor communities most who engage in the communities also work other full time jobs, it would be wonderful if more people donated to fund endeavors like goatfungus and other useful apps here on git. I generally do not post on places like git because some people think that they are special and that it is okay to call other people assholes without good warrant as if they believe the world and everyone else's opinions should revolve around them. Although I am autistic  contrary to popular belief i do not see myself as being special, nor do I think posting a new thread to a open issue makes my issue any more or any less valuable than those of others in the world around me, but going on a thread someone else has posted to call someone who is brand new to the not only git but this community and has very little experience with places like git or who have had little to no exposure to a community like git does on all accounts make you an asshole. but i digress because i did not start this thread to bash anyone nor am i here to for your opinion. further more when you post insulting comments to threads like this directed at persons like myself,  you actually cause harm to the projects creators and contributors. you know the 4 persons listed on the master page of the project which you do not appear to be one of.  All in all it just makes you look foolish and unprofessional. My sincere apologies to the project creator and it's contributors for mt rant.

**Comment by goatfungus** [comment]
Currently working on this, see https://github.com/goatfungus/NMSSaveEditor/issues/923 for updates.

PS: Please be civil with each other, and also please don't flood the issues list with the same thing :)
