### ISSUE TITLE
NMS Omega 4.5

### ISSUE THREAD

**Issue by louanfontenele** [goatfungus/NMSSaveEditor#922]
Hi @goatfungus can you please update the NMS Save Editor for Omega version?

**Comment by PappyVanWink** [comment]
Yea I too request an update, all save files I now showing as corrupted!   After OMEGA 4.5 update

**Comment by cjg67** [comment]
You are complete asshole morons for posting a new thread WHEN IT HAS BEEN STATED MULTIPLE TIMES BEFORE.

You are not special, just plain SCUM.

**Comment by theCoup** [comment]
> You are complete asshole morons for posting a new thread WHEN IT HAS BEEN STATED MULTIPLE TIMES BEFORE.
> 
> You are not special, just plain SCUM.
You're angry that other people have opened issues because it adds clutter to work through, so you exacerbate the clutter by verbally abusing them. Stop being a hypocrite. Stop abusing people in these threads.

**Comment by louanfontenele** [comment]
> > You are complete asshole morons for posting a new thread WHEN IT HAS BEEN STATED MULTIPLE TIMES BEFORE.
> > You are not special, just plain SCUM.
> 
> You're angry that other people have opened issues because it adds clutter to work through, so you exacerbate the clutter by verbally abusing them. Stop being a hypocrite. Stop abusing people in these threads.

This Idi has been doing this on several issues

**Comment by Forthamos11** [comment]
This is fucking hilarious 😂 but yea i would like an update too. but on the other hand, the update just released 2 days ago so chill everyone

**Comment by goatfungus** [comment]
Currently working on this, see https://github.com/goatfungus/NMSSaveEditor/issues/923 for updates.
