### ISSUE TITLE
New Expedition 12 and Twitch Ids for Omega Update

### ISSUE THREAD

**Issue by Theliel** [goatfungus/NMSSaveEditor#925]
While the application is updated to solve the problem with the new format, I leave you the list of IDs of the new update for whoever wants to use them

TWITCH_256 to TWITCH_285

EXPD_BANNER12
EXPD_TITLE12
EXPD_DECAL12
EXPD_SHIP12
EXPD_ATLASPACK
EXPD_ATLASSTAFF
EXPD_ATLASHELM
EXPD_POSTER12C
EXPD_POSTER12B
EXPD_POSTER12A

All of them are tested and working fine

**Comment by kobs57** [comment]
> While the application is updated to solve the problem with the new format, I leave you the list of IDs of the new update for whoever wants to use them
> 
> TWITCH_256 to TWITCH_285
> 
> EXPD_BANNER12 EXPD_TITLE12 EXPD_DECAL12 EXPD_SHIP12 EXPD_ATLASPACK EXPD_ATLASSTAFF EXPD_ATLASHELM EXPD_POSTER12C EXPD_POSTER12B EXPD_POSTER12A
> 
> All of them are tested and working fine

Aaaand how do you use those???

**Comment by Theliel** [comment]
Edit account (accountdata.hg), and add them to the respective secction, UnlockedTwitchRewards and UnlockedSeasonRewards.

Another option, extract and edit rewards.xml file inside NMSSaveEditor and add the IDs, repack the jar and they will be listed in the editor.

**Comment by Nyrdin** [comment]
Suggestion: Please add a link to "About" so we can jump directly to your "https://github.com/goatfungus/NMSSaveEditor" page. Thanks in advance. :)

**Comment by goatfungus** [comment]
Thanks for the info @Theliel
I've been able to successfully extract these from the game files and verified with your list.

I'm currently working on the changes for OMEGA, see https://github.com/goatfungus/NMSSaveEditor/issues/923 for updates.
