### ISSUE TITLE
PS4 SW "WARNING: name mapping not found: "..."

### ISSUE THREAD

**Issue by MrMfG** [goatfungus/NMSSaveEditor#926]
Initializing environment...
Starting Editor...
Loading storage: D:\
Loading saves for Slot 2...
Reading save file...
  Slot: Slot 2 - NORMAL - Feb 16, 20:27
  Filename: savedata05.hg
  WARNING: name mapping not found: ASZ
  WARNING: name mapping not found: XvU
  WARNING: name mapping not found: IsE
  WARNING: name mapping not found: yID
  WARNING: name mapping not found: X;?
  WARNING: name mapping not found: WmI
  WARNING: name mapping not found: :?x
  WARNING: name mapping not found: he5
  WARNING: name mapping not found: @;C
  WARNING: name mapping not found: IsL
  WARNING: name mapping not found: MMA
  WARNING: name mapping not found: U:h
  WARNING: name mapping not found: nS>
  WARNING: name mapping not found: me6
  WARNING: name mapping not found: 4q6
  WARNING: name mapping not found: >iu
  WARNING: name mapping not found: AllowFriendBases
  WARNING: name mapping not found: dAR
  WARNING: name mapping not found: AeI
  WARNING: name mapping not found: L8=
  WARNING: name mapping not found: waR
  WARNING: name mapping not found: rER
  WARNING: name mapping not found: OHU
  WARNING: name mapping not found: gnU
  WARNING: name mapping not found: 4=k
  WARNING: name mapping not found: BBw
  WARNING: name mapping not found: 33q
  WARNING: name mapping not found: S2k
  WARNING: name mapping not found: @xZ
  WARNING: name mapping not found: GFy
  WARNING: name mapping not found: WoW
  WARNING: name mapping not found: LFj
  WARNING: name mapping not found: J>I
  WARNING: name mapping not found: eem
  WARNING: name mapping not found: hQ1
  WARNING: name mapping not found: MLJ
  WARNING: name mapping not found: l?S
  WARNING: name mapping not found: TbT
  WARNING: name mapping not found: Zq4
  WARNING: name mapping not found: TlS
  WARNING: name mapping not found: W=G
  WARNING: name mapping not found: @xT
  WARNING: name mapping not found: 9J<
  WARNING: name mapping not found: c=A
  WARNING: name mapping not found: s;F
  WARNING: name mapping not found: gsT
  WARNING: name mapping not found: aS@
  WARNING: name mapping not found: TuK
  WARNING: name mapping not found: xFq
  WARNING: name mapping not found: uEG
  WARNING: name mapping not found: iBF
  WARNING: name mapping not found: kOX
  WARNING: name mapping not found: H:b
  WARNING: name mapping not found: KxX
  WARNING: name mapping not found: 6:a
  WARNING: name mapping not found: TOS
  WARNING: name mapping not found: wFw
  WARNING: name mapping not found: Ch:
  WARNING: name mapping not found: VUh
  WARNING: name mapping not found: H9K
  WARNING: name mapping not found: ec8
  WARNING: name mapping not found: XbO
  WARNING: name mapping not found: pFl
  WARNING: name mapping not found: Go<
  WARNING: name mapping not found: n5h
  WARNING: name mapping not found: rHh
  WARNING: name mapping not found: e;b
  WARNING: name mapping not found: E?H
  WARNING: name mapping not found: LMQ
  WARNING: name mapping not found: RxV
  WARNING: name mapping not found: YeP
  WARNING: name mapping not found: uWE
  WARNING: name mapping not found: 2YS
  Error parsing JSON: Short read
Finished.

**Comment by J0K3RJAKE** [comment]
goatfungus writes...
> I'm currently working on the changes for OMEGA, see #923 for updates.

New Expedition 12 and Twitch Ids for Omega Update #925
https://github.com/goatfungus/NMSSaveEditor/issues/925
