### ISSUE TITLE
SEVERE errors, program won't start

### ISSUE THREAD

**Issue by belowchaos** [goatfungus/NMSSaveEditor#927]
![image](https://github.com/goatfungus/NMSSaveEditor/assets/103081270/ed9d92ab-7ba9-4ff6-b5f9-9e4a677c5f8a)
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/14316548/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
That's weird... can you send me your NMSSaveEditor.conf file?

**Comment by belowchaos** [comment]
![image](https://github.com/goatfungus/NMSSaveEditor/assets/103081270/188ba175-c95a-4696-831a-79b722adac87)
It didn't make a conf file

**Comment by goatfungus** [comment]
odd... nothing has really changed in that area... can you post the log file?

**Comment by belowchaos** [comment]
The log is posted beneath the first screenshot

**Comment by goatfungus** [comment]
Looks like an issue with your file path... can you try moving the editor directory somewhere else?
Log says it can't find C:\!\NMS\Goatfungus

**Comment by belowchaos** [comment]
Unsure if it is a java issue, I've reinstalled java and your program 3 times each and the issue persists, and I've done a restart of my system

**Comment by belowchaos** [comment]
I will move it somewhere else, previous comment was made before github showed me yours!

**Comment by goatfungus** [comment]
> I will move it somewhere else, previous comment was made before github showed me yours!

See if that changes anything... it might also be something wrong with Java, but the path shouldn't contain a "!" character.

**Comment by belowchaos** [comment]
Oh, I have my folder named with an exclamation mark LOL we found the problem

**Comment by goatfungus** [comment]
All good! Yeah, I just tested puting my local copy into a directory named "!" and get the same issue. Java just doesn't know what to do with it.

**Comment by belowchaos** [comment]
silly java

**Comment by goatfungus** [comment]
> silly java

I should have used .NET, but then again I originally only built this for personal use and invested a lot of time into it before deciding to actually publish it. Kinda stuck with it now unless I do a rewrite from scratch.
