### ISSUE TITLE
File flagged as virus - False positive

### ISSUE THREAD

**Issue by DeltaQuasar** [goatfungus/NMSSaveEditor#928]
title says it all idk why this is but it just doesn't work for me

**Comment by goatfungus** [comment]
Some antivirus detect this as a virus, but it's a false positive. I am not sure why some of them do this while others don't, but you could try disabling it temporarily while you download. Once you've extracted the files, re-enable your antivirus and do a scan on the folder for peace of mind.

**Comment by DeltaQuasar** [comment]
tried it and it worked thanks
