### ISSUE TITLE
Still need Freighter Model Type

### ISSUE THREAD

**Issue by DigitalHytop** [goatfungus/NMSSaveEditor#929]
The model type for the new Pirate Freighter is still missing in the drop-down on Freighter tab

**Comment by DigitalHytop** [comment]
Figured I'd grab the freighter and get the path and share it

"MODELS/COMMON/SPACECRAFT/INDUSTRIAL/PIRATEFREIGHTER.SCENE.MBIN"

**Comment by goatfungus** [comment]
I've just added the new freighter, multitool, and ship for Omega. Enjoy!

**Comment by DigitalHytop** [comment]
> I've just added the new freighter, multitool, and ship for Omega. Enjoy!

Huge TY GF, you daMan !
