### ISSUE TITLE
Issue with expedition saves that will solve itself in 2 days but still annoying

### ISSUE THREAD

**Issue by Giozee** [goatfungus/NMSSaveEditor#936]
I was playing on an expedition savegame (i don't own the game. I'm playing with the free weekend) tried editing the savegame and the slot was changed from "expedition" to "normal".
Can't access the savegame from the game anymore without buying the game.
I thought my mistake was doing something specific, but i'm pretty sure the save editor changes from expedition to normal or custom at any change. (Ok, yeah. While writing this i sacrificed another savegame to the cause: made a new expedition savegame, edited a quantity in my inventory from 30 to 31 and saved. not an expedition save anymore.)
![image](https://github.com/goatfungus/NMSSaveEditor/assets/64650196/a8125820-1445-4d16-b3d7-12bbd24c117e)
![image](https://github.com/goatfungus/NMSSaveEditor/assets/64650196/88f7fbc0-553a-4a59-8ef5-a849ecea6326)

**Comment by SmallMegazord** [comment]
Currently I am noticing that the expedition once started it will set it as a community event in game. But once you try to edit the game via save editor via the tabs and saved it will convert it back to its original game save type. I have only had success finding the specific information in the json file in what was originally a file called Y2K or something of that nature. But with the newer update that was posted a few hours after the new save file editor there is now a ExpeditionContext file. I will play around and edit that json file to see if it will change anything in game. When I was changing simple things like item count on the json file it was not reflected in game which I thought was odd. As if there was another part of the json file that would verify or be the master back up which in that case both parts would need to be edited. 

I dont think the free weekend is structured differently. I think with the expedition embedded into the normal save file it will need its own set of tabs in the ez view of editing the game save.

**Comment by Giozee** [comment]
The solution to this is:
navigate to the folder where your saves are,
copy all the files there
Edit your savegame
put all the files back (overwrite) BUT your savegame.

I'm 100% sure this is not the best approach, but it worked and even though i assume the result would be the same by copying the mf_save(number).hg files, i cannot be bothered to try.
