### ISSUE TITLE
Already owned items on quicksilver shop

### ISSUE THREAD

**Issue by Ashendale** [goatfungus/NMSSaveEditor#945]
I once went on a "select all stuff to claim" on the save editor and some stuff I already had. It's a minor annoyance but, things like armor, that I already owned, I cannot claim from the quicksilver/rewards shop and it just clutters the UI.

Is there a simple way to do this that I'm missing?

**Comment by ThunderStruck5966** [comment]
If you know you have the stuff just ignore it been around since Adam n Eve..
