### ISSUE TITLE
Un-Supercharge a slot?

### ISSUE THREAD

**Issue by Dawnmyst** [goatfungus/NMSSaveEditor#949]
Is there a way to remove a supercharged spot? 

Unfortunately an issue i thought was resolved is not. When i've loaded the game and then used the Editor for any reason all new saves have all personal and multitool spots Supercharged. 

I have not been able to find a way to "un-supercharge" slots, right clicking on the slot only gives "supercharge" option. 
Please help.

**Comment by garywilliams** [comment]
You're supposed to use the same menu item to supercharge and un-supercharge a slot. There's a checkmark that appears beside the menu item when the slot is supercharged.

**Comment by Dawnmyst** [comment]
Sorry i'm an idiot and didn't realize i could just ... remove... the check mark to un supercharge it lol ... altho it is a little annoying that i can't do an "unsupercharge all" 
Thanks!
