### ISSUE TITLE
When loading a savegame; "There was an error loading the file."

### ISSUE THREAD

**Issue by Twietergaming** [goatfungus/NMSSaveEditor#968]
Each time I try to load my savegame, it gives me the error message "There was an error loading the file."
Ive supplied images of the error, if someone knows a fix. Please help!

![2024-03-27_09h31_05](https://github.com/goatfungus/NMSSaveEditor/assets/165141380/693e4ec1-43ff-4504-9bac-e1738c469f16)
![2024-03-27_09h28_16](https://github.com/goatfungus/NMSSaveEditor/assets/165141380/c152e7eb-98f1-4291-a58f-880d08ffb392)

**Comment by Natbugasaurus** [comment]
I have the exact same issue
![Screenshot 2024-03-29 092904](https://github.com/goatfungus/NMSSaveEditor/assets/21271833/0fdc589f-5865-405b-9f65-f44cfd9ce504)

**Comment by goatfungus** [comment]
Can you please email me a copy of your save files?
If you could zip them all up with WinZip or something equivalent I will have a look and see what the issue is. I don't have the Xbox version of NMS so I have to rely on users to send me the save data.

**Comment by goatfungus** [comment]
Thanks for the info, I have been working on it all day and have released a new version with updated WGS/XBox support. Hope it works out for you :)

**Comment by Twietergaming** [comment]
> I have been working on the editor all day and have released a new version with updated WGS/XBox support. Hope it works out for you :)

It does work now!
Thanks a lot! And keep up the good work! This is by far my favourite save editor :D
