### ISSUE TITLE
No Man's Sky has been vastly updated, and the editor is beginning to fall behind. May we have an update?

### ISSUE THREAD

**Issue by Khurthis** [goatfungus/NMSSaveEditor#970]
Title says it all, but yes, NMS is well passed the Interceptor update, and several new items/features have been added to the game itself, as well as massive overhauls.

I hope the Editor will be updated, as it's the only one presently worth using. 

Kind regards!

**Comment by ponycannon** [comment]
Although the README.md file has not been updated, the editor has been. With the exception of the latest update from hello games. It should just be a matter of time. The change log shows the changes and you can see it was last updated for OMEGA, the previous update.

**Comment by goatfungus** [comment]
I have just released an update for Orbital. It looks like not much has changed except for the addition of ship customization pieces, so not exactly a vast update from an editor perspective.

I should probably update the README each time i release a new version, but have been a bit lazy on that front. I have kept the editor updated though :)
