### ISSUE TITLE
Can't Edit Microsft Store (Xbox) NMS version on the editor, it shows as "EMPTY"

### ISSUE THREAD

**Issue by Chariot7000** [goatfungus/NMSSaveEditor#973]
Please could you fix it? I really like your save editor it's way better than the NomNom editor, I honestly only play nms because of your save editor, the other one always bugs my save.

**Comment by goatfungus** [comment]
Can you please email me a copy of your save files?
If you could zip them all up with WinZip or something equivalent I will have a look and see what the issue is. I don't have the Xbox version of NMS so I have to rely on users to send me the save data.

**Comment by Chariot7000** [comment]
I just sender it to you but I could only compress it to .rar can you open it? If not I can try to make them .zip

**Comment by goatfungus** [comment]
Thanks for the info, I have been working on it all day and have released a new version with updated WGS/XBox support. Hope it works out for you :)
