### ISSUE TITLE
Enable Hidden Files in the Save Path open dialog so that we can get to the files on our LInux systems

### ISSUE THREAD

**Issue by tolistim** [goatfungus/NMSSaveEditor#975]
Since the Steam folder on a Linux system is hidden (.steam), we can't get to our saves.  Can you either provide the ability to add the save path as a launch argument or turn on view hidden folders in the Save Path initial dialog?  Even manually typing the path in the dialog doesn't get things set properly:

/home/tjones/file:/home/tjones/.steam/steam/steamapps/common/No\ Man\'s\ Sky

**Comment by goatfungus** [comment]
Looks like there is a problem with directory handling in the file dialogs anyway, so I have added a fix to the latest version. It currently doesn't show hidden directories, but you should still be able to navigate them by manually typing the path as you tried before... let me know if this doesn't work.

**Comment by ponycannon** [comment]
Some work-arounds for this issue on linux. 

Create a symbolic link to the steam directory in your home folder. If you are using wine/ proton the windows (and java) dialogs never work well with the hidden folders in linux, you'll need it for multiple games.

For the editor, you can edit the NMSSaveEditor.conf file and add the file location, with a line like follows, in my conf file its just below the line for "FontScaling"
"GameSaveDir": "/home/username/.steam/steam/steamapps/compatdata/275850/pfx/drive_c/users/steamuser/AppData/Roaming/HelloGames/NMS/st_76561197976771480",

The final folder st_76561197976771480, might be different for you?

Other issues with linux. When running the editor use the command line.

java -jar NMSSaveEditor.jar -autoupdate

This will mean if there is an update it will prompt you to download it, which gets saved in the NMSSaveditor directory as ~NMSSaveEditor.dl.
You then need to copy this file to the NMSSaveEditor.jar file.

cp \~NMSSaveEditor.dl NMSSaveEditor.jar

These are basically what the windows bat file does, the obvious thing would be to create a shell script which does this, but that would make too much sense. This one is lazy.

**Comment by tolistim** [comment]
Thanks Goat and Pony - I'll grab the latest build.  I do use the Linux native JRE - OpenJDK 8 - when launching the editor so that's at least solid.  Asking about the .conf file was my next question, so again - thanks!.

**Comment by tolistim** [comment]
Updated and then typed the path directly and it worked.
Created a new .conf file and added the path manually and it worked.

It also seems snappier on Linux than on my Native Windows 11 system!

Happy days.
