### ISSUE TITLE
whiped my save after restoring multi-tool

### ISSUE THREAD

**Issue by HillBillyBong** [goatfungus/NMSSaveEditor#982]
multi-tool and freighter back up and restore is broken. 
refill stacks is not working.
added technology  in exosuit not saving 

while i was copying my main multi tool and restored it my savegame was starting like a new save game. totally messed up everything  on my 2k playhours ( i was able to restore a back up from the cloud)

PC gamepass
version Update 1.15.4

**Comment by OhGee01** [comment]
Jup, same here

**Comment by goatfungus** [comment]
Yeah, there was an issue with the meta data file, but i think I have sorted it now. Let me know how it goes.

**Comment by OhGee01** [comment]
> Yeah, there was an issue with the meta data file, but i think I have sorted it now. Let me know how it goes.

hey sorry, but sadly it still whipes it to the whitescreen at the beginning.

**Comment by goatfungus** [comment]
ok, that's a bit weird... I'll keep trying.

**Comment by LimeBoiGaming** [comment]
Same here, added ship parts and filled some stacks to my exosuit and it wiped my save.

**Comment by HillBillyBong** [comment]
> Yeah, there was an issue with the meta data file, but i think I have sorted it now. Let me know how it goes.

Thanks for the fast response! 
I see other people tried it and it's still not working correctly. I'll wait till you release a new update and try it again.
Thanks for for investing your time to make it work again.

**Comment by HillBillyBong** [comment]
It wasn't my intention to close the post.

**Comment by Chariot7000** [comment]
Mine still like that too

**Comment by goatfungus** [comment]
As it turned out, there were still bugs in the format, which are hopefully fixed now.
If you still have issues, please post comments on #978
