### ISSUE TITLE
Doesnt seem to be bringing changes over from the JSON file.

### ISSUE THREAD

**Issue by githubUser01946** [goatfungus/NMSSaveEditor#983]
There seems to be an error when making changes to a base and thats it doesnt actually change anything.

I used the No Mans Sky Base Builder: https://www.nexusmods.com/nomanssky/mods/2598
I made a few changes like resized the portal, add some furniture etc then exported the text into the relavant bases json file but nothing is changed when I load back into the game. 

The time etc of the save is updating but the RAW Json doesnt appear to being loaded or the changes at least.

The steps I take are as follows:

- Load your app
- Load the save file located at C:\Users\my windows name\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\folder with numbers etc
- Edit raw json
- Base context
- - PlayerStateData
- - - PersistantPlayerBases
- - - - Open 7th Base "Portal in the 11th Galaxy ELKUPALOS"
- Open the base builder and make relevant changes
- Choose export
- Copy all the text
- Head back to your save editor and paste over the text
- Click the little X in top right
- Click yes on the popup about things being changed
- Click save changes below the save details and wait for the date and time to update
- Wait for it to say finished on the CMD window and load the game
- No changes made
- Cry into coffee

**Comment by goatfungus** [comment]
There was a problem with WGS / XBox Game Pass file formats which I have been addressing here: #978 

If you still have issues from the latest version (1.15.6) please post a message in the other thread.
