### ISSUE TITLE
Feature: Unlock all Ship Builder Customizations

### ISSUE THREAD

**Issue by HoleInOneGolfer** [goatfungus/NMSSaveEditor#985]
Feature: Unlock all Ship Builder Customizations

**Comment by goatfungus** [comment]
Unlock? I don't think there is a specific unlock setting for them.

They are just items in the game that you get by deconstructing ships... alternately you can add the items to your inventory using the save editor, just pick the ones you want then visit the ship builder to use the items.

**Comment by Ymmit34** [comment]
It would be nice if you could make it completely free, or at least make an option to load in all the parts or the parts you need or something

**Comment by IvvyDevMC** [comment]
That is very different to how a Safe Editor functions. It just Changes a binary Format without the Game running. Doing anything to the Game while running that depends on the gamestate is in the realm of mods / Trainers.

**Comment by BingoFuel5X5** [comment]
Just type the name of the module into the add item field.  Presto.  All are available.  Though I think the editor is tripping over some bs hello games procedural content hard lock.
