### ISSUE TITLE
New Expedition (Adrift) is out, NMSSaveEditor isn't working for new saves

### ISSUE THREAD

**Issue by HQuest** [goatfungus/NMSSaveEditor#994]
Mandatory post so @goatfungus knows about the new update and doesn't get spammed with more requests. Looking forward a new update of the tool. Thanks!

**Comment by Patola** [comment]
It actually works with adrift. Once you save it shows in "No Man's Sky" as a normal save which you can load, but once you save again in-game it reverts to the expedition save.

**Comment by HQuest** [comment]
It works with the Orbital update? Yes. Does it work with Adrift Expedition? No. So it does not "actually works with adrift", it works with Orbital but not with the new expedition.

**Comment by Patola** [comment]
> It works with the Orbital update? Yes. Does it work with Adrift Expedition? No. So it does not "actually works with adrift", it works with Orbital but not with the new expedition.

It does not work flawlessly, after editing it shows as a normal save game (and once you save again in-game it shows "expedition" again). But it does work. I finished the Adrift Expedition after having editted my savegame. And the prizes of that expedition are in my account now.

**Comment by goatfungus** [comment]
I have just released a new version, 1.16.0, which should work with Adrift now. Enjoy!
