### ISSUE TITLE
Some items not recognized

### ISSUE THREAD

**Issue by PappyVanWink** [goatfungus/NMSSaveEditor#998]
Some items that seem to be new in Adrift the editor can't fine or doesn't recognize. For example the Surge Battery,  the editor can't find or list it in a search. other times that show in inventory only show a partial description/gibberish with no thumbnail

**Comment by skullcrowtommy** [comment]
Yeah, that's because the editor still has yet to be updated. Frustrating, yes I know.

**Comment by goatfungus** [comment]
I have just released a new version, 1.16.0, which should work with Adrift now. Enjoy!

**Comment by HQuest** [comment]
There are still unmapped items with the latest update.
![image](https://github.com/goatfungus/NMSSaveEditor/assets/1088309/62872e0f-a3dc-4dfd-bf4f-6e07e49e468e)
